In [1]:
import pandas as pd
import numpy as np
import os
import sys
from notebook.services.config import ConfigManager
cm = ConfigManager().update('notebook', {'limit_output': 1000})
pd.options.display.max_rows=999
pd.options.display.max_columns=999
%matplotlib widget
import matplotlib.pyplot as plt
from edw_functions import *
sys.path.append('/home/wolfgang/repos/sleep_research_io/')
from sleep_research_functions import *
%load_ext autoreload
%autoreload 2

In [8]:
delirium_dir = '/media/mad3/Projects/Wolfgang/Covid19_Delirium'
sedation_dir = '/media/mad3/Projects/Wolfgang/Covid19_Sedation'

In [31]:
cohort = pd.read_csv(os.path.join(delirium_dir, 'covid_delirium_meds.csv'))
cohort_sedation = pd.read_excel(os.path.join(sedation_dir, 'MeganBarra_MRNs_Final Cohort.xlsx'))

In [32]:
cohort.head(2)

,study _id,mrn,Admission,Discharge,Weight,quetiapine,haloperidol,olanzapine,risperidone,ziprasidone,aripiprazole,chlorpromazine,valproic acid,phenobarbital,gabapentin,ketamine,dexmedetomidine,clonidine,isoflurane,propofol,midazolam,diazepam,lorazepam,clonazepam,alprazolam,chlordiazepoxide,methadone,fentanyl,hydromorphone,morphine,oxycodone,hydrocodone,tramadol,meperidine,cisatracurium,rocuronium,vecuronium,modafinil,methylphenidate,amantadine,caffeine,melatonin,opioids_sum,benzos_sum,antipsychotics_sum
0,1,5474581,2020-04-15,2020-05-03,70.1,787.5,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,9.064133,2.3,2.0,13037.516667,8.0,0.0,0.0,0.0,0,0,0.0,1.416667,44.954167,0.0,110.0,0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,27.0,496.361111,83.637331,1.96875
1,2,4700402,2020-04-06,2020-04-30,108.5,800.0,2.5,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,24.567967,0.0,2.0,68733.600000,8.0,0.0,1.0,0.0,0,0,180.0,14.064058,108.063333,0.0,0.0,0,0.0,0.0,0.0,32550.0,0.0,0.0,0.0,0.0,0.0,0.0,2239.328056,432.999300,2.31250

In [33]:
os.listdir(delirium_dir)

['medications_all_timeseries_hourly_w_route_csv',
 'edw_covid_delirium_flowsheets.csv',
 'edw_covid_delirium_labs.csv',
 'medications_hourly_figures_pdf',
 'medications_covid_delirium_not_successfully_processed.csv',
 'medications_hourly_figures_png',
 'covid_delirium_meds.csv',
 'medications_all_timeseries_hourly_h5',
 'edw_covid_delirium_demographics.csv',
 'edw_covid_delirium_adt.csv',
 'medications_all_timeseries_hourly_csv',
 'medications_covid_delirium_successfully_processed.csv',
 'edw_covid_delirium_meds.csv']

In [34]:
adt = pd.read_csv(os.path.join(delirium_dir, 'edw_covid_delirium_adt.csv'))

In [43]:
adt;

In [63]:
if not 'PatientID' in cohort.columns:
    
    cohort['PatientID'] = np.nan
    for jloc, row in cohort.iterrows():
        mrn = row.mrn
        cohort.loc[jloc, 'PatientID'] = adt.loc[adt.MRN == mrn, 'PatientID'].unique()[0]
    cohort = cohort[[cohort.columns[-1]] + list(cohort.columns[:-1])]
cohort.rename({'study _id': 'study_id'}, axis=1, inplace=True)

In [64]:
cohort_sedation.head(2)

,PatientID,AdmissionDTS,DischargeDTS,First_ICU_Admit,First_ICU_Discharge,Second_ICU_Admit,Second_ICU_Discharge,Third_ICU_Admit,Third_ICU_Discharge,Fourth_ICU_Admit,Fourth_ICU_Discharge,Number_ICU_Admissions,"Age, years","Hospital LOS, days","ICU LOS, days",OnsetDTS,Hospital,PatientEncounterID,MRN,BirthDTS,SexDSC,EthnicGroupDSC,PatientRaceDSC,Extubation,Intubation,CMO,DNR,DNI,Age,Weight,Height,PMH Neurological Disorder,"If PMH neuro disorder, describe",Stroke,Coma,Clinical or Electrographc Seizure/Status Epilepticus,Neuroimaging,ECMO,Dialysis/CRRT,CMO.1,In Hospital Death (yes/no),Date of death,1stETTplacementDTS,1stETTremovalDTS,2ndETTplacementDTS,2ndETTremovalDTS,3rdETTplacementDTS,3rdETTremovalDTS,4thETTplacementDTS,4thETTremovalDTS,Duration of ETT Placement,Intubation_DTS_Final,InHospitalMortality,CVVH_HD,Baseline Opioid/BZD (no=0; prn=1; scheduled=2),Baseline Opioid/BZD Comment,Intubated > 24 h at OSH,Discharge Disposition,"Discharge Opioids (no=0, prn =1, scheduled =2)",Discharge BZDs,Discharge Rx,Unnamed: 61
0,Z10002895,2020-05-04 15:09:00,2020-05-19 11:38:00,2020-05-06 17:23:00,2020-05-15 13:23:00,NaT,NaT,NaT,NaT,NaT,NaT,1,56.431866,14.853472,8.833333,2020-04-28,MGH,3305390010,10087535802,1963-12-13,Male,Not Hispanic or Latino,Other,Yes,Yes,No,No,No,56,104.33,172.72,No,NaN,No,Yes,No,No,No,No,No,No,No,2020-05-06 18:05:00,2020-05-15 03:00:00,NaT,NaT,NaT,NaT,NaT,NaT,8.371528,2020-05-06 18:05:00,0.0,0.0,0.0,NaN,0.0,Long Term Care,0.0,0.0,NaN,NaN
1,Z10063961,2020-04-16 13:31:00,2020-04-17 10:13:00,2020-04-16 14:42:00,2020-04-17 10:13:00,NaT,NaT,NaT,NaT,NaT,NaT,1,67.880995,0.862500,0.813194,2020-04-16,MGH,3303566961,10087857248,1952-06-16,Male,Not Hispanic or Latino,Black or African American,Yes,Yes,Yes,Yes,Yes,67,89.00,182.88,No,NaN,No,No,No,Yes,No,No,Yes,Yes,2020-04-17 10:13:00,2020-04-16 11:16:00,2020-04-17 10:13:00,NaT,NaT,NaT,NaT,NaT,NaT,0.956250,2020-04-16 11:16:00,1.0,0.0,0.0,NaN,0.0,In-hospital mortality,NaN,NaN,NaN,NaN

In [69]:
cohort['PartOfSedationProject'] = np.nan
for jloc, row in cohort.iterrows():
    patientid = row.PatientID
    cohort.loc[jloc, 'PartOfSedationProject'] = patientid in list(cohort_sedation.PatientID)

In [132]:
if 1:
    flowsheets = pd.read_csv(os.path.join(delirium_dir, 'edw_covid_delirium_flowsheets.csv'))
    
    rass_and_cam_keywords = [x for x in flowsheets.FlowsheetMeasureNM.unique() if 'rass' in x.lower()] + [x for x in flowsheets.FlowsheetMeasureNM.unique() if 'cam' in x.lower()]
    rass_and_cam_entries = flowsheets.loc[np.isin(flowsheets.FlowsheetMeasureNM, rass_and_cam_keywords), :]
    rass_and_cam_entries = rass_and_cam_entries[['MRN', 'PatientID', 'PatientEncounterID', 'FlowsheetMeasureNM', 'RecordedDTS', 'MeasureTXT']]

    rass_and_cam_entries['study_id'] = np.nan
    for jloc, row in cohort.iterrows():    
        rass_and_cam_entries.loc[rass_and_cam_entries.MRN == row.mrn, 'study_id'] = row.study_id
    rass_and_cam_entries['study_id'] = rass_and_cam_entries['study_id'].astype(int)
    rass_and_cam_entries = rass_and_cam_entries[[rass_and_cam_entries.columns[-1]] + list(rass_and_cam_entries.columns[:-1])]
    rass_and_cam_entries = rass_and_cam_entries.sort_values(by=['study_id', 'RecordedDTS'])
    rass_and_cam_entries.drop_duplicates(inplace=True)

In [135]:
rass_and_cam_entries

,study_id,MRN,PatientID,PatientEncounterID,FlowsheetMeasureNM,RecordedDTS,MeasureTXT
955359,1,5474581,Z12922609,3.303423e+09,R PHS IP RASS,2020-04-15 15:15:00.0000000,+1
955360,1,5474581,Z12922609,3.303423e+09,R PHS IP RASS,2020-04-15 16:00:00.0000000,-4
955361,1,5474581,Z12922609,3.303423e+09,R PHS IP RASS,2020-04-15 17:00:00.0000000,-4
955362,1,5474581,Z12922609,3.303423e+09,R PHS IP RASS,2020-04-15 18:00:00.0000000,-4
955363,1,5474581,Z12922609,3.303423e+09,R PHS IP RASS,2020-04-15 20:00:00.0000000,-4
...,...,...,...,...,...,...,...
1893283,67,6971196,Z17796471,3.319529e+09,R PHS IP RASS,2020-08-12 05:00:00.0000000,0
1893284,67,6971196,Z17796471,3.319529e+09,R PHS IP RASS,2020-08-12 20:15:00.0000000,0
1893285,67,6971196,Z17796471,3.319529e+09,RETIRED-R PHS IP OVERALL CAM ICU,2020-08-12 20:15:00.0000000,Negative
1893658,67,6971196,Z17796471,3.319529e+09,R PHS IP RASS,2020-08-13 03:35:00.0000000,0
1893659,67,6971196,Z17796471,3.319529e+09,RETIRED-R PHS IP OVERALL CAM ICU,2020-08-13 03:35:00.0000000,Negative

In [138]:
cohort.to_csv(os.path.join(delirium_dir, 'cohort.csv'), index=False)
rass_and_cam_entries.to_csv(os.path.join(delirium_dir, 'covid_delirium_rass_cam.csv'), index=False)

In [139]:
cohort.PartOfSedationProject.sum()

60