## csv file example

In [24]:
import pandas as pd
import numpy as np

In [13]:
df = pd.DataFrame(columns=['TP','AHI_pred'])

In [18]:
i = 0

In [14]:
df.loc[i,'TP'] = 46
df.loc[i,'AHI_pred'] = 12

In [15]:
df

   TP  AHI_pred
0  46        12

In [19]:
# or:
df.loc[i,:] = [22,33]

In [17]:
df

   TP  AHI_pred
0  22        33

In [21]:
df.to_csv('samplefile.csv') # or with filepath

## txt file:

In [40]:
for i in range(2):
    AHI_pred = np.random.rand()
    FP = np.random.rand()
    sensitivity = 0.99999
    all_values_to_save = [AHI_pred, FP, sensitivity]
    with open('samplefile.txt','a') as f:
        for element in all_values_to_save:
            f.write(str(element) + '\t')
        f.write('\n')