In [2]:
import pandas as pd
import numpy as np
import os
import sys
%load_ext autoreload
%autoreload 2
# sys.path.append('/home/wolfgang/repos/sleep_research_io')
# from sleep_research_functions import *
%matplotlib widget
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

from icu_sleep_breathing_2020_help_functions import * 
pd.options.display.max_columns = 200

In [3]:
[summary_subjects_icu, summary_subjects_sleeplab, 
 summary_days_icu, summary_days_sleeplab] = load_summary_data_with_inclusion_criteria()

/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3338: DtypeWarning: Columns (15,91,92,93,6455,6456,6457,12819,12820,12821,19185,19186,19187,21491,21492,21493,21519,21520,21521,21526,21527,21528,25549,25550,25551,31913,31914,31915,38279,38280,38281,44643,44644,44645,46851,46852,46853,46865,46866,46867,46879,46880,46881,46949,46950,46951,46956,46957,46958,46963,46964,46965,46970,46971,46972,46977,46978,46979,46984,46985,46986,51007,51008,51009,53336,53337,53338,57305,57373,57374,57375,59588,59589,59590,59602,59603,59604,59686,59687,59688,63669,63737,63738,63739,65952,65953,65954,65959,65960,65961,65980,65981,65982,66036,66037,66038,66043,66044,66045,66050,66051,66052,66057,66058,66059,66071,66072,66073,66078,66079,66080,70033,70101,70102,70103,72318,72319,72320,72332,72333,72334,72402,72403,72404,72416,72417,72418,76399,76467,76468,76469,78682,78683,78684,78696,78697,78698,78710,78711,78712,78766,78767,78768,78787,78788,78789,78801,78802,78803,78808,78809,78810,82763,82831,82832,82833,85039,85040,85041,85046,85047,85048,85053,85054,85055,85060,85061,85062,85067,85068,85069,85074,85075,85076,85137,85138,85139,85144,85145,85146,85151,85152,85153,89127,89195,89196,89197,91405,91406,91407,91412,91413,91414,91419,91420,91421,91426,91427,91428,91433,91434,91435,91440,91441,91442,91496,91497,91498,91503,91504,91505,91510,91511,91512,91517,91518,91519,91531,91532,91533,91538,91539,91540,95493,95561,95562,95563,97776,97777,97778,97783,97784,97785,97790,97791,97792,97804,97805,97806,97867,97868,97869,97874,97875,97876,97881,97882,97883,97888,97889,97890,97895,97896,97897,97902,97903,97904,101857,101925,101926,101927,104126,104127,104128,104133,104134,104135,104140,104141,104142,104154,104155,104156,104161,104162,104163,104168,104169,104170,104224,104225,104226,104231,104232,104233,104238,104239,104240,104245,104246,104247,104259,104260,104261,104266,104267,104268,108221,108289,108290,108291,110492,110493,110494,110499,110500,110501,110506,110507,110508,110513,110514,110515,110520,110521,110522,110527,110528,110529,110534,110535,110536,110590,110591,110592,110597,110598,110599,110604,110605,110606,110611,110612,110613,110618,110619,110620,110625,110626,110627,110632,110633,110634,114587,114655,114656,114657,116863,116864,116865,116870,116871,116872,116877,116878,116879,116884,116885,116886,116891,116892,116893,116898,116899,116900,116961,116962,116963,116968,116969,116970,116975,116976,116977,116989,116990,116991,116996,116997,116998,120951,121019,121020,121021,123234,123235,123236,123241,123242,123243,123248,123249,123250,123262,123263,123264,123318,123319,123320,123325,123326,123327,123332,123333,123334,123339,123340,123341,123353,123354,123355,123360,123361,123362,127315,127383,127384,127385,129593,129594,129595,129600,129601,129602,129607,129608,129609,129614,129615,129616,129621,129622,129623,129628,129629,129630,129684,129685,129686,129691,129692,129693,129698,129699,129700,129705,129706,129707,129719,129720,129721,129726,129727,129728,133681,133749,133750,133751,135964,135965,135966,135978,135979,135980,135992,135993,135994,136069,136070,136071,136090,136091,136092,140045,140113,140114,140115,142328,142329,142330,142342,142343,142344,142356,142357,142358,142412,142413,142414,142419,142420,142421,142447,142448,142449,142454,142455,142456,146409,146477,146478,146479,148694,148695,148696,148708,148709,148710,148722,148723,148724,148778,148779,148780,148785,148786,148787,148792,148793,148794,148799,148800,148801,148813,148814,148815,148820,148821,148822,152775,159139,159207,159208,159209,165503) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3338: DtypeWarning: Columns (15,93,94,95,2294,2295,2296,2301,2302,2303,2308,2309,2310,2315,2316,2317,2322,2323,2324,2329,2330,2331,2336,2337,2338,2392,2393,2394,2399,2400,2401,2406,2407,2408,2413,2414,2415,2420,2421,2422,2427,2428,2429,2434,2435,2436) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

# of subjects ICU before inclusion criteria: 102
# of 12-hour segments ICU before inclusion criteria: 1161
# of subjects ICU after inclusion criteria: 102
# of 12-hour segments ICU after inclusion criteria: 1161
24-hour segments: 387
12-hour segments: 774

# of subjects sleeplab before inclusion criteria: 412
# of 12-hour segments sleeplab before inclusion criteria: 412

In [3]:
print(summary_subjects_icu.shape[0])
summary_subjects_icu.head()

102

,inclusion_subject,study_id,mrn,enrolled,age,bmi,sex,osa_diagnosis_yn,osa_diagnosis,icu_mortality,3_month_mortality,icu_los,hospital_los,icu_readmission,diagnosis,lvef,date_of_echo,chf,copd,med_surg,CCI,CCI_weighted,Belt_Length,d1_timerange,d1_hr_mean,d1_hr_std,d1_hr_median,d1_hr_q25,d1_hr_q75,d1_hr_sda,d1_hr_asd,d1_spo2_mean,d1_spo2_std,d1_spo2_median,d1_spo2_q25,d1_spo2_q75,d1_spo2_sda,d1_spo2_asd,d1_spo2_airgo_mean,d1_spo2_airgo_std,d1_spo2_airgo_median,d1_spo2_airgo_q25,d1_spo2_airgo_q75,d1_spo2_airgo_sda,d1_spo2_airgo_asd,d1_spo2_clean_mean,d1_spo2_clean_std,d1_spo2_clean_median,d1_spo2_clean_q25,d1_spo2_clean_q75,d1_spo2_clean_sda,d1_spo2_clean_asd,d1_spo2_airgo_clean_mean,d1_spo2_airgo_clean_std,d1_spo2_airgo_clean_median,d1_spo2_airgo_clean_q25,d1_spo2_airgo_clean_q75,d1_spo2_airgo_clean_sda,d1_spo2_airgo_clean_asd,d1_edw_bp_systolic_mean,d1_edw_bp_systolic_std,d1_edw_bp_systolic_median,d1_edw_bp_systolic_q25,d1_edw_bp_systolic_q75,d1_edw_bp_diastolic_mean,d1_edw_bp_diastolic_std,d1_edw_bp_diastolic_median,d1_edw_bp_diastolic_q25,d1_edw_bp_diastolic_q75,d1_edw_bp_map_mean,d1_edw_bp_map_std,d1_edw_bp_map_median,d1_edw_bp_map_q25,d1_edw_bp_map_q75,d1_cpc_hfc_lfc_ratio_mean,d1_cpc_hfc_lfc_ratio_std,d1_cpc_hfc_lfc_ratio_median,d1_cpc_hfc_lfc_ratio_q25,d1_cpc_hfc_lfc_ratio_q75,d1_cpc_hfc_mean,d1_cpc_hfc_std,d1_cpc_hfc_median,d1_cpc_hfc_q25,d1_cpc_hfc_q75,d1_cpc_hfc_sum,d1_cpc_lfc_mean,d1_cpc_lfc_std,d1_cpc_lfc_median,d1_cpc_lfc_q25,d1_cpc_lfc_q75,d1_cpc_lfc_sum,d1_hrv_nn_mean,d1_hrv_nn_std,d1_hrv_nn_median,d1_hrv_nn_q25,d1_hrv_nn_q75,d1_hrv_nn_sda,d1_hrv_nn_asd,d1_hco3_arterial_mean,d1_hco3_arterial_min,...,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_asd,airgo_available_h_sum,ecg_available_sum,airgo_ecg_available_sum
0,1,1,1298742.0,2018-06-06,79.0,25.82,1.0,no,0.0,0.0,0.0,3.0,5.0,no,acute lower GI hemorrhage,76,2018-03-09 00:00:00,0,1,1,3.0,3.0,NaN,2018-06-05 08:00:00 - 2018-06-05 20:00:00,76.256767,7.606795,75.0000,70.0000,81.437500,6.535857,2.761764,98.345352,2.877457,99.0,97.0,100.0,1.925557,1.048249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.502052,2.137409,99.0,97.0625,100.0,1.632532,0.750813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.7813025712966919,0.08696668595075607,0.7875000238418579,0.725000,0.841667,0.067258,0.048887,21.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.020250,48.000556,12.020250
1,1,3,1910753.0,2018-06-18,84.0,29.32,1.0,no,0.0,0.0,0.0,3.0,10.0,no,sepsis,54,2018-06-18 00:00:00,1,1,1,6.0,12.0,NaN,2018-06-17 08:00:00 - 2018-06-17 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Series([], Freq: 100L, Name: hrv_nn, dtype: fl...","Series([], Freq: 100L, Name: hrv_nn, dtype: fl...","Series([], Freq: 100L, Name: hrv_nn, dtype: fl...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.497528,92.276444,35.103444
3,1,6,4875316.0,2018-07-09,68.0,20.09,1.0,no,0.0,0.0,0.0,3.0,10.0,no,cervical stenosis of spine,none,-,0,0,0,1.0,2.0,NaN,2018-07-09 08:00:00 - 2018-07-09 20:00:00,81.413933,8.740714,81.0000,74.5625,87.140625,8.041395,3.367075,97.676781,1.819102,98.0,97.0,99.0,0.946101,1.340657,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.676781,1.819102,98.0,97.0000,99.0,0.946101,1.340657,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8271409869194031,0.06240355968475342,0.8291666507720947,0.783333,0.875000,0.036631,0.050600,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.580028,58.004194,51.500861
5,1,11,2770155.0,2018-09-20,56.0,24.89,0.0,yes,1.0,0.0,0.0,11.0,21.0,yes (to neuro ICU),schwannoma,none,-,0,0,0,1.0,2.0,NaN,2018-09-19 08:00:00 - 2018-09-19 20:00:00,78.421303,8.166085,75.5625,73.0000,81.875000,4.737754,4.169563,97.658913,2.010296,98.0,97.0,99.0,1.380660,0.505857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.658913,2.010296,98.0,97.0000,99.0,1.380660,0.505857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106.0,NaN,106.0,106.0,106.0,58.0,NaN,58.0,58.0,58.0,74.0,NaN,74.0,74.0,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8995518684387207,0.330157071352005,0.800000011920929,0.716667,0.866667,0.072375,0.321991,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.197472,66.900778,41.032833
6,1,12,3826907.0,2018-09-25,77.0,30.91,0.0,no,0.0,0.0,0.0,26.0,58.0,yes (2x),pulmonary embolism,71,2018-09-25 00:00:00,0,0,1,2.0,2.0,NaN,2018-09-24 08:00:00 - 2018-09-24 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Series([], Freq: 100L, Name: hrv_nn, dtype: fl...","Series([], Freq: 100L, Name: hrv_nn, dtype: fl...","Series([], Freq: 100L, Name: hrv_nn, dtype: fl...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.634444,82.764722,38.542194

In [4]:
print('Age, mean (std), range:')
print(summary_subjects_icu.age.mean())
print(summary_subjects_icu.age.std())
print(summary_subjects_icu.age.min())
print(summary_subjects_icu.age.max())

Age, mean (std), range:
67.95098039215686
8.98445020933213
50.0
88.0

In [5]:
print('Male/Female')
print(sum(summary_subjects_icu.sex == 1))
print(sum(summary_subjects_icu.sex == 1) / summary_subjects_icu.shape[0])
print(sum(summary_subjects_icu.sex == 0))
print(sum(summary_subjects_icu.sex == 0) / summary_subjects_icu.shape[0])

Male/Female
61
0.5980392156862745
41
0.4019607843137255

In [6]:
summary_subjects_icu.columns[:50]

Index(['inclusion_subject', 'study_id', 'mrn', 'enrolled', 'age', 'bmi', 'sex',
       'osa_diagnosis_yn', 'osa_diagnosis', 'icu_mortality',
       '3_month_mortality', 'icu_los', 'hospital_los', 'icu_readmission',
       'diagnosis', 'lvef', 'date_of_echo', 'chf', 'copd', 'med_surg', 'CCI',
       'CCI_weighted', 'Belt_Length', 'd1_timerange', 'd1_hr_mean',
       'd1_hr_std', 'd1_hr_median', 'd1_hr_q25', 'd1_hr_q75', 'd1_hr_sda',
       'd1_hr_asd', 'd1_spo2_mean', 'd1_spo2_std', 'd1_spo2_median',
       'd1_spo2_q25', 'd1_spo2_q75', 'd1_spo2_sda', 'd1_spo2_asd',
       'd1_spo2_airgo_mean', 'd1_spo2_airgo_std', 'd1_spo2_airgo_median',
       'd1_spo2_airgo_q25', 'd1_spo2_airgo_q75', 'd1_spo2_airgo_sda',
       'd1_spo2_airgo_asd', 'd1_spo2_clean_mean', 'd1_spo2_clean_std',
       'd1_spo2_clean_median', 'd1_spo2_clean_q25', 'd1_spo2_clean_q75'],
      dtype='object')

In [7]:
demographics = '/scr/wolfgang/Dropbox (Partners HealthCare)/CDAC_STUDIES_shared/2017P000090_ICU-SLEEP-MATERIALS/Data (DSMB code, RC backup)/Data-Vitals & Meds/edw_icu_sleep_2020_07_07_demographics.csv'
demographics = pd.read_csv(demographics)

In [8]:
summary_subjects_icu['race'] = np.nan
summary_subjects_icu['ethnicity'] = np.nan

for jloc, row in summary_subjects_icu.iterrows():
    dem_sel = demographics[demographics.MRN == row.mrn]
    race = np.unique(dem_sel.PatientRaceDSC)
    ethnicity = np.unique(dem_sel.EthnicGroupDSC)
    if len(race) > 1:
        print(race)
        race = list(set(race) - set(['Unavailable']))
    if len(ethnicity) > 1:
        print(ethnicity)
    summary_subjects_icu.loc[jloc, 'race'] = race[0]
    summary_subjects_icu.loc[jloc, 'ethnicity'] = ethnicity[0]

['Unavailable' 'White']
['Unavailable' 'White']

In [9]:
summary_subjects_icu['race'].value_counts()

White or Caucasian                  53
White                               39
Black or African American            5
Unavailable                          2
Asian                                2
American Indian or Alaska Native     1
Name: race, dtype: int64

In [10]:
summary_subjects_icu['race'].value_counts() / summary_subjects_icu.shape[0]

White or Caucasian                  0.519608
White                               0.382353
Black or African American           0.049020
Unavailable                         0.019608
Asian                               0.019608
American Indian or Alaska Native    0.009804
Name: race, dtype: float64

In [11]:
summary_subjects_icu['ethnicity'].value_counts()

No Non Hispanic    95
Unavailable         4
Yes Hispanic        2
Declined            1
Name: ethnicity, dtype: int64

In [12]:
summary_subjects_icu['ethnicity'].value_counts()/ summary_subjects_icu.shape[0]

No Non Hispanic    0.931373
Unavailable        0.039216
Yes Hispanic       0.019608
Declined           0.009804
Name: ethnicity, dtype: float64

In [13]:
print('BMI')
print(summary_subjects_icu.bmi.mean())
print(summary_subjects_icu.bmi.std())

BMI
27.22294117647059
6.059823313477461

In [14]:
print('AirGo Belt Length')
print(summary_subjects_icu.Belt_Length.mean())
print(summary_subjects_icu.Belt_Length.std())

AirGo Belt Length
89.25274725274726
11.762079754300265

In [15]:
print('CCI')
print(summary_subjects_icu.CCI.mean())
print(summary_subjects_icu.CCI.std())

CCI
2.2254901960784315
2.147560728841293

In [16]:
print('CCI Weighted')
print(summary_subjects_icu.CCI_weighted.mean())
print(summary_subjects_icu.CCI_weighted.std())

CCI Weighted
3.480392156862745
3.7356468342755482

In [17]:
print('SOFA')
print(summary_subjects_icu['f1_sofa_score_max'].mean())
print(summary_subjects_icu['f1_sofa_score_max'].std())
print(summary_subjects_icu['f1_sofa_score_max'].min())
print(summary_subjects_icu['f1_sofa_score_max'].max())

SOFA
3.0721649484536084
2.5870165517783716
0.0
11.0

In [18]:
summary_subjects_icu['sofa_max'] = summary_subjects_icu[['f1_sofa_score_max',
                                                        'f2_sofa_score_max',
                                                        'f3_sofa_score_max',
                                                        'f4_sofa_score_max',
                                                        'f5_sofa_score_max',
                                                        'f6_sofa_score_max',
                                                        'f7_sofa_score_max',
                                                        'f8_sofa_score_max']].max(axis=1)

In [19]:
print('SOFA max during stay')
print(summary_subjects_icu['sofa_max'].mean())
print(summary_subjects_icu['sofa_max'].std())

SOFA max during stay
3.3137254901960786
2.412756494985827

In [20]:
print(summary_subjects_icu['osa_diagnosis'].sum())
print(summary_subjects_icu['osa_diagnosis'].sum() / summary_subjects_icu.shape[0])

28.0
0.27450980392156865

In [21]:
print(summary_subjects_icu['chf'].sum())
print(summary_subjects_icu['chf'].sum() / summary_subjects_icu.shape[0])

29
0.28431372549019607

In [22]:
print(summary_subjects_icu['copd'].sum())
print(summary_subjects_icu['copd'].sum() / summary_subjects_icu.shape[0])

31
0.30392156862745096

In [23]:
print(summary_subjects_icu['med_surg'].sum())
print(summary_subjects_icu['med_surg'].sum() / summary_subjects_icu.shape[0])

34
0.3333333333333333

In [24]:
print(summary_subjects_icu['icu_mortality'].sum())
print(summary_subjects_icu['icu_mortality'].sum() / summary_subjects_icu.shape[0])

0.0
0.0

In [25]:
print(summary_subjects_icu['icu_mortality'].sum())
print(summary_subjects_icu['icu_mortality'].sum() / summary_subjects_icu.shape[0])

0.0
0.0

In [26]:
print(summary_subjects_icu['3_month_mortality'].sum())
print(summary_subjects_icu['3_month_mortality'].sum() / summary_subjects_icu.shape[0])

19.0
0.18627450980392157

In [27]:
sl = summary_subjects_sleeplab.query('matched_all == 1').copy()

In [28]:
sl.shape

(220, 5962)

In [29]:
print('Age, mean (std), range:')
print(sl.age.mean())
print(sl.age.std())
print(sl.age.min())
print(sl.age.max())

Age, mean (std), range:
67.68768181818182
8.809544310961334
51.595
101.337

In [30]:
sl.sex.replace('Unknown', 'Female', inplace=True)

In [31]:
print(sum(sl.sex == 'Male'))
print(sum(sl.sex == 'Male') / sl.shape[0])
print(sum(sl.sex == 'Female'))
print(sum(sl.sex == 'Female') / sl.shape[0])

122
0.5545454545454546
98
0.44545454545454544

In [32]:
sl_airgo_table = pd.read_csv('AirGoStudies_OverviewTable.csv')

In [33]:
sl_airgo_table['mrn'] = (sl_airgo_table['PseudoID'] + 183938).round().astype(int)

In [34]:
# sl_airgo_table[np.isin(sl_airgo_table.mrn, sl.mrn)]
sl_airgo_table = sl_airgo_table[np.isin(sl_airgo_table.SID.apply(lambda x: int(x.replace('Air', ''))), sl.study_id)]

In [35]:
# print(np.sum(sl_airgo_table.Sex == 'Male'))
# print(np.sum(sl_airgo_table.Sex == 'Female'))

In [36]:
print(pd.isna(sl_airgo_table.Race).sum())
sl_airgo_table.Race.value_counts()

29

White-WHITE                                         151
Other-OTHER                                          15
BLACK OR AFRICAN AMERICAN                             9
Asian-ASIAN                                           7
Not Recorded-DECLINED                                 2
Hispanic-OTHER@HISPANIC                               2
Hispanic White-WHITE@HISPANIC                         1
Hispanic-HISPANIC OR LATINO                           1
Not Recorded-@                                        1
American Indian-AMERICAN INDIAN OR ALASKA NATIVE      1
Hispanic-HISPANIC                                     1
Name: Race, dtype: int64

In [37]:
sl_airgo_table.shape

(220, 9)

In [46]:
sl_airgo_table.loc[np.isin(sl_airgo_table.SID, ['Air' + str(x).zfill(3) for x in [26, 377, 387]])]

,SID,Age,Race,Sex,BMI,TypeTest,Scorer,PseudoID,mrn
22,Air026,60.0,NaN,Female,44.59,Titration CPAP,B,2780693.0,2964631
342,Air377,61.0,White-WHITE,Female,28.93,Diagnostic,A,2376612.0,2560550
352,Air387,65.0,BLACK OR AFRICAN AMERICAN,Male,44.98,Titration CPAP,D,1680385.0,1864323

In [38]:
print((151 + 1) / 220)
print(9 / 220)
print(7 / 220)
print(1 / 220)

print(15+2+2+1+1+1+29)
print((15+2+2+1+1+1+29) / 220)

print('Hispanic 6')
print(6/220)

print('Hispanic No')
print(151+9+7+1)
print((151+9+7+1) / 220)
print(220-168-6)
print((220-168-6) / 220)

0.6909090909090909
0.04090909090909091
0.031818181818181815
0.004545454545454545
51
0.2318181818181818
Hispanic 6
0.02727272727272727
Hispanic No
168
0.7636363636363637
46
0.20909090909090908

In [39]:
bmi = sl_airgo_table.BMI[sl_airgo_table.BMI != ' ']
print(bmi.astype(float).mean())
print(bmi.astype(float).std())

30.951612903225808
6.427445324934155

In [40]:
print(sl.cci.mean())
print(sl.cci.std())

1.8681818181818182
1.7296465085146069

In [41]:
print(sl.ahi_expert.mean())
print(sl.ahi_expert.std())

AttributeError: 'DataFrame' object has no attribute 'ahi_expert'

In [ ]:
[x for x in sl if 'ahi' in x]

In [17]:
### Ventilator


df_oxygen = pd.read_csv('/home/wolfgang/repos/Undiagnosed_Apnea/OxygenEDW_all.csv')
df_oxygen['datetime'] = pd.to_datetime(df_oxygen['datetime'])
df_oxygen.set_index('datetime', inplace=True)

In [23]:
from datetime import timedelta

summary_subjects_icu['ventilated_pre'] = np.nan
summary_subjects_icu['ventilated_peri'] = np.nan
summary_subjects_icu['ventilated_post'] = np.nan


for jloc, row in summary_subjects_icu.iterrows():
    mrn = row.mrn
    enrollment_date = pd.to_datetime(row.enrolled)
    
    df_mrn = df_oxygen.loc[df_oxygen.MRN == mrn]
    df_mrn = df_mrn.loc[df_mrn['OXYGEN DEVICE'] == 'Ventilator']
    df_mrn_pre = df_mrn.loc[enrollment_date - timedelta(days=31) : enrollment_date]
    df_mrn_peri = df_mrn.loc[enrollment_date : enrollment_date + timedelta(days=14)]
    df_mrn_post = df_mrn.loc[enrollment_date  + timedelta(days=14) : enrollment_date  + timedelta(days=14) + timedelta(days=31)]

    duration_days = 0
    if df_mrn_pre.shape[0] > 0:
        summary_subjects_icu.loc[jloc, 'ventilated_pre'] = 1
        duration_days += (df_mrn_pre.index[-1] - df_mrn_pre.index[0]).total_seconds() / 3600 / 24
    else:
        summary_subjects_icu.loc[jloc, 'ventilated_pre'] = 0

    if df_mrn_peri.shape[0] > 0:
        summary_subjects_icu.loc[jloc, 'ventilated_peri'] = 1
        duration_days += (df_mrn_peri.index[-1] - df_mrn_peri.index[0]).total_seconds() / 3600 / 24
    else:
        summary_subjects_icu.loc[jloc, 'ventilated_peri'] = 0

    if df_mrn_post.shape[0] > 0:
        summary_subjects_icu.loc[jloc, 'ventilated_post'] = 1
        duration_days += (df_mrn_post.index[-1] - df_mrn_post.index[0]).total_seconds() / 3600 / 24
    else:
        summary_subjects_icu.loc[jloc, 'ventilated_post'] = 0
        
    summary_subjects_icu.loc[jloc, 'ventilated_duration_days'] = duration_days

        
summary_subjects_icu['ventilated'] = summary_subjects_icu[['ventilated_pre', 'ventilated_peri', 'ventilated_post']].any(axis=1)

In [24]:
summary_subjects_icu.shape

(102, 171894)

In [25]:
summary_subjects_icu[['ventilated', 'ventilated_pre', 'ventilated_peri', 'ventilated_post']].sum()

ventilated         26.0
ventilated_pre     21.0
ventilated_peri     7.0
ventilated_post     6.0
dtype: float64

In [26]:
summary_subjects_icu[['ventilated', 'ventilated_pre', 'ventilated_peri', 'ventilated_post']].sum() / summary_subjects_icu.shape[0]

ventilated         0.254902
ventilated_pre     0.205882
ventilated_peri    0.068627
ventilated_post    0.058824
dtype: float64

In [27]:
print(summary_subjects_icu.query("ventilated == 1").ventilated_duration_days.mean())
print(summary_subjects_icu.query("ventilated == 1").ventilated_duration_days.std())
print('')
print(summary_subjects_icu.query("ventilated == 1").ventilated_duration_days.median())
print(summary_subjects_icu.query("ventilated == 1").ventilated_duration_days.quantile(0.25))
print(summary_subjects_icu.query("ventilated == 1").ventilated_duration_days.quantile(0.75))

4.233733974358975
9.11187198968295

0.4979166666666666
0.1234375
2.3223958333333337

# t-tests

In [137]:
from scipy.stats import ttest_ind, fisher_exact

In [138]:
sl['sex'] = (sl['sex'] == 'Male').astype(int)

In [148]:
var = 'age'
print(f"{var:<10} {ttest_ind(summary_subjects_icu[var], sl[var])}")
    
var = 'sex'
# print(f"{var:<10} {ttest_ind(summary_subjects_icu[var], sl[var])}")
print(var)
print(f"{var:<10} {chisquare(np.array([61, 41])/(61+41), np.array([122, 98])/(122+98))}")

print(f"{'bmi':<10} {ttest_ind(summary_subjects_icu.bmi, bmi.astype(float))}")
print(f"{'cci':<10} {ttest_ind(summary_subjects_icu.CCI, sl['cci'])}")

var = 'race'
print(f"{var:<10} {chisquare(np.array([92, 5, 2, 1, 2])/(102), np.array([152, 9, 7, 1, 22])/(220))}")

var = 'ethnicity'
print(f"{var:<10} {chisquare(np.array([95, 2, 5])/(102), np.array([168, 6, 46])/(220))}")

age        Ttest_indResult(statistic=0.24794039901911358, pvalue=0.8043395446077131)
sex
sex        Power_divergenceResult(statistic=0.007657965146843039, pvalue=0.930266295812413)
bmi        Ttest_indResult(statistic=-4.92014245818633, pvalue=1.3921675495772535e-06)
cci        Ttest_indResult(statistic=1.5936781428307982, pvalue=0.11199535230529595)
race       Power_divergenceResult(statistic=0.14147590820631556, pvalue=0.9976129868425142)
ethnicity  Power_divergenceResult(statistic=0.16154212466458592, pvalue=0.9224048404865639)

In [102]:
summary_subjects_icu.bmi

0      25.82
1      29.32
3      20.09
5      24.89
6      30.91
       ...
102    23.18
104    32.25
105    23.29
106    24.51
107    24.17
Name: bmi, Length: 102, dtype: float64

In [126]:
sl_airgo_table_hypnogram_selection = sl_airgo_table.loc[np.isin(sl_airgo_table.SID, ['Air' + str(x).zfill(3) for x in [26, 390, 387]])]

In [127]:
sleeplab_table_full = pd.read_csv('sleeplab_table_hypoxia.csv')

In [128]:
sleeplab_table_full['MRN'] = sleeplab_table_full['MRN'].apply(lambda x: x.replace('-', ''))
sleeplab_table_full['MRN'] = pd.to_numeric(sleeplab_table_full['MRN'], errors='coerce')

In [129]:
match1 = sleeplab_table_full.loc[np.isin(sleeplab_table_full.MRN, sl_airgo_table_hypnogram_selection.mrn.values.astype(float)), :]

In [130]:
for i in range(1, 4):
    print(f"MRN: {match1.iloc[i].MRN}")
    print(sl_airgo_table.loc[sl_airgo_table.mrn == match1.iloc[i].MRN, 'SID'].values[0])
    print(match1.iloc[i].Path.replace('M:', '/media/mad3').replace('\\', '/'))

MRN: 5481509.0
Air390
/media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Delgreco~ Mary_c1bf9b9b-a9b6-4dd1-838c-f2429d4f3d41
MRN: 1864323.0
Air387
/media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a
MRN: 2964631.0
Air026
/media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Burgess~ Chery_46639851-2530-4db3-b4fd-0c5e8dca3ec2

In [131]:
match1

,Unnamed: 0,FolderName,PatientID,MRN,LastName,FirstName,Sex,DateOfBirth,DateOfVisit,TypeOfTest,Path,path_signal,path_annotations,Total_Sleep_Time,AHI,HypoxiaBurden,T90_minutes,T90_minutes_desat,T90_minutes_unspecific
12211,12211,Davis_Lawrence_022516_2226.000,Z11294350,1864323.0,Davis,Lawrence,Male,1954-04-24,2016-02-25,PSG Split night,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,7.233333,43.0,53.2,26.527417,21.245667,5.281750
22356,22356,Delgreco~ Mary_c1bf9b9b-a9b6-4dd1-838c-f2429d4...,Z11277469,5481509.0,Delgreco,Mary,Female,1942-07-12,2019-11-17,Split Night,M:\Datasets_ConvertedData\sleeplab\natus_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/na...,/media/mad3/Datasets_ConvertedData/sleeplab/na...,5.766667,0.0,0.0,11.503288,11.503288,0.000000
23694,23694,Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f...,Z11294350,1864323.0,Davis,Lawrence,Male,1954-04-24,2019-11-16,Titration CPAP,M:\Datasets_ConvertedData\sleeplab\natus_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/na...,/media/mad3/Datasets_ConvertedData/sleeplab/na...,4.808333,0.0,0.0,9.037858,4.243913,4.793945
25080,25080,Burgess~ Chery_46639851-2530-4db3-b4fd-0c5e8dc...,Z10191372,2964631.0,Burgess,Cheryl A,Female,1959-04-25,2019-02-01,Titration CPAP,M:\Datasets_ConvertedData\sleeplab\natus_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/na...,/media/mad3/Datasets_ConvertedData/sleeplab/na...,6.350000,0.0,0.0,0.000000,0.000000,0.000000

In [117]:
os.listdir('/media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a')

['eeg_metadata.mat',
 'Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a_Davis Pre.pdf',
 'Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a_PSG.pdf',
 'Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a_MGH CPAP Titration.doc',
 'ID_archived.csv',
 'Labels_Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a.mat',
 'Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a_MGH Split Night.doc',
 'study_metadata.mat',
 'annotations.csv',
 'ID.csv',
 'Signal_Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a.mat',
 'Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a_Davis TECH.docx',
 'Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a.edf',
 'Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a_HX.pdf',
 'Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a_REQ.pdf',
 'Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a_Davis Post.pdf']

In [4]:
readmission = pd.read_excel('/scr/wolfgang/Dropbox (Partners HealthCare)/UndiagnosedOSA_Project/Analysis_ICU/readmission_data.xlsx')

In [7]:
readmission = readmission[['SID', 'Readmission rates within 30days (*Options 1-4)']]
readmission.rename({'Readmission rates within 30days (*Options 1-4)': 'readmission'}, axis=1, inplace=True)
readmission = readmission[np.isin(readmission.SID, summary_subjects_icu.study_id.unique())].copy()

In [12]:
readmission.shape

(102, 2)

In [10]:
# 1 - Neither readmitted to a hospital/ICU within 30 days     ;     
# 2 - Readmitted to hosp. within 30d   ;   
# 3 - Readmitted to ICU within 30d (if both hosp. & ICU -> Coded as 2)   ; 
# 4 - ED visit within 30d

readmission.readmission.value_counts()

1    77
2    10
4     7
-     4
3     4
Name: readmission, dtype: int64

In [11]:
readmission.readmission.value_counts() / len(summary_subjects_icu.study_id.unique())

1    0.754902
2    0.098039
4    0.068627
-    0.039216
3    0.039216
Name: readmission, dtype: float64

In [13]:
summary_subjects = summary_subjects_icu

columns = [f'f{i}_opioids_sum' for i in range(1,9)]
summary_subjects['opioids_median'] = summary_subjects[columns].median(axis=1, skipna=True)
summary_subjects['opioids_mean'] = summary_subjects[columns].mean(axis=1, skipna=True)
summary_subjects['opioids_min'] = summary_subjects[columns].min(axis=1, skipna=True)
summary_subjects['opioids_max'] = summary_subjects[columns].max(axis=1, skipna=True)
summary_subjects['opioids_totalsum'] = summary_subjects[columns].sum(axis=1, skipna=True)

columns = [f'f{i}_benzos_sum' for i in range(1,9)]
summary_subjects['benzos_median'] = summary_subjects[columns].median(axis=1, skipna=True)
summary_subjects['benzos_mean'] = summary_subjects[columns].mean(axis=1, skipna=True)
summary_subjects['benzos_min'] = summary_subjects[columns].min(axis=1, skipna=True)
summary_subjects['benzos_max'] = summary_subjects[columns].max(axis=1, skipna=True)
summary_subjects['benzos_totalsum'] = summary_subjects[columns].sum(axis=1, skipna=True)

columns = [f'f{i}_antipsychotics_sum' for i in range(1,9)]
summary_subjects['antipsychotics_totalsum'] = summary_subjects[columns].sum(axis=1, skipna=True)

columns = [f'f{i}_sofa_score_max' for i in range(1,9)]
summary_subjects['sofa_median'] = summary_subjects[columns].median(axis=1, skipna=True)
summary_subjects['sofa_mean'] = summary_subjects[columns].mean(axis=1, skipna=True)
summary_subjects['sofa_min'] = summary_subjects[columns].min(axis=1, skipna=True)
summary_subjects['sofa_max'] = summary_subjects[columns].max(axis=1, skipna=True)
summary_subjects['sofa_totalsum'] = summary_subjects[columns].sum(axis=1, skipna=True)

columns = [f'f{i}_oxygen_flow_rate_max' for i in range(1,9)]
summary_subjects['oxygen_flow_rate_max'] = summary_subjects[columns].max(axis=1, skipna=True)

In [15]:
from scipy.stats import ttest_ind
# medication variables:
print(f"Number of patients with opioids usage within study period: {np.sum(summary_subjects['opioids_totalsum'] > 0)}")
opioid_sel = summary_subjects.loc[summary_subjects['opioids_totalsum'] > 0, 'opioids_totalsum']
print(f"Mean (STD) opioids: {np.round(opioid_sel.mean(), 2)} ({np.round(opioid_sel.std(), 2)})")

print(f"Number of patients with benzos usage within study period: {np.sum(summary_subjects['benzos_totalsum'] > 0)}")
benzos_sel = summary_subjects.loc[summary_subjects['benzos_totalsum'] > 0, 'benzos_totalsum']
print(f"Mean (STD) benzos: {np.round(benzos_sel.mean(), 2)} ({np.round(benzos_sel.std(), 2)})")

print('')

print(f"Number of patients with antipsychotics usage within study period: {np.sum(summary_subjects['antipsychotics_totalsum'] > 0)}")
antipsychotics_sel = summary_subjects.loc[summary_subjects['antipsychotics_totalsum'] > 0, 'antipsychotics_totalsum']
print(f"Mean (STD) antipsychotics: {np.round(antipsychotics_sel.mean(), 2)} ({np.round(antipsychotics_sel.std(), 2)})")

Number of patients with opioids usage within study period: 68
Mean (STD) opioids: 37.78 (44.96)
Number of patients with benzos usage within study period: 23
Mean (STD) benzos: 4.33 (5.69)

Number of patients with antipsychotics usage within study period: 24
Mean (STD) antipsychotics: 0.28 (0.38)