In [1]:
import pandas as pd
import numpy as np
import os
import sys
%load_ext autoreload
%autoreload 2
# sys.path.append('/home/wolfgang/repos/sleep_research_io')
# from sleep_research_functions import *
%matplotlib widget
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

from icu_sleep_breathing_2020_help_functions import * 

pd.options.display.max_rows = 300
pd.options.display.max_columns = 300

font = {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : 7}

font_headers =  {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : 8}

matplotlib.rc('font', **font)

In [2]:
plots_savedir = '/media/mad3/Projects/ICU_SLEEP_STUDY/Sleep_And_Breathing/plots'

[summary_subjects_icu, summary_subjects_sleeplab, 
 summary_days_icu, summary_days_sleeplab] = load_summary_data_with_inclusion_criteria()

/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3254: DtypeWarning: Columns (15,91,92,93,6455,6456,6457,12819,12820,12821,19185,19186,19187,21491,21492,21493,21519,21520,21521,21526,21527,21528,25549,25550,25551,31913,31914,31915,38279,38280,38281,44643,44644,44645,46851,46852,46853,46865,46866,46867,46879,46880,46881,46949,46950,46951,46956,46957,46958,46963,46964,46965,46970,46971,46972,46977,46978,46979,46984,46985,46986,51007,51008,51009,53336,53337,53338,57305,57373,57374,57375,59588,59589,59590,59602,59603,59604,59686,59687,59688,63669,63737,63738,63739,65952,65953,65954,65959,65960,65961,65980,65981,65982,66036,66037,66038,66043,66044,66045,66050,66051,66052,66057,66058,66059,66071,66072,66073,66078,66079,66080,70033,70101,70102,70103,72318,72319,72320,72332,72333,72334,72402,72403,72404,72416,72417,72418,76399,76467,76468,76469,78682,78683,78684,78696,78697,78698,78710,78711,78712,78766,78767,78768,78787,78788,78789,78801,78802,78803,78808,78809,78810,82763,82831,82832,82833,85039,85040,85041,85046,85047,85048,85053,85054,85055,85060,85061,85062,85067,85068,85069,85074,85075,85076,85137,85138,85139,85144,85145,85146,85151,85152,85153,89127,89195,89196,89197,91405,91406,91407,91412,91413,91414,91419,91420,91421,91426,91427,91428,91433,91434,91435,91440,91441,91442,91496,91497,91498,91503,91504,91505,91510,91511,91512,91517,91518,91519,91531,91532,91533,91538,91539,91540,95493,95561,95562,95563,97776,97777,97778,97783,97784,97785,97790,97791,97792,97804,97805,97806,97867,97868,97869,97874,97875,97876,97881,97882,97883,97888,97889,97890,97895,97896,97897,97902,97903,97904,101857,101925,101926,101927,104126,104127,104128,104133,104134,104135,104140,104141,104142,104154,104155,104156,104161,104162,104163,104168,104169,104170,104224,104225,104226,104231,104232,104233,104238,104239,104240,104245,104246,104247,104259,104260,104261,104266,104267,104268,108221,108289,108290,108291,110492,110493,110494,110499,110500,110501,110506,110507,110508,110513,110514,110515,110520,110521,110522,110527,110528,110529,110534,110535,110536,110590,110591,110592,110597,110598,110599,110604,110605,110606,110611,110612,110613,110618,110619,110620,110625,110626,110627,110632,110633,110634,114587,114655,114656,114657,116863,116864,116865,116870,116871,116872,116877,116878,116879,116884,116885,116886,116891,116892,116893,116898,116899,116900,116961,116962,116963,116968,116969,116970,116975,116976,116977,116989,116990,116991,116996,116997,116998,120951,121019,121020,121021,123234,123235,123236,123241,123242,123243,123248,123249,123250,123262,123263,123264,123318,123319,123320,123325,123326,123327,123332,123333,123334,123339,123340,123341,123353,123354,123355,123360,123361,123362,127315,127383,127384,127385,129593,129594,129595,129600,129601,129602,129607,129608,129609,129614,129615,129616,129621,129622,129623,129628,129629,129630,129684,129685,129686,129691,129692,129693,129698,129699,129700,129705,129706,129707,129719,129720,129721,129726,129727,129728,133681,133749,133750,133751,135964,135965,135966,135978,135979,135980,135992,135993,135994,136069,136070,136071,136090,136091,136092,140045,140113,140114,140115,142328,142329,142330,142342,142343,142344,142356,142357,142358,142412,142413,142414,142419,142420,142421,142447,142448,142449,142454,142455,142456,146409,146477,146478,146479,148694,148695,148696,148708,148709,148710,148722,148723,148724,148778,148779,148780,148785,148786,148787,148792,148793,148794,148799,148800,148801,148813,148814,148815,148820,148821,148822,152775,159139,159207,159208,159209,165503) have mixed types. Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3254: DtypeWarning: Columns (15,93,94,95,2294,2295,2296,2301,2302,2303,2308,2309,2310,2315,2316,2317,2322,2323,2324,2329,2330,2331,2336,2337,2338,2392,2393,2394,2399,2400,2401,2406,2407,2408,2413,2414,2415,2420,2421,2422,2427,2428,2429,2434,2435,2436) have mixed types. Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

# of subjects ICU before inclusion criteria: 102
# of 12-hour segments ICU before inclusion criteria: 1161
# of subjects ICU after inclusion criteria: 102
# of 12-hour segments ICU after inclusion criteria: 1161
24-hour segments: 387
12-hour segments: 774

# of subjects sleeplab before inclusion criteria: 412
# of 12-hour segments sleeplab before inclusion criteria: 412

In [3]:
for modality in ['breathing', 'ecg_nn']:
    var_n2 = 'stages_distribution_MODALITY_agrelaxed_N2'.replace('MODALITY', modality)
    var_n3 = 'stages_distribution_MODALITY_agrelaxed_N3'.replace('MODALITY', modality)
    var_sum = 'stages_distribution_MODALITY_agrelaxed_N2N3'.replace('MODALITY', modality)
    
    summary_days_icu[var_sum] = summary_days_icu[var_n2] + summary_days_icu[var_n3]
    summary_days_sleeplab[var_sum] = summary_days_sleeplab[var_n2] + summary_days_sleeplab[var_n3]

In [4]:
for agreement in ['agreement_relaxed', 'agreement']:
    for modality in ['amendsumeffort', 'ecg_nn']:
        var_sleep = 'hours_sleep_MODALITY_all'.replace('MODALITY', modality) # all overlap sleep
        var_agreeing = 'hours_sleep_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        
        if agreement == 'agreement_relaxed':
             # all overlap sleep
            var_discordant = 'hours_discordant_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement) # discordant sleep among overlap sleep
        elif agreement == 'agreement':
            var_discordant = 'hours_discordant_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)

            
        summary_days_icu[var_discordant] = summary_days_icu[var_sleep] - summary_days_icu[var_agreeing]
        summary_days_sleeplab[var_discordant] = summary_days_sleeplab[var_sleep] - summary_days_sleeplab[var_agreeing]

In [5]:
summary_days_icu.loc[:, ['stages_distribution' in x for x in summary_days_icu.columns]] *= 100
summary_days_sleeplab.loc[:, ['stages_distribution' in x for x in summary_days_sleeplab.columns]] *= 100

summary_f_icu = summary_days_icu.loc[summary_days_icu.day_cat == 'f', :]
summary_dn_icu = summary_days_icu.loc[summary_days_icu.day_cat != 'f', :]

summary_days_sleeplab_full = summary_days_sleeplab.copy()

In [6]:
### 3x2 plot
# cols: data type, rows: stage version (resp, ecg, expert)

variables_template = ['sleep_hours_MODALITY',
             'stages_distribution_MODALITY_S',
             'stages_distribution_MODALITY_R',
             'stages_distribution_MODALITY_N1',
            'stages_distribution_MODALITY_N2',
             'stages_distribution_MODALITY_N3',
             'sleep_MODALITY_sfi',
             'sleep_MODALITY_sfi_w',
             'sleep_MODALITY_arousali',
            ]
labels = ['Sleep Dur. (h)', 'Sleep Efficiency', 'Stage R (%)', 'Stage N1 (%)', 'Stage N2 (%)', 'Stage N3 (%)', 'SFI', 'SFI Wake', 'Arousal I.']

In [25]:
Xy_sleeplab = summary_days_sleeplab_full[summary_days_sleeplab_full['matched_all'] == 1].copy()

days = 'full'
agreement = 'agreement_relaxed'

# min_hours_sleep_overlap_icu = 2
# if days == 'day_night':
#     Xy_icu = summary_dn_icu.loc[np.any([summary_dn_icu.hours_sleep_ecg_nn_all >= min_hours_sleep_overlap_icu],
#                                                    axis=0), :].copy()
# elif days == 'full':
#     Xy_icu = summary_f_icu.loc[np.any([summary_f_icu.hours_sleep_ecg_nn_all >= min_hours_sleep_overlap_icu],
#                                                    axis=0), :].copy()
    
min_hours_sleep_icu = 2
if days == 'day_night':
    Xy_icu = summary_dn_icu.loc[np.any([summary_dn_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_dn_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :].copy()
elif days == 'full':
    Xy_icu = summary_f_icu.loc[np.any([summary_f_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_f_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :].copy()

print(f'Segments: {Xy_icu.shape[0]}')
print(f'Subjects: {Xy_icu.study_id.unique().shape[0]}')

Segments: 163
Subjects: 80

In [26]:
sleep_total =  f'hours_sleep_{modality}_all'
sleep_agree = f'hours_sleep_{modality}_{agreement}'
sleep_discordant = f'hours_discordant_{modality}_{agreement}'
discordant_proportion = f'discordant_proportion_{modality}_{agreement}'

In [27]:
Xy_icu[discordant_proportion] = np.divide(Xy_icu[sleep_discordant], Xy_icu[sleep_total])

In [28]:
Xy_icu[[sleep_agree, sleep_discordant, sleep_total, discordant_proportion]].head()

,hours_sleep_amendsumeffort_agreement_relaxed,hours_discordant_amendsumeffort_agreement_relaxed,hours_sleep_amendsumeffort_all,discordant_proportion_amendsumeffort_agreement_relaxed
5,3.875001,1.083333,4.958334,0.218487
11,2.908334,4.716667,7.625001,0.618579
17,5.408334,0.491667,5.900001,0.083333
26,3.808334,0.325000,4.133334,0.078629
29,2.125001,6.791667,8.916668,0.761682

In [29]:
[x for x in Xy_icu.columns if 'discordant' in x]

['hours_discordant_amendsumeffort_agreement_relaxed',
 'hours_discordant_ecg_nn_agreement_relaxed',
 'hours_discordant_amendsumeffort_agreement',
 'hours_discordant_ecg_nn_agreement',
 'discordant_proportion_amendsumeffort_agreement_relaxed']

In [30]:
from scipy.stats import ttest_1samp, pearsonr, spearmanr, ttest_rel, wilcoxon
import itertools

### compute table with feature value for each sleep stage and agreeing | discordant sleep

In [32]:
variables = ['hrv_nn',  'hrv_vlf', 'hrv_lf', 'hrv_hf', 'hrv_rmssd',
            'ibi', 'rr_10s_smooth', 'instability_30sec', 'ventilation_cvar_30sec',
            'cpc_lfc', 'cpc_hfc',
            ]

# statistic = 'mean'

In [33]:
cols = list(itertools.product(['Breathing', 'HRV'], ['N_Segments', 'Agree', 'Discordant', '(wil-stat, pval)', 'EffectPositive'])) + ['Significance', 'Sig_Breathing', 'Sig_HRV'] # , '(t-stat, pval)'
index = list(itertools.product(['N1', 'N2', 'N3', 'R'], variables))
df_fvalues = pd.DataFrame(columns= cols, index=index)

In [34]:
stage = 'N1'
modality = 'ecg_nn'
variable = 'cpc_hfc_lfc_ratio'
statistic_extracted = 'mean'

for stage in ['N1', 'N2', 'N3', 'R']:
    for variable in variables:
        for modality in ['ecg_nn', 'amendsumeffort']:

            j_col = modality.replace('ecg_nn', 'HRV').replace('amendsumeffort', 'Breathing')
            j_index = (stage, variable)

            feature_agree = variable + '_stagewise_agrelaxed_' + modality + '_' + stage + '_' + statistic_extracted
            feature_discordant = variable + '_stagewise_disrelaxed_' + modality + '_' + stage + '_' + statistic_extracted

            if variable in ['cpc_lfc', 'cpc_hfc']:
                # For HRV derived measures, the code performs some quality check that i did not do for CPC calculation. so it's weird to use those
                # CPC results if the HRV did not qualify. so here, let's remove those CPC entries. 
                # basically same code as default except we further also only take the rows with good HRV.
                hrv_good_quality = Xy_icu[[feature_agree.replace(variable, 'hrv_lf'), feature_discordant.replace(variable, 'hrv_lf')]]
                hrv_good_quality = np.all(pd.notna(hrv_good_quality), axis=1).values
                values = Xy_icu[[feature_agree, feature_discordant]].replace('Series([], Name: hrv_nn, dtype: float32)', np.nan).astype(float)
                values = values.iloc[hrv_good_quality, :]
                values = values.dropna(axis=0, how='any').copy()

            else:
                values = Xy_icu[[feature_agree, feature_discordant]].replace('Series([], Name: hrv_nn, dtype: float32)', np.nan).astype(float).dropna(axis=0, how='any').copy()
            
            df_fvalues.loc[j_index, (j_col, 'N_Segments')] = values.shape[0]

            values_agree = values[feature_agree].values
            values_discordant = values[feature_discordant].values

            decimals=1
            if np.any([np.abs(np.mean(values_agree)) < 1, np.abs(np.mean(values_discordant)) < 1]):
                decimals=3
            elif np.any([np.abs(np.mean(values_agree)) < 1, np.abs(np.mean(values_discordant)) < 10]):
                decimals=2
            df_fvalues.loc[j_index, (j_col, 'Agree')] = np.mean(values_agree).round(decimals)
            df_fvalues.loc[j_index, (j_col, 'Discordant')] = np.mean(values_discordant).round(decimals)
            df_fvalues.loc[j_index, (j_col, 'EffectPositive')] = np.mean(values_agree).round(decimals) < np.mean(values_discordant).round(decimals)
    #         df_fvalues.loc[j_index, (j_col, '(t-stat, pval)')] = ttest_rel(values_agree, values_discordant)
            W, p = wilcoxon(values_agree, values_discordant)
            df_fvalues.loc[j_index, (j_col, '(wil-stat, pval)')] = (int(W), np.round(p, 5))

        p_hrv = df_fvalues.loc[[j_index], [('HRV', '(wil-stat, pval)')]].values[0][0][1]
        p_breathing = df_fvalues.loc[[j_index], [('Breathing', '(wil-stat, pval)')]].values[0][0][1]

        df_fvalues.loc[j_index, 'Significance'] = (p_hrv <= 0.01) | (p_breathing <= 0.01)
        df_fvalues.loc[j_index, 'Sig_Breathing'] = p_breathing <= 0.01
        df_fvalues.loc[j_index, 'Sig_HRV'] = p_hrv <= 0.01

In [35]:
df_fvalues_save = df_fvalues[[('Breathing', 'N_Segments'),           ('Breathing', 'Agree'),       ('Breathing', 'Discordant'),
       ('Breathing', '(wil-stat, pval)'), ('HRV', 'N_Segments'),
                        ('HRV', 'Agree'),             ('HRV', 'Discordant'),
             ('HRV', '(wil-stat, pval)'),   
                          'Significance']]

df_fvalues_save.to_csv('Discordant_Sleep_FeatureDifference_Analysis_Details.csv')

In [36]:
df_fvalues_save

,"(Breathing, N_Segments)","(Breathing, Agree)","(Breathing, Discordant)","(Breathing, (wil-stat, pval))","(HRV, N_Segments)","(HRV, Agree)","(HRV, Discordant)","(HRV, (wil-stat, pval))",Significance
"(N1, hrv_nn)",100,0.756,0.76,"(2091, 0.13564)",71,0.791,0.792,"(1229, 0.77889)",False
"(N1, hrv_vlf)",80,1914.6,1474.2,"(840, 0.00018)",59,2297.9,2172.6,"(773, 0.3979)",True
"(N1, hrv_lf)",80,1129.3,914.3,"(916, 0.00073)",59,1376.2,1388.9,"(848, 0.78003)",True
"(N1, hrv_hf)",80,2055,1793.7,"(994, 0.00268)",59,2858.1,3010.8,"(847, 0.77425)",True
"(N1, hrv_rmssd)",80,65.5,60,"(926, 0.00087)",59,76.3,73.1,"(655, 0.08256)",True
"(N1, ibi)",104,3.98,4.01,"(2595, 0.66155)",71,3.95,3.55,"(518, 1e-05)",True
"(N1, rr_10s_smooth)",104,17.7,17.4,"(2246, 0.11653)",71,17.8,19.5,"(537, 2e-05)",True
"(N1, instability_30sec)",104,0.243,0.238,"(2286, 0.14992)",71,0.225,0.194,"(653, 0.00034)",True
"(N1, ventilation_cvar_30sec)",104,0.235,0.233,"(2446, 0.35707)",71,0.218,0.181,"(554, 3e-05)",True
"(N1, cpc_lfc)",80,4.29,3.38,"(978, 0.00208)",59,4.92,2.67,"(588, 0.02498)",True
"(N1, cpc_hfc)",80,0.408,0.348,"(927, 0.00089)",59,0.415,0.338,"(715, 0.19944)",True
"(N2, hrv_nn)",109,0.786,0.769,"(2019, 0.00309)",35,0.867,0.853,"(229, 0.15895)",True
"(N2, hrv_vlf)",89,1258.7,1784.9,"(1008, 5e-05)",35,1055.9,1122.8,"(294, 0.73087)",True
"(N2, hrv_lf)",89,910.9,1200.5,"(1170, 0.00066)",35,726.7,726.9,"(309, 0.92171)",True
"(N2, hrv_hf)",89,2527,2355.4,"(1332, 0.00608)",35,2272,2377.2,"(300, 0.80592)",True
"(N2, hrv_rmssd)",89,67,70.2,"(1378, 0.01062)",35,55.3,54.6,"(311, 0.94776)",False
"(N2, ibi)",112,3.75,3.59,"(1677, 2e-05)",35,4.02,3.82,"(162, 0.01221)",True
"(N2, rr_10s_smooth)",112,18.1,18.8,"(1485, 0.0)",35,16.8,17.9,"(121, 0.00149)",True
"(N2, instability_30sec)",112,0.185,0.167,"(2121, 0.00246)",35,0.182,0.183,"(284, 0.61163)",True
"(N2, ventilation_cvar_30sec)",112,0.184,0.162,"(2016, 0.00086)",35,0.179,0.167,"(311, 0.94776)",True
"(N2, cpc_lfc)",89,2.11,1.88,"(1496, 0.03824)",35,2.78,1.39,"(302, 0.83138)",False
"(N2, cpc_hfc)",89,1.07,1.38,"(1939, 0.79502)",35,1.025,0.887,"(312, 0.96081)",False
"(N3, hrv_nn)",30,0.823,0.787,"(119, 0.01957)",74,0.8,0.771,"(695, 0.00019)",True
"(N3, hrv_vlf)",25,618,1793.2,"(21, 3e-05)",66,587.8,765.5,"(899, 0.18712)",True
"(N3, hrv_lf)",25,733.4,1366.3,"(50, 0.00163)",66,618.7,652.8,"(1021, 0.58934)",True
"(N3, hrv_hf)",25,2252.3,2989.3,"(62, 0.00558)",66,1586.7,1574.8,"(961, 0.35597)",True
"(N3, hrv_rmssd)",25,69.2,78.8,"(64, 0.00673)",66,56.6,56.9,"(990, 0.46062)",True
"(N3, ibi)",31,3.26,3.16,"(193, 0.28112)",74,3.66,3.68,"(1343, 0.81054)",False
"(N3, rr_10s_smooth)",31,20.2,20.7,"(182, 0.19588)",74,18.2,18.5,"(1105, 0.12804)",False
"(N3, instability_30sec)",31,0.134,0.124,"(235, 0.79891)",74,0.146,0.179,"(485, 0.0)",True
"(N3, ventilation_cvar_30sec)",31,0.131,0.117,"(182, 0.19588)",74,0.143,0.166,"(634, 5e-05)",True
"(N3, cpc_lfc)",25,0.193,1.122,"(17, 1e-05)",66,0.82,1.341,"(528, 0.00023)",True
"(N3, cpc_hfc)",25,0.344,0.474,"(94, 0.0667)",66,0.842,0.52,"(1022, 0.59375)",False
"(R, hrv_nn)",50,0.771,0.762,"(493, 0.16305)",41,0.767,0.766,"(386, 0.56418)",False
"(R, hrv_vlf)",44,1899,1922.2,"(475, 0.81545)",40,1948.2,2194.9,"(384, 0.72673)",False
"(R, hrv_lf)",44,1090.4,1137.7,"(390, 0.22044)",40,970.3,1138,"(332, 0.29444)",False
"(R, hrv_hf)",44,1803,2048.1,"(291, 0.01728)",40,1207,1408.9,"(289, 0.10387)",False
"(R, hrv_rmssd)",44,58.2,64.2,"(248, 0.00394)",40,44.3,47.4,"(303, 0.15037)",True
"(R, ibi)",53,3.54,3.57,"(711, 0.96822)",41,3.57,3.72,"(278, 0.04814)",False
"(R, rr_10s_smooth)",53,19.1,19,"(688, 0.80766)",41,18.9,18.2,"(253, 0.02144)",False
"(R, instability_30sec)",53,0.198,0.188,"(487, 0.04309)",41,0.2,0.196,"(371, 0.44069)",False
"(R, ventilation_cvar_30sec)",53,0.179,0.167,"(459, 0.02316)",41,0.178,0.183,"(375, 0.47202)",False
"(R, cpc_lfc)",44,4.1,3.1,"(443, 0.54395)",40,3.48,3.88,"(354, 0.45162)",False
"(R, cpc_hfc)",44,0.445,0.617,"(253, 0.00474)",40,0.34,0.614,"(297, 0.1288)",True

In [37]:
print(df_fvalues.Significance.values.astype(int).shape)
print(df_fvalues.Significance.values.astype(int).sum())
print(df_fvalues.Significance.values.astype(int).mean().round(3))

(44,)
28
0.636

In [38]:
print('Any significance:')
print(list(df_fvalues.index[df_fvalues.Significance==True]))
print('')
print('Breathing Disc. sleep. Significance:')
print(list(df_fvalues.index[df_fvalues.Sig_Breathing==True]))
print('')
print('HRV Disc. sleep.')
print(list(df_fvalues.index[df_fvalues.Sig_HRV==True]))

Any significance:
[('N1', 'hrv_vlf'), ('N1', 'hrv_lf'), ('N1', 'hrv_hf'), ('N1', 'hrv_rmssd'), ('N1', 'ibi'), ('N1', 'rr_10s_smooth'), ('N1', 'instability_30sec'), ('N1', 'ventilation_cvar_30sec'), ('N1', 'cpc_lfc'), ('N1', 'cpc_hfc'), ('N2', 'hrv_nn'), ('N2', 'hrv_vlf'), ('N2', 'hrv_lf'), ('N2', 'hrv_hf'), ('N2', 'ibi'), ('N2', 'rr_10s_smooth'), ('N2', 'instability_30sec'), ('N2', 'ventilation_cvar_30sec'), ('N3', 'hrv_nn'), ('N3', 'hrv_vlf'), ('N3', 'hrv_lf'), ('N3', 'hrv_hf'), ('N3', 'hrv_rmssd'), ('N3', 'instability_30sec'), ('N3', 'ventilation_cvar_30sec'), ('N3', 'cpc_lfc'), ('R', 'hrv_rmssd'), ('R', 'cpc_hfc')]

Breathing Disc. sleep. Significance:
[('N1', 'hrv_vlf'), ('N1', 'hrv_lf'), ('N1', 'hrv_hf'), ('N1', 'hrv_rmssd'), ('N1', 'cpc_lfc'), ('N1', 'cpc_hfc'), ('N2', 'hrv_nn'), ('N2', 'hrv_vlf'), ('N2', 'hrv_lf'), ('N2', 'hrv_hf'), ('N2', 'ibi'), ('N2', 'rr_10s_smooth'), ('N2', 'instability_30sec'), ('N2', 'ventilation_cvar_30sec'), ('N3', 'hrv_vlf'), ('N3', 'hrv_lf'), ('N3', 'hrv_hf'), ('N3', 'hrv_rmssd'), ('N3', 'cpc_lfc'), ('R', 'hrv_rmssd'), ('R', 'cpc_hfc')]

HRV Disc. sleep.
[('N1', 'ibi'), ('N1', 'rr_10s_smooth'), ('N1', 'instability_30sec'), ('N1', 'ventilation_cvar_30sec'), ('N2', 'rr_10s_smooth'), ('N3', 'hrv_nn'), ('N3', 'instability_30sec'), ('N3', 'ventilation_cvar_30sec'), ('N3', 'cpc_lfc')]

In [39]:
print('Breathing Disc. Sleep, Elevated Mean for Discordant Sleep:')
print(list(df_fvalues[(df_fvalues.Sig_Breathing==True) & (df_fvalues[('Breathing', 'EffectPositive')]==True)].index))
print('')
print('Breathing Disc. Sleep, Decreased Mean for Discordant Sleep:')
print(list(df_fvalues[(df_fvalues.Sig_Breathing==True) & (df_fvalues[('Breathing', 'EffectPositive')]==False)].index))
print('')
print('HRV Disc. Sleep, Elevated Mean for Discordant Sleep:')
print(list(df_fvalues[(df_fvalues.Sig_HRV==True) & (df_fvalues[('HRV', 'EffectPositive')]==True)].index))
print('')
print('HRV Disc. Sleep, Decreased Mean for Discordant Sleep:')
print(list(df_fvalues[(df_fvalues.Sig_HRV==True) & (df_fvalues[('HRV', 'EffectPositive')]==False)].index))

Breathing Disc. Sleep, Elevated Mean for Discordant Sleep:
[('N2', 'hrv_vlf'), ('N2', 'hrv_lf'), ('N2', 'rr_10s_smooth'), ('N3', 'hrv_vlf'), ('N3', 'hrv_lf'), ('N3', 'hrv_hf'), ('N3', 'hrv_rmssd'), ('N3', 'cpc_lfc'), ('R', 'hrv_rmssd'), ('R', 'cpc_hfc')]

Breathing Disc. Sleep, Decreased Mean for Discordant Sleep:
[('N1', 'hrv_vlf'), ('N1', 'hrv_lf'), ('N1', 'hrv_hf'), ('N1', 'hrv_rmssd'), ('N1', 'cpc_lfc'), ('N1', 'cpc_hfc'), ('N2', 'hrv_nn'), ('N2', 'hrv_hf'), ('N2', 'ibi'), ('N2', 'instability_30sec'), ('N2', 'ventilation_cvar_30sec')]

HRV Disc. Sleep, Elevated Mean for Discordant Sleep:
[('N1', 'rr_10s_smooth'), ('N2', 'rr_10s_smooth'), ('N3', 'instability_30sec'), ('N3', 'ventilation_cvar_30sec'), ('N3', 'cpc_lfc')]

HRV Disc. Sleep, Decreased Mean for Discordant Sleep:
[('N1', 'ibi'), ('N1', 'instability_30sec'), ('N1', 'ventilation_cvar_30sec'), ('N3', 'hrv_nn')]

In [40]:
df_effectdir = df_fvalues.loc[df_fvalues.Significance==True, ['Sig_Breathing', ('Breathing', 'EffectPositive'), 'Sig_HRV', ('HRV', 'EffectPositive')]].copy()

In [41]:
df_effectdir['Breathing_Effect_DiscordantSleep'] = np.nan
df_effectdir['HRV_Effect_DiscordantSleep'] = np.nan

for jloc, row in df_effectdir.iterrows():
    if row.Sig_Breathing == False:
        df_effectdir.loc[jloc, 'Breathing_Effect_DiscordantSleep'] = ''
    else:
        if row[('Breathing', 'EffectPositive')] == True:
            df_effectdir.loc[jloc, 'Breathing_Effect_DiscordantSleep'] = '+'
        else:
            df_effectdir.loc[jloc, 'Breathing_Effect_DiscordantSleep'] = '-'
            
    if row.Sig_HRV == False:
        df_effectdir.loc[jloc, 'HRV_Effect_DiscordantSleep'] = ''
    else:
        if row[('HRV', 'EffectPositive')] == True:
            df_effectdir.loc[jloc, 'HRV_Effect_DiscordantSleep'] = '+'
        else:
            df_effectdir.loc[jloc, 'HRV_Effect_DiscordantSleep'] = '-'

In [42]:
df_effectdir[['Breathing_Effect_DiscordantSleep', 'HRV_Effect_DiscordantSleep']].to_csv('Discordant_Sleep_FeatureDifference_Analysis_Overview.csv')

In [43]:
df_effectdir.head()

,Sig_Breathing,"(Breathing, EffectPositive)",Sig_HRV,"(HRV, EffectPositive)",Breathing_Effect_DiscordantSleep,HRV_Effect_DiscordantSleep
"(N1, hrv_vlf)",True,False,False,False,-,
"(N1, hrv_lf)",True,False,False,True,-,
"(N1, hrv_hf)",True,False,False,True,-,
"(N1, hrv_rmssd)",True,False,False,False,-,
"(N1, ibi)",False,True,True,False,,-

### compute correlation between features and proportion of discordant sleep

In [44]:
variables = ['chf', 'copd', 'CCI', 'hr_median', 'hr_q25', 'hr_q75', 'spo2_median', 'spo2_q25', 'spo2_q75', 'edw_bp_systolic_median', 'edw_bp_systolic_q25', 'edw_bp_systolic_q75', 
            'cpc_hfc_lfc_ratio_median', 'cpc_hfc_median', 'cpc_lfc_median', 'cpc_hfc_lfc_ratio_q25', 'cpc_hfc_lfc_ratio_q75',
             'hrv_nn_median', 'po2_arterial_mean', 'pco2_arterial_mean', 'hco3_arterial_mean', 'ph_arterial_mean', 'sofa_score_mean', 'sofa_score_max',
            'ibi_median', 'rr_10s_smooth_median', 'instability_30sec_median', 'ventilation_cvar_30sec_median', 'hrv_ulf_median', 'hrv_vlf_median', 'hrv_lf_median', 'hrv_hf_median', 
             'hrv_lfhf_median', 'hrv_rmssd_median', 'hrv_sd1sd2_median', 'opioids_sum', 'benzos_sum', 'antipsychotics_sum',
            ]
df_correlations = pd.DataFrame(columns=['pearson_c', 'pearson_p', 'spearman_c', 'spearman_p'], index=variables)

In [45]:
for variable in variables:
    
    var_values = Xy_icu[variable].replace('Series([], Freq: 100L, Name: hrv_nn, dtype: float32)', np.nan).astype(float).values
    discordant_prop = Xy_icu[discordant_proportion].values

    not_na = np.where(pd.notna(var_values))[0]
    var_values = var_values[not_na]
    discordant_prop = discordant_prop[not_na]

    pearson_c, pearson_p = pearsonr(var_values, discordant_prop)
    spearman_c, spearman_p = spearmanr(var_values, discordant_prop)
    
    df_correlations.loc[variable, :] = [pearson_c, pearson_p, spearman_c, spearman_p]

In [46]:
df_correlations['significance_pearson'] = df_correlations['pearson_p'] < 0.05
df_correlations['significance_spearman'] = df_correlations['spearman_p'] < 0.05

In [47]:
df_correlations.round(3)

,pearson_c,pearson_p,spearman_c,spearman_p,significance_pearson,significance_spearman
chf,-0.0484342,0.539236,-0.0261924,0.739976,False,False
copd,-0.149735,0.0564242,-0.151805,0.0530612,False,False
CCI,-0.0610756,0.438645,-0.0634193,0.421246,False,False
hr_median,-0.103006,0.190721,-0.07796,0.322579,False,False
hr_q25,-0.123631,0.115881,-0.0988157,0.209494,False,False
hr_q75,-0.126543,0.107478,-0.0742887,0.345958,False,False
spo2_median,-0.0507779,0.51976,-0.0391932,0.619383,False,False
spo2_q25,-0.0783765,0.319992,-0.0529948,0.501674,False,False
spo2_q75,-0.0417017,0.597122,-0.0349959,0.657408,False,False
edw_bp_systolic_median,-0.118746,0.165389,-0.111583,0.192592,False,False
edw_bp_systolic_q25,-0.0879874,0.304793,-0.0765253,0.372339,False,False
edw_bp_systolic_q75,-0.116256,0.174498,-0.121444,0.155919,False,False
cpc_hfc_lfc_ratio_median,0.133038,0.094574,0.153795,0.0529283,False,False
cpc_hfc_median,-0.00187051,0.981272,-0.00204665,0.979508,False,False
cpc_lfc_median,-0.144065,0.0691407,-0.0966627,0.224,False,False
cpc_hfc_lfc_ratio_q25,0.107982,0.175474,0.14185,0.0744926,False,False
cpc_hfc_lfc_ratio_q75,0.154393,0.0520001,0.168314,0.0339411,False,True
hrv_nn_median,0.145504,0.0663805,0.110351,0.16479,False,False
po2_arterial_mean,-0.473124,0.0351254,-0.42406,0.0624065,True,False
pco2_arterial_mean,0.12738,0.592533,-0.162528,0.493583,False,False
hco3_arterial_mean,0.136081,0.567281,0.0361583,0.879706,False,False
ph_arterial_mean,0.0241618,0.919462,0.0775311,0.745262,False,False
sofa_score_mean,0.069868,0.375492,0.116677,0.13801,False,False
sofa_score_max,0.0586497,0.457078,0.0895043,0.255872,False,False
ibi_median,-0.185786,0.0175766,-0.207116,0.0079837,True,True
rr_10s_smooth_median,0.235182,0.00251108,0.218415,0.00509477,True,True
instability_30sec_median,-0.256294,0.000958988,-0.267895,0.000545531,True,True
ventilation_cvar_30sec_median,-0.281789,0.000268349,-0.312875,4.77569e-05,True,True
hrv_ulf_median,-0.050011,0.548862,-0.115926,0.163497,False,False
hrv_vlf_median,-0.0991805,0.233638,-0.18242,0.0275404,False,True
hrv_lf_median,-0.0560789,0.501387,-0.0769071,0.356189,False,False
hrv_hf_median,-0.00607368,0.941998,0.0476165,0.568182,False,False
hrv_lfhf_median,-0.218645,0.00801716,-0.225728,0.0061536,True,True
hrv_rmssd_median,0.0380433,0.648467,0.0875729,0.293225,False,False
hrv_sd1sd2_median,0.206015,0.0126058,0.203413,0.0137965,True,True
opioids_sum,-0.0857905,0.276207,-0.0804131,0.30754,False,False
benzos_sum,-0.0224143,0.776411,0.0122068,0.877095,False,False
antipsychotics_sum,-0.0390815,0.620382,0.0200301,0.799662,False,False

In [48]:
savedir = '/scr/wolfgang/Dropbox (Partners HealthCare)/SleepInICUandSleeplabPaper/Results'

df_correlations.loc[['sofa_score_max', 'opioids_sum', 'benzos_sum', 'antipsychotics_sum']].to_csv(os.path.join(savedir, 'Discordant_Sleep_CorrelationsMedsSOFA.csv'))

### Linear Regression. 
Independent variable: proportion of discordance (transformed)  
Dependent variables: sleep-stagewise (both breathing and hrv models) features

In [49]:
# same variables as above for 'statistical difference check'
variables = ['hrv_nn',  'hrv_vlf', 'hrv_lf', 'hrv_hf', 'hrv_rmssd',
            'ibi', 'rr_10s_smooth', 'instability_30sec', 'ventilation_cvar_30sec',
            'cpc_lfc', 'cpc_hfc']

In [50]:
vars_dependent = []

for stage in ['N1', 'N2', 'N3', 'R']:
    for variable in variables:
        for modality in ['ecg_nn', 'amendsumeffort']:
            for statistic_extracted in ['mean', 'std', 'median', 'q25', 'q75']:
                vars_dependent += [variable + '_stagewise_agrelaxed_' + modality + '_' + stage + '_' + statistic_extracted]
                vars_dependent += [variable + '_stagewise_disrelaxed_' + modality + '_' + stage + '_' + statistic_extracted]
                
vars_dependent += ['hours_data_ecg_nn_all',
'hours_sleep_ecg_nn_all',
'stages_distribution_breathing_R',
'stages_distribution_breathing_N1',
'stages_distribution_breathing_N2',
'stages_distribution_breathing_N3']

In [51]:
X = Xy_icu[vars_dependent].copy()
X = X.replace('Series([], Name: hrv_nn, dtype: float32)', np.nan)
X = X.astype(float)
X = X.replace(np.inf, np.nan)
X.dropna(how='all', axis=1, inplace=True)
X.dropna(how='all', axis=0, inplace=True)
X = X.fillna(X.mean())
# X = X.values

In [52]:
X.shape

(163, 886)

In [53]:
list(df_fvalues.index[df_fvalues.Significance==True]);

In [59]:
y = Xy_icu[discordant_proportion].values
y = y + 0.0001
# transform y so it is more gaussian and unbounded (instead of [0, 1]):
y = np.log(np.divide(y, (1 - y)))

In [60]:
plt.figure(figsize=(4, 2))
plt.hist(y, histtype='step');

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [61]:
import statsmodels.api as sm

In [62]:
fvals = []
fpvals = []
nparams = []
rsquared = []
alpha_range = np.arange(0.01, 10, 0.1)
for alpha in alpha_range:
    lin_reg = sm.OLS(y, sm.add_constant(X)).fit_regularized(alpha=alpha, L1_wt=1)
    X_elasticnet = X.loc[:, lin_reg.params[1:] > 0]
    lin_reg = sm.OLS(y, sm.add_constant(X_elasticnet)).fit()
    fvals.append(lin_reg.fvalue)
    fpvals.append(lin_reg.f_pvalue)
    nparams.append(sum(lin_reg.params > 0))
    rsquared.append(lin_reg.rsquared)

/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

In [63]:
plt.close('all')

fig, ax = plt.subplots(4, 1, figsize=(6,4), sharex=True)
ax[0].plot(alpha_range, rsquared)
ax[0].set_ylabel('R squared')

ax[1].plot(alpha_range, fpvals)
ax[1].plot(alpha_range, [0.05] * len(alpha_range), c='r', ls='--', lw=0.8)
ax[1].set_yticks([0.05, 0.2, 0.4, 0.6])
ax[1].set_ylabel('F p-value')

ax[2].plot(alpha_range, fvals)
ax[2].set_ylabel('F statistic')
ax[2].set_yticks([0, 2, 4, 6, 8])
ax[3].plot(alpha_range, nparams)
ax[3].set_ylabel('# Variables\nincluded\nin Model')
ax[3].set_xlabel('Regularization strength LASSO (alpha)')

plt.tight_layout()
plt.subplots_adjust(hspace=0)
plt.savefig('discordance_linear_regression_results.tiff', dpi=500)
plt.savefig('discordance_linear_regression_results.svg', dpi=500)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [403]:
plt.subplots_adjust?

Signature:
plt.subplots_adjust(
    left=None,
    bottom=None,
    right=None,
    top=None,
    wspace=None,
    hspace=None,
)
Docstring:
Tune the subplot layout.

The parameter meanings (and suggested defaults) are::

  left = 0.125  # the left side of the subplots of the figure
  right = 0.9   # the right side of the subplots of the figure
  bottom = 0.1  # the bottom of the subplots of the figure
  top = 0.9     # the top of the subplots of the figure
  wspace = 0.2  # the amount of width reserved for space between subplots,
                # expressed as a fraction of the average axis width
  hspace = 0.2  # the amount of height reserved for space between subplots,
                # expressed as a fraction of the average axis height

The actual defaults are controlled by the rc file
File:      ~/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/matplotlib/pyplot.py
Type:      function

In [70]:
alpha = 4
lin_reg = sm.OLS(y, sm.add_constant(X)).fit_regularized(alpha=alpha, L1_wt=1)
X_elasticnet = X.loc[:, lin_reg.params[1:] > 0]
lin_reg = sm.OLS(y, sm.add_constant(X_elasticnet)).fit()
lin_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.424
Model:                            OLS   Adj. R-squared:                  0.143
Method:                 Least Squares   F-statistic:                     1.511
Date:                Fri, 23 Jul 2021   Prob (F-statistic):             0.0359
Time:                        10:36:42   Log-Likelihood:                -246.87
No. Observations:                 163   AIC:                             601.7
Df Residuals:                     109   BIC:                             768.8
Df Model:                          53
Covariance Type:            nonrobust
========================================================================================================================
                                                           coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------------
const                                                   -2.4044      0.753     -3.194      0.002      -3.896      -0.912
hrv_vlf_stagewise_agrelaxed_ecg_nn_N1_median         -6.601e-05      0.000     -0.234      0.815      -0.001       0.000
hrv_vlf_stagewise_disrelaxed_ecg_nn_N1_q25              -0.0003      0.000     -0.677      0.500      -0.001       0.001
hrv_vlf_stagewise_agrelaxed_amendsumeffort_N1_q75    -6.231e-05      0.000     -0.316      0.753      -0.000       0.000
hrv_lf_stagewise_disrelaxed_ecg_nn_N1_mean               0.0004      0.001      0.556      0.579      -0.001       0.002
hrv_lf_stagewise_disrelaxed_ecg_nn_N1_std             7.668e-05      0.000      0.163      0.871      -0.001       0.001
hrv_hf_stagewise_agrelaxed_ecg_nn_N1_std                -0.0004      0.000     -1.063      0.290      -0.001       0.000
hrv_hf_stagewise_agrelaxed_ecg_nn_N1_median           8.735e-05      0.001      0.132      0.895      -0.001       0.001
hrv_hf_stagewise_agrelaxed_ecg_nn_N1_q25                -0.0008      0.001     -1.386      0.169      -0.002       0.000
hrv_hf_stagewise_agrelaxed_ecg_nn_N1_q75                 0.0002      0.000      0.537      0.593      -0.000       0.001
hrv_hf_stagewise_agrelaxed_amendsumeffort_N1_mean       -0.0002      0.001     -0.360      0.720      -0.001       0.001
hrv_hf_stagewise_agrelaxed_amendsumeffort_N1_median      0.0003      0.001      0.396      0.693      -0.001       0.002
hrv_vlf_stagewise_disrelaxed_ecg_nn_N2_mean             -0.0011      0.001     -1.325      0.188      -0.003       0.001
hrv_vlf_stagewise_disrelaxed_ecg_nn_N2_std               0.0006      0.001      1.001      0.319      -0.001       0.002
hrv_vlf_stagewise_agrelaxed_ecg_nn_N2_q75            -3.252e-05      0.000     -0.112      0.911      -0.001       0.001
hrv_vlf_stagewise_disrelaxed_amendsumeffort_N2_std      -0.0001      0.000     -0.588      0.558      -0.001       0.000
hrv_vlf_stagewise_agrelaxed_amendsumeffort_N2_q75        0.0002      0.000      0.952      0.343      -0.000       0.001
hrv_lf_stagewise_disrelaxed_amendsumeffort_N2_q75       -0.0001      0.000     -0.247      0.806      -0.001       0.001
hrv_hf_stagewise_disrelaxed_ecg_nn_N2_mean               0.0002      0.000      0.926      0.356      -0.000       0.001
hrv_hf_stagewise_disrelaxed_amendsumeffort_N2_mean       0.0012      0.003      0.376      0.707      -0.005       0.007
hrv_hf_stagewise_disrelaxed_amendsumeffort_N2_std    -1.602e-05      0.001     -0.013      0.990      -0.003       0.002
hrv_hf_stagewise_disrelaxed_amendsumeffort_N2_median     0.0004      0.001      0.426      0.671      -0.001       0.002
hrv_hf_stagewise_disrelaxed_amendsumeffort_N2_q25       -0.0006      0.002     -0.389      0.698      -0.004       0.003
hrv_hf_stagewise_disrelaxed_amendsumeffort_N2_q75       -0.0007      0.001     -0.702      0.484      -0.003       0.001
hrv_vlf_stagewise_agrelaxed_amendsumeffort_N3_q75       -0.0003      0.001     -0.487      0.627      -0.002       0.001
hrv_lf_stagewise_agrelaxed_ecg_nn_N3_median              0.0017      0.002      1.001      0.319      -0.002       0.005
hrv_lf_stagewise_agrelaxed_ecg_nn_N3_q75                -0.0010      0.001     -0.848      0.398      -0.003       0.001
hrv_lf_stagewise_agrelaxed_amendsumeffort_N3_std         0.0012      0.001      1.324      0.188      -0.001       0.003
hrv_hf_stagewise_disrelaxed_ecg_nn_N3_mean               0.0006      0.001      0.660      0.511      -0.001       0.002
hrv_hf_stagewise_agrelaxed_ecg_nn_N3_median           2.312e-05      0.000      0.100      0.920      -0.000       0.000
hrv_hf_stagewise_disrelaxed_ecg_nn_N3_median            -0.0002      0.001     -0.194      0.846      -0.003       0.002
hrv_hf_stagewise_disrelaxed_ecg_nn_N3_q25               -0.0003      0.001     -0.260      0.795      -0.003       0.002
hrv_hf_stagewise_agrelaxed_amendsumeffort_N3_std        -0.0007      0.001     -1.022      0.309      -0.002       0.001
hrv_hf_stagewise_agrelaxed_amendsumeffort_N3_q75      3.954e-05      0.000      0.172      0.864      -0.000       0.000
hrv_vlf_stagewise_agrelaxed_ecg_nn_R_mean               -0.0006      0.002     -0.409      0.683      -0.004       0.002
hrv_vlf_stagewise_disrelaxed_ecg_nn_R_std             9.315e-05      0.000      0.257      0.798      -0.001       0.001
hrv_vlf_stagewise_agrelaxed_ecg_nn_R_median             -0.0002      0.001     -0.170      0.865      -0.003       0.002
hrv_vlf_stagewise_agrelaxed_ecg_nn_R_q25                 0.0013      0.001      0.966      0.336      -0.001       0.004
hrv_vlf_stagewise_agrelaxed_ecg_nn_R_q75                 0.0003      0.001      0.357      0.722      -0.001       0.002
hrv_vlf_stagewise_disrelaxed_ecg_nn_R_q75               -0.0001      0.000     -0.462      0.645      -0.001       0.000
hrv_vlf_stagewise_agrelaxed_amendsumeffort_R_mean        0.0003      0.002      0.178      0.859      -0.003       0.004
hrv_vlf_stagewise_agrelaxed_amendsumeffort_R_std      8.154e-05      0.001      0.103      0.918      -0.001       0.002
hrv_vlf_stagewise_disrelaxed_amendsumeffort_R_median -5.375e-05      0.000     -0.189      0.850      -0.001       0.001
hrv_vlf_stagewise_agrelaxed_amendsumeffort_R_q75        -0.0001      0.001     -0.124      0.902      -0.002       0.002
hrv_lf_stagewise_disrelaxed_ecg_nn_R_median          -5.326e-05      0.000     -0.129      0.898      -0.001       0.001
hrv_lf_stagewise_agrelaxed_amendsumeffort_R_mean        -0.0006      0.002     -0.267      0.790      -0.005       0.004
hrv_lf_stagewise_agrelaxed_amendsumeffort_R_q75          0.0006      0.001      0.432      0.667      -0.002       0.003
hrv_hf_stagewise_disrelaxed_ecg_nn_R_std                 0.0005      0.001      0.795      0.428      -0.001       0.002
hrv_hf_stagewise_agrelaxed_ecg_nn_R_q25                 -0.0003      0.001     -0.319      0.751      -0.002       0.002
hrv_hf_stagewise_disrelaxed_amendsumeffort_R_mean       -0.0011      0.001     -1.059      0.292      -0.003       0.001
hrv_hf_stagewise_disrelaxed_amendsumeffort_R_median      0.0008      0.000      1.623      0.107      -0.000       0.002
hrv_hf_stagewise_disrelaxed_amendsumeffort_R_q75         0.0003      0.001      0.399      0.691      -0.001       0.002
stages_distribution_breathing_R                          0.0352      0.005      6.578      0.000       0.025       0.046
stages_distribution_breathing_N2                         0.0279      0.007      4.142      0.000       0.015       0.041
==============================================================================
Omnibus:                      161.493   Durbin-Watson:                   2.110
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3836.287
Skew:                          -3.580   Prob(JB):                         0.00
Kurtosis:                      25.663   Cond. No.                     1.11e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.11e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [400]:
lin_reg.params.to_csv('discordance_final_model_params.csv')

/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.

In [380]:
sum(lin_reg.params > 0)

32

In [381]:
print(X_elasticnet.shape)

(129, 56)

In [31]:
plt.figure(figsize=(4, 2))
plt.hist(Xy_icu[discordant_proportion], histtype='step')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([ 7.,  5., 11., 19., 13., 14., 20., 20., 10., 10.]),
 array([0.02580645, 0.11342346, 0.20104047, 0.28865748, 0.37627449,
        0.4638915 , 0.55150851, 0.63912553, 0.72674254, 0.81435955,
        0.90197656]),
 <a list of 1 Patch objects>)

In [52]:
plt.figure(figsize=(4, 2))
plt.hist(Xy_icu['sofa_score_max'], histtype='step')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([18., 32., 34., 12., 13.,  7.,  5.,  6.,  1.,  1.]),
 array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 8.1, 9. ]),
 <a list of 1 Patch objects>)

In [58]:
variable = 'opioids_sum'
var_values = Xy_icu[variable].values
discordant_prop = Xy_icu[discordant_proportion].values
not_na = np.where(pd.notna(var_values))[0]
var_values = var_values[not_na]
discordant_prop = discordant_prop[not_na]

In [59]:
plt.figure()
plt.scatter(var_values, discordant_prop)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [330]:
variable1 = 'opioids_sum'
variable2 = 'stages_distribution_breathing_R'


var1_values = Xy_icu[variable1].astype(float).values
var2_values = Xy_icu[variable2].astype(float).values

not_na = np.where(pd.notna(var1_values) & pd.notna(var2_values))[0]
var1_values = var1_values[not_na]
var2_values = var2_values[not_na]

pearson_c, pearson_p = pearsonr(var1_values, var2_values)
spearman_c, spearman_p = spearmanr(var1_values, var2_values)
plt.figure(figsize=(3,3))
plt.scatter(var1_values, var2_values)
print(np.array([pearson_c, pearson_p, spearman_c, spearman_p]).round(4))

/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[0.0284 0.7536 0.0175 0.8465]

In [329]:
[x for x in Xy_icu.columns if 'R' in x]

['stages_distribution_breathing_R',
 'stages_distribution_breathing_agrelaxed_R',
 'stages_distribution_ecg_nn_R',
 'stages_distribution_ecg_nn_agrelaxed_R',
 'stages_distribution_expert_R',
 'hr_stagewise_agrelaxed_ecg_nn_R_mean',
 'hr_stagewise_agrelaxed_ecg_nn_R_std',
 'hr_stagewise_agrelaxed_ecg_nn_R_median',
 'hr_stagewise_agrelaxed_ecg_nn_R_q25',
 'hr_stagewise_agrelaxed_ecg_nn_R_q75',
 'hr_stagewise_agrelaxed_ecg_nn_R_sda',
 'hr_stagewise_agrelaxed_ecg_nn_R_asd',
 'hr_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hr_stagewise_agrelaxed_amendsumeffort_R_std',
 'hr_stagewise_agrelaxed_amendsumeffort_R_median',
 'hr_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hr_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hr_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hr_stagewise_agrelaxed_amendsumeffort_R_asd',
 'spo2_stagewise_agrelaxed_ecg_nn_R_mean',
 'spo2_stagewise_agrelaxed_ecg_nn_R_std',
 'spo2_stagewise_agrelaxed_ecg_nn_R_median',
 'spo2_stagewise_agrelaxed_ecg_nn_R_q25',
 'spo2_stagewise_agrelaxed_ecg_nn_R_q75',
 'spo2_stagewise_agrelaxed_ecg_nn_R_sda',
 'spo2_stagewise_agrelaxed_ecg_nn_R_asd',
 'spo2_stagewise_agrelaxed_amendsumeffort_R_mean',
 'spo2_stagewise_agrelaxed_amendsumeffort_R_std',
 'spo2_stagewise_agrelaxed_amendsumeffort_R_median',
 'spo2_stagewise_agrelaxed_amendsumeffort_R_q25',
 'spo2_stagewise_agrelaxed_amendsumeffort_R_q75',
 'spo2_stagewise_agrelaxed_amendsumeffort_R_sda',
 'spo2_stagewise_agrelaxed_amendsumeffort_R_asd',
 'spo2_airgo_stagewise_agrelaxed_ecg_nn_R_mean',
 'spo2_airgo_stagewise_agrelaxed_ecg_nn_R_std',
 'spo2_airgo_stagewise_agrelaxed_ecg_nn_R_median',
 'spo2_airgo_stagewise_agrelaxed_ecg_nn_R_q25',
 'spo2_airgo_stagewise_agrelaxed_ecg_nn_R_q75',
 'spo2_airgo_stagewise_agrelaxed_ecg_nn_R_sda',
 'spo2_airgo_stagewise_agrelaxed_ecg_nn_R_asd',
 'spo2_airgo_stagewise_agrelaxed_amendsumeffort_R_mean',
 'spo2_airgo_stagewise_agrelaxed_amendsumeffort_R_std',
 'spo2_airgo_stagewise_agrelaxed_amendsumeffort_R_median',
 'spo2_airgo_stagewise_agrelaxed_amendsumeffort_R_q25',
 'spo2_airgo_stagewise_agrelaxed_amendsumeffort_R_q75',
 'spo2_airgo_stagewise_agrelaxed_amendsumeffort_R_sda',
 'spo2_airgo_stagewise_agrelaxed_amendsumeffort_R_asd',
 'edw_bp_systolic_stagewise_agrelaxed_ecg_nn_R_mean',
 'edw_bp_systolic_stagewise_agrelaxed_ecg_nn_R_std',
 'edw_bp_systolic_stagewise_agrelaxed_ecg_nn_R_median',
 'edw_bp_systolic_stagewise_agrelaxed_ecg_nn_R_q25',
 'edw_bp_systolic_stagewise_agrelaxed_ecg_nn_R_q75',
 'edw_bp_systolic_stagewise_agrelaxed_amendsumeffort_R_mean',
 'edw_bp_systolic_stagewise_agrelaxed_amendsumeffort_R_std',
 'edw_bp_systolic_stagewise_agrelaxed_amendsumeffort_R_median',
 'edw_bp_systolic_stagewise_agrelaxed_amendsumeffort_R_q25',
 'edw_bp_systolic_stagewise_agrelaxed_amendsumeffort_R_q75',
 'edw_bp_diastolic_stagewise_agrelaxed_ecg_nn_R_mean',
 'edw_bp_diastolic_stagewise_agrelaxed_ecg_nn_R_std',
 'edw_bp_diastolic_stagewise_agrelaxed_ecg_nn_R_median',
 'edw_bp_diastolic_stagewise_agrelaxed_ecg_nn_R_q25',
 'edw_bp_diastolic_stagewise_agrelaxed_ecg_nn_R_q75',
 'edw_bp_diastolic_stagewise_agrelaxed_amendsumeffort_R_mean',
 'edw_bp_diastolic_stagewise_agrelaxed_amendsumeffort_R_std',
 'edw_bp_diastolic_stagewise_agrelaxed_amendsumeffort_R_median',
 'edw_bp_diastolic_stagewise_agrelaxed_amendsumeffort_R_q25',
 'edw_bp_diastolic_stagewise_agrelaxed_amendsumeffort_R_q75',
 'edw_bp_map_stagewise_agrelaxed_ecg_nn_R_mean',
 'edw_bp_map_stagewise_agrelaxed_ecg_nn_R_std',
 'edw_bp_map_stagewise_agrelaxed_ecg_nn_R_median',
 'edw_bp_map_stagewise_agrelaxed_ecg_nn_R_q25',
 'edw_bp_map_stagewise_agrelaxed_ecg_nn_R_q75',
 'edw_bp_map_stagewise_agrelaxed_amendsumeffort_R_mean',
 'edw_bp_map_stagewise_agrelaxed_amendsumeffort_R_std',
 'edw_bp_map_stagewise_agrelaxed_amendsumeffort_R_median',
 'edw_bp_map_stagewise_agrelaxed_amendsumeffort_R_q25',
 'edw_bp_map_stagewise_agrelaxed_amendsumeffort_R_q75',
 'cpc_hfc_lfc_ratio_stagewise_agrelaxed_ecg_nn_R_mean',
 'cpc_hfc_lfc_ratio_stagewise_agrelaxed_ecg_nn_R_std',
 'cpc_hfc_lfc_ratio_stagewise_agrelaxed_ecg_nn_R_median',
 'cpc_hfc_lfc_ratio_stagewise_agrelaxed_ecg_nn_R_q25',
 'cpc_hfc_lfc_ratio_stagewise_agrelaxed_ecg_nn_R_q75',
 'cpc_hfc_lfc_ratio_stagewise_agrelaxed_amendsumeffort_R_mean',
 'cpc_hfc_lfc_ratio_stagewise_agrelaxed_amendsumeffort_R_std',
 'cpc_hfc_lfc_ratio_stagewise_agrelaxed_amendsumeffort_R_median',
 'cpc_hfc_lfc_ratio_stagewise_agrelaxed_amendsumeffort_R_q25',
 'cpc_hfc_lfc_ratio_stagewise_agrelaxed_amendsumeffort_R_q75',
 'cpc_hfc_stagewise_agrelaxed_ecg_nn_R_mean',
 'cpc_hfc_stagewise_agrelaxed_ecg_nn_R_std',
 'cpc_hfc_stagewise_agrelaxed_ecg_nn_R_median',
 'cpc_hfc_stagewise_agrelaxed_ecg_nn_R_q25',
 'cpc_hfc_stagewise_agrelaxed_ecg_nn_R_q75',
 'cpc_hfc_stagewise_agrelaxed_ecg_nn_R_sum',
 'cpc_hfc_stagewise_agrelaxed_amendsumeffort_R_mean',
 'cpc_hfc_stagewise_agrelaxed_amendsumeffort_R_std',
 'cpc_hfc_stagewise_agrelaxed_amendsumeffort_R_median',
 'cpc_hfc_stagewise_agrelaxed_amendsumeffort_R_q25',
 'cpc_hfc_stagewise_agrelaxed_amendsumeffort_R_q75',
 'cpc_hfc_stagewise_agrelaxed_amendsumeffort_R_sum',
 'cpc_lfc_stagewise_agrelaxed_ecg_nn_R_mean',
 'cpc_lfc_stagewise_agrelaxed_ecg_nn_R_std',
 'cpc_lfc_stagewise_agrelaxed_ecg_nn_R_median',
 'cpc_lfc_stagewise_agrelaxed_ecg_nn_R_q25',
 'cpc_lfc_stagewise_agrelaxed_ecg_nn_R_q75',
 'cpc_lfc_stagewise_agrelaxed_ecg_nn_R_sum',
 'cpc_lfc_stagewise_agrelaxed_amendsumeffort_R_mean',
 'cpc_lfc_stagewise_agrelaxed_amendsumeffort_R_std',
 'cpc_lfc_stagewise_agrelaxed_amendsumeffort_R_median',
 'cpc_lfc_stagewise_agrelaxed_amendsumeffort_R_q25',
 'cpc_lfc_stagewise_agrelaxed_amendsumeffort_R_q75',
 'cpc_lfc_stagewise_agrelaxed_amendsumeffort_R_sum',
 'hrv_nn_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_nn_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_nn_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_nn_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_nn_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_nn_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_nn_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_nn_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hrv_nn_stagewise_agrelaxed_amendsumeffort_R_std',
 'hrv_nn_stagewise_agrelaxed_amendsumeffort_R_median',
 'hrv_nn_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hrv_nn_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hrv_nn_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hrv_nn_stagewise_agrelaxed_amendsumeffort_R_asd',
 'oxygen_flow_rate_stagewise_agrelaxed_ecg_nn_R_max',
 'oxygen_flow_rate_stagewise_agrelaxed_amendsumeffort_R_max',
 'spo2_available_stagewise_agrelaxed_ecg_nn_R',
 'spo2_available_stagewise_agrelaxed_amendsumeffort_R',
 'spo2_airgo_available_stagewise_agrelaxed_ecg_nn_R',
 'spo2_airgo_available_stagewise_agrelaxed_amendsumeffort_R',
 'ibi_stagewise_agrelaxed_ecg_nn_R_mean',
 'ibi_stagewise_agrelaxed_ecg_nn_R_std',
 'ibi_stagewise_agrelaxed_ecg_nn_R_median',
 'ibi_stagewise_agrelaxed_ecg_nn_R_q25',
 'ibi_stagewise_agrelaxed_ecg_nn_R_q75',
 'ibi_stagewise_agrelaxed_ecg_nn_R_sda',
 'ibi_stagewise_agrelaxed_ecg_nn_R_asd',
 'ibi_stagewise_agrelaxed_amendsumeffort_R_mean',
 'ibi_stagewise_agrelaxed_amendsumeffort_R_std',
 'ibi_stagewise_agrelaxed_amendsumeffort_R_median',
 'ibi_stagewise_agrelaxed_amendsumeffort_R_q25',
 'ibi_stagewise_agrelaxed_amendsumeffort_R_q75',
 'ibi_stagewise_agrelaxed_amendsumeffort_R_sda',
 'ibi_stagewise_agrelaxed_amendsumeffort_R_asd',
 'rr_10s_smooth_stagewise_agrelaxed_ecg_nn_R_mean',
 'rr_10s_smooth_stagewise_agrelaxed_ecg_nn_R_std',
 'rr_10s_smooth_stagewise_agrelaxed_ecg_nn_R_median',
 'rr_10s_smooth_stagewise_agrelaxed_ecg_nn_R_q25',
 'rr_10s_smooth_stagewise_agrelaxed_ecg_nn_R_q75',
 'rr_10s_smooth_stagewise_agrelaxed_ecg_nn_R_sda',
 'rr_10s_smooth_stagewise_agrelaxed_ecg_nn_R_asd',
 'rr_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_mean',
 'rr_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_std',
 'rr_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_median',
 'rr_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_q25',
 'rr_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_q75',
 'rr_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_sda',
 'rr_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_asd',
 'instability_1min_stagewise_agrelaxed_ecg_nn_R_mean',
 'instability_1min_stagewise_agrelaxed_ecg_nn_R_std',
 'instability_1min_stagewise_agrelaxed_ecg_nn_R_median',
 'instability_1min_stagewise_agrelaxed_ecg_nn_R_q25',
 'instability_1min_stagewise_agrelaxed_ecg_nn_R_q75',
 'instability_1min_stagewise_agrelaxed_ecg_nn_R_sda',
 'instability_1min_stagewise_agrelaxed_ecg_nn_R_asd',
 'instability_1min_stagewise_agrelaxed_amendsumeffort_R_mean',
 'instability_1min_stagewise_agrelaxed_amendsumeffort_R_std',
 'instability_1min_stagewise_agrelaxed_amendsumeffort_R_median',
 'instability_1min_stagewise_agrelaxed_amendsumeffort_R_q25',
 'instability_1min_stagewise_agrelaxed_amendsumeffort_R_q75',
 'instability_1min_stagewise_agrelaxed_amendsumeffort_R_sda',
 'instability_1min_stagewise_agrelaxed_amendsumeffort_R_asd',
 'instability_30sec_stagewise_agrelaxed_ecg_nn_R_mean',
 'instability_30sec_stagewise_agrelaxed_ecg_nn_R_std',
 'instability_30sec_stagewise_agrelaxed_ecg_nn_R_median',
 'instability_30sec_stagewise_agrelaxed_ecg_nn_R_q25',
 'instability_30sec_stagewise_agrelaxed_ecg_nn_R_q75',
 'instability_30sec_stagewise_agrelaxed_ecg_nn_R_sda',
 'instability_30sec_stagewise_agrelaxed_ecg_nn_R_asd',
 'instability_30sec_stagewise_agrelaxed_amendsumeffort_R_mean',
 'instability_30sec_stagewise_agrelaxed_amendsumeffort_R_std',
 'instability_30sec_stagewise_agrelaxed_amendsumeffort_R_median',
 'instability_30sec_stagewise_agrelaxed_amendsumeffort_R_q25',
 'instability_30sec_stagewise_agrelaxed_amendsumeffort_R_q75',
 'instability_30sec_stagewise_agrelaxed_amendsumeffort_R_sda',
 'instability_30sec_stagewise_agrelaxed_amendsumeffort_R_asd',
 'ventilation_10s_smooth_stagewise_agrelaxed_ecg_nn_R_mean',
 'ventilation_10s_smooth_stagewise_agrelaxed_ecg_nn_R_std',
 'ventilation_10s_smooth_stagewise_agrelaxed_ecg_nn_R_median',
 'ventilation_10s_smooth_stagewise_agrelaxed_ecg_nn_R_q25',
 'ventilation_10s_smooth_stagewise_agrelaxed_ecg_nn_R_q75',
 'ventilation_10s_smooth_stagewise_agrelaxed_ecg_nn_R_sda',
 'ventilation_10s_smooth_stagewise_agrelaxed_ecg_nn_R_asd',
 'ventilation_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_mean',
 'ventilation_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_std',
 'ventilation_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_median',
 'ventilation_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_q25',
 'ventilation_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_q75',
 'ventilation_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_sda',
 'ventilation_10s_smooth_stagewise_agrelaxed_amendsumeffort_R_asd',
 'ventilation_cvar_30sec_stagewise_agrelaxed_ecg_nn_R_mean',
 'ventilation_cvar_30sec_stagewise_agrelaxed_ecg_nn_R_std',
 'ventilation_cvar_30sec_stagewise_agrelaxed_ecg_nn_R_median',
 'ventilation_cvar_30sec_stagewise_agrelaxed_ecg_nn_R_q25',
 'ventilation_cvar_30sec_stagewise_agrelaxed_ecg_nn_R_q75',
 'ventilation_cvar_30sec_stagewise_agrelaxed_ecg_nn_R_sda',
 'ventilation_cvar_30sec_stagewise_agrelaxed_ecg_nn_R_asd',
 'ventilation_cvar_30sec_stagewise_agrelaxed_amendsumeffort_R_mean',
 'ventilation_cvar_30sec_stagewise_agrelaxed_amendsumeffort_R_std',
 'ventilation_cvar_30sec_stagewise_agrelaxed_amendsumeffort_R_median',
 'ventilation_cvar_30sec_stagewise_agrelaxed_amendsumeffort_R_q25',
 'ventilation_cvar_30sec_stagewise_agrelaxed_amendsumeffort_R_q75',
 'ventilation_cvar_30sec_stagewise_agrelaxed_amendsumeffort_R_sda',
 'ventilation_cvar_30sec_stagewise_agrelaxed_amendsumeffort_R_asd',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_ecg_nn_R_mean',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_ecg_nn_R_std',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_ecg_nn_R_median',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_ecg_nn_R_q25',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_ecg_nn_R_q75',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_ecg_nn_R_sda',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_ecg_nn_R_asd',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_amendsumeffort_R_mean',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_amendsumeffort_R_std',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_amendsumeffort_R_median',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_amendsumeffort_R_q25',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_amendsumeffort_R_q75',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_amendsumeffort_R_sda',
 'inht_cycle_ratio_10sec_stagewise_agrelaxed_amendsumeffort_R_asd',
 'hrv_ulf_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_ulf_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_ulf_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_ulf_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_ulf_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_ulf_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_ulf_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_ulf_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hrv_ulf_stagewise_agrelaxed_amendsumeffort_R_std',
 'hrv_ulf_stagewise_agrelaxed_amendsumeffort_R_median',
 'hrv_ulf_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hrv_ulf_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hrv_ulf_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hrv_ulf_stagewise_agrelaxed_amendsumeffort_R_asd',
 'hrv_vlf_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_vlf_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_vlf_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_vlf_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_vlf_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_vlf_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_vlf_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_vlf_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hrv_vlf_stagewise_agrelaxed_amendsumeffort_R_std',
 'hrv_vlf_stagewise_agrelaxed_amendsumeffort_R_median',
 'hrv_vlf_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hrv_vlf_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hrv_vlf_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hrv_vlf_stagewise_agrelaxed_amendsumeffort_R_asd',
 'hrv_lf_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_lf_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_lf_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_lf_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_lf_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_lf_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_lf_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_lf_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hrv_lf_stagewise_agrelaxed_amendsumeffort_R_std',
 'hrv_lf_stagewise_agrelaxed_amendsumeffort_R_median',
 'hrv_lf_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hrv_lf_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hrv_lf_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hrv_lf_stagewise_agrelaxed_amendsumeffort_R_asd',
 'hrv_hf_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_hf_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_hf_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_hf_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_hf_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_hf_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_hf_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_hf_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hrv_hf_stagewise_agrelaxed_amendsumeffort_R_std',
 'hrv_hf_stagewise_agrelaxed_amendsumeffort_R_median',
 'hrv_hf_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hrv_hf_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hrv_hf_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hrv_hf_stagewise_agrelaxed_amendsumeffort_R_asd',
 'hrv_lfhf_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_lfhf_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_lfhf_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_lfhf_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_lfhf_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_lfhf_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_lfhf_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_lfhf_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hrv_lfhf_stagewise_agrelaxed_amendsumeffort_R_std',
 'hrv_lfhf_stagewise_agrelaxed_amendsumeffort_R_median',
 'hrv_lfhf_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hrv_lfhf_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hrv_lfhf_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hrv_lfhf_stagewise_agrelaxed_amendsumeffort_R_asd',
 'hrv_nnmean_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_nnmean_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_nnmean_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_nnmean_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_nnmean_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_nnmean_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_nnmean_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_nnmean_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hrv_nnmean_stagewise_agrelaxed_amendsumeffort_R_std',
 'hrv_nnmean_stagewise_agrelaxed_amendsumeffort_R_median',
 'hrv_nnmean_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hrv_nnmean_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hrv_nnmean_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hrv_nnmean_stagewise_agrelaxed_amendsumeffort_R_asd',
 'hrv_nnmedian_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_nnmedian_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_nnmedian_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_nnmedian_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_nnmedian_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_nnmedian_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_nnmedian_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_nnmedian_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hrv_nnmedian_stagewise_agrelaxed_amendsumeffort_R_std',
 'hrv_nnmedian_stagewise_agrelaxed_amendsumeffort_R_median',
 'hrv_nnmedian_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hrv_nnmedian_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hrv_nnmedian_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hrv_nnmedian_stagewise_agrelaxed_amendsumeffort_R_asd',
 'hrv_rmssd_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_rmssd_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_rmssd_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_rmssd_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_rmssd_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_rmssd_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_rmssd_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_rmssd_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hrv_rmssd_stagewise_agrelaxed_amendsumeffort_R_std',
 'hrv_rmssd_stagewise_agrelaxed_amendsumeffort_R_median',
 'hrv_rmssd_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hrv_rmssd_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hrv_rmssd_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hrv_rmssd_stagewise_agrelaxed_amendsumeffort_R_asd',
 'hrv_sd1_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_sd1_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_sd1_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_sd1_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_sd1_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_sd1_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_sd1_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_sd1_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hrv_sd1_stagewise_agrelaxed_amendsumeffort_R_std',
 'hrv_sd1_stagewise_agrelaxed_amendsumeffort_R_median',
 'hrv_sd1_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hrv_sd1_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hrv_sd1_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hrv_sd1_stagewise_agrelaxed_amendsumeffort_R_asd',
 'hrv_sd2_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_sd2_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_sd2_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_sd2_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_sd2_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_sd2_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_sd2_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_sd2_stagewise_agrelaxed_amendsumeffort_R_mean',
 'hrv_sd2_stagewise_agrelaxed_amendsumeffort_R_std',
 'hrv_sd2_stagewise_agrelaxed_amendsumeffort_R_median',
 'hrv_sd2_stagewise_agrelaxed_amendsumeffort_R_q25',
 'hrv_sd2_stagewise_agrelaxed_amendsumeffort_R_q75',
 'hrv_sd2_stagewise_agrelaxed_amendsumeffort_R_sda',
 'hrv_sd2_stagewise_agrelaxed_amendsumeffort_R_asd',
 'hrv_sd1sd2_stagewise_agrelaxed_ecg_nn_R_mean',
 'hrv_sd1sd2_stagewise_agrelaxed_ecg_nn_R_std',
 'hrv_sd1sd2_stagewise_agrelaxed_ecg_nn_R_median',
 'hrv_sd1sd2_stagewise_agrelaxed_ecg_nn_R_q25',
 'hrv_sd1sd2_stagewise_agrelaxed_ecg_nn_R_q75',
 'hrv_sd1sd2_stagewise_agrelaxed_ecg_nn_R_sda',
 'hrv_sd1sd2_stagewise_agrelaxed_ecg_nn_R_asd',
 'hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_mean',

In [34]:
plt.figure()
plt.scatter(Xy_icu['opioids_sum'], Xy_icu['stages_distribution_breathing_R'] - Xy_icu['stages_distribution_breathing_agrelaxed_R'])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [35]:
Xy_icu[['stages_distribution_breathing_R', 'stages_distribution_breathing_agrelaxed_R']]

,stages_distribution_breathing_R,stages_distribution_breathing_agrelaxed_R
5,15.161287,2.075401
11,4.635249,1.092474
17,0.000000,0.000000
83,2.428978,0.293151
86,3.171404,0.723282
89,6.882394,0.280770
95,49.467564,14.672682
104,8.472121,0.027268
107,50.090085,0.091113
113,0.000000,0.000000
116,0.243200,0.219481
119,7.349642,0.851023
122,0.325144,0.208507
131,0.000000,0.000000
134,0.000000,0.000000
155,0.000000,0.000000
158,0.000000,0.000000
167,18.490353,1.767883
170,39.074682,5.308376
173,12.326477,5.789472
182,0.330033,0.014968
185,5.683191,4.543735
203,0.000000,0.000000
206,0.082849,0.059417
209,0.000000,0.000000
218,74.519523,42.965984
224,44.021735,42.721699
230,0.000000,0.000000
239,88.960805,83.012229
248,44.226124,14.143507
251,37.666168,14.982572
257,47.310644,35.334233
260,75.485294,55.470929
263,60.561236,15.143150
272,34.904570,3.384711
275,72.151714,5.586832
296,0.000000,0.000000
308,1.778656,0.012284
311,0.000000,0.000000
347,0.000000,0.000000
368,67.858450,2.201693
371,47.374562,20.123575
413,0.228125,0.113900
416,2.118424,0.849205
437,0.934579,0.173310
461,11.132436,5.250595
464,0.470035,0.000000
470,20.115309,0.117216
473,42.188167,2.487802
485,15.401060,0.951921
503,4.659249,5.910277
506,28.196542,33.834633
509,92.170187,92.856804
518,99.999991,99.999969
524,69.854671,28.413272
542,18.801993,19.782940
545,9.717865,0.050891
551,5.354410,0.211863
554,3.932390,0.277516
560,70.950625,54.566291
569,0.000000,0.000000
572,0.135683,0.133690
596,98.150503,99.983136
632,41.131590,2.591283
644,13.651537,0.371860
653,0.505050,0.739817
659,1.505484,0.469371
668,12.596896,4.010147
686,0.000000,0.000000
719,0.000000,0.000000
731,6.544761,10.529708
740,10.602409,0.071938
743,21.824983,0.034190
752,16.599461,22.447793
755,51.300845,30.661865
758,47.610691,62.773990
761,17.602642,25.568924
770,25.332299,1.211305
773,54.335835,57.160955
776,41.750123,22.950813
779,11.793660,7.324362
782,9.116401,7.799442
785,1.588271,0.000000
791,2.588438,0.624945
794,22.077652,2.322106
797,7.456817,1.252345
800,8.273683,0.754513
803,8.471043,0.637576
806,2.340421,0.910241
815,28.402997,1.767706
818,54.448169,10.130109
821,50.519089,0.685142
860,1.605685,0.000000
869,43.715549,0.151732
872,6.844794,0.057285
896,0.271370,0.181818
914,27.843100,0.262785
917,44.848008,2.120535
950,1.955307,0.494438
953,0.000000,0.000000
962,19.103707,2.222221
965,7.026598,1.034103
983,47.904320,20.468126
992,50.165013,5.637583
1001,3.430234,0.419838
1022,58.736389,7.427782
1025,57.373725,5.396966
1028,49.126878,2.819482
1049,57.168293,12.268618
1097,1.365546,0.796813
1100,21.450148,2.546871
1112,0.000000,0.000000
1142,18.664104,3.098759
1145,21.408918,0.954580
1151,42.058879,0.091314
1160,0.000000,0.000000
1163,22.943788,6.501950
1169,48.781874,23.760004
1172,42.947198,42.535539
1190,38.373706,0.071248
1193,58.741527,18.077994
1202,41.561710,1.966982
1211,32.253669,0.000000
1226,50.203624,98.316719
1229,89.779075,54.567874

In [238]:
Xy_icu[['stages_distribution_ecg_nn_all_R', 'stages_distribution_ecg_nn_agrelaxed_R']]

KeyError: "['stages_distribution_ecg_nn_all_R'] not in index"

In [ ]:
### opiates R investigation for breathing.

, ,

In [ ]:
for agreement in ['agreement_relaxed', 'agreement']:
    for modality in ['amendsumeffort', 'ecg_nn']:
        var_sleep = 'hours_sleep_MODALITY_all'.replace('MODALITY', modality) # all overlap sleep
        var_agreeing = 'hours_sleep_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        
        if agreement == 'agreement_relaxed':
             # all overlap sleep
            var_discordant = 'hours_discordant_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement) # discordant sleep among overlap sleep
        elif agreement == 'agreement':
            var_discordant = 'hours_discordant_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)

            
        summary_days_icu[var_discordant] = summary_days_icu[var_sleep] - summary_days_icu[var_agreeing]
        summary_days_sleeplab[var_discordant] = summary_days_sleeplab[var_sleep] - summary_days_sleeplab[var_agreeing]

### linear regression modelling, to check if we can predict on individual level if discordant sleep occurs.
currently: most important coefficients seem reasonable, but overall score is low. to be checked more carefully, i believe not needed for current paper.

In [68]:
# Xy_icu_imputed = Xy_icu.replace('Series([], Freq: 100L, Name: hrv_nn, dtype: float32)', np.nan).fillna(Xy_icu.mean())

import sklearn
from sklearn.linear_model import LinearRegression, ElasticNet, SGDClassifier
from sklearn.model_selection import GridSearchCV
# reg = LinearRegression().fit(Xy_icu_imputed[variables], Xy_icu_imputed[discordant_proportion])
# reg = ElasticNet(alpha=0.5, l1_ratio=0.25).fit(Xy_icu_imputed[variables], Xy_icu_imputed[discordant_proportion])

In [ ]:
parameters = {'alpha':[0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1], 'l1_ratio':[0.25, 0.5, 0.75]}

In [89]:
variables = ['sofa_score_mean',
             'opioids_sum',
#  'benzos_sum',
#  'antipsychotics_sum',
            ]

In [90]:
Xy_icu_imputed = Xy_icu[variables + [discordant_proportion]]
Xy_icu_imputed = Xy_icu_imputed.dropna(how='any')

In [91]:
Xy_icu_imputed.shape

(129, 3)

In [92]:
# discordant_proportion = 'stages_distribution_breathing_R'

In [93]:
x = Xy_icu_imputed[variables]
y = Xy_icu_imputed[discordant_proportion]

lin_reg = LinearRegression()
lin_reg = lin_reg.fit(x, y)

In [94]:
lin_reg.score(x, y)

0.03001131204679719

In [95]:
lin_reg.coef_

array([ 0.00456763, -0.00263014])

In [75]:
model = 'linear'

if model == 'linear':
    reg = ElasticNet()
    x = Xy_icu_imputed[variables]
    y = Xy_icu_imputed[discordant_proportion]
elif model == 'logistic':
    reg = SGDClassifier(loss="log", penalty="elasticnet")
    x = Xy_icu_imputed[variables]
    y = (Xy_icu_imputed[discordant_proportion] > 0.5).astype(int)
#     y = (Xy_icu_imputed[discordant_proportion] > 40).astype(int)

In [325]:
plt.figure()
plt.hist(Xy_icu_imputed[discordant_proportion])

/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  """Entry point for launching an IPython kernel.

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([56., 14., 10.,  5., 17., 11.,  3.,  4.,  2.,  3.]),
 array([ 0.        ,  9.99999913, 19.99999826, 29.99999738, 39.99999651,
        49.99999564, 59.99999477, 69.9999939 , 79.99999302, 89.99999215,
        99.99999128]),
 <a list of 10 Patch objects>)

In [319]:
clf = GridSearchCV(reg, parameters, cv=10, scoring = 'roc_auc')

In [320]:
clf.fit(x, y)

GridSearchCV(cv=10, estimator=SGDClassifier(loss='log', penalty='elasticnet'),
             param_grid={'alpha': [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1],
                         'l1_ratio': [0.25, 0.5, 0.75]},
             scoring='roc_auc')

In [321]:
clf.cv_results_.keys()
pd.DataFrame(clf.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002583,0.000174,0.002201,0.000101,0.01,0.25,"{'alpha': 0.01, 'l1_ratio': 0.25}",0.972222,0.777778,0.222222,0.611111,0.305556,0.343750,0.625,0.8125,0.68750,0.18750,0.554514,0.258507,1
1,0.002635,0.000132,0.002220,0.000116,0.01,0.5,"{'alpha': 0.01, 'l1_ratio': 0.5}",0.500000,0.777778,0.222222,0.611111,0.375000,0.562500,0.375,0.8125,0.62500,0.18750,0.504861,0.203107,2
2,0.002532,0.000311,0.002223,0.000307,0.01,0.75,"{'alpha': 0.01, 'l1_ratio': 0.75}",0.500000,0.500000,0.222222,0.555556,0.222222,0.687500,0.500,0.5000,0.71875,0.56250,0.496875,0.156277,9
3,0.002505,0.000120,0.002227,0.000255,0.02,0.25,"{'alpha': 0.02, 'l1_ratio': 0.25}",0.500000,0.777778,0.222222,0.611111,0.222222,0.562500,0.625,0.5000,0.62500,0.18750,0.483333,0.193355,11
4,0.002626,0.000242,0.002126,0.000100,0.02,0.5,"{'alpha': 0.02, 'l1_ratio': 0.5}",0.500000,0.500000,0.500000,0.500000,0.222222,0.343750,0.500,0.5000,0.62500,0.18750,0.437847,0.132750,17
5,0.002525,0.000122,0.002243,0.000140,0.02,0.75,"{'alpha': 0.02, 'l1_ratio': 0.75}",0.500000,0.500000,0.222222,0.555556,0.222222,0.468750,0.500,0.5000,0.62500,0.18750,0.428125,0.148326,18
6,0.002433,0.000161,0.002131,0.000093,0.05,0.25,"{'alpha': 0.05, 'l1_ratio': 0.25}",0.500000,0.500000,0.222222,0.555556,0.277778,0.468750,0.500,0.5000,0.62500,0.56250,0.471181,0.119093,12
7,0.002538,0.000386,0.002169,0.000117,0.05,0.5,"{'alpha': 0.05, 'l1_ratio': 0.5}",0.500000,0.500000,0.500000,0.500000,0.277778,0.421875,0.500,0.5000,0.50000,0.50000,0.469965,0.068166,13
8,0.002566,0.000123,0.002237,0.000087,0.05,0.75,"{'alpha': 0.05, 'l1_ratio': 0.75}",0.500000,0.500000,0.500000,0.500000,0.277778,0.375000,0.500,0.5000,0.50000,0.50000,0.465278,0.072768,14
9,0.002364,0.000125,0.002094,0.000064,0.1,0.25,"{'alpha': 0.1, 'l1_ratio': 0.25}",0.500000,0.555556,0.500000,0.500000,0.277778,0.250000,0.375,0.5000,0.50000,0.18750,0.414583,0.124616,19
10,0.002409,0.000175,0.002196,0.000126,0.1,0.5,"{'alpha': 0.1, 'l1_ratio': 0.5}",0.027778,0.500000,0.222222,0.500000,0.277778,0.421875,0.500,0.5000,0.50000,0.50000,0.394965,0.156626,21
11,0.002517,0.000161,0.002210,0.000084,0.1,0.75,"{'alpha': 0.1, 'l1_ratio': 0.75}",0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500,0.5000,0.50000,0.50000,0.500000,0.000000,4
12,0.002445,0.000121,0.002150,0.000099,0.2,0.25,"{'alpha': 0.2, 'l1_ratio': 0.25}",0.500000,0.500000,0.222222,0.500000,0.277778,0.437500,0.500,0.5000,0.50000,0.50000,0.443750,0.099403,16
13,0.002460,0.000149,0.002225,0.000133,0.2,0.5,"{'alpha': 0.2, 'l1_ratio': 0.5}",0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500,0.5000,0.50000,0.50000,0.500000,0.000000,4
14,0.002289,0.000033,0.002050,0.000072,0.2,0.75,"{'alpha': 0.2, 'l1_ratio': 0.75}",0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500,0.5000,0.50000,0.50000,0.500000,0.000000,4
15,0.002301,0.000141,0.002085,0.000087,0.5,0.25,"{'alpha': 0.5, 'l1_ratio': 0.25}",0.500000,0.444444,0.222222,0.388889,0.500000,0.421875,0.500,0.5000,0.50000,0.09375,0.407118,0.133216,20
16,0.002356,0.000150,0.002112,0.000160,0.5,0.5,"{'alpha': 0.5, 'l1_ratio': 0.5}",0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500,0.5000,0.50000,0.50000,0.500000,0.000000,4
17,0.002513,0.000139,0.002251,0.000025,0.5,0.75,"{'alpha': 0.5, 'l1_ratio': 0.75}",0.500000,0.500000,0.500000,0.500000,0.375000,0.500000,0.500,0.5000,0.50000,0.50000,0.487500,0.037500,10
18,0.002791,0.000386,0.002500,0.000313,1,0.25,"{'alpha': 1, 'l1_ratio': 0.25}",0.027778,0.500000,0.500000,0.500000,0.500000,0.421875,0.500,0.5000,0.50000,0.50000,0.444965,0.141000,15
19,0.003011,0.000141,0.002696,0.000115,1,0.5,"{'alpha': 1, 'l1_ratio': 0.5}",0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500,0.5000,0.50000,0.53125,0.503125,0.009375,3
20,0.003026,0.000237,0.002699,0.000199,1,0.75,"{'alpha': 1, 'l1_ratio': 0.75}",0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500,0.5000,0.50000,0.50000,0.500000,0.000000,4

In [322]:
clf.cv_results_['mean_test_score']

array([0.55451389, 0.50486111, 0.496875  , 0.48333333, 0.43784722,
       0.428125  , 0.47118056, 0.46996528, 0.46527778, 0.41458333,
       0.39496528, 0.5       , 0.44375   , 0.5       , 0.5       ,
       0.40711806, 0.5       , 0.4875    , 0.44496528, 0.503125  ,
       0.5       ])

In [253]:
clf.cv_results_['params']

[{'alpha': 0.01, 'l1_ratio': 0.25},
 {'alpha': 0.01, 'l1_ratio': 0.5},
 {'alpha': 0.01, 'l1_ratio': 0.75},
 {'alpha': 0.02, 'l1_ratio': 0.25},
 {'alpha': 0.02, 'l1_ratio': 0.5},
 {'alpha': 0.02, 'l1_ratio': 0.75},
 {'alpha': 0.05, 'l1_ratio': 0.25},
 {'alpha': 0.05, 'l1_ratio': 0.5},
 {'alpha': 0.05, 'l1_ratio': 0.75},
 {'alpha': 0.1, 'l1_ratio': 0.25},
 {'alpha': 0.1, 'l1_ratio': 0.5},
 {'alpha': 0.1, 'l1_ratio': 0.75},
 {'alpha': 0.2, 'l1_ratio': 0.25},
 {'alpha': 0.2, 'l1_ratio': 0.5},
 {'alpha': 0.2, 'l1_ratio': 0.75},
 {'alpha': 0.5, 'l1_ratio': 0.25},
 {'alpha': 0.5, 'l1_ratio': 0.5},
 {'alpha': 0.5, 'l1_ratio': 0.75},
 {'alpha': 1, 'l1_ratio': 0.25},
 {'alpha': 1, 'l1_ratio': 0.5},
 {'alpha': 1, 'l1_ratio': 0.75}]

In [219]:
print(reg.score(Xy_icu_imputed[variables], Xy_icu_imputed[discordant_proportion]))

0.10608757890812248

In [220]:
reg.coef_

array([ 0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00, -1.76249985e-03, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -1.87418367e-03,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -2.68387813e-03,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00,  4.08875601e-03, -0.00000000e+00, -0.00000000e+00,
        1.86704952e-04, -1.08553102e-05, -6.32607122e-05,  2.21462782e-05,
       -0.00000000e+00, -1.30367172e-04,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -0.00000000e+00])

In [221]:
df_correlations.shape

(38, 8)

In [222]:
reg.coef_.shape

(38,)

In [223]:
df_correlations['LinearRegCoef'] = reg.coef_

In [224]:
df_correlations['LinearRegCoefAbs'] = df_correlations['LinearRegCoef'].abs()

In [225]:
df_correlations.sort_values(by='LinearRegCoefAbs', ascending=False)[:10]

,pearson_c,pearson_p,spearman_c,spearman_p,significance_pearson,significance_spearman,LinearRegCoef,LinearRegCoefAbs
rr_10s_smooth_median,0.206869,0.00933511,0.207834,0.00900347,True,True,0.004089,0.004089
po2_arterial_mean,-0.429372,0.0665678,-0.4,0.0897187,False,False,-0.002684,0.002684
edw_bp_systolic_q75,-0.195113,0.0223232,-0.227258,0.00757041,True,True,-0.001874,0.001874
hr_q75,-0.12906,0.107193,-0.0988418,0.218097,False,False,-0.001762,0.001762
hrv_ulf_median,0.0775241,0.344077,-0.0492297,0.548318,False,False,0.000187,0.000187
hrv_rmssd_median,0.0266267,0.745534,0.0504723,0.538256,False,False,-0.000130,0.000130
hrv_lf_median,0.00992397,0.903741,-0.028008,0.732821,False,False,-0.000063,0.000063
hrv_hf_median,0.0488961,0.551036,0.0321245,0.695374,False,False,0.000022,0.000022
hrv_vlf_median,0.0211977,0.79614,-0.0806519,0.324901,False,False,-0.000011,0.000011
ventilation_cvar_30sec_median,-0.306983,9.20672e-05,-0.323444,3.59642e-05,True,True,-0.000000,0.000000