In [1]:
import pandas as pd
import numpy as np
import os
import sys
%load_ext autoreload
%autoreload 2
# sys.path.append('/home/wolfgang/repos/sleep_research_io')
# from sleep_research_functions import *
%matplotlib widget
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

from icu_sleep_breathing_2020_help_functions import * 

pd.options.display.max_rows = 300
pd.options.display.max_columns = 300


font = {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : 8}

font_headers =  {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : 9}

font_subplots =  {'family' : 'sans-serif',
        'weight' : 'bold',
        'size'   : 9}

matplotlib.rc('font', **font)

### load summary tables:

In [2]:
plots_savedir = '/media/mad3/Projects/ICU_SLEEP_STUDY/Sleep_And_Breathing/plots'
plots_savedir = '/scr/wolfgang/Dropbox (Partners HealthCare)/SleepInICUandSleeplabPaper/Plots/sleep_staging'

In [3]:
[summary_subjects_icu, summary_subjects_sleeplab, 
 summary_days_icu, summary_days_sleeplab] = load_summary_data_with_inclusion_criteria()

/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3254: DtypeWarning: Columns (15,91,92,93,6455,6456,6457,12819,12820,12821,19185,19186,19187,21491,21492,21493,21519,21520,21521,21526,21527,21528,25549,25550,25551,31913,31914,31915,38279,38280,38281,44643,44644,44645,46851,46852,46853,46865,46866,46867,46879,46880,46881,46949,46950,46951,46956,46957,46958,46963,46964,46965,46970,46971,46972,46977,46978,46979,46984,46985,46986,51007,51008,51009,53336,53337,53338,57305,57373,57374,57375,59588,59589,59590,59602,59603,59604,59686,59687,59688,63669,63737,63738,63739,65952,65953,65954,65959,65960,65961,65980,65981,65982,66036,66037,66038,66043,66044,66045,66050,66051,66052,66057,66058,66059,66071,66072,66073,66078,66079,66080,70033,70101,70102,70103,72318,72319,72320,72332,72333,72334,72402,72403,72404,72416,72417,72418,76399,76467,76468,76469,78682,78683,78684,78696,78697,78698,78710,78711,78712,78766,78767,78768,78787,78788,78789,78801,78802,78803,78808,78809,78810,82763,82831,82832,82833,85039,85040,85041,85046,85047,85048,85053,85054,85055,85060,85061,85062,85067,85068,85069,85074,85075,85076,85137,85138,85139,85144,85145,85146,85151,85152,85153,89127,89195,89196,89197,91405,91406,91407,91412,91413,91414,91419,91420,91421,91426,91427,91428,91433,91434,91435,91440,91441,91442,91496,91497,91498,91503,91504,91505,91510,91511,91512,91517,91518,91519,91531,91532,91533,91538,91539,91540,95493,95561,95562,95563,97776,97777,97778,97783,97784,97785,97790,97791,97792,97804,97805,97806,97867,97868,97869,97874,97875,97876,97881,97882,97883,97888,97889,97890,97895,97896,97897,97902,97903,97904,101857,101925,101926,101927,104126,104127,104128,104133,104134,104135,104140,104141,104142,104154,104155,104156,104161,104162,104163,104168,104169,104170,104224,104225,104226,104231,104232,104233,104238,104239,104240,104245,104246,104247,104259,104260,104261,104266,104267,104268,108221,108289,108290,108291,110492,110493,110494,110499,110500,110501,110506,110507,110508,110513,110514,110515,110520,110521,110522,110527,110528,110529,110534,110535,110536,110590,110591,110592,110597,110598,110599,110604,110605,110606,110611,110612,110613,110618,110619,110620,110625,110626,110627,110632,110633,110634,114587,114655,114656,114657,116863,116864,116865,116870,116871,116872,116877,116878,116879,116884,116885,116886,116891,116892,116893,116898,116899,116900,116961,116962,116963,116968,116969,116970,116975,116976,116977,116989,116990,116991,116996,116997,116998,120951,121019,121020,121021,123234,123235,123236,123241,123242,123243,123248,123249,123250,123262,123263,123264,123318,123319,123320,123325,123326,123327,123332,123333,123334,123339,123340,123341,123353,123354,123355,123360,123361,123362,127315,127383,127384,127385,129593,129594,129595,129600,129601,129602,129607,129608,129609,129614,129615,129616,129621,129622,129623,129628,129629,129630,129684,129685,129686,129691,129692,129693,129698,129699,129700,129705,129706,129707,129719,129720,129721,129726,129727,129728,133681,133749,133750,133751,135964,135965,135966,135978,135979,135980,135992,135993,135994,136069,136070,136071,136090,136091,136092,140045,140113,140114,140115,142328,142329,142330,142342,142343,142344,142356,142357,142358,142412,142413,142414,142419,142420,142421,142447,142448,142449,142454,142455,142456,146409,146477,146478,146479,148694,148695,148696,148708,148709,148710,148722,148723,148724,148778,148779,148780,148785,148786,148787,148792,148793,148794,148799,148800,148801,148813,148814,148815,148820,148821,148822,152775,159139,159207,159208,159209,165503) have mixed types. Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3254: DtypeWarning: Columns (15,93,94,95,2294,2295,2296,2301,2302,2303,2308,2309,2310,2315,2316,2317,2322,2323,2324,2329,2330,2331,2336,2337,2338,2392,2393,2394,2399,2400,2401,2406,2407,2408,2413,2414,2415,2420,2421,2422,2427,2428,2429,2434,2435,2436) have mixed types. Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

# of subjects ICU before inclusion criteria: 102
# of 12-hour segments ICU before inclusion criteria: 1161
# of subjects ICU after inclusion criteria: 102
# of 12-hour segments ICU after inclusion criteria: 1161
24-hour segments: 387
12-hour segments: 774

# of subjects sleeplab before inclusion criteria: 412
# of 12-hour segments sleeplab before inclusion criteria: 412

In [4]:
[x for x in summary_days_icu.columns if 'hours_sleep' in x]

['hours_sleep_ecg_nn_all',
 'hours_sleep_ecg_nn_agreement',
 'hours_sleep_ecg_nn_disagreement',
 'hours_sleep_ecg_nn_agreement_relaxed',
 'hours_sleep_ecg_nn_disagreement_relaxed',
 'hours_sleep_amendsumeffort_all',
 'hours_sleep_amendsumeffort_agreement',
 'hours_sleep_amendsumeffort_disagreement',
 'hours_sleep_amendsumeffort_agreement_relaxed',
 'hours_sleep_amendsumeffort_disagreement_relaxed',
 'hours_sleep_expert_all',
 'hours_sleep_expert_agreement',
 'hours_sleep_expert_disagreement',
 'hours_sleep_expert_agreement_relaxed',
 'hours_sleep_expert_disagreement_relaxed']

In [5]:
### Difference between 'all' and original sleep indices is that for 'all' only overlap with airgo data is considered
# e.g. ecg_available vs. hours_data_ecg_nn_all.

agreement = 'all'
# agreement = 'agreement_relaxed'

summary_days_icu[['airgo_ecg_available', 'ecg_available', 'stages_distribution_ecg_nn_S', 'sleep_hours_ecg_nn', f'hours_data_ecg_nn_{agreement}', f'hours_data_amendsumeffort_{agreement}',  f'hours_sleep_ecg_nn_{agreement}', f'perc_S_ecg_nn_{agreement}' , 'sleep_hours_breathing', f'hours_sleep_amendsumeffort_{agreement}']].iloc[5:10]

,airgo_ecg_available,ecg_available,stages_distribution_ecg_nn_S,sleep_hours_ecg_nn,hours_data_ecg_nn_all,hours_data_amendsumeffort_all,hours_sleep_ecg_nn_all,perc_S_ecg_nn_all,sleep_hours_breathing,hours_sleep_amendsumeffort_all
5,12.02025,24.000278,0.128124,3.075000,9.958334,9.958334,1.225001,0.123013,5.166667,4.958334
6,0.00000,0.000000,0.000000,0.000000,0.000001,0.000001,0.000001,0.000000,0.000000,0.000001
7,0.00000,6.500833,0.262787,1.708333,0.000001,0.000001,0.000001,0.000000,0.000000,0.000001
8,0.00000,6.500833,0.262787,1.708333,0.000001,0.000001,0.000001,0.000000,0.000000,0.000001
9,0.00000,12.000278,0.170135,2.041667,0.000001,0.000001,0.000001,0.000000,0.000000,0.000001

In [6]:
#NEW
### Difference between 'all' and original sleep indices is that for 'all' only overlap with airgo data is considered
# e.g. ecg_available vs. hours_data_ecg_nn_all.

agreement = 'all'
# agreement = 'agreement_relaxed'

summary_days_icu[['airgo_ecg_available', 'ecg_available', 'stages_distribution_ecg_nn_S', 'sleep_hours_ecg_nn', f'hours_data_ecg_nn_{agreement}', f'hours_data_amendsumeffort_{agreement}',  f'hours_sleep_ecg_nn_{agreement}', f'perc_S_ecg_nn_{agreement}' , 'sleep_hours_breathing', f'hours_sleep_amendsumeffort_{agreement}']].iloc[5:10]

,airgo_ecg_available,ecg_available,stages_distribution_ecg_nn_S,sleep_hours_ecg_nn,hours_data_ecg_nn_all,hours_data_amendsumeffort_all,hours_sleep_ecg_nn_all,perc_S_ecg_nn_all,sleep_hours_breathing,hours_sleep_amendsumeffort_all
5,12.02025,24.000278,0.128124,3.075000,9.958334,9.958334,1.225001,0.123013,5.166667,4.958334
6,0.00000,0.000000,0.000000,0.000000,0.000001,0.000001,0.000001,0.000000,0.000000,0.000001
7,0.00000,6.500833,0.262787,1.708333,0.000001,0.000001,0.000001,0.000000,0.000000,0.000001
8,0.00000,6.500833,0.262787,1.708333,0.000001,0.000001,0.000001,0.000000,0.000000,0.000001
9,0.00000,12.000278,0.170135,2.041667,0.000001,0.000001,0.000001,0.000000,0.000000,0.000001

In [7]:
for agreement in ['all', 'agreement_relaxed', 'disagreement_relaxed', 'agreement', 'disagreement']:
    for modality in ['amendsumeffort', 'ecg_nn']:
        var_n2 = 'perc_N2_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        var_n3 = 'perc_N3_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        var_sum = 'perc_N2N3_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)

        summary_days_icu[var_sum] = summary_days_icu[var_n2] + summary_days_icu[var_n3]
        summary_days_sleeplab[var_sum] = summary_days_sleeplab[var_n2] + summary_days_sleeplab[var_n3]

In [8]:
for agreement in ['agreement_relaxed', 'agreement', 'all']:
    for modality in ['amendsumeffort', 'ecg_nn']:
        var_sleep = 'hours_sleep_MODALITY_all'.replace('MODALITY', modality) # all overlap sleep
        var_agreeing = 'hours_sleep_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        
        var_discordant = 'hours_discordant_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement) # discordant sleep among overlap sleep
        summary_days_icu[var_discordant] = summary_days_icu[var_sleep] - summary_days_icu[var_agreeing]
        summary_days_sleeplab[var_discordant] = summary_days_sleeplab[var_sleep] - summary_days_sleeplab[var_agreeing]
        
        var_discordant_perc = 'perc_discordant_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement) # discordant sleep among overlap sleep in %
        summary_days_icu[var_discordant_perc] = np.divide(summary_days_icu[var_sleep] - summary_days_icu[var_agreeing], summary_days_icu[var_sleep])
        summary_days_sleeplab[var_discordant_perc] = np.divide(summary_days_sleeplab[var_sleep] - summary_days_sleeplab[var_agreeing], summary_days_sleeplab[var_sleep])

In [9]:
cols_percentage = [x for x in summary_days_sleeplab.columns if 'perc_' in x]
summary_days_sleeplab[cols_percentage] *= 100
summary_days_icu[cols_percentage] *= 100

In [10]:
summary_days_sleeplab.shape

(412, 6148)

In [11]:
summary_days_icu.loc[:, ['stages_distribution' in x for x in summary_days_icu.columns]] *= 100
summary_days_sleeplab.loc[:, ['stages_distribution' in x for x in summary_days_sleeplab.columns]] *= 100

summary_f_icu = summary_days_icu.loc[summary_days_icu.day_cat == 'f', :]
summary_dn_icu = summary_days_icu.loc[summary_days_icu.day_cat != 'f', :]

summary_days_sleeplab_full = summary_days_sleeplab.copy()

In [12]:
def sleep_summary_barplots(ax, data, variables, x_labels,  color='navy', title = ''):
    
    num = len(variables)
    
    means = data[variables].mean(axis=0)
    stds = data[variables].std(axis=0)
    
    if (variables[1] == 'hours_sleep_expert_all'): #manual fix for experts, we don't wanna show hours of sleep twice (total and concordant the same for experts)
        means[1] = 0
        stds[1] = 0

    ax.bar(np.arange(num), means, yerr=[np.zeros(num,), stds], color=color)
    ax.set_xticks(np.arange(num))
    ax.set_xticklabels(x_labels, rotation=90)
    ax.set_title(title)

    for iV in range(num):
        if np.any([x in variables[iV] for x in ['hours']]): 
            decimals = 1
        else: 
            decimals = 0
        if 'hours_sleep' in variables[iV]:
#             offset_text_x = -0.25
            offset_text_x = 0
            offset_text_y = 2
            if iV == 0:
                offset_text_y += 11
        else:
            offset_text_x = 0
            offset_text_y = 2


        var_mean = np.round(data[variables[iV]].mean(), decimals)
        
        # manual correction here for Discordant Sleep = 0. We want to display that as NA in the plots for now.
        if ('discordant' in variables[iV]) & (var_mean == 0):
            var_mean = np.nan

        if (variables[iV] == 'hours_sleep_expert_all') & (iV == 1): #manual fix for experts, we don't wanna show hours of sleep twice (total and concordant the same for experts)
            var_mean = np.nan

        if not np.isnan(var_mean):
            if decimals == 0: 
                    var_mean = int(var_mean)
            var_std = int(np.round(data[variables[iV]].std(),0))
            if (var_mean > 10) & ('hours_sleep' not in variables[iV]):
                ax.annotate(str(var_mean), xy=(iV + offset_text_x, 2), color='white', ha='center', fontweight='normal', fontsize=7, fontfamily='sans-serif')
            else:                
                ax.annotate(str(var_mean), xy=(iV + offset_text_x, var_mean+var_std+offset_text_y), color='black', ha='center', fontweight='normal', fontsize=7, fontfamily='sans-serif')
        else:
            ax.annotate(str('NA'), xy=(iV, 2), fontsize=7, color='black', ha='center')
            
    return ax

In [13]:
ahi_categories = ['all', 'ahi_0_5', 'ahi_5_15', 'ahi_15_30', 'ahi_30_100', 'ahi_15_100']
ahi_names = {
    'all': 'All',
    'ahi_0_5': 'AHI < 5',
    'ahi_5_15': '5 < AHI <=15',
    'ahi_15_30': '15 < AHI <= 30',
    'ahi_30_100': 'AHI > 30',
    'ahi_15_100': 'AHI > 15',
}

In [14]:
### 3x2 plot
# cols: data type, rows: stage version (resp, ecg, expert)

variables_template = ['sleep_hours_MODALITY',
             'stages_distribution_MODALITY_S',
             'stages_distribution_MODALITY_R',
             'stages_distribution_MODALITY_N1',
            'stages_distribution_MODALITY_N2',
             'stages_distribution_MODALITY_N3',
             'sleep_MODALITY_sfi',
             'sleep_MODALITY_sfi_w',
             'sleep_MODALITY_arousali',
            ]

variables_template = [
# 'hours_data_MODALITY_AGREEMENT',
 'hours_sleep_MODALITY_AGREEMENT',
#  'perc_W_MODALITY_AGREEMENT',
 'perc_S_MODALITY_AGREEMENT',
 'perc_R_MODALITY_AGREEMENT',
 'perc_N1_MODALITY_AGREEMENT',
 'perc_N2_MODALITY_AGREEMENT',
 'perc_N3_MODALITY_AGREEMENT',
 'sfi_MODALITY_AGREEMENT',
 'sfi_w_MODALITY_AGREEMENT',
 'arousali_MODALITY_AGREEMENT',
]

x_labels = ['Sleep Dur. (h)', 'Sleep (%)', 'Stage R (%)', 'Stage N1 (%)', 'Stage N2 (%)', 'Stage N3 (%)', 'SFI', 'SFI Wake', 'Arousal I.']

In [15]:
def set_shared_ylim(ax1, ax2):
    
    ylim_min1, ylim_max1 = ax1.get_ylim()
    ylim_min2, ylim_max2 = ax2.get_ylim()
    ylim_min = np.min([ylim_min1, ylim_min2])
    ylim_min = np.max([ylim_min, 0])
    ylim_max = np.max([ylim_max1, ylim_max2])
    
    ax1.set_ylim(ylim_min, ylim_max)
    ax2.set_ylim(ylim_min, ylim_max)
    
    return ax1, ax2

In [16]:

def plot_mean_std_element(data, var, ax, position=0, color='blue', marker=None):
    
    mean_var = data[var].mean()
    std_var = data[var].std()
    ax.errorbar(position, mean_var, yerr=std_var, color=color, fmt='.', zorder=1, marker=marker)
    
    return ax

def plot_median_iqr_element(data, var, ax, position=0, color='blue', marker=None):
    
    mean_var = data[var].median()
    std_var = data[var].quantile(0.75) - data[var].quantile(0.25)
    ax.errorbar(position, mean_var, yerr=std_var, color=color, fmt='.', zorder=1, marker=marker)
    
    return ax

def plot_mean_std_all_elements(var, ax):
    
    ax = plot_mean_std_element(icu_2, var, ax, position=0, color='royalblue')
    ax = plot_mean_std_element(icu_4, var, ax, position=1, color='navy')
    ax = plot_mean_std_element(sleeplab_all, var, ax, position=2, color='gray')
    ax = plot_mean_std_element(sleeplab_ahi_0_5, var, ax, position=3, color='limegreen')
    ax = plot_mean_std_element(sleeplab_ahi_5_15, var, ax, position=4, color='darkgreen')
    ax = plot_mean_std_element(sleeplab_ahi_15_30, var, ax, position=5, color='orange')
    ax = plot_mean_std_element(sleeplab_ahi_30_100, var, ax, position=6, color='red')

    return ax

def plot_median_iqr_all_elements(var, ax):
    
    ax = plot_median_iqr_element(icu_2, var, ax, position=0, color='royalblue')
    ax = plot_median_iqr_element(icu_4, var, ax, position=1, color='navy')
    ax = plot_median_iqr_element(sleeplab_all, var, ax, position=2, color='gray')
    ax = plot_median_iqr_element(sleeplab_ahi_0_5, var, ax, position=3, color='limegreen')
    ax = plot_median_iqr_element(sleeplab_ahi_5_15, var, ax, position=4, color='darkgreen')
    ax = plot_median_iqr_element(sleeplab_ahi_15_30, var, ax, position=5, color='orange')
    ax = plot_median_iqr_element(sleeplab_ahi_30_100, var, ax, position=6, color='red')

    return ax

In [17]:
##### check subjects without any sleep

min_hours_sleep_icu = 0.01
inclusion_agreement = 'all'

f_included = summary_f_icu.loc[np.any([summary_f_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                                   summary_f_icu[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :]

f_excluded = summary_f_icu.loc[np.all([summary_f_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] <= min_hours_sleep_icu, 
                                                   summary_f_icu[f'hours_sleep_ecg_nn_{inclusion_agreement}'] <= min_hours_sleep_icu],
                                                   axis=0), :] 

f_excluded = f_excluded[~np.isin(f_excluded.study_id.values, f_included.study_id.unique())] # only full days for subjects that are not included

f_excluded[['study_id', 'airgo_ecg_available']];

hours_data_available = []
for study_id in f_excluded.study_id.unique():
    hours_data_available.append(f_excluded.loc[f_excluded.study_id == study_id, :].airgo_ecg_available.sum())
    
print(f'N patients excluded: {f_excluded.shape[0]}')
print(f'Mean (STD) hours of data (synchronous ECG and airgo) available for patients without sleep detected: {np.mean(hours_data_available).round(2)}  ({np.std(hours_data_available).round(2)})')

N patients excluded: 0
Mean (STD) hours of data (synchronous ECG and airgo) available for patients without sleep detected: nan  (nan)

/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [18]:
print(summary_f_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'].mean())
print(summary_f_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'].std())

6.154479897502152
6.787259452023646

In [19]:
print(summary_f_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'].mean())
print(summary_f_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'].std())

6.154479897502152
6.787259452023646

In [20]:
#### select version of plot:
ahi_category = 'all'
force_concordant_discordant_sleep = True # if we use 'all' agreement option, do you still want to retrieve concordant/discordant sleep info from relaxed_agreement option. this is True for the paper figures.

# compare ICU group 2 and sleeplab group 2:
agreement = 'all'
min_hours_sleep_icu = 0.01
inclusion_agreement = 'all'
do_agreement_for_sleeplab = False

## compare ICU group 3 and sleeplab group 3, compute sleep statistics on ALL sleep:
# agreement = 'all'
# min_hours_sleep_icu = 2
# inclusion_agreement = 'agreement_relaxed'
# do_agreement_for_sleeplab = True

# ## compare ICU group 3 and sleeplab group 3, compute sleep statistics on CONCORDANT sleep:
# agreement = 'agreement_relaxed'
# min_hours_sleep_icu = 2
# inclusion_agreement = 'agreement_relaxed'
# do_agreement_for_sleeplab = True

# ## compare ICU group 3 and sleeplab group 2: (NOT INCLUDED IN PAPER)
# agreement = 'all'
# min_hours_sleep_icu = 2
# inclusion_agreement = 'agreement_relaxed'
# do_agreement_for_sleeplab = False

agreement_expert = 'all'
icu_day_v = 'full'

####
marker = {'amendsumeffort': 'o',
         'ecg_nn': 's'}

legend_handles = []

figdummy, axdummy = plt.subplots(1,1);
plt.close()
legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='navy', fmt='.', zorder=1, marker=marker['amendsumeffort']))
legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='navy', fmt='.', zorder=1, marker=marker['ecg_nn']))
legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='orange', fmt='.', zorder=1, marker=marker['amendsumeffort']))
legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='orange', fmt='.', zorder=1, marker=marker['ecg_nn']))


### same as above but remove SFI Wake and relabel variables.


### 3x2 plot
# cols: data type, rows: stage version (resp, ecg, expert)

variables_template = [
 'hours_sleep_MODALITY_all', # overall sleep duration.
 'hours_sleep_MODALITY_AGREEMENT',
 'hours_discordant_MODALITY_AGREEMENT', 
 'perc_S_MODALITY_AGREEMENT',
 'perc_R_MODALITY_AGREEMENT',
 'perc_N1_MODALITY_AGREEMENT',
 'perc_N2_MODALITY_AGREEMENT',
 'perc_N3_MODALITY_AGREEMENT',
 'sfi_MODALITY_AGREEMENT',
 'arousali_MODALITY_AGREEMENT',
]


x_labels = ['Total Sleep (h)', 'Concordant S. (h)', 'Discordant S. (h)',  'Sleep (%)', 'Stage R (%)', 'Stage N1 (%)', 'Stage N2 (%)', 'Stage N3 (%)', 'SFI', 'Wake Trans./h']
x_labels_short = ['TS', 'CS', 'DS', 'S', 'R', 'N1', 'N2', 'N3', 'SFI', 'WT']

summary_days_sleeplab_full['hours_discordant_expert_all'] = np.nan

# summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]

    
if icu_day_v == 'day_night':
    summary_dn_icu_sel = summary_dn_icu.loc[np.any([summary_dn_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                                   summary_dn_icu[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :]
elif icu_day_v == 'full':
    summary_dn_icu_sel = summary_f_icu.loc[np.any([summary_f_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                                   summary_f_icu[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :] 
    
print(f'Min Hours of Sleep: {min_hours_sleep_icu}')
print(f'Agreement: {agreement}')
print(f'{icu_day_v} Segments included:')
print(f'ICU:      {summary_dn_icu_sel.shape[0]} ({summary_dn_icu_sel.study_id.unique().shape[0]} subjects)')

print(f'Agreement for Sleeplab: {do_agreement_for_sleeplab}')

ahi_categories_to_plot = 'all_low_high'

if ahi_categories_to_plot == 'all':
    ahi_categories_sel = ahi_categories[:-1]
elif ahi_categories_to_plot == 'all_low_high':
    ahi_categories_sel = ['all', 'ahi_0_5', 'ahi_15_100']

n_ahi_categories = len(ahi_categories_sel)

widths = [0.25, 0.25, 0.25, 0.25]
heights = [0.23, 0.23, 0.23, 0.02, 0.29]
gs_kw = dict(height_ratios=heights, wspace=0.05, hspace=0.2) # left=0.4 , bottom=0, right=1, top=1

fig, ax = plt.subplots(5, 1+n_ahi_categories, figsize=(7, 7.5), gridspec_kw=gs_kw, constrained_layout=True,          
                      )

for ax_tmp in ax.flatten():
    ax_tmp.spines['top'].set_visible(False)
    ax_tmp.spines['right'].set_visible(False)
    ax_tmp.spines['bottom'].set_visible(False)
    ax_tmp.spines['left'].set_visible(False)
    ax_tmp.set_yticks([])
    ax_tmp.tick_params(length=0.05)
# ICU first column:
for ax_tmp in ax[3,:]:
    ax_tmp.set_xticks([])


# row 1: RESPIRATION COMPARISON.
modality = 'amendsumeffort'
variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
# if force_concordant_discordant_sleep:
#     variables = [x.replace('all', 'agreement_relaxed') if 'hours' in x else x for x in variables]
if force_concordant_discordant_sleep:
    variables = [x.replace('all', 'agreement_relaxed') if i_x in [1, 2] else x for i_x, x in enumerate(variables)] # assumption: var1 and 2 are conc/disc sleep
title = None
sleep_summary_barplots(ax[0,0], summary_dn_icu_sel, variables, x_labels_short,  color='navy', title=title)

# row 2: ECG COMPARISON.
modality = 'ecg_nn'
variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
# if force_concordant_discordant_sleep:
#     variables = [x.replace('all', 'agreement_relaxed') if 'hours' in x else x for x in variables]
if force_concordant_discordant_sleep:
    variables = [x.replace('all', 'agreement_relaxed') if i_x in [1, 2] else x for i_x, x in enumerate(variables)] # assumption: var1 and 2 are conc/disc sleep
title = None
sleep_summary_barplots(ax[1,0], summary_dn_icu_sel, variables, x_labels_short,  color='darkred', title=title)

ax[2,0].set_xticks([])
ax[2,0].text(0.2, 0.5, 'No Expert Labels\navailable for ICU.')

ax[0,0].text(  
0.5, 1.5, f'ICU \n\n(n={summary_dn_icu_sel.shape[0]})',
ha='center', va='top', fontdict = font_headers,
transform=ax[0,0].transAxes
)
    
    
for i_ahi_cat, ahi_category in enumerate(ahi_categories_sel):

    summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]
    
    if do_agreement_for_sleeplab:
        summary_days_sleeplab = summary_days_sleeplab.loc[np.any([summary_days_sleeplab[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                               summary_days_sleeplab[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                               axis=0), :]
    
    print(f'Sleeplab AHI {ahi_category}: {summary_days_sleeplab.shape[0]} ({summary_days_sleeplab.study_id.unique().shape[0]} subjects)')

    ax[0,i_ahi_cat+1].text( 
    0.5, 1.3, f'{ahi_names[ahi_category]} \n(n={summary_days_sleeplab.shape[0]})',
    ha='center', va='top', fontdict = font_headers,
    transform=ax[0,i_ahi_cat+1].transAxes
    )
    # row 1: RESPIRATION COMPARISON.

    modality = 'amendsumeffort'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
#     if force_concordant_discordant_sleep:
#         variables = [x.replace('all', 'agreement_relaxed') if 'hours' in x else x for x in variables]
    if force_concordant_discordant_sleep:
        variables = [x.replace('all', 'agreement_relaxed') if i_x in [1, 2] else x for i_x, x in enumerate(variables)] # assumption: var1 and 2 are conc/disc sleep
    title = None
    sleep_summary_barplots(ax[0,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels_short,  color='cornflowerblue', title=title)

    # row 2: ECG COMPARISON.
    modality = 'ecg_nn'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
#     if force_concordant_discordant_sleep:
#         variables = [x.replace('all', 'agreement_relaxed') if 'hours' in x else x for x in variables]
    if force_concordant_discordant_sleep:
        variables = [x.replace('all', 'agreement_relaxed') if i_x in [1, 2] else x for i_x, x in enumerate(variables)] # assumption: var1 and 2 are conc/disc sleep
    sleep_summary_barplots(ax[1,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels_short,  color='tomato', title=title)

    # row 3: EXPERT, only available for sleeplab
    modality = 'expert'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement_expert) for x in variables_template]
    sleep_summary_barplots(ax[2,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels,  color='green', title=title)


ax[0,(n_ahi_categories+1)//2].text( 
0.5, 1.5, f'Sleeplab',
ha='center', va='top', fontdict = font_headers,
transform=ax[0,(n_ahi_categories+1)//2].transAxes
)

ax[0, 0].text( 
-0.1, 0.4, f'Breathing',
ha='center', va='center', fontdict = font_headers, rotation='vertical',
transform=ax[0, 0].transAxes
)

ax[1, 0].text( 
-0.1, 0.4, f'HRV',
ha='center', va='center', fontdict = font_headers, rotation='vertical',
transform=ax[1, 0].transAxes
)

ax[2, 0].text( 
-0.1, 0.4, f'Expert',
ha='center', va='center', fontdict = font_headers, rotation='vertical',
transform=ax[2, 0].transAxes
)


############ PART B:

gs = ax[-1, 0].get_gridspec()

# remove the underlying axes
for ax_tmp in ax[-1, :2]:
    ax_tmp.remove()
ax2 = fig.add_subplot(gs[-1:, :2])

gs = ax[-1, 2].get_gridspec()

# remove the underlying axes
for ax_tmp in ax[-1, 2:]:
    ax_tmp.remove()
ax3 = fig.add_subplot(gs[-1:, 2:])

#### select version of plot:
variables_to_use = 'n2n3_discordant'
statistic = 'mean_std'
statistic = 'median_iqr'
####

if variables_to_use == 'n2n3_sum':
    variables_template = [
         'perc_N1_MODALITY_AGREEMENT', 
         'perc_N2N3_MODALITY_AGREEMENT',
        'perc_R_MODALITY_AGREEMENT', 
        'hours_sleep_MODALITY_AGREEMENT',
         'sfi_MODALITY_AGREEMENT',
         'arousali_MODALITY_AGREEMENT']

    var_names = ['N1', 'N2 + N3', 'R', 'Sleep Dur (h)', 'SFI', 'Wake T./h']

elif variables_to_use == 'n2n3_discordant':
    variables_template = [
         'perc_N1_MODALITY_AGREEMENT', 
         'perc_N2N3_MODALITY_AGREEMENT',
        'perc_R_MODALITY_AGREEMENT', 
        'hours_sleep_MODALITY_AGREEMENT',
         'hours_discordant_MODALITY_AGREEMENT', 
         'arousali_MODALITY_AGREEMENT'] 

    var_names = ['N1', 'N2 + N3', 'R', 'Concordant\nSleep (h)', 'Discordant\nSleep (h)', 'Wake\nTransitions /h']
    
ahi_category = 'all'
summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]

if do_agreement_for_sleeplab:
    summary_days_sleeplab = summary_days_sleeplab.loc[np.any([summary_days_sleeplab[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                           summary_days_sleeplab[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                           axis=0), :]
i_pos = 0

for i_var, var_temp in enumerate(variables_template[:3]):

    for modality in ['amendsumeffort', 'ecg_nn']:
        var = var_temp.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        if force_concordant_discordant_sleep & ('hours' in var):
            var = var.replace('all', 'agreement_relaxed') 
        if statistic == 'mean_std':
            ax2 = plot_mean_std_element(summary_dn_icu_sel, var, ax2, position=i_pos, color='navy', marker=marker[modality])
            ax2 = plot_mean_std_element(summary_days_sleeplab, var, ax2, position=i_pos+2, color='orange', marker=marker[modality])
        elif statistic == 'median_iqr':
            ax2 = plot_mean_std_element(summary_dn_icu_sel, var, ax2, position=i_pos, color='navy', marker=marker[modality])
            ax2 = plot_mean_std_element(summary_days_sleeplab, var, ax2, position=i_pos+2, color='orange', marker=marker[modality])
        i_pos += 1
        
    i_pos += 3

ax2.set_xticks([1.5, 6.5, 11.5])
ax2.set_xticklabels(var_names[:3])

ax2.set_ylim([0, 95])

ax2.set_ylabel('%', labelpad=-0.1)

# Subplot 2:

i_pos = 0

for i_var, var_temp in enumerate(variables_template[3:]):
    if ('hours_discordant' in var_temp) & (agreement == 'all') & (~force_concordant_discordant_sleep):
        i_pos += 5
        ax3.text(0.5, 0.1, 'N/A', ha='center', transform=ax3.transAxes)
        continue

    for modality in ['amendsumeffort', 'ecg_nn']:
        var = var_temp.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        if force_concordant_discordant_sleep & ('hours' in var):
            var = var.replace('all', 'agreement_relaxed') 
            print(var)
        if statistic == 'mean_std':
            ax3 = plot_mean_std_element(summary_dn_icu_sel, var, ax3, position=i_pos, color='navy', marker=marker[modality])
            ax3 = plot_mean_std_element(summary_days_sleeplab, var, ax3, position=i_pos+2, color='orange', marker=marker[modality])
        elif statistic == 'median_iqr':
            ax3 = plot_median_iqr_element(summary_dn_icu_sel, var, ax3, position=i_pos, color='navy', marker=marker[modality])
            ax3 = plot_median_iqr_element(summary_days_sleeplab, var, ax3, position=i_pos+2, color='orange', marker=marker[modality])
            
        i_pos += 1
    i_pos += 3

ax3.set_xticks([1.5, 6.5, 11.5])
ax3.set_xticklabels(var_names[3:])
ymin, ymax = ax3.get_ylim()
ax3.set_ylim([0, ymax])
# ax[1].set_ylabel('%')

ax3.legend(legend_handles, ['ICU, Breathing', 'ICU, HRV', 'Sleeplab, Breathing', 'Sleeplab, HRV'], 
             frameon=False, markerscale=1, ncol=1, bbox_to_anchor=(0.1, 0.66, 0.5, 0.5), loc='best')

c_axis = 'black'
ticklength = 1
lw = 0.3
for ax_tmp in [ax2, ax3]:
    for spine in ['bottom', 'top', 'right', 'left']:
        ax_tmp.spines[spine].set_color(c_axis)
        ax_tmp.spines[spine].set_linewidth(lw)
        
        ax_tmp.spines['top'].set_visible(False)
        ax_tmp.spines['right'].set_visible(False)
        ax_tmp.spines['bottom'].set_visible(False)
#         ax_tmp.spines['left'].set_visible(False)

    ax_tmp.tick_params(axis='x', colors=c_axis, length=0)
    ax_tmp.tick_params(axis='y', colors=c_axis, length=ticklength)
    ax_tmp.yaxis.label.set_color(c_axis)
    ax_tmp.xaxis.label.set_color(c_axis)
    
ax[0,0].text(-0.25, 1.45, 'A', transform=ax[0,0].transAxes, fontdict=font_subplots)
ax2.text(-0.125, 1, 'B', transform=ax2.transAxes, fontdict=font_subplots)

# fig.subplots_adjust(left=0.02, bottom=0.05, right=0.99, top=0.91) #, wspace=0, hspace=0)
plt.tight_layout()
fig.tight_layout()
plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_A1_{str(min_hours_sleep_icu)}_inclusion_{inclusion_agreement}_ahi_{ahi_categories_to_plot}_sleepstatistics_{agreement}_{icu_day_v}_sleeplabagree_{do_agreement_for_sleeplab}_forcedisc{force_concordant_discordant_sleep}.jpg'), dpi=600)
plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_A1_{str(min_hours_sleep_icu)}_inclusion_{inclusion_agreement}_ahi_{ahi_categories_to_plot}_sleepstatistics_{agreement}_{icu_day_v}_sleeplabagree_{do_agreement_for_sleeplab}_forcedisc{force_concordant_discordant_sleep}.svg'))
plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_A1_{str(min_hours_sleep_icu)}_inclusion_{inclusion_agreement}_ahi_{ahi_categories_to_plot}_sleepstatistics_{agreement}_{icu_day_v}_sleeplabagree_{do_agreement_for_sleeplab}_forcedisc{force_concordant_discordant_sleep}.eps'))
plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_A1_{str(min_hours_sleep_icu)}_inclusion_{inclusion_agreement}_ahi_{ahi_categories_to_plot}_sleepstatistics_{agreement}_{icu_day_v}_sleeplabagree_{do_agreement_for_sleeplab}_forcedisc{force_concordant_discordant_sleep}.tiff'), dpi=600)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Min Hours of Sleep: 0.01
Agreement: all
full Segments included:
ICU:      274 (102 subjects)
Agreement for Sleeplab: False

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Sleeplab AHI all: 220 (220 subjects)
Sleeplab AHI ahi_0_5: 77 (77 subjects)
Sleeplab AHI ahi_15_100: 52 (52 subjects)
hours_sleep_amendsumeffort_agreement_relaxed
hours_sleep_ecg_nn_agreement_relaxed
hours_discordant_amendsumeffort_agreement_relaxed
hours_discordant_ecg_nn_agreement_relaxed

/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/ipykernel_launcher.py:347: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/ipykernel_launcher.py:348: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.

In [21]:
plots_savedir

'/scr/wolfgang/Dropbox (Partners HealthCare)/SleepInICUandSleeplabPaper/Plots/sleep_staging'

In [22]:
# last version:

# Min Hours of Sleep: 0.01
# Agreement: all
# full Segments included:
# ICU:      223 (83 subjects)
# Agreement for Sleeplab: False

# Sleeplab AHI all: 220 (220 subjects)
# Sleeplab AHI ahi_0_5: 77 (77 subjects)
# Sleeplab AHI ahi_15_100: 52 (52 subjects)
# hours_sleep_amendsumeffort_agreement_relaxed
# hours_sleep_ecg_nn_agreement_relaxed
# hours_discordant_amendsumeffort_agreement_relaxed
# hours_discordant_ecg_nn_agreement_relaxed

In [23]:
# variables_template = [
#  'hours_sleep_MODALITY_all', # overall sleep duration.
#  'hours_sleep_MODALITY_AGREEMENT',
#  'hours_discordant_MODALITY_AGREEMENT', 
#  'perc_S_MODALITY_AGREEMENT',

# summary_dn_icu_sel['hours_sleep_MODALITY_AGREEMENT'.replace()]
# summary_days_sleeplab

In [24]:
if 0:
    
    #### same as above but discordant sleep as percentage, not absolute value.

    #### select version of plot:
    ahi_category = 'all'
    force_concordant_discordant_sleep = True # if we use 'all' agreement option, do you still want to retrieve concordant/discordant sleep info from relaxed_agreement option. this is True for the paper figures.

    ### compare ICU group 3 and sleeplab group 3:
    agreement = 'agreement_relaxed'
    min_hours_sleep_icu = 2
    inclusion_agreement = 'agreement_relaxed'
    do_agreement_for_sleeplab = True

    ### compare ICU group 3 and sleeplab group 2:
    # agreement = 'all'
    # min_hours_sleep_icu = 2
    # inclusion_agreement = 'agreement_relaxed'
    # do_agreement_for_sleeplab = False

    # # compare ICU group 2 and sleeplab group 2:
    # agreement = 'all'
    # min_hours_sleep_icu = 0.01
    # inclusion_agreement = 'all'
    # do_agreement_for_sleeplab = False


    agreement_expert = 'all'
    icu_day_v = 'full'

    ####
    marker = {'amendsumeffort': 'o',
             'ecg_nn': 's'}

    legend_handles = []

    figdummy, axdummy = plt.subplots(1,1);
    plt.close()
    legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='navy', fmt='.', zorder=1, marker=marker['amendsumeffort']))
    legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='navy', fmt='.', zorder=1, marker=marker['ecg_nn']))
    legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='orange', fmt='.', zorder=1, marker=marker['amendsumeffort']))
    legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='orange', fmt='.', zorder=1, marker=marker['ecg_nn']))


    ### same as above but remove SFI Wake and relabel variables.


    ### 3x2 plot
    # cols: data type, rows: stage version (resp, ecg, expert)

    variables_template = [
     'hours_sleep_MODALITY_all', # overall sleep duration.
     'hours_sleep_MODALITY_AGREEMENT', # concordant sleep duration
     'perc_discordant_MODALITY_AGREEMENT', 
     'perc_S_MODALITY_AGREEMENT',
     'perc_R_MODALITY_AGREEMENT',
     'perc_N1_MODALITY_AGREEMENT',
     'perc_N2_MODALITY_AGREEMENT',
     'perc_N3_MODALITY_AGREEMENT',
     'sfi_MODALITY_AGREEMENT',
     'arousali_MODALITY_AGREEMENT',
    ]


    x_labels = ['Total Sleep (h)', 'Concordant Sleep (h)', 'Discordant S. (%)',  'Sleep (%)', 'Stage R (%)', 'Stage N1 (%)', 'Stage N2 (%)', 'Stage N3 (%)', 'SFI', 'Wake Trans./h']
    x_labels_short = ['TS', 'CS', 'DS', 'S', 'R', 'N1', 'N2', 'N3', 'SFI', 'WT']

    summary_days_sleeplab_full['hours_discordant_expert_all'] = np.nan
    summary_days_sleeplab_full['perc_discordant_expert_all'] = np.nan
    summary_days_sleeplab_full['hours_sleep_expert_agreement_relaxed'] = np.nan

    # summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]


    if icu_day_v == 'day_night':
        summary_dn_icu_sel = summary_dn_icu.loc[np.any([summary_dn_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                                       summary_dn_icu[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                                       axis=0), :]
    elif icu_day_v == 'full':
        summary_dn_icu_sel = summary_f_icu.loc[np.any([summary_f_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                                       summary_f_icu[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                                       axis=0), :] 

    print(f'Min Hours of Sleep: {min_hours_sleep_icu}')
    print(f'Agreement: {agreement}')
    print(f'{icu_day_v} Segments included:')
    print(f'ICU:      {summary_dn_icu_sel.shape[0]} ({summary_dn_icu_sel.study_id.unique().shape[0]} subjects)')

    print(f'Agreement for Sleeplab: {do_agreement_for_sleeplab}')

    ahi_categories_to_plot = 'all_low_high'

    if ahi_categories_to_plot == 'all':
        ahi_categories_sel = ahi_categories[:-1]
    elif ahi_categories_to_plot == 'all_low_high':
        ahi_categories_sel = ['all', 'ahi_0_5', 'ahi_15_100']

    n_ahi_categories = len(ahi_categories_sel)

    widths = [0.25, 0.25, 0.25, 0.25]
    heights = [0.23, 0.23, 0.23, 0.02, 0.29]
    gs_kw = dict(height_ratios=heights, wspace=0.05, hspace=0.2) # left=0.4 , bottom=0, right=1, top=1

    fig, ax = plt.subplots(5, 1+n_ahi_categories, figsize=(7, 7.5), gridspec_kw=gs_kw, constrained_layout=True,                     
                          )

    for ax_tmp in ax.flatten():
        ax_tmp.spines['top'].set_visible(False)
        ax_tmp.spines['right'].set_visible(False)
        ax_tmp.spines['bottom'].set_visible(False)
        ax_tmp.spines['left'].set_visible(False)
        ax_tmp.set_yticks([])
        ax_tmp.tick_params(length=0.05)
    # ICU first column:
    for ax_tmp in ax[3,:]:
        ax_tmp.set_xticks([])


    # row 1: RESPIRATION COMPARISON.
    modality = 'amendsumeffort'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
    if force_concordant_discordant_sleep:
        variables = [x.replace('all', 'agreement_relaxed') if i_x in [1, 2] else x for i_x, x in enumerate(variables)] # assumption: var1 and 2 are conc/disc sleep
    title = None
    sleep_summary_barplots(ax[0,0], summary_dn_icu_sel, variables, x_labels_short,  color='navy', title=title)

    # row 2: ECG COMPARISON.
    modality = 'ecg_nn'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
    if force_concordant_discordant_sleep:
        variables = [x.replace('all', 'agreement_relaxed') if i_x in [1, 2] else x for i_x, x in enumerate(variables)] # assumption: var1 and 2 are conc/disc sleep
    title = None
    sleep_summary_barplots(ax[1,0], summary_dn_icu_sel, variables, x_labels_short,  color='darkred', title=title)

    ax[2,0].set_xticks([])
    ax[2,0].text(0.2, 0.5, 'No Expert Labels\navailable for ICU.')

    ax[0,0].text(  
    0.5, 1.5, f'ICU \n\n(n={summary_dn_icu_sel.shape[0]})', # 1.27
    ha='center', va='top', fontdict = font_headers,
    transform=ax[0,0].transAxes
    )


    for i_ahi_cat, ahi_category in enumerate(ahi_categories_sel):

        summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]

        if do_agreement_for_sleeplab:
            summary_days_sleeplab = summary_days_sleeplab.loc[np.any([summary_days_sleeplab[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                                   summary_days_sleeplab[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :]

        print(f'Sleeplab AHI {ahi_category}: {summary_days_sleeplab.shape[0]} ({summary_days_sleeplab.study_id.unique().shape[0]} subjects)')

        ax[0,i_ahi_cat+1].text( 
        0.5, 1.3, f'{ahi_names[ahi_category]} \n(n={summary_days_sleeplab.shape[0]})',
        ha='center', va='top', fontdict = font_headers,
        transform=ax[0,i_ahi_cat+1].transAxes
        )
        # row 1: RESPIRATION COMPARISON.

        modality = 'amendsumeffort'
        variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
        if force_concordant_discordant_sleep:
            variables = [x.replace('all', 'agreement_relaxed') if i_x in [1, 2] else x for i_x, x in enumerate(variables)] # assumption: var1 and 2 are conc/disc sleep
        title = None
        sleep_summary_barplots(ax[0,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels_short,  color='cornflowerblue', title=title)

        # row 2: ECG COMPARISON.
        modality = 'ecg_nn'
        variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
        if force_concordant_discordant_sleep:
            variables = [x.replace('all', 'agreement_relaxed') if i_x in [1, 2] else x for i_x, x in enumerate(variables)] # assumption: var1 and 2 are conc/disc sleep
        sleep_summary_barplots(ax[1,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels_short,  color='tomato', title=title)

        # row 3: EXPERT, only available for sleeplab
        modality = 'expert'
        variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement_expert) for x in variables_template]
        print(variables)
        sleep_summary_barplots(ax[2,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels,  color='green', title=title)


    ax[0,(n_ahi_categories+1)//2].text( 
    0.5, 1.5, f'Sleeplab',
    ha='center', va='top', fontdict = font_headers,
    transform=ax[0,(n_ahi_categories+1)//2].transAxes
    )

    ax[0, 0].text( 
    -0.1, 0.4, f'Breathing',
    ha='center', va='center', fontdict = font_headers, rotation='vertical',
    transform=ax[0, 0].transAxes
    )

    ax[1, 0].text( 
    -0.1, 0.4, f'HRV',
    ha='center', va='center', fontdict = font_headers, rotation='vertical',
    transform=ax[1, 0].transAxes
    )

    ax[2, 0].text( 
    -0.1, 0.4, f'Expert',
    ha='center', va='center', fontdict = font_headers, rotation='vertical',
    transform=ax[2, 0].transAxes
    )


    ############ PART B:

    gs = ax[-1, 0].get_gridspec()

    # remove the underlying axes
    for ax_tmp in ax[-1, :2]:
        ax_tmp.remove()
    ax2 = fig.add_subplot(gs[-1:, :2])

    gs = ax[-1, 2].get_gridspec()

    # remove the underlying axes
    for ax_tmp in ax[-1, 2:]:
        ax_tmp.remove()
    ax3 = fig.add_subplot(gs[-1:, 2:])

    #### select version of plot:
    variables_to_use = 'n2n3_discordant'
    statistic = 'mean_std'
    statistic = 'median_iqr'
    ####

    if variables_to_use == 'n2n3_sum':
        variables_template = [
             'perc_N1_MODALITY_AGREEMENT', 
             'perc_N2N3_MODALITY_AGREEMENT',
            'perc_R_MODALITY_AGREEMENT', 
            'hours_sleep_MODALITY_AGREEMENT',
             'sfi_MODALITY_AGREEMENT',
             'arousali_MODALITY_AGREEMENT']

        var_names = ['N1', 'N2 + N3', 'R', 'Sleep Dur (h)', 'SFI', 'Wake T./h']

    elif variables_to_use == 'n2n3_discordant':
        variables_template = [
             'perc_N1_MODALITY_AGREEMENT', 
             'perc_N2N3_MODALITY_AGREEMENT',
            'perc_R_MODALITY_AGREEMENT', 
            'hours_sleep_MODALITY_AGREEMENT',
             'hours_discordant_MODALITY_AGREEMENT', 
             'arousali_MODALITY_AGREEMENT'] 

        var_names = ['N1', 'N2 + N3', 'R', 'Concordant\nSleep (h)', 'Discordant\nSleep (h)', 'Wake\nTransitions /h']

    ahi_category = 'all'
    summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]

    if do_agreement_for_sleeplab:
        summary_days_sleeplab = summary_days_sleeplab.loc[np.any([summary_days_sleeplab[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                               summary_days_sleeplab[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                               axis=0), :]
    i_pos = 0

    for i_var, var_temp in enumerate(variables_template[:3]):

        for modality in ['amendsumeffort', 'ecg_nn']:
            var = var_temp.replace('MODALITY', modality).replace('AGREEMENT', agreement)
            if force_concordant_discordant_sleep & (i_var in [1, 2]): # assume var 1 and 2 are conc/disc sleep
                var = var.replace('all', 'agreement_relaxed') 
            if statistic == 'mean_std':
                ax2 = plot_mean_std_element(summary_dn_icu_sel, var, ax2, position=i_pos, color='navy', marker=marker[modality])
                ax2 = plot_mean_std_element(summary_days_sleeplab, var, ax2, position=i_pos+2, color='orange', marker=marker[modality])
            elif statistic == 'median_iqr':
                ax2 = plot_mean_std_element(summary_dn_icu_sel, var, ax2, position=i_pos, color='navy', marker=marker[modality])
                ax2 = plot_mean_std_element(summary_days_sleeplab, var, ax2, position=i_pos+2, color='orange', marker=marker[modality])
            i_pos += 1

        i_pos += 3

    ax2.set_xticks([1.5, 6.5, 11.5])
    ax2.set_xticklabels(var_names[:3])

    ax2.set_ylim([0, 95])

    ax2.set_ylabel('%', labelpad=-0.1)

    # Subplot 2:

    i_pos = 0

    for i_var, var_temp in enumerate(variables_template[3:]):
        if ('hours_discordant' in var_temp) & (agreement == 'all') & (~force_concordant_discordant_sleep):
            i_pos += 5
            ax3.text(0.5, 0.1, 'N/A', ha='center', transform=ax3.transAxes)
            continue

        for modality in ['amendsumeffort', 'ecg_nn']:
            var = var_temp.replace('MODALITY', modality).replace('AGREEMENT', agreement)
            if force_concordant_discordant_sleep & (i_var in [1, 2]): # assume var 1 and 2 are conc/disc sleep
                var = var.replace('all', 'agreement_relaxed') 
                print(var)
            if statistic == 'mean_std':
                ax3 = plot_mean_std_element(summary_dn_icu_sel, var, ax3, position=i_pos, color='navy', marker=marker[modality])
                ax3 = plot_mean_std_element(summary_days_sleeplab, var, ax3, position=i_pos+2, color='orange', marker=marker[modality])
            elif statistic == 'median_iqr':
                ax3 = plot_median_iqr_element(summary_dn_icu_sel, var, ax3, position=i_pos, color='navy', marker=marker[modality])
                ax3 = plot_median_iqr_element(summary_days_sleeplab, var, ax3, position=i_pos+2, color='orange', marker=marker[modality])

            i_pos += 1
        i_pos += 3

    ax3.set_xticks([1.5, 6.5, 11.5])
    ax3.set_xticklabels(var_names[3:])
    ymin, ymax = ax3.get_ylim()
    ax3.set_ylim([0, ymax])
    # ax[1].set_ylabel('%')

    ax3.legend(legend_handles, ['ICU, Breathing', 'ICU, HRV', 'Sleeplab, Breathing', 'Sleeplab, HRV'], 
                 frameon=False, markerscale=1, ncol=1, bbox_to_anchor=(0.1, 0.66, 0.5, 0.5), loc='best')

    c_axis = 'black'
    ticklength = 1
    lw = 0.3
    for ax_tmp in [ax2, ax3]:
        for spine in ['bottom', 'top', 'right', 'left']:
            ax_tmp.spines[spine].set_color(c_axis)
            ax_tmp.spines[spine].set_linewidth(lw)

            ax_tmp.spines['top'].set_visible(False)
            ax_tmp.spines['right'].set_visible(False)
            ax_tmp.spines['bottom'].set_visible(False)
    #         ax_tmp.spines['left'].set_visible(False)

        ax_tmp.tick_params(axis='x', colors=c_axis, length=0)
        ax_tmp.tick_params(axis='y', colors=c_axis, length=ticklength)
        ax_tmp.yaxis.label.set_color(c_axis)
        ax_tmp.xaxis.label.set_color(c_axis)

    ax[0,0].text(-0.25, 1.45, 'A', transform=ax[0,0].transAxes, fontdict=font_subplots)
    ax2.text(-0.125, 1, 'B', transform=ax2.transAxes, fontdict=font_subplots)

    # fig.subplots_adjust(left=0.02, bottom=0.05, right=0.99, top=0.91) #, wspace=0, hspace=0)
    plt.tight_layout()
    fig.tight_layout()
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_A1_{str(min_hours_sleep_icu)}_{inclusion_agreement}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_sleeplabagree_{do_agreement_for_sleeplab}_percdiscordant.jpg'), dpi=600)
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_A1_{str(min_hours_sleep_icu)}_{inclusion_agreement}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_sleeplabagree_{do_agreement_for_sleeplab}_percdiscordant.svg'))
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_A1_{str(min_hours_sleep_icu)}_{inclusion_agreement}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_sleeplabagree_{do_agreement_for_sleeplab}_percdiscordant.eps'))
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_A1_{str(min_hours_sleep_icu)}_{inclusion_agreement}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_sleeplabagree_{do_agreement_for_sleeplab}_percdiscordant.tiff'), dpi=600)

In [25]:
plt.close('all')

### Mean between HRV and Breathing. Statistical tests.

In [26]:
from scipy.stats import shapiro, mannwhitneyu, median_test, ttest_ind, normaltest, shapiro

In [27]:
# Mean HRV and Breathing.
variables_template = [
 'hours_sleep_MODALITY_all',
 'hours_sleep_MODALITY_AGREEMENT',
 'hours_discordant_MODALITY_AGREEMENT', 
 'perc_discordant_MODALITY_AGREEMENT', 
 'perc_S_MODALITY_AGREEMENT',
 'perc_R_MODALITY_AGREEMENT',
 'perc_N1_MODALITY_AGREEMENT',
 'perc_N2_MODALITY_AGREEMENT',
 'perc_N3_MODALITY_AGREEMENT',
 'perc_N2N3_MODALITY_AGREEMENT',
 'sfi_MODALITY_AGREEMENT',
 'arousali_MODALITY_AGREEMENT',
]

x_labels = ['Total S. (h)', 'Concordant S. (h)', 'Discordant S. (h)', 'Discordant S. (%)'  'Sleep (%)', 'Stage R (%)', 'Stage N1 (%)', 'Stage N2 (%)', 'Stage N3 (%)', 'Stage N2+N3(%)', 'SFI', 'Wake Trans./h']
x_labels_short = ['TS', 'CS', 'DS', 'DS%', 'S', 'R', 'N1', 'N2', 'N3', 'N2+N3', 'SFI', 'WT']
print(agreement)
modality = 'amendsumeffort'
variables_breathing = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
modality = 'ecg_nn'
variables_hrv = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
modality = 'mean'
variables_mean = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]

if force_concordant_discordant_sleep:
    
    variables_breathing = [x.replace('all', 'agreement_relaxed') if i_x in [1, 2, 3] else x for i_x, x in enumerate(variables_breathing)] # assume var 1, 2, 3 are conc./disc. sleep
    variables_hrv = [x.replace('all', 'agreement_relaxed') if i_x in [1, 2, 3] else x for i_x, x in enumerate(variables_hrv)] # assume var 1, 2, 3 are conc./disc. sleep
    variables_mean = [x.replace('all', 'agreement_relaxed') if i_x in [1, 2, 3] else x for i_x, x in enumerate(variables_mean)] # assume var 1, 2, 3 are conc./disc. sleep

# var_concordant = [x for x in variables_breathing if 'hours_sleep' in x][0]
# var_discordant = [x for x in variables_breathing if 'hours_discordant' in x][0]
# var_total = var_concordant.replace('hours_sleep', 'total_sleep')
# variables_breathing = [var_total] + variables_breathing
# summary_dn_icu_sel[var_total] = summary_dn_icu_sel[var_concordant] + summary_dn_icu_sel[var_discordant]
# variables_hrv = [var_total.replace('amendsumeffort', 'ecg_nn')] + variables_hrv
# variables_mean = [var_total.replace('amendsumeffort', 'mean')] + variables_mean

# summary_dn_icu_sel[var_total] = summary_dn_icu_sel[var_concordant] + summary_dn_icu_sel[var_discordant]
# summary_dn_icu_sel[var_total.replace('amendsumeffort', 'ecg_nn')] = summary_dn_icu_sel[var_concordant.replace('amendsumeffort', 'ecg_nn')] + summary_dn_icu_sel[var_discordant.replace('amendsumeffort', 'ecg_nn')]
# summary_days_sleeplab_full[var_total] = summary_days_sleeplab_full[var_concordant] + summary_days_sleeplab_full[var_discordant]
# summary_days_sleeplab_full[var_total.replace('amendsumeffort', 'ecg_nn')] = summary_days_sleeplab_full[var_concordant.replace('amendsumeffort', 'ecg_nn')] + summary_days_sleeplab_full[var_discordant.replace('amendsumeffort', 'ecg_nn')]

for var_breathing, var_hrv, var_mean in zip(variables_breathing, variables_hrv, variables_mean):
    summary_dn_icu_sel[var_mean] = (summary_dn_icu_sel[var_breathing] + summary_dn_icu_sel[var_hrv]) / 2
    summary_days_sleeplab_full[var_mean] = (summary_days_sleeplab_full[var_breathing] + summary_days_sleeplab_full[var_hrv]) / 2
    
# variables_template += ['hours_sleep_total_MODALITY_AGREEMENT']
# for modality in ['amendsumeffort', 'ecg_nn', 'mean']:
#     summary_dn_icu_sel[f'hours_sleep_total_{modality}_{agreement}'] = summary_dn_icu_sel[f'hours_sleep_{modality}_{agreement}'] + summary_dn_icu_sel[f'hours_discordant_{modality}_{agreement}']
#     summary_days_sleeplab_full[f'hours_sleep_total_{modality}_{agreement}'] = summary_days_sleeplab_full[f'hours_sleep_{modality}_{agreement}'] + summary_days_sleeplab_full[f'hours_discordant_{modality}_{agreement}']

all

/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [28]:
if 0:
    plt.figure(figsize=(5,3))
    plt.hist(summary_dn_icu_sel['perc_R_mean_agreement_relaxed'].values, histtype='step', density=True)
    plt.hist(summary_days_sleeplab_full['perc_R_mean_agreement_relaxed'].values, histtype='step', density=True)
    plt.xlabel('% REM per subject')
    plt.ylabel('Density')
    plt.legend(['ICU', 'Sleeplab'])
    plt.tight_layout()

    print('ICU')
    print(summary_dn_icu_sel['perc_R_mean_agreement_relaxed'].quantile(0.25))
    print(summary_dn_icu_sel['perc_R_mean_agreement_relaxed'].quantile(0.5))
    print(summary_dn_icu_sel['perc_R_mean_agreement_relaxed'].quantile(0.75))
    print(summary_dn_icu_sel['perc_R_mean_agreement_relaxed'].quantile(0.9))

    print('sleeplab')
    print(summary_days_sleeplab_full['perc_R_mean_agreement_relaxed'].quantile(0.25))
    print(summary_days_sleeplab_full['perc_R_mean_agreement_relaxed'].quantile(0.50))
    print(summary_days_sleeplab_full['perc_R_mean_agreement_relaxed'].quantile(0.75))
    print(summary_days_sleeplab_full['perc_R_mean_agreement_relaxed'].quantile(0.9))

In [29]:
import itertools
# statistics = ['Mean', 'Std', 'Median', 'Iqr', 'p_dag', 'p_sha', 'gaussian', 'p_tt', 'p_medians', 'p_mwu', 'diff_tt', 'sig_medians', 'sig_mwu']
# cohorts_names = ['ICU', 'Sleeplab All', 'Sleeplab AHI 0-5', 'Sleeplab AHI 15-100']
# statistics_pop = list(itertools.product(cohorts_names, statistics))

cohorts_names = ['ICU', 'Sleeplab All', 'Sleeplab AHI 0-5', 'Sleeplab AHI 15-100']

n_subjects = list(itertools.product(cohorts_names, ['N Subjects']))
statistics = ['Mean', 'Median']
statistics_pop = n_subjects + list(itertools.product(cohorts_names, statistics))
statistics = [ 'p_tt', 's_tt', 'p_medians', 's_medians', 'p_mwu', 's_mwu', 'Std',  'Iqr', 'p_dag', 'p_sha', 'gaussian',]
statistics_pop += list(itertools.product(cohorts_names, statistics))


df_results = pd.DataFrame(index=x_labels_short, columns = statistics_pop)

In [30]:
# compute 1 row per patient ICU version:

summary_dn_icu_sel_subject = summary_dn_icu_sel.loc[:, summary_dn_icu_sel.dtypes != 'object'].copy()
for study_id_tmp in summary_dn_icu_sel.study_id.unique():
    
    new_values = pd.DataFrame(summary_dn_icu_sel_subject.loc[summary_dn_icu_sel_subject.study_id == study_id_tmp].mean()).transpose()
    summary_dn_icu_sel_subject = summary_dn_icu_sel_subject[summary_dn_icu_sel_subject.study_id != study_id_tmp]
    summary_dn_icu_sel_subject = pd.concat([summary_dn_icu_sel_subject, new_values], axis=0, ignore_index=True)

In [31]:
summary_dn_icu_sel_subject.to_csv('summary_icu_mean_per_subject.csv', index=False)

In [32]:
summary_dn_icu_sel_subject.head(2)

,inclusion_subject,study_id,mrn,age,bmi,sex,osa_diagnosis,icu_mortality,3_month_mortality,icu_los,hospital_los,chf,copd,med_surg,CCI,CCI_weighted,Belt_Length,day_no,hr_mean,hr_std,hr_median,hr_q25,hr_q75,hr_sda,hr_asd,spo2_mean,spo2_std,spo2_median,spo2_q25,spo2_q75,spo2_sda,spo2_asd,spo2_airgo_mean,spo2_airgo_std,spo2_airgo_median,spo2_airgo_q25,spo2_airgo_q75,spo2_airgo_sda,spo2_airgo_asd,spo2_clean_mean,spo2_clean_std,spo2_clean_median,spo2_clean_q25,spo2_clean_q75,spo2_clean_sda,spo2_clean_asd,spo2_airgo_clean_mean,spo2_airgo_clean_std,spo2_airgo_clean_median,spo2_airgo_clean_q25,spo2_airgo_clean_q75,spo2_airgo_clean_sda,spo2_airgo_clean_asd,edw_bp_systolic_mean,edw_bp_systolic_std,edw_bp_systolic_median,edw_bp_systolic_q25,edw_bp_systolic_q75,edw_bp_diastolic_mean,edw_bp_diastolic_std,edw_bp_diastolic_median,edw_bp_diastolic_q25,edw_bp_diastolic_q75,edw_bp_map_mean,edw_bp_map_std,edw_bp_map_median,edw_bp_map_q25,edw_bp_map_q75,cpc_hfc_lfc_ratio_mean,cpc_hfc_lfc_ratio_std,cpc_hfc_lfc_ratio_median,cpc_hfc_lfc_ratio_q25,cpc_hfc_lfc_ratio_q75,cpc_hfc_mean,cpc_hfc_std,cpc_hfc_median,cpc_hfc_q25,cpc_hfc_q75,cpc_hfc_sum,cpc_lfc_mean,cpc_lfc_std,cpc_lfc_median,cpc_lfc_q25,cpc_lfc_q75,cpc_lfc_sum,hrv_nn_q25,hrv_nn_q75,hrv_nn_sda,hrv_nn_asd,hco3_arterial_mean,hco3_arterial_min,hco3_arterial_max,pco2_arterial_mean,pco2_arterial_min,pco2_arterial_max,po2_arterial_mean,po2_arterial_min,po2_arterial_max,ph_arterial_mean,ph_arterial_min,ph_arterial_max,oxygen_flow_rate_max,sofa_score_mean,sofa_score_min,sofa_score_max,ahi_va_a3,ahi_va_a3_ss,ahi_vb_a3,ahi_vb_a3_ss,ahi_ro_a3,ahi_ro_a3_ss,ahi_rsr_a3,ahi_rsr_a3_ss,ahi_expert,ahi_va_a3_ss_aswti,ahi_vb_a3_ss_aswti,ahi_ro_a3_ss_aswti,ahi_rsr_a3_ss_aswti,hypoxic_burden_va_a3,hypoxic_burden_va_a3_ss,hypoxic_burden_vb_a3,hypoxic_burden_vb_a3_ss,hypoxic_burden_ro_a3,hypoxic_burden_ro_a3_ss,hypoxic_burden_rsr_a3,hypoxic_burden_rsr_a3_ss,hypoxic_burden_expert,hypoxic_burden_va_a3_ss_aswti,hypoxic_burden_vb_a3_ss_aswti,hypoxic_burden_ro_a3_ss_aswti,hypoxic_burden_rsr_a3_ss_aswti,hypoxia_LDI,hypoxia_SDI,hypoxia_TDI,hypoxia_pu90,hypoxia_ss_LDI,hypoxia_ss_SDI,hypoxia_ss_TDI,hypoxia_ss_pu90,hypoxia_ss_aswti_LDI,hypoxia_ss_aswti_SDI,hypoxia_ss_aswti_TDI,hypoxia_ss_aswti_pu90,self_similarity_sleep,self_similarity_sleep_q50,self_similarity_sleep_q75,self_similarity_apnea,self_similarity_apnea_q50,self_similarity_apnea_q75,opioids_sum,...,perc_N1_ecg_nn_disagreement_relaxed,perc_N2_ecg_nn_disagreement_relaxed,perc_N3_ecg_nn_disagreement_relaxed,sfi_ecg_nn_disagreement_relaxed,sfi_w_ecg_nn_disagreement_relaxed,arousali_ecg_nn_disagreement_relaxed,hours_data_amendsumeffort_all,hours_sleep_amendsumeffort_all,perc_W_amendsumeffort_all,perc_S_amendsumeffort_all,perc_R_amendsumeffort_all,perc_N1_amendsumeffort_all,perc_N2_amendsumeffort_all,perc_N3_amendsumeffort_all,sfi_amendsumeffort_all,sfi_w_amendsumeffort_all,arousali_amendsumeffort_all,hours_data_amendsumeffort_agreement,hours_sleep_amendsumeffort_agreement,perc_W_amendsumeffort_agreement,perc_S_amendsumeffort_agreement,perc_R_amendsumeffort_agreement,perc_N1_amendsumeffort_agreement,perc_N2_amendsumeffort_agreement,perc_N3_amendsumeffort_agreement,sfi_amendsumeffort_agreement,sfi_w_amendsumeffort_agreement,arousali_amendsumeffort_agreement,hours_data_amendsumeffort_disagreement,hours_sleep_amendsumeffort_disagreement,perc_W_amendsumeffort_disagreement,perc_S_amendsumeffort_disagreement,perc_R_amendsumeffort_disagreement,perc_N1_amendsumeffort_disagreement,perc_N2_amendsumeffort_disagreement,perc_N3_amendsumeffort_disagreement,sfi_amendsumeffort_disagreement,sfi_w_amendsumeffort_disagreement,arousali_amendsumeffort_disagreement,hours_data_amendsumeffort_agreement_relaxed,hours_sleep_amendsumeffort_agreement_relaxed,perc_W_amendsumeffort_agreement_relaxed,perc_S_amendsumeffort_agreement_relaxed,perc_R_amendsumeffort_agreement_relaxed,perc_N1_amendsumeffort_agreement_relaxed,perc_N2_amendsumeffort_agreement_relaxed,perc_N3_amendsumeffort_agreement_relaxed,sfi_amendsumeffort_agreement_relaxed,sfi_w_amendsumeffort_agreement_relaxed,arousali_amendsumeffort_agreement_relaxed,hours_data_amendsumeffort_disagreement_relaxed,hours_sleep_amendsumeffort_disagreement_relaxed,perc_W_amendsumeffort_disagreement_relaxed,perc_S_amendsumeffort_disagreement_relaxed,perc_R_amendsumeffort_disagreement_relaxed,perc_N1_amendsumeffort_disagreement_relaxed,perc_N2_amendsumeffort_disagreement_relaxed,perc_N3_amendsumeffort_disagreement_relaxed,sfi_amendsumeffort_disagreement_relaxed,sfi_w_amendsumeffort_disagreement_relaxed,arousali_amendsumeffort_disagreement_relaxed,hours_data_expert_all,hours_sleep_expert_all,perc_W_expert_all,perc_S_expert_all,perc_R_expert_all,perc_N1_expert_all,perc_N2_expert_all,perc_N3_expert_all,sfi_expert_all,sfi_w_expert_all,arousali_expert_all,hours_data_expert_agreement,hours_sleep_expert_agreement,perc_W_expert_agreement,perc_S_expert_agreement,perc_R_expert_agreement,perc_N1_expert_agreement,perc_N2_expert_agreement,perc_N3_expert_agreement,sfi_expert_agreement,sfi_w_expert_agreement,arousali_expert_agreement,hours_data_expert_disagreement,hours_sleep_expert_disagreement,perc_W_expert_disagreement,perc_S_expert_disagreement,perc_R_expert_disagreement,perc_N1_expert_disagreement,perc_N2_expert_disagreement,perc_N3_expert_disagreement,sfi_expert_disagreement,sfi_w_expert_disagreement,arousali_expert_disagreement,hours_data_expert_agreement_relaxed,hours_sleep_expert_agreement_relaxed,perc_W_expert_agreement_relaxed,perc_S_expert_agreement_relaxed,perc_R_expert_agreement_relaxed,perc_N1_expert_agreement_relaxed,perc_N2_expert_agreement_relaxed,perc_N3_expert_agreement_relaxed,sfi_expert_agreement_relaxed,sfi_w_expert_agreement_relaxed,arousali_expert_agreement_relaxed,hours_data_expert_disagreement_relaxed,hours_sleep_expert_disagreement_relaxed,perc_W_expert_disagreement_relaxed,perc_S_expert_disagreement_relaxed,perc_R_expert_disagreement_relaxed,perc_N1_expert_disagreement_relaxed,perc_N2_expert_disagreement_relaxed,perc_N3_expert_disagreement_relaxed,sfi_expert_disagreement_relaxed,sfi_w_expert_disagreement_relaxed,arousali_expert_disagreement_relaxed,perc_N2N3_amendsumeffort_all,perc_N2N3_ecg_nn_all,perc_N2N3_amendsumeffort_agreement_relaxed,perc_N2N3_ecg_nn_agreement_relaxed,perc_N2N3_amendsumeffort_disagreement_relaxed,perc_N2N3_ecg_nn_disagreement_relaxed,perc_N2N3_amendsumeffort_agreement,perc_N2N3_ecg_nn_agreement,perc_N2N3_amendsumeffort_disagreement,perc_N2N3_ecg_nn_disagreement,hours_discordant_amendsumeffort_agreement_relaxed,perc_discordant_amendsumeffort_agreement_relaxed,hours_discordant_ecg_nn_agreement_relaxed,perc_discordant_ecg_nn_agreement_relaxed,hours_discordant_amendsumeffort_agreement,perc_discordant_amendsumeffort_agreement,hours_discordant_ecg_nn_agreement,perc_discordant_ecg_nn_agreement,hours_discordant_amendsumeffort_all,perc_discordant_amendsumeffort_all,hours_discordant_ecg_nn_all,perc_discordant_ecg_nn_all,hours_sleep_mean_all,hours_sleep_mean_agreement_relaxed,hours_discordant_mean_agreement_relaxed,perc_discordant_mean_agreement_relaxed,perc_S_mean_all,perc_R_mean_all,perc_N1_mean_all,perc_N2_mean_all,perc_N3_mean_all,perc_N2N3_mean_all,sfi_mean_all,arousali_mean_all
0,1.0,1.0,1298742.0,79.0,25.82,1.0,0.0,0.0,0.0,3.0,5.0,0.0,1.0,1.0,3.0,3.0,NaN,2.0,78.913475,9.344049,77.000000,74.0000,81.875,6.976189,4.291044,94.476364,2.086595,95.000000,93.18750,96.000000,1.574854,1.126852,94.307457,1.868568,94.68750,93.00000,95.875000,1.394984,1.017925,94.498398,2.013908,95.000000,93.3125,96.0000,1.542379,1.101906,94.346497,1.710806,94.68750,93.125,95.87500,1.328358,0.975476,105.000000,12.727922,105.000,100.500,109.5000,54.500000,6.363961,54.5,52.250,56.7500,71.333336,8.485281,71.333336,68.333336,74.333336,-0.149197,2.166908,0.042522,-1.605968,1.544118,0.557920,0.862907,0.150333,0.00000,0.696384,259232.390625,4.126880,16.148140,0.108961,0.000000,0.667470,1.917518e+06,0.737500,0.812500,0.061105,0.081164,28.0,28.0,28.0,44.0,44.0,44.0,126.0,126.0,126.0,7.43,7.43,7.43,2.0,3.000000,2.00,5.00,10.810311,30.666667,10.810311,30.666667,10.810311,30.666667,10.893468,34.00000,NaN,28.142244,28.142244,28.142244,33.660331,90.90,9.700,0.0,0.0,90.90,9.700,70.5,12.500,NaN,25.4,25.4,25.4,41.50,7.152317,11.622515,18.774833,0.011130,9.999993,17.999988,27.999981,0.000722,10.958731,18.629843,29.588575,0.001674,0.000005,0.085022,0.110046,0.001709,0.110046,0.306641,0.0,...,24.999813,0.0,74.999438,7.500,7.500,15.000,9.958334,4.958334,50.209200,49.790790,20.336130,78.151245,1.512605,0.0,1.80,0.400,3.600,5.308334,0.750001,85.871255,14.128726,0.0,99.999867,0.0,0.0,0.0,0.0,8.0,4.650001,4.208334,9.498206,90.501773,23.960390,74.257408,1.782178,0.0,2.1,0.00,0.200,8.775001,3.875001,55.840449,44.159539,0.0,99.999974,0.000000,0.0,0.0,0.00,4.600,1.183334,1.083334,8.450697,91.549218,93.076837,0.0,6.923071,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.512605,8.163259,0.000000,0.0,6.923071,74.999438,0.0,0.0,1.782178,21.052587,1.083333,21.848735,0.133333,10.884345,4.208333,84.873932,0.475000,38.775479,0.0,0.0,0.0,0.0,3.091668,2.483334,0.608333,16.366540,31.046022,10.168065,84.993952,0.756302,4.081629,4.837932,1.7,12.4000
1,1.0,3.0,1910753.0,84.0,29.32,1.0,0.0,0.0,0.0,3.0,10.0,1.0,1.0,1.0,6.0,12.0,NaN,3.5,85.380047,7.912157,84.109375,80.0625,89.125,6.016096,4.662004,96.417011,2.553721,96.796875,95.28125,98.015625,1.952044,1.192901,94.519642,1.174693,94.78125,94.15625,95.203125,0.809533,0.632244,96.484253,2.363064,96.796875,95.3750,98.0625,1.860322,1.112769,94.558687,1.076383,94.78125,94.250,95.21875,0.753813,0.595585,128.646832,14.241632,127.625,118.875,136.9375,63.390808,9.105971,61.5,58.625,65.4375,85.142813,8.993769,84.708332,80.458334,90.729167,-2.074447,0.824376,-2.059786,-2.655428,-1.493903,0.338556,0.679005,0.129319,0.02528,0.269821,244632.131836,3.027992,7.964289,0.814228,0.103943,1.817041,2.113921e+06,0.472917,0.733333,0.064706,0.152804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5,0.583333,0.25,0.75,16.367270,25.954703,16.367270,25.954703,16.367270,25.954703,2.632331,0.84507,NaN,26.150661,26.150661,26.150661,0.993789,284.05,1.325,0.0,0.0,284.05,1.325,743.9,1.175,NaN,1.1,1.1,1.1,1.05,1.712099,1.500581,3.212680,0.006551,2.535209,2.535209,5.070418,0.000000,2.236023,3.726705,5.962728,0.000000,0.000010,0.045593,0.266724,0.006246,0.190369,0.190369,0.0,...,0.000000,0.0,49.999312,0.875,0.875,0.875,8.291668,4.135418,41.415013,58.584963,1.746291,68.565443,29.688225,0.0,7.45,2.425,8.275,3.979168,0.295834,95.749128,4.250802,0.0,99.997127,0.0,0.0,0.0,0.0,30.8,4.312501,3.839584,8.455667,91.544293,1.766113,67.616838,30.617006,0.0,7.4,0.75,1.125,6.712501,2.637501,49.931282,50.068686,0.0,99.141002,0.858936,0.0,0.5,0.35,11.025,1.579168,1.497918,15.389736,84.610039,3.165114,0.0,96.834592,0.0,2.0,2.0,2.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.688225,11.989597,0.858936,0.0,96.834592,49.999312,0.0,0.0,30.617006,15.108004,1.497917,30.838865,0.081250,11.989597,3.839583,94.398834,0.510417,57.838618,0.0,0.0,0.0,0.0,2.470834,1.681251,0.789583,21.414231,32.116987,0.873146,78.287404,14.844112,5.994798,20.838911,5.0,31.1125

In [33]:
# RUN WITH AIRGOSLEEP, PYTHON 3.6

#### select version:

alpha_normal = 0.05
alpha_diff = 0.05
modality = 'mean'
icu_data = 'subjects'

if modality == 'mean':
    variables_sel = variables_mean
elif modality == 'amendsumeffort':
    variables_sel = variables_breathing
elif modality == 'ecg_nn':
    variables_sel = variables_hrv
else:
    raise ValueError('Wrong modality name')
    
if icu_data == 'segments':
    icu_data_sel = summary_dn_icu_sel
if icu_data == 'subjects':
    icu_data_sel = summary_dn_icu_sel_subject
    
if do_agreement_for_sleeplab:
    summary_days_sleeplab = summary_days_sleeplab_full.loc[np.any([summary_days_sleeplab_full[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                           summary_days_sleeplab_full[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                           axis=0), :].copy()

else:
    summary_days_sleeplab = summary_days_sleeplab_full.copy()
    

for i_var in range(len(variables_mean)):
    
    var_tmp = variables_sel[i_var]
    name_tmp = x_labels_short[i_var]
    
    icu_values = icu_data_sel[var_tmp]
    sl_all_values = summary_days_sleeplab.loc[summary_days_sleeplab['matched_all'] == 1, var_tmp]
    sl_ahi_0_5_values = summary_days_sleeplab.loc[summary_days_sleeplab['matched_ahi_0_5'] == 1, var_tmp]
    sl_ahi_15_100_values = summary_days_sleeplab.loc[summary_days_sleeplab['matched_ahi_15_100'] == 1, var_tmp]

    cohorts_values = [icu_values, sl_all_values, sl_ahi_0_5_values, sl_ahi_15_100_values]
    
    for cohort_values, cohort_name in zip(cohorts_values, cohorts_names):
        
        # get mean, std, median, iqr:
        df_results.loc[name_tmp, (cohort_name, 'N Subjects')] = cohort_values.shape[0]
        df_results.loc[name_tmp, (cohort_name, 'Mean')] = cohort_values.mean().round(1)
        df_results.loc[name_tmp, (cohort_name, 'Std')] = cohort_values.std().round(1)
        df_results.loc[name_tmp, (cohort_name, 'Median')] = cohort_values.median().round(1)
        df_results.loc[name_tmp, (cohort_name, 'Iqr')] = (cohort_values.quantile(0.75) - cohort_values.quantile(0.25)).round(1)
        # normality checks:
        p_dag = normaltest(cohort_values)[1]
        p_sha = shapiro(cohort_values)[1]
        gaussian = np.any([p_dag > alpha_normal, p_sha > alpha_normal])
        df_results.loc[name_tmp, (cohort_name, 'p_dag')] = p_dag.round(4)
        df_results.loc[name_tmp, (cohort_name, 'p_sha')] = np.round(p_sha, 4)
        df_results.loc[name_tmp, (cohort_name, 'gaussian')] = gaussian
    
        if cohort_name == 'ICU':
            gaussian_icu = gaussian
            continue
            
        # test p-values:
        if 1: #False: # gaussian & gaussian_icu:
#             print(name_tmp)
#             print('gaussian')
            df_results.loc[name_tmp, (cohort_name, 'p_tt')] = ttest_ind(icu_values, cohort_values)[1].round(4)
            df_results.loc[name_tmp, (cohort_name, 's_tt')] = ttest_ind(icu_values, cohort_values)[0].round(1)
            significance_1 = ttest_ind(icu_values, cohort_values)[1] <= 0.01
            significance_5 = ttest_ind(icu_values, cohort_values)[1] <= 0.05
            
            if significance_1:
                df_results.loc[name_tmp, (cohort_name, 'Mean')] = '** ' + str(cohort_values.mean().round(1))
            elif significance_5:
                df_results.loc[name_tmp, (cohort_name, 'Mean')] = '* ' + str(cohort_values.mean().round(1))
    
        if 1:
#             try:
            df_results.loc[name_tmp, (cohort_name, 'p_medians')] = median_test(icu_values, cohort_values)[1].round(4)
            df_results.loc[name_tmp, (cohort_name, 's_medians')] = median_test(icu_values, cohort_values)[0].round(1)
#             except:
#             df_results.loc[name_tmp, (cohort_name, 'p_medians')] = 'NA'
#             df_results.loc[name_tmp, (cohort_name, 's_medians')] = 'NA'             
#             df_results.loc[name_tmp, (cohort_name, 'sig_medians')] = median_test(icu_values, cohort_values)[1] <= alpha_diff
#             try:
            df_results.loc[name_tmp, (cohort_name, 'p_mwu')] = mannwhitneyu(icu_values, cohort_values)[1].round(4)
            df_results.loc[name_tmp, (cohort_name, 's_mwu')] = mannwhitneyu(icu_values, cohort_values)[0].round(1)
#             except:
#             df_results.loc[name_tmp, (cohort_name, 'p_mwu')] = 'NA'
#             df_results.loc[name_tmp, (cohort_name, 's_mwu')] = 'NA'  
#             df_results.loc[name_tmp, (cohort_name, 'sig_mwu')] = mannwhitneyu(icu_values, cohort_values)[1] <= alpha_diff

#             try:
            significance_1 = (median_test(icu_values, cohort_values)[1] <= 0.01) & (mannwhitneyu(icu_values, cohort_values)[1] <= 0.01)
            significance_5 = (median_test(icu_values, cohort_values)[1] <= 0.05) & (mannwhitneyu(icu_values, cohort_values)[1] <= 0.05)

            if significance_1:
#                 df_results.loc[name_tmp, (cohort_name, 'Mean')] = '** ' + str(cohort_values.mean().round(1))
                df_results.loc[name_tmp, (cohort_name, 'Median')] = '** ' + str(cohort_values.median().round(1))
            elif significance_5:
#                 df_results.loc[name_tmp, (cohort_name, 'Mean')] = '* ' + str(cohort_values.mean().round(1))
                df_results.loc[name_tmp, (cohort_name, 'Median')] = '* ' + str(cohort_values.median().round(1))
#             except:
#                 continue

df_results.dropna(axis=1, how='all', inplace=True)
df_results.transpose().to_csv(f'results_sleep_stage_analysis_{str(min_hours_sleep_icu)}_inclusion_{inclusion_agreement}_sleepstatistics_{agreement}_sleeplabagree_{do_agreement_for_sleeplab}_forcedisc{force_concordant_discordant_sleep}.csv')

In [34]:
np.round(0.0001, 4)

0.0001

In [35]:
df_results.transpose().iloc[:10]

,TS,CS,DS,DS%,S,R,N1,N2,N3,N2+N3,SFI,WT
"(ICU, N Subjects)",102,102,102,102,102,102,102,102,102,102,102,102
"(Sleeplab All, N Subjects)",220,220,220,220,220,220,220,220,220,220,220,220
"(Sleeplab AHI 0-5, N Subjects)",77,77,77,77,77,77,77,77,77,77,77,77
"(Sleeplab AHI 15-100, N Subjects)",52,52,52,52,52,52,52,52,52,52,52,52
"(ICU, Mean)",6.2,2.5,3.6,49.5,50.4,23.4,32.5,18,20,38,3.2,7
"(ICU, Median)",6,2.3,3.4,48.2,51,17.4,29.2,17.5,15.2,35.2,2.8,5.3
"(Sleeplab All, Mean)",** 4.9,** 3.7,** 1.2,** 23.6,** 73.9,** 14.4,30.7,** 38.6,** 15.5,** 54.1,3.5,** 4.7
"(Sleeplab All, Median)",5.2,** 3.9,** 1.0,** 20.6,** 79.9,13.8,24.1,** 40.4,12.8,** 55.8,3.3,** 3.1
"(Sleeplab AHI 0-5, Mean)",** 5.0,** 3.8,** 1.2,** 23.7,** 77.1,* 16.7,** 24.2,** 42.1,15.6,** 57.8,3.4,** 3.2
"(Sleeplab AHI 0-5, Median)",5.4,** 4.1,** 1.0,** 20.6,** 82.3,16.7,** 20.1,** 44.5,13.8,** 60.7,3.1,** 2.6

In [36]:
print(f'# nights: {summary_dn_icu_sel.shape[0]}')
print(f'# subjects: {summary_dn_icu_sel.study_id.unique().shape[0]}')

# nights: 274
# subjects: 102

In [37]:
sl_all_values = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_all'] == 1, var_tmp]
sl_ahi_0_5_values = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_ahi_0_5'] == 1, var_tmp]
sl_ahi_15_100_values = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_ahi_15_100'] == 1, var_tmp]

In [38]:
print(f"# nights: {summary_days_sleeplab_full[summary_days_sleeplab_full['matched_all'] == 1].shape[0]}")
print(f"# subjects: {summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_all'] == 1, 'study_id'].unique().shape[0]}")

# nights: 220
# subjects: 220

In [39]:
print(f"# nights: {summary_days_sleeplab_full[summary_days_sleeplab_full['matched_ahi_0_5'] == 1].shape[0]}")
print(f"# subjects: {summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_ahi_0_5'] == 1, 'study_id'].unique().shape[0]}")

# nights: 77
# subjects: 77

In [40]:
print(f"# nights: {summary_days_sleeplab_full[summary_days_sleeplab_full['matched_ahi_15_100'] == 1].shape[0]}")
print(f"# subjects: {summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_ahi_15_100'] == 1, 'study_id'].unique().shape[0]}")

# nights: 52
# subjects: 52

In [41]:
df_results

,"(ICU, N Subjects)","(Sleeplab All, N Subjects)","(Sleeplab AHI 0-5, N Subjects)","(Sleeplab AHI 15-100, N Subjects)","(ICU, Mean)","(ICU, Median)","(Sleeplab All, Mean)","(Sleeplab All, Median)","(Sleeplab AHI 0-5, Mean)","(Sleeplab AHI 0-5, Median)","(Sleeplab AHI 15-100, Mean)","(Sleeplab AHI 15-100, Median)","(ICU, Std)","(ICU, Iqr)","(ICU, p_dag)","(ICU, p_sha)","(ICU, gaussian)","(Sleeplab All, p_tt)","(Sleeplab All, s_tt)","(Sleeplab All, p_medians)","(Sleeplab All, s_medians)","(Sleeplab All, p_mwu)","(Sleeplab All, s_mwu)","(Sleeplab All, Std)","(Sleeplab All, Iqr)","(Sleeplab All, p_dag)","(Sleeplab All, p_sha)","(Sleeplab All, gaussian)","(Sleeplab AHI 0-5, p_tt)","(Sleeplab AHI 0-5, s_tt)","(Sleeplab AHI 0-5, p_medians)","(Sleeplab AHI 0-5, s_medians)","(Sleeplab AHI 0-5, p_mwu)","(Sleeplab AHI 0-5, s_mwu)","(Sleeplab AHI 0-5, Std)","(Sleeplab AHI 0-5, Iqr)","(Sleeplab AHI 0-5, p_dag)","(Sleeplab AHI 0-5, p_sha)","(Sleeplab AHI 0-5, gaussian)","(Sleeplab AHI 15-100, p_tt)","(Sleeplab AHI 15-100, s_tt)","(Sleeplab AHI 15-100, p_medians)","(Sleeplab AHI 15-100, s_medians)","(Sleeplab AHI 15-100, p_mwu)","(Sleeplab AHI 15-100, s_mwu)","(Sleeplab AHI 15-100, Std)","(Sleeplab AHI 15-100, Iqr)","(Sleeplab AHI 15-100, p_dag)","(Sleeplab AHI 15-100, p_sha)","(Sleeplab AHI 15-100, gaussian)"
TS,102,220,77,52,6.2,6,** 4.9,5.2,** 5.0,5.4,** 4.9,5.2,3.1,5.2,0.0322,0.0525,True,0,4.9,0.281,1.2,0.0005,8647,1.6,2.3,0.0006,0,False,0.0031,3,0.5899,0.3,0.011,3140,1.6,2,0.0533,0.0086,True,0.0073,2.7,0.3942,0.7,0.0198,2113,1.4,1.6,0.1139,0.034,True
CS,102,220,77,52,2.5,2.3,** 3.7,** 3.9,** 3.8,** 4.1,** 3.7,** 3.9,1.7,2.3,0.0185,0.0017,False,0,-5.8,0,29.1,0,6883.5,1.7,2.6,0,0.0008,False,0,-5,0,21.1,0,2220.5,1.6,2.2,0.3946,0.2383,True,0.0001,-3.9,0.0012,10.5,0.0001,1635,1.5,2.1,0.2976,0.2246,True
DS,102,220,77,52,3.6,3.4,** 1.2,** 1.0,** 1.2,** 1.0,** 1.3,** 1.2,2.4,3.4,0.0363,0.0005,False,0,14,0,57,0,3670,0.8,0.9,0,0,False,0,8.8,0,51.6,0,1323,0.7,0.9,0.0091,0.0001,False,0,7,0,35.6,0,982,0.8,0.8,0.0001,0.0011,False
DS%,102,220,77,52,49.5,48.2,** 23.6,** 20.6,** 23.7,** 20.6,** 25.3,** 23.2,20.4,30,0.4277,0.5801,True,0,12.9,0,76.5,0,3302,14.9,17.1,0,0,False,0,9.5,0,51.6,0,1141,14.3,15.1,0.0002,0.0001,False,0,7.6,0,35.6,0,887,14.8,15.5,0.0114,0.0072,False
S,102,220,77,52,50.4,51,** 73.9,** 79.9,** 77.1,** 82.3,** 71.0,** 76.0,19.7,31.8,0.2723,0.1666,True,0,-10.1,0,72.3,0,4391,19.3,27.9,0,0,False,0,-9.4,0,41,0,1236,17.5,23.1,0.0002,0,False,0,-6.3,0,18.1,0,1136,18.5,25.1,0.0358,0.0033,False
R,102,220,77,52,23.4,17.4,** 14.4,13.8,* 16.7,16.7,** 12.3,10.6,20.6,32.3,0.0043,0,False,0,5.2,0.5492,0.4,0.0015,8913,10.3,15.6,0.0169,0,False,0.0101,2.6,0.9482,0,0.0961,3479,10.5,15,0.2759,0.1244,True,0.0003,3.7,0.1251,2.4,0.0014,1869,9.8,17.1,0.0299,0.0034,False
N1,102,220,77,52,32.5,29.2,30.7,24.1,** 24.2,** 20.1,* 41.8,40.1,22.1,31.1,0.0216,0.0008,False,0.483,0.7,0.0724,3.2,0.2619,10724,19.9,22.8,0,0,False,0.0064,2.8,0.0011,10.6,0.0048,3037,16.3,12.5,0,0,False,0.0122,-2.5,0.0609,3.5,0.0033,1940,20.6,37.6,0.075,0.029,True
N2,102,220,77,52,18,17.5,** 38.6,** 40.4,** 42.1,** 44.5,** 33.6,** 32.7,12.7,14.8,0,0,False,0,-12.4,0,98.9,0,3132,14.4,20.7,0.0916,0.0246,True,0,-12.5,0,77.8,0,773,12.9,16.5,0.0234,0.0142,False,0,-6.9,0,27.9,0,1018,14.5,19.5,0.8121,0.8231,True
N3,102,220,77,52,20,15.2,** 15.5,12.8,15.6,13.8,** 12.3,10,17,25.4,0.0051,0,False,0.0094,2.6,0.5492,0.4,0.0335,9796,13.2,16.4,0,0,False,0.051,2,0.5899,0.3,0.1485,3568.5,11.6,12.9,0,0,False,0.0032,3,0.0609,3.5,0.0062,1997,11,11.9,0.0004,0.0001,False
N2+N3,102,220,77,52,38,35.2,** 54.1,** 55.8,** 57.8,** 60.7,* 45.9,* 46.1,20.3,30.8,0.0521,0.013,True,0,-7,0,34.5,0,6195,18.7,25.2,0.0066,0.0002,False,0,-6.8,0,41,0,1837,18,17.6,0.0053,0.0013,False,0.0191,-2.4,0.0106,6.5,0.005,1977,17.7,24.3,0.2887,0.1343,True
SFI,102,220,77,52,3.2,2.8,3.5,3.3,3.4,3.1,* 3.9,* 3.7,2.1,2.1,0,0,False,0.0738,-1.8,0.1194,2.4,0.0012,8857,1.4,1.7,0,0.0001,False,0.42,-0.8,0.4244,0.6,0.0225,3238.5,1.2,1.5,0.4098,0.1084,True,0.0243,-2.3,0.0466,4,0.0005,1795,1.6,1.8,0.0122,0.015,False
WT,102,220,77,52,7,5.3,** 4.7,** 3.1,** 3.2,** 2.6,7.3,4,6.7,5.4,0,0,False,0.0027,3,0.0007,11.5,0,7831.5,6.5,3.1,0,0,False,0,4.7,0,17.3,0,2140,2.4,2,0,0,False,0.85,-0.2,0.0609,3.5,0.0872,2296,11.8,2.9,0,0,False

In [42]:
summary_dn_icu_sel[f'hours_sleep_{modality}_{agreement}'].mean()

6.6583799537712895

### summary sleep indices figure

In [43]:
variables_mean

['hours_sleep_mean_all',
 'hours_sleep_mean_agreement_relaxed',
 'hours_discordant_mean_agreement_relaxed',
 'perc_discordant_mean_agreement_relaxed',
 'perc_S_mean_all',
 'perc_R_mean_all',
 'perc_N1_mean_all',
 'perc_N2_mean_all',
 'perc_N3_mean_all',
 'perc_N2N3_mean_all',
 'sfi_mean_all',
 'arousali_mean_all']

In [44]:
def adjacent_values(vals, q1, q3):
    upper_adjacent_value = q3 + (q3 - q1) * 1.5
    upper_adjacent_value = np.clip(upper_adjacent_value, q3, np.max(vals))

    lower_adjacent_value = q1 - (q3 - q1) * 1.5
    lower_adjacent_value = np.clip(lower_adjacent_value, np.min(vals), q1)
    return lower_adjacent_value, upper_adjacent_value


def set_axis_style(ax, labels):
    ax.get_xaxis().set_tick_params(direction='out')
    ax.xaxis.set_ticks_position('bottom')
    ax.set_xticks(np.arange(1, len(labels) + 1))
    ax.set_xticklabels(labels)
    ax.set_xlim(0.25, len(labels) + 0.75)
    ax.set_xlabel('Sample name')

In [45]:
plots_savedir = '/scr/wolfgang/Dropbox (Partners HealthCare)/SleepInICUandSleeplabPaper/Plots/summary_sleep_stage'

variables_plot = [ 'perc_R_mean_all',
 'perc_N1_mean_all',
 'perc_N2_mean_all',
 'perc_N3_mean_all',
 'perc_N2N3_mean_all',
 'arousali_mean_all',
'perc_discordant_mean_agreement_relaxed',
]



variables_plot = [ f'perc_R_mean_{agreement}',
 f'perc_N1_mean_{agreement}',
 f'perc_N2_mean_{agreement}',
 f'perc_N3_mean_{agreement}',
 f'perc_N2N3_mean_{agreement}',
 f'arousali_mean_{agreement}',
 f'perc_discordant_mean_agreement_relaxed',
]




# labels = ['Total Sleep (h)', 'Concordant S. (h)', 'Discordant S. (h)',  'Sleep (%)', 'Stage R (%)', 'Stage N1 (%)', 'Stage N2 (%)', 'Stage N3 (%)', 'SFI', 'Wake Trans./h']
labels = ['', 'Stage R', 'Stage N1', 'Stage N2', 'Stage N3', 'Stage N2+N3', 'Wake Transition\n per Hour of Sleep', 'Discordance\nProportion']



print(f'Adjust subplot number to number of variables: {len(variables_plot)}')

plt.close('all')

colors4 = [(0, 0.4, 1), 'darkorange', 'green', 'crimson']

fig, ax = plt.subplots(2, 4, figsize=(7.3, 4))
ax = ax.flatten()
i_axis = -1

#### select version:

alpha_normal = 0.05
alpha_diff = 0.05
modality = 'mean'
icu_data = 'subjects'

if icu_data == 'segments':
    icu_data_sel = summary_dn_icu_sel
if icu_data == 'subjects':
    icu_data_sel = summary_dn_icu_sel_subject
    
if do_agreement_for_sleeplab:
    summary_days_sleeplab = summary_days_sleeplab_full.loc[np.any([summary_days_sleeplab_full[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                           summary_days_sleeplab_full[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                           axis=0), :].copy()

else:
    summary_days_sleeplab = summary_days_sleeplab_full.copy()
    

        
# LEGEND subplot
i_axis = 0
random = np.random.randn(100, )
data_4_groups = [random]*4
positions = [0.25, 1, 1.5, 2]
parts = ax[i_axis].violinplot(data_4_groups, positions = positions, showmedians=False, showmeans=False, showextrema=False)
quartile25 = [np.percentile(x, 25) for x in data_4_groups]
medians = [np.percentile(x, 50) for x in data_4_groups]
quartile75 = [np.percentile(x, 75) for x in data_4_groups]
quartile99 = [np.percentile(x, 99) for x in data_4_groups]
quartile01 = [np.percentile(x, 1) for x in data_4_groups]
maximums = np.array([np.max(x) for x in data_4_groups])
for i_pc, pc in enumerate(parts['bodies']):
    pc.set_facecolor(colors4[i_pc])
    pc.set_edgecolor('black')
    pc.set_alpha(1)

whiskers = np.array([
    adjacent_values(sorted_array, q1, q3)
    for sorted_array, q1, q3 in zip(data_4_groups, quartile25, quartile75)])
whiskers_min, whiskers_max = whiskers[:, 0], whiskers[:, 1]
ax[i_axis].scatter(positions, medians, marker='o', color='white', s=7, zorder=3)
ax[i_axis].vlines(positions, quartile25, quartile75, color='k', linestyle='-', lw=6)
ax[i_axis].vlines(positions, whiskers_min, whiskers_max, color='k', linestyle='-', lw=2)
ax[i_axis].spines['right'].set_visible(False)
ax[i_axis].spines['top'].set_visible(False)
ax[i_axis].spines['bottom'].set_visible(False)
ax[i_axis].set_xticks(positions)
ax[i_axis].tick_params(axis='x', length=0)
ax[i_axis].set_ylim([-12, 3])
ax[i_axis].set_ylim([-12, 3])
ax[i_axis].set_yticklabels([])
ax[i_axis].set_xticklabels([])
ax[i_axis].tick_params(length=0)
ax[i_axis].axis('off')
ax[i_axis].set_title('Legend', fontstyle='italic')

ax[i_axis].text(positions[0], -6, 'ICU', ha='center', rotation=0, fontsize=9.5)
ax[i_axis].text(positions[2], -9.5, 'Sleeplab', ha='center', rotation=0, fontsize=9.5)
ax[i_axis].text(positions[1], -7.5, 'All', ha='center', va='bottom', rotation=90)
ax[i_axis].text(positions[2], -7.5, 'AHI<5', ha='center', va='bottom', rotation=90)
ax[i_axis].text(positions[3], -7.5, 'AHI>15', ha='center', va='bottom', rotation=90)
ax[i_axis].text(1.65, -11.7, '   * p-val. < 0.05  ', ha='right', va='bottom', rotation=0)
ax[i_axis].text(1.65, -13.2, ' ** p-val. < 0.01  ', ha='right', va='bottom', rotation=0)
ax[i_axis].text(1.65, -14.7, '*** p-val. < 0.001', ha='right', va='bottom', rotation=0)


for i_var in range(len(variables_plot)):
    ###### COMPUTATION
    
    significance_symbols_groups = []
    
    var_tmp = variables_plot[i_var]
#     name_tmp = x_labels_short[i_var]
    
    icu_values = icu_data_sel[var_tmp]
    sl_all_values = summary_days_sleeplab.loc[summary_days_sleeplab['matched_all'] == 1, var_tmp]
    sl_ahi_0_5_values = summary_days_sleeplab.loc[summary_days_sleeplab['matched_ahi_0_5'] == 1, var_tmp]
    sl_ahi_15_100_values = summary_days_sleeplab.loc[summary_days_sleeplab['matched_ahi_15_100'] == 1, var_tmp]

    cohorts_values = [icu_values, sl_all_values, sl_ahi_0_5_values, sl_ahi_15_100_values]
    
    for cohort_values, cohort_name in zip(cohorts_values, cohorts_names):

        # get mean, std, median, iqr:
        df_results.loc[name_tmp, (cohort_name, 'N Subjects')] = cohort_values.shape[0]
        df_results.loc[name_tmp, (cohort_name, 'Mean')] = cohort_values.mean().round(1)
        df_results.loc[name_tmp, (cohort_name, 'Std')] = cohort_values.std().round(1)
        df_results.loc[name_tmp, (cohort_name, 'Median')] = cohort_values.median().round(1)
        df_results.loc[name_tmp, (cohort_name, 'Iqr')] = (cohort_values.quantile(0.75) - cohort_values.quantile(0.25)).round(1)

        p_medians = median_test(icu_values, cohort_values)[1].round(4)
        s_medians = median_test(icu_values, cohort_values)[0].round(1)
             
        p_mwu = mannwhitneyu(icu_values, cohort_values)[1].round(4)
        s_mwu = mannwhitneyu(icu_values, cohort_values)[0].round(1)

        significance_01 = (median_test(icu_values, cohort_values)[1] <= 0.001) & (mannwhitneyu(icu_values, cohort_values)[1] <= 0.001)
        significance_1 = (median_test(icu_values, cohort_values)[1] <= 0.01) & (mannwhitneyu(icu_values, cohort_values)[1] <= 0.01)
        significance_5 = (median_test(icu_values, cohort_values)[1] <= 0.05) & (mannwhitneyu(icu_values, cohort_values)[1] <= 0.05)

        if significance_01:
            significance_symbol = '***'
        elif significance_1:
            significance_symbol = '**'
        elif significance_5:
            significance_symbol = '*'
        else:
            significance_symbol = ''
            
        significance_symbols_groups.append(significance_symbol)
        
        
    ###### PLOT

    i_axis += 1

    data_4_groups = [icu_values.values, sl_all_values.values, sl_ahi_0_5_values.values, sl_ahi_15_100_values.values]

    positions = [0.25, 1, 1.5, 2]
    parts = ax[i_axis].violinplot(data_4_groups, positions = positions, showmedians=False, showmeans=False, showextrema=False)

    quartile25 = [np.percentile(x, 25) for x in data_4_groups]
    medians = [np.percentile(x, 50) for x in data_4_groups]
    quartile75 = [np.percentile(x, 75) for x in data_4_groups]
    quartile99 = [np.percentile(x, 99) for x in data_4_groups]
    quartile01 = [np.percentile(x, 1) for x in data_4_groups]
    maximums = np.array([np.max(x) for x in data_4_groups])

    for i_pc, pc in enumerate(parts['bodies']):
        pc.set_facecolor(colors4[i_pc])
        pc.set_edgecolor('black')
        pc.set_alpha(1)
        ax_position = [0.15, 0.45, 0.65, 0.85]

        y_significance_text = maximums[i_pc] * 1.02

        if i_axis == 1:
            print('manual ylim')
            ylim_max = 65
            ax[i_axis].set_ylim([0, ylim_max])
            y_significance_text = np.min([y_significance_text, ylim_max - 2])
        elif i_axis == 6:
            print('manual ylim')
            ylim_max = 30
            ax[i_axis].set_ylim([0, ylim_max])
            y_significance_text = np.min([y_significance_text, ylim_max - 1])

        if i_axis == 6:
            dec = 1
            ax[i_axis].text(positions[i_pc], y_significance_text, significance_symbols_groups[i_pc], fontsize=10, ha='center');
            ax[i_axis].text(ax_position[i_pc], -0.16, f'{np.round(medians[i_pc], dec)}\n({np.round(quartile75[i_pc] - quartile25[i_pc], dec)})', 
                            fontsize=7, ha='center', transform=ax[i_axis].transAxes);
        else:
            ax[i_axis].text(positions[i_pc], y_significance_text, significance_symbols_groups[i_pc], fontsize=10, ha='center');
            ax[i_axis].text(ax_position[i_pc], -0.16, f'{int(medians[i_pc])}\n({int(quartile75[i_pc] - quartile25[i_pc])})', 
                            fontsize=7, ha='center', transform=ax[i_axis].transAxes);

    whiskers = np.array([
        adjacent_values(sorted_array, q1, q3)
        for sorted_array, q1, q3 in zip(data_4_groups, quartile25, quartile75)])
    whiskers_min, whiskers_max = whiskers[:, 0], whiskers[:, 1]

    ax[i_axis].scatter(positions, medians, marker='o', color='white', s=7, zorder=3)
    ax[i_axis].vlines(positions, quartile25, quartile75, color='k', linestyle='-', lw=5)
    ax[i_axis].vlines(positions, whiskers_min, whiskers_max, color='k', linestyle='-', lw=2)

    ax[i_axis].spines['right'].set_visible(False)
    ax[i_axis].spines['top'].set_visible(False)
    ax[i_axis].spines['bottom'].set_visible(False)
    ax[i_axis].set_xticks(positions)
    ax[i_axis].tick_params(axis='x', length=0)
    # ax[i_axis].set_ylim(np.min(quartile01)*0.9, np.max(quartile99)*1.1)

#     ax[i_axis].set_xticklabels(['ICU', 'Sleeplab All', 'AHI<5', 'AHI>15'])
    ax[i_axis].set_xticklabels([]*4)

    ax[i_axis].set_title(labels[i_axis])


    
    if i_axis == 3:
        ax[i_axis].set_yticks([0, 25, 50, 75])
        
    if i_axis in [1, 2, 3, 4, 5]:
        ax[i_axis].set_ylabel('%', labelpad=-5)
    if i_axis in [7]:
        ax[i_axis].set_ylabel('     %', labelpad=-5)

ax[0].text(0, 0.975, 'A', fontweight='bold', transform=fig.transFigure, fontsize=10)

# ax[i_axis].text(positions[i_pc], -5, ['ICU', 'Sleeplab All', 'AHI<5', 'AHI>15'][i_pc], ha='center', rotation=45)
plt.subplots_adjust(left=0.04, right=1, bottom=0.07, top=0.94, wspace=0.3, hspace=0.5)

plt.savefig(os.path.join(plots_savedir, f'results_sleep_stage_analysis_{str(min_hours_sleep_icu)}_inclusion_{inclusion_agreement}_sleepstatistics_{agreement}_sleeplabagree_{do_agreement_for_sleeplab}_forcedisc{force_concordant_discordant_sleep}.tiff'), dpi=600)
plt.savefig(os.path.join(plots_savedir, f'results_sleep_stage_analysis_{str(min_hours_sleep_icu)}_inclusion_{inclusion_agreement}_sleepstatistics_{agreement}_sleeplabagree_{do_agreement_for_sleeplab}_forcedisc{force_concordant_discordant_sleep}.svg'))
plt.savefig(os.path.join(plots_savedir, f'results_sleep_stage_analysis_{str(min_hours_sleep_icu)}_inclusion_{inclusion_agreement}_sleepstatistics_{agreement}_sleeplabagree_{do_agreement_for_sleeplab}_forcedisc{force_concordant_discordant_sleep}.eps'))
plt.savefig(os.path.join(plots_savedir, f'results_sleep_stage_analysis_{str(min_hours_sleep_icu)}_inclusion_{inclusion_agreement}_sleepstatistics_{agreement}_sleeplabagree_{do_agreement_for_sleeplab}_forcedisc{force_concordant_discordant_sleep}.pdf'))

Adjust subplot number to number of variables: 7

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

manual ylim
manual ylim
manual ylim
manual ylim
manual ylim
manual ylim
manual ylim
manual ylim

In [46]:
plots_savedir

'/scr/wolfgang/Dropbox (Partners HealthCare)/SleepInICUandSleeplabPaper/Plots/summary_sleep_stage'

In [47]:
# sw_hours computed in icu_sleep_breathing_swimmer.ipynb
sw_hours = pd.read_csv('icu_sleep_breathing_sw_hours.csv')
sw_hours_rem_occuring = pd.read_csv('icu_sleep_breathing_sw_hours_rem_occuring.csv')
sleep_periods_1 = pd.read_csv('icu_sleep_breathing_sleep_periods_1.csv')
sleep_periods_5 = pd.read_csv('icu_sleep_breathing_sleep_periods_5.csv')

In [48]:
sw_hours.set_index(['modality', 'study_id'], inplace=True)
sw_hours_rem_occuring.set_index(['modality', 'study_id'], inplace=True)
sleep_periods_1.set_index(['modality', 'study_id'], inplace=True)
sleep_periods_5.set_index(['modality', 'study_id'], inplace=True)

In [49]:
sw_hours.loc['stage_pred_ecg_nn'].head()

,data,sleep,wake,R,night_data,night_sleep,night_wake,day_data,day_sleep,day_wake,day_r,night_r,day_sleep_proportion,night_sleep_proportion,sleep_day_proportion,sleep_night_proportion,day_sleep_per24hours,day_wake_per24hours,night_sleep_per24hours,night_wake_per24hours,day_r_per24hours,night_r_per24hours,sleep_day_proportion_adjusted24hours,sleep_night_proportion_adjusted24hours
study_id,,,,,,,,,,,,,,,,,,,,,,,,
35,4601,1376,3225,0,2396,1078,1318,2205,298,1907,0,0,13.51,44.99,21.66,78.34,0.027029,0.172971,0.089983,0.110017,0.000000,0.000000,23.10,76.90
50,4350,1663,2687,22,2387,1320,1067,1963,343,1620,2,20,17.47,55.30,20.63,79.37,0.034947,0.165053,0.110599,0.089401,0.000204,0.001676,24.01,75.99
1,7506,1297,6209,144,3840,923,2917,3666,374,3292,55,89,10.20,24.04,28.84,71.16,0.020404,0.179596,0.048073,0.151927,0.003001,0.004635,29.80,70.20
15,13249,1293,11956,0,6577,973,5604,6672,320,6352,0,0,4.80,14.79,24.75,75.25,0.009592,0.190408,0.029588,0.170412,0.000000,0.000000,24.48,75.52
123,4130,903,3227,31,2106,835,1271,2024,68,1956,0,31,3.36,39.65,7.53,92.47,0.006719,0.193281,0.079297,0.120703,0.000000,0.002944,7.81,92.19

In [50]:
# we could use mean, however we have much more data with ecg, hence let's use ecg.
(sw_hours.loc['stage_pred_amendsumeffort'] + sw_hours.loc['stage_pred_ecg_nn']) / 2;

In [51]:
stage_col = 'stage_pred_ecg_nn'

print(f"Day sleep proportion:                     {sw_hours.loc[stage_col, 'day_sleep_proportion'].mean().round(2)} ({sw_hours.loc[stage_col, 'day_sleep_proportion'].std().round(2)})")
print(f"Night sleep proportion:                   {sw_hours.loc[stage_col, 'night_sleep_proportion'].mean().round(2)} ({sw_hours.loc[stage_col, 'night_sleep_proportion'].std().round(2)})")
print(f"Sleep day proportion:                     {sw_hours.loc[stage_col, 'sleep_day_proportion'].mean().round(2)} ({sw_hours.loc[stage_col, 'sleep_day_proportion'].std().round(2)})")
print(f"Sleep night proportion:                   {sw_hours.loc[stage_col, 'sleep_night_proportion'].mean().round(2)} ({sw_hours.loc[stage_col, 'sleep_night_proportion'].std().round(2)})")
print(f"Sleep day proportion - 24hour adjusted:   {sw_hours.loc[stage_col, 'sleep_day_proportion_adjusted24hours'].mean().round(2)} ({sw_hours.loc[stage_col, 'sleep_day_proportion_adjusted24hours'].std().round(2)})")
print(f"Sleep night proportion - 24hour adjusted: {sw_hours.loc[stage_col, 'sleep_night_proportion_adjusted24hours'].mean().round(2)} ({sw_hours.loc[stage_col, 'sleep_night_proportion_adjusted24hours'].std().round(2)})")
print(f"REM day proportion:                       {sw_hours_rem_occuring.loc[stage_col, 'rem_day_proportion'].mean().round(2)} ({sw_hours_rem_occuring.loc[stage_col, 'rem_day_proportion'].std().round(2)})")
print(f"REM night proportion:                     {sw_hours_rem_occuring.loc[stage_col, 'rem_night_proportion'].mean().round(2)} ({sw_hours_rem_occuring.loc[stage_col, 'rem_night_proportion'].std().round(2)})")
print(f"REM day proportion - 24hour adjusted:     {sw_hours_rem_occuring.loc[stage_col, 'rem_day_proportion_adjusted24hours'].mean().round(2)} ({sw_hours_rem_occuring.loc[stage_col, 'rem_day_proportion_adjusted24hours'].std().round(2)})")
print(f"REM night proportion - 24hour adjusted:   {sw_hours_rem_occuring.loc[stage_col, 'rem_night_proportion_adjusted24hours'].mean().round(2)} ({sw_hours_rem_occuring.loc[stage_col, 'rem_night_proportion_adjusted24hours'].std().round(2)})")

day_sleep_proportion = sw_hours.loc[stage_col, 'day_sleep_proportion'].dropna().values
night_sleep_proportion = sw_hours.loc[stage_col, 'night_sleep_proportion'].dropna().values
sleep_day_proportion = sw_hours.loc[stage_col, 'sleep_day_proportion_adjusted24hours'].dropna().values
sleep_night_proportion = sw_hours.loc[stage_col, 'sleep_night_proportion_adjusted24hours'].dropna().values
rem_day_proportion = sw_hours_rem_occuring.loc[stage_col, 'rem_day_proportion_adjusted24hours'].dropna().values
rem_night_proportion = sw_hours_rem_occuring.loc[stage_col, 'rem_night_proportion_adjusted24hours'].dropna().values

Day sleep proportion:                     29.8 (22.92)
Night sleep proportion:                   44.07 (25.38)
Sleep day proportion:                     38.05 (16.67)
Sleep night proportion:                   61.95 (16.67)
Sleep day proportion - 24hour adjusted:   38.61 (16.08)
Sleep night proportion - 24hour adjusted: 61.39 (16.08)
REM day proportion:                       48.04 (29.04)
REM night proportion:                     51.96 (29.04)
REM day proportion - 24hour adjusted:     48.31 (28.78)
REM night proportion - 24hour adjusted:   51.69 (28.78)

In [52]:
print(1)
print(f"Number of sleep periods Mean (SD) : {sleep_periods_1.loc[stage_col, 'num_sleep_periods'].mean().round(2)} ({sleep_periods_1.loc[stage_col, 'num_sleep_periods'].std().round(2)})")
print(f"Number of sleep periods / 24 hour of data Mean (SD) : {(sleep_periods_1.loc[stage_col, 'num_sleep_periods']/sleep_periods_1.loc[stage_col, 'hours_data']*24).mean().round(2)} ({(sleep_periods_1.loc[stage_col, 'num_sleep_periods']/sleep_periods_1.loc[stage_col, 'hours_data']*24).std().round(2)})")
print('5')
print(f"Number of sleep periods Mean (SD) : {sleep_periods_5.loc[stage_col, 'num_sleep_periods'].mean().round(2)} ({sleep_periods_5.loc[stage_col, 'num_sleep_periods'].std().round(2)})")
print(f"Number of sleep periods / 24 hour of data Mean (SD) : {(sleep_periods_5.loc[stage_col, 'num_sleep_periods']/sleep_periods_5.loc[stage_col, 'hours_data']*24).mean().round(2)} ({(sleep_periods_5.loc[stage_col, 'num_sleep_periods']/sleep_periods_5.loc[stage_col, 'hours_data']*24).std().round(2)})")

number_sleep_periods_1 = (sleep_periods_1.loc[stage_col, 'num_sleep_periods']/sleep_periods_1.loc[stage_col, 'hours_data']*24).dropna().values
number_sleep_periods_5 = (sleep_periods_5.loc[stage_col, 'num_sleep_periods']/sleep_periods_5.loc[stage_col, 'hours_data']*24).dropna().values

1
Number of sleep periods Mean (SD) : 82.32 (63.66)
Number of sleep periods / 24 hour of data Mean (SD) : 8.1 (4.71)
5
Number of sleep periods Mean (SD) : 42.77 (31.71)
Number of sleep periods / 24 hour of data Mean (SD) : 4.27 (2.31)

In [53]:
if 0:

    fig, ax = plt.subplots(1, 2, figsize=(7.3, 1.5), gridspec_kw={'width_ratios': [3, 1]})

    group1 = [day_sleep_proportion,
    night_sleep_proportion, 
    sleep_day_proportion,
    sleep_night_proportion, 
    rem_day_proportion,
    rem_night_proportion,
    ]

    labels1 = ['Day Sleep Proportion', 'Night Sleep Proportion', 'Sleep Day Proportion', 'Sleep Night Proportion', 
             'Stage R Day Proportion', 'Stage R Night Proportion']

    group2 = [number_sleep_periods_1,
    number_sleep_periods_5]
    labels2 = ['Number of Sleep\nPeriods >= 1min', 'Number of Sleep\nPeriods >= 5min']

    i_axis = -1

    for data_4_groups, labels in zip([group1, group2], [labels1, labels2]):

        i_axis += 1

        positions = np.arange(0, len(data_4_groups))
        parts = ax[i_axis].violinplot(data_4_groups, positions = positions, showmedians=False, showmeans=False, showextrema=False)

        quartile25 = [np.percentile(x, 25) for x in data_4_groups]
        medians = [np.percentile(x, 50) for x in data_4_groups]
        quartile75 = [np.percentile(x, 75) for x in data_4_groups]
        quartile99 = [np.percentile(x, 99) for x in data_4_groups]
        quartile01 = [np.percentile(x, 1) for x in data_4_groups]
        maximums = np.array([np.max(x) for x in data_4_groups])

        for i_pc, pc in enumerate(parts['bodies']):
            pc.set_facecolor(colors4[0])
            pc.set_edgecolor('black')
            pc.set_alpha(1)

        #     ax_position = [0.15, 0.45, 0.65, 0.85]

        #     if i_axis == 5:
        #         dec = 1
        #         ax.text(positions[i_pc], maximums[i_pc] * 1.02, significance_symbols_groups[i_pc], fontsize=10, ha='center');
        #         ax.text(ax_position[i_pc], -0.16, f'{np.round(medians[i_pc], dec)}\n({np.round(quartile75[i_pc] - quartile25[i_pc], dec)})', 
        #                         fontsize=7, ha='center', transform=ax.transAxes);
        #     else:
        #         ax.text(positions[i_pc], maximums[i_pc] * 1.02, significance_symbols_groups[i_pc], fontsize=10, ha='center');


        whiskers = np.array([
            adjacent_values(sorted_array, q1, q3)
            for sorted_array, q1, q3 in zip(data_4_groups, quartile25, quartile75)])
        whiskers_min, whiskers_max = whiskers[:, 0], whiskers[:, 1]

        ax[i_axis].scatter(positions, medians, marker='o', color='white', s=7, zorder=3)
        ax[i_axis].vlines(positions, quartile25, quartile75, color='k', linestyle='-', lw=5)
        ax[i_axis].vlines(positions, whiskers_min, whiskers_max, color='k', linestyle='-', lw=2)

        ax[i_axis].spines['right'].set_visible(False)
        ax[i_axis].spines['top'].set_visible(False)
        ax[i_axis].spines['bottom'].set_visible(False)
        ax[i_axis].set_xticks(positions)
        ax[i_axis].tick_params(axis='x', length=0)
        # ax.set_ylim(np.min(quartile01)*0.9, np.max(quartile99)*1.1)

        #     ax.set_xticklabels(['ICU', 'Sleeplab All', 'AHI<5', 'AHI>15'])
        ax[i_axis].set_xticklabels([]*4)

        if i_axis == 0:
            ax[0].text(positions[0] - 0.4, 50, labels[0], fontsize=7, ha='left', va='center', rotation=90)
            ax[0].text(positions[1] - 0.4, medians[1], labels[1], fontsize=7, ha='left', va='center', rotation=90)
            ax[0].text(positions[2] - 0.4, medians[2], labels[2], fontsize=7, ha='left', va='center', rotation=90)
            ax[0].text(positions[3] - 0.4, medians[3]-8, labels[3], fontsize=7, ha='left', va='center', rotation=90)
            ax[0].text(positions[4] - 0.4, medians[4], labels[4], fontsize=7, ha='left', va='center', rotation=90)
            ax[0].text(positions[5] - 0.4, medians[5]-3, labels[5], fontsize=7, ha='left', va='center', rotation=90)

            ax_position = [1/12, 3/12, 5/12, 7/12, 9/12, 11/12]
            for i_pc in range(6):
                ax[0].text(ax_position[i_pc], -0.16, f'{int(medians[i_pc])}\n({int(quartile75[i_pc] - quartile25[i_pc])})', 
                                fontsize=7, ha='center', transform=ax[0].transAxes);
        elif i_axis == 1:
            ax[1].text(positions[0] - 0.6, 10, labels[0], fontsize=7, ha='left', va='center', rotation=90)
            ax[1].text(positions[1] - 0.6, 10, labels[1], fontsize=7, ha='left', va='center', rotation=90)
            ax_position = [1/3, 0.78]
            for i_pc in range(2):
                ax[1].text(ax_position[i_pc], -0.16, f'{int(medians[i_pc])}\n({int(quartile75[i_pc] - quartile25[i_pc])})', 
                                fontsize=7, ha='center', transform=ax[1].transAxes);
    ax[0].set_ylabel('%', labelpad=-4)
    ax[1].set_xlim([-0.7, 1.5])
    # ax.set_title(labels)
    ax[0].text(0, 0.93, 'B', fontweight='bold', transform=fig.transFigure, fontsize=10)

    plt.subplots_adjust(left=0.06, right=1, bottom=0.16, top=1, wspace=0.08, hspace=0)

    plt.savefig(os.path.join(plots_savedir, f'results_sleep_stage_analysis_icu_sleep_fragmentation.tiff'), dpi=600)
    plt.savefig(os.path.join(plots_savedir, f'results_sleep_stage_analysis_icu_sleep_fragmentation.pdf'))
    plt.savefig(os.path.join(plots_savedir, f'results_sleep_stage_analysis_icu_sleep_fragmentation.svg'))
    plt.savefig(os.path.join(plots_savedir, f'results_sleep_stage_analysis_icu_sleep_fragmentation.eps'))

In [56]:
#### select version of plot:
ahi_category = 'all'
force_concordant_discordant_sleep = True # if we use 'all' agreement option, do you still want to retrieve concordant/discordant sleep info from relaxed_agreement option. this is True for the paper figures.


for version in range(3):
    
    if version == 0:
        # compare ICU group 2 and sleeplab group 2:
        agreement = 'all'
        min_hours_sleep_icu = 0.01
        inclusion_agreement = 'all'
        do_agreement_for_sleeplab = False

    elif version == 1:
        # ### compare ICU group 3 and sleeplab group 3, compute sleep statistics on ALL sleep:
        agreement = 'all'
        min_hours_sleep_icu = 2
        inclusion_agreement = 'agreement_relaxed'
        do_agreement_for_sleeplab = True

    elif version == 2:
        # ### compare ICU group 3 and sleeplab group 3, compute sleep statistics on ALL sleep:
        agreement = 'agreement_relaxed'
        min_hours_sleep_icu = 2
        inclusion_agreement = 'agreement_relaxed'
        do_agreement_for_sleeplab = True

    result_mean_breathing_hrv = pd.read_csv(f'results_sleep_stage_analysis_{str(min_hours_sleep_icu)}_inclusion_{inclusion_agreement}_sleepstatistics_{agreement}_sleeplabagree_{do_agreement_for_sleeplab}_forcedisc{force_concordant_discordant_sleep}.csv', index_col=0)

    print(f'\n version {version} \n')
    print('N ICU         ' + result_mean_breathing_hrv.loc["('ICU', 'N Subjects')", 'TS'])
    print('N Sleeplab    ' + result_mean_breathing_hrv.loc["('Sleeplab All', 'N Subjects')", 'TS'])

    if version < 2:
        print('ICU TS        ' + result_mean_breathing_hrv.loc["('ICU', 'Mean')", 'TS'] + ' (' + result_mean_breathing_hrv.loc["('ICU', 'Std')", 'TS'] + ')')
        print('Sleeplab TS   ' + result_mean_breathing_hrv.loc["('Sleeplab All', 'Mean')", 'TS']+ ' (' + result_mean_breathing_hrv.loc["('Sleeplab All', 'Std')", 'TS'] + ')')
    elif version == 2:
        print('ICU TS        ' + result_mean_breathing_hrv.loc["('ICU', 'Mean')", 'CS'] + ' (' + result_mean_breathing_hrv.loc["('ICU', 'Std')", 'CS'] + ')')
        print('Sleeplab TS   ' + result_mean_breathing_hrv.loc["('Sleeplab All', 'Mean')", 'CS']+ ' (' + result_mean_breathing_hrv.loc["('Sleeplab All', 'Std')", 'CS'] + ')')

    print('ICU S(%)      ' + result_mean_breathing_hrv.loc["('ICU', 'Mean')", 'S']+ ' (' + result_mean_breathing_hrv.loc["('ICU', 'Std')", 'S'] + ')')
    print('Sleeplab S(%) ' + result_mean_breathing_hrv.loc["('Sleeplab All', 'Mean')", 'S']+ ' (' + result_mean_breathing_hrv.loc["('Sleeplab All', 'Std')", 'S'] + ')')

 version 0

N ICU         102
N Sleeplab    220
ICU TS        6.2 (3.1)
Sleeplab TS   ** 4.9 (1.6)
ICU S(%)      50.4 (19.7)
Sleeplab S(%) ** 73.9 (19.3)

 version 1

N ICU         80
N Sleeplab    190
ICU TS        8.6 (3.0)
Sleeplab TS   ** 5.3 (1.3)
ICU S(%)      56.4 (18.7)
Sleeplab S(%) ** 76.7 (16.4)

 version 2

N ICU         80
N Sleeplab    190
ICU TS        4.2 (1.7)
Sleeplab TS   4.1 (1.4)
ICU S(%)      58.3 (26.9)
Sleeplab S(%) ** 76.8 (18.2)

In [59]:
result_mean_breathing_hrv

,TS,CS,DS,DS%,S,R,N1,N2,N3,N2+N3,SFI,WT
"('ICU', 'N Subjects')",80,80,80,80,80,80,80,80,80,80,80,80
"('Sleeplab All', 'N Subjects')",190,190,190,190,190,190,190,190,190,190,190,190
"('Sleeplab AHI 0-5', 'N Subjects')",69,69,69,69,69,69,69,69,69,69,69,69
"('Sleeplab AHI 15-100', 'N Subjects')",49,49,49,49,49,49,49,49,49,49,49,49
"('ICU', 'Mean')",8.6,4.2,4.4,42.7,58.3,12.1,46.2,21.5,18.8,40.2,1.7,6.4
"('ICU', 'Median')",8.2,4.0,3.9,41.2,54.8,0.0,37.6,19.3,11.1,33.6,1.3,4.1
"('Sleeplab All', 'Mean')",** 5.3,4.1,** 1.1,** 21.6,** 76.8,9.9,** 34.2,** 40.6,15.0,** 55.6,** 3.0,** 4.1
"('Sleeplab All', 'Median')",** 5.5,4.2,** 1.0,** 19.4,** 81.6,** 7.8,** 25.7,** 43.6,12.5,** 58.7,** 2.9,* 2.6
"('Sleeplab AHI 0-5', 'Mean')",** 5.4,4.2,** 1.2,** 22.4,** 79.5,11.6,** 27.5,** 44.1,16.8,** 60.9,** 2.8,** 3.1
"('Sleeplab AHI 0-5', 'Median')",** 5.7,4.3,** 1.0,** 19.3,** 84.1,** 9.3,** 20.9,** 47.9,14.9,** 64.5,** 2.8,** 2.1
"('Sleeplab AHI 15-100', 'Mean')",** 5.1,3.8,** 1.3,** 24.6,** 72.6,6.7,50.1,** 33.2,** 9.9,43.1,** 3.3,6.5
"('Sleeplab AHI 15-100', 'Median')",** 5.3,4.0,** 1.2,** 22.8,** 75.5,1.6,47.5,** 35.1,7.6,46.1,** 3.0,4.0
"('ICU', 'Std')",3.0,1.7,2.5,16.9,26.9,24.3,33.8,17.0,20.6,32.3,1.5,8.1
"('ICU', 'Iqr')",4.3,2.6,3.7,27.8,42.4,11.9,58.1,25.7,31.3,63.5,2.0,6.6
"('ICU', 'p_dag')",0.0051,0.0603,0.1126,0.1981,0.0001,0.0,0.0,0.0717,0.0071,0.0,0.0,0.0
"('ICU', 'p_sha')",0.0261,0.0037,0.0184,0.2501,0.0026,0.0,0.0,0.0008,0.0,0.0,0.0,0.0
"('ICU', 'gaussian')",False,True,True,True,False,False,False,True,False,False,False,False
"('Sleeplab All', 'p_tt')",0.0,0.5921,0.0,0.0,0.0,0.2904,0.0013,0.0,0.0731,0.0,0.0,0.0092
"('Sleeplab All', 's_tt')",12.7,0.5,16.2,11.1,-6.6,1.1,3.2,-8.7,1.8,-4.4,-7.0,2.6
"('Sleeplab All', 'p_medians')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab All', 's_medians')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab All', 'p_mwu')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab All', 's_mwu')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab All', 'Std')",1.3,1.4,0.7,13.0,18.2,9.8,24.8,16.4,13.0,22.7,1.4,6.0
"('Sleeplab All', 'Iqr')",1.9,2.3,0.8,14.7,24.0,18.1,28.0,18.6,15.8,27.0,1.7,3.1
"('Sleeplab All', 'p_dag')",0.0258,0.0004,0.0,0.0,0.0,0.0003,0.0,0.0011,0.0,0.0003,0.0001,0.0
"('Sleeplab All', 'p_sha')",0.0033,0.0149,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0006,0.0
"('Sleeplab All', 'gaussian')",False,False,False,False,False,False,False,False,False,False,False,False
"('Sleeplab AHI 0-5', 'p_tt')",0.0,0.805,0.0,0.0,0.0,0.8792,0.0001,0.0,0.4957,0.0,0.0,0.0013
"('Sleeplab AHI 0-5', 's_tt')",8.3,0.2,10.1,8.1,-5.7,0.2,3.9,-8.5,0.7,-4.5,-5.4,3.3
"('Sleeplab AHI 0-5', 'p_medians')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab AHI 0-5', 's_medians')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab AHI 0-5', 'p_mwu')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab AHI 0-5', 's_mwu')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab AHI 0-5', 'Std')",1.2,1.3,0.7,13.4,16.5,10.8,21.9,15.1,13.0,21.4,1.1,3.1
"('Sleeplab AHI 0-5', 'Iqr')",1.8,1.9,0.7,14.7,19.3,19.7,13.9,16.2,13.5,21.2,1.6,2.6
"('Sleeplab AHI 0-5', 'p_dag')",0.435,0.8154,0.0085,0.0001,0.001,0.0301,0.0,0.0013,0.0002,0.0009,0.7701,0.0
"('Sleeplab AHI 0-5', 'p_sha')",0.2551,0.8811,0.0004,0.0002,0.0,0.0001,0.0,0.0001,0.0001,0.0001,0.6995,0.0
"('Sleeplab AHI 0-5', 'gaussian')",True,True,False,False,False,False,False,False,False,False,True,False
"('Sleeplab AHI 15-100', 'p_tt')",0.0,0.1552,0.0,0.0,0.0014,0.1399,0.4933,0.0003,0.0049,0.5851,0.0,0.9709
"('Sleeplab AHI 15-100', 's_tt')",7.8,1.4,8.3,6.2,-3.3,1.5,-0.7,-3.7,2.9,-0.5,-5.2,-0.0
"('Sleeplab AHI 15-100', 'p_medians')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab AHI 15-100', 's_medians')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab AHI 15-100', 'p_mwu')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab AHI 15-100', 's_mwu')",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"('Sleeplab AHI 15-100', 'Std')",1.3,1.5,0.8,14.7,18.6,8.9,27.4,18.1,8.9,22.7,2.0,10.1
"('Sleeplab AHI 15-100', 'Iqr')",1.3,1.8,0.8,15.5,24.6,12.1,39.9,22.3,12.3,24.0,2.0,3.9
"('Sleeplab AHI 15-100', 'p_dag')",0.0595,0.4443,0.0,0.0048,0.0229,0.0028,0.0999,0.9111,0.0589,0.2116,0.0153,0.0
"('Sleeplab AHI 15-100', 'p_sha')",0.034,0.2717,0.0005,0.0042,0.0049,0.0,0.0255,0.2145,0.0009,0.0118,0.017,0.0
"('Sleeplab AHI 15-100', 'gaussian')",True,True,False,False,False,False,True,True,True,True,False,False

# backups from earlier, including some variants of above plots:

### Sleep Stage and Indices Comparison for Signal Modalities; ICU and all matched sleeplab subjects.

In [15]:
#### select version of plot:
ahi_category = 'all'
agreement = 'agreement_relaxed'
icu_day_v = 'full'
####

summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]

min_hours_sleep_icu = 2
if icu_day_v == 'day_night':
    summary_dn_icu_sel = summary_dn_icu.loc[np.any([summary_dn_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_dn_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :]
elif icu_day_v == 'full':
    summary_dn_icu_sel = summary_f_icu.loc[np.any([summary_f_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_f_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :] 
    
summary_days_sleeplab = summary_days_sleeplab.loc[np.any([summary_days_sleeplab[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_days_sleeplab[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :] 

print(f'Min Hours of Sleep: {min_hours_sleep_icu}')
print(f'{icu_day_v} Segments included:')
print(f'ICU:      {summary_dn_icu_sel.shape[0]} ({summary_dn_icu_sel.study_id.unique().shape[0]} subjects)')
print(f'Sleeplab: {summary_days_sleeplab.shape[0]} ({summary_days_sleeplab.study_id.unique().shape[0]} subjects)')



# agreements = ['all', 'agreement', 'disagreement', 'agreement_relaxed', 'disagreement_relaxed']

fig, ax = plt.subplots(3,2,figsize=(6.4,6.4))
for ax_tmp in ax.flatten():
    ax_tmp.spines['top'].set_visible(False)
    ax_tmp.spines['right'].set_visible(False)
    ax_tmp.spines['bottom'].set_visible(False)
    ax_tmp.spines['left'].set_visible(False)
    ax_tmp.set_yticks([])
    
# row 1: RESPIRATION COMPARISON.
modality = 'amendsumeffort'
variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
title = f'ICU (n={summary_dn_icu_sel.shape[0]}), Breathing'
sleep_summary_barplots(ax[0,0], summary_dn_icu_sel, variables, x_labels,  color='navy', title=title)

modality = 'amendsumeffort'
variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
title = f'Sleeplab (n={summary_days_sleeplab.shape[0]}), Breathing'
sleep_summary_barplots(ax[0,1], summary_days_sleeplab, variables, x_labels,  color='cornflowerblue', title=title)

# row 2: ECG COMPARISON.
modality = 'ecg_nn'
variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
title = f'ICU (n={summary_dn_icu_sel.shape[0]}), HRV'
sleep_summary_barplots(ax[1,0], summary_dn_icu_sel, variables, x_labels,  color='darkred', title=title)

modality = 'ecg_nn'
variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
title = f'Sleeplab (n={summary_days_sleeplab.shape[0]}), HRV'
sleep_summary_barplots(ax[1,1], summary_days_sleeplab, variables, x_labels,  color='tomato', title=title)

# row 3: EXPERT, only available for sleeplab
modality = 'expert'
variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
title = f'Sleeplab (n={summary_days_sleeplab.shape[0]}), Expert'
sleep_summary_barplots(ax[2,1], summary_days_sleeplab, variables, x_labels,  color='green', title=title)

ax[2,0].set_xticks([])
ax[2,0].text(0.2, 0.5, 'No Expert Labels available for ICU.')


plt.tight_layout()
plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_category}_agree_{agreement}_{icu_day_v}.jpg'), dpi=500)
plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_category}_agree_{agreement}_{icu_day_v}.svg'))

Min Hours of Sleep: 2
full Segments included:
ICU:      129 (65 subjects)
Sleeplab: 190 (190 subjects)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [16]:
for ax_tmp in ax[:2,:].flatten():   
    ax_tmp.set_xticklabels(['Dur', 'Eff', 'R', 'N1', 'N2', 'N3', 'SFI', 'SFW', 'AI'])

### same as above but loop over all AHI categories:

In [17]:
#### select version of plot:
ahi_category = 'all'
agreement = 'agreement_relaxed'
icu_day_v = 'full'
####

min_hours_sleep_icu = 2
if icu_day_v == 'day_night':
    summary_dn_icu_sel = summary_dn_icu.loc[np.any([summary_dn_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_dn_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :]
elif icu_day_v == 'full':
    summary_dn_icu_sel = summary_f_icu.loc[np.any([summary_f_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_f_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :] 
    


print(f'Min Hours of Sleep: {min_hours_sleep_icu}')
print(f'Agreement: {agreement}')
print(f'{icu_day_v} Segments included:')
print(f'ICU:      {summary_dn_icu_sel.shape[0]} ({summary_dn_icu_sel.study_id.unique().shape[0]} subjects)')

    
for ahi_category in ahi_categories:
    if ahi_category == 'all': continue
        
    summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]
    summary_days_sleeplab = summary_days_sleeplab.loc[np.any([summary_days_sleeplab[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_days_sleeplab[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :] 
    
    print(f'Sleeplab AHI {ahi_category}: {summary_days_sleeplab.shape[0]} ({summary_days_sleeplab.study_id.unique().shape[0]} subjects)')

    fig, ax = plt.subplots(3,2,figsize=(6,9))
    for ax_tmp in ax.flatten():
        ax_tmp.spines['top'].set_visible(False)
        ax_tmp.spines['right'].set_visible(False)
        ax_tmp.spines['bottom'].set_visible(False)
        ax_tmp.spines['left'].set_visible(False)
        ax_tmp.set_yticks([])

    # row 1: RESPIRATION COMPARISON.
    modality = 'amendsumeffort'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
    title = f'ICU (n={summary_dn_icu_sel.shape[0]}), Respiration'
    sleep_summary_barplots(ax[0,0], summary_dn_icu_sel, variables, x_labels,  color='navy', title=title)

    modality = 'amendsumeffort'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
    title = f'Sleeplab (n={summary_days_sleeplab.shape[0]}), Respiration'
    sleep_summary_barplots(ax[0,1], summary_days_sleeplab, variables, x_labels,  color='cornflowerblue', title=title)

    # row 2: ECG COMPARISON.
    modality = 'ecg_nn'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
    title = f'ICU (n={summary_dn_icu_sel.shape[0]}), ECG'
    sleep_summary_barplots(ax[1,0], summary_dn_icu_sel, variables, x_labels,  color='darkred', title=title)

    modality = 'ecg_nn'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
    title = f'Sleeplab (n={summary_days_sleeplab.shape[0]}), ECG'
    sleep_summary_barplots(ax[1,1], summary_days_sleeplab, variables, x_labels,  color='tomato', title=title)

    # row 3: EXPERT, only available for sleeplab
    modality = 'expert'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
    title = f'Sleeplab (n={summary_days_sleeplab.shape[0]}), Expert'
    sleep_summary_barplots(ax[2,1], summary_days_sleeplab, variables, x_labels,  color='green', title=title)

    ax[2,0].set_xticks([])
    ax[2,0].text(0.2, 0.5, 'No Expert Labels available for ICU.')

    plt.tight_layout()
#     plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_category}_agree_{agreement}_{icu_day_v}.jpg'), dpi=500)
#     plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_category}_agree_{agreement}_{icu_day_v}.svg'))

Min Hours of Sleep: 2
Agreement: agreement_relaxed
full Segments included:
ICU:      129 (65 subjects)
Sleeplab AHI ahi_0_5: 69 (69 subjects)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Sleeplab AHI ahi_5_15: 60 (60 subjects)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Sleeplab AHI ahi_15_30: 36 (36 subjects)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Sleeplab AHI ahi_30_100: 18 (18 subjects)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Sleeplab AHI ahi_15_100: 49 (49 subjects)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [18]:
ahi_categories

['all', 'ahi_0_5', 'ahi_5_15', 'ahi_15_30', 'ahi_30_100', 'ahi_15_100']

In [37]:
#### select version of plot:
ahi_category = 'all'
agreement = 'agreement_relaxed'
icu_day_v = 'full'
####

summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]

min_hours_sleep_icu = 2
if icu_day_v == 'day_night':
    summary_dn_icu_sel = summary_dn_icu.loc[np.any([summary_dn_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_dn_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :]
elif icu_day_v == 'full':
    summary_dn_icu_sel = summary_f_icu.loc[np.any([summary_f_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_f_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :] 
    
print(f'Min Hours of Sleep: {min_hours_sleep_icu}')
print(f'{icu_day_v} Segments included:')
print(f'ICU:      {summary_dn_icu_sel.shape[0]} ({summary_dn_icu_sel.study_id.unique().shape[0]} subjects)')


ahi_categories_to_plot = 'all_low_high'

if ahi_categories_to_plot == 'all':
    ahi_categories_sel = ahi_categories[:-1]
elif ahi_categories_to_plot == 'all_low_high':
    ahi_categories_sel = ['all', 'ahi_0_5', 'ahi_15_100']

n_ahi_categories = len(ahi_categories_sel)


fig, ax = plt.subplots(3, 1+n_ahi_categories, figsize=(6.4, 6.4))

for ax_tmp in ax.flatten():
    ax_tmp.spines['top'].set_visible(False)
    ax_tmp.spines['right'].set_visible(False)
    ax_tmp.spines['bottom'].set_visible(False)
    ax_tmp.spines['left'].set_visible(False)
    ax_tmp.set_yticks([])
    ax_tmp.tick_params(length=0.05)
# ICU first column:


# row 1: RESPIRATION COMPARISON.
modality = 'amendsumeffort'
variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
title = None
sleep_summary_barplots(ax[0,0], summary_dn_icu_sel, variables, x_labels,  color='navy', title=title)

# row 2: ECG COMPARISON.
modality = 'ecg_nn'
variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
title = None
sleep_summary_barplots(ax[1,0], summary_dn_icu_sel, variables, x_labels,  color='darkred', title=title)

ax[2,0].set_xticks([])
ax[2,0].text(0.2, 0.5, 'No Expert Labels\navailable for ICU.')

ax[0,0].text(  
0.5, 1.5, f'ICU \n\n(n={summary_dn_icu_sel.shape[0]})', # 1.27
ha='center', va='top', fontdict = font_headers,
transform=ax[0,0].transAxes
)
    
    
for i_ahi_cat, ahi_category in enumerate(ahi_categories_sel):

    summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]
    summary_days_sleeplab = summary_days_sleeplab.loc[np.any([summary_days_sleeplab[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_days_sleeplab[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :] 
    
    print(f'Sleeplab AHI={ahi_category}: {summary_days_sleeplab.shape[0]} ({summary_days_sleeplab.study_id.unique().shape[0]} subjects)')

    ax[0,i_ahi_cat+1].text( 
    0.5, 1.3, f'{ahi_names[ahi_category]} \n(n={summary_days_sleeplab.shape[0]})',
    ha='center', va='top', fontdict = font_headers,
    transform=ax[0,i_ahi_cat+1].transAxes
    )
    # row 1: RESPIRATION COMPARISON.

    modality = 'amendsumeffort'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
    title = None
    sleep_summary_barplots(ax[0,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels,  color='cornflowerblue', title=title)

    # row 2: ECG COMPARISON.
    modality = 'ecg_nn'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
    sleep_summary_barplots(ax[1,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels,  color='tomato', title=title)

    # row 3: EXPERT, only available for sleeplab
    modality = 'expert'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]

    sleep_summary_barplots(ax[2,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels,  color='green', title=title)


ax[0,(n_ahi_categories+1)//2].text( 
0.5, 1.5, f'Sleeplab',
ha='center', va='top', fontdict = font_headers,
transform=ax[0,(n_ahi_categories+1)//2].transAxes
)

ax[0, 0].text( 
-0.1, 0.5, f'Breathing',
ha='center', va='top', fontdict = font_headers, rotation='vertical',
transform=ax[0, 0].transAxes
)

ax[1, 0].text( 
-0.1, 0.5, f'HRV',
ha='center', va='top', fontdict = font_headers, rotation='vertical',
transform=ax[1, 0].transAxes
)

ax[2, 0].text( 
-0.1, 0.5, f'Expert',
ha='center', va='top', fontdict = font_headers, rotation='vertical',
transform=ax[2, 0].transAxes
)

for ax_tmp in ax[:2,:].flatten():   
    ax_tmp.set_xticklabels(['Dur', 'Eff', 'R', 'N1', 'N2', 'N3', 'SFI', 'SFW', 'AI'])

plt.subplots_adjust(left=None, bottom=None, right=None, top=None, wspace=0.02, hspace=0.5)
plt.tight_layout()

if 0:
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}.jpg'), dpi=500)
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}.svg'))

if 0: 
    
    fig.set_size_inches(8,7)
    plt.subplots_adjust(left=None, bottom=0.1, right=None, top=None, wspace=0.02, hspace=0.5)


    plt.tight_layout()
    plt.subplots_adjust(bottom=0.14)

if 0:
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_shortxlabels.jpg'), dpi=500)
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_shortxlabels.svg'))


if 0:
    
    fig.set_size_inches(8,4)
    plt.tight_layout()
    plt.tight_layout()
    plt.subplots_adjust(bottom=0.2)
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_shortxlabels_8_4.jpg'), dpi=500)
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_shortxlabels_8_4.svg'))


if 0:
    fig.set_size_inches(6.5,4)
    plt.tight_layout()
    plt.tight_layout()
    plt.subplots_adjust(bottom=0.22)
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_shortxlabels_8_4.jpg'), dpi=500)
    plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_shortxlabels_8_4.svg'))


# fig.set_size_inches(8,6)
    
# for ax_tmp in ax[:2,:].flatten():
#     ax_tmp.set_xticklabels([])
#     ax_tmp.set_xticks([])
    
# plt.tight_layout()
# plt.subplots_adjust(bottom=0.14)
# if 0:
#     plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_noxlabels.jpg'), dpi=500)
#     plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_noxlabels.svg'))

Min Hours of Sleep: 2
full Segments included:
ICU:      129 (65 subjects)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Sleeplab AHI=all: 190 (190 subjects)
Sleeplab AHI=ahi_0_5: 69 (69 subjects)
Sleeplab AHI=ahi_15_100: 49 (49 subjects)

In [38]:
### same as above but remove SFI Wake and relabel variables.


### 3x2 plot
# cols: data type, rows: stage version (resp, ecg, expert)

variables_template = ['sleep_hours_MODALITY',
             'stages_distribution_MODALITY_S',
             'stages_distribution_MODALITY_R',
             'stages_distribution_MODALITY_N1',
            'stages_distribution_MODALITY_N2',
             'stages_distribution_MODALITY_N3',
             'sleep_MODALITY_sfi',
             'sleep_MODALITY_arousali',
            ]

variables_template = [
# 'hours_data_MODALITY_AGREEMENT',
 'hours_sleep_MODALITY_AGREEMENT',
#  'perc_W_MODALITY_AGREEMENT',
 'perc_S_MODALITY_AGREEMENT',
 'perc_R_MODALITY_AGREEMENT',
 'perc_N1_MODALITY_AGREEMENT',
 'perc_N2_MODALITY_AGREEMENT',
 'perc_N3_MODALITY_AGREEMENT',
 'sfi_MODALITY_AGREEMENT',
 'arousali_MODALITY_AGREEMENT',
]

x_labels = ['Sleep Dur. (h)', 'Sleep (%)', 'Stage R (%)', 'Stage N1 (%)', 'Stage N2 (%)', 'Stage N3 (%)', 'SFI', 'Wake Trans./h']


#### select version of plot:
ahi_category = 'all'
agreement = 'agreement_relaxed'
icu_day_v = 'full'
####

summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]

min_hours_sleep_icu = 2
if icu_day_v == 'day_night':
    summary_dn_icu_sel = summary_dn_icu.loc[np.any([summary_dn_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_dn_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :]
elif icu_day_v == 'full':
    summary_dn_icu_sel = summary_f_icu.loc[np.any([summary_f_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_f_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :] 
    
print(f'Min Hours of Sleep: {min_hours_sleep_icu}')
print(f'{icu_day_v} Segments included:')
print(f'ICU:      {summary_dn_icu_sel.shape[0]} ({summary_dn_icu_sel.study_id.unique().shape[0]} subjects)')

ahi_categories_to_plot = 'all_low_high'

if ahi_categories_to_plot == 'all':
    ahi_categories_sel = ahi_categories[:-1]
elif ahi_categories_to_plot == 'all_low_high':
    ahi_categories_sel = ['all', 'ahi_0_5', 'ahi_15_100']

n_ahi_categories = len(ahi_categories_sel)


fig, ax = plt.subplots(3, 1+n_ahi_categories, figsize=(6.4, 6.4))

for ax_tmp in ax.flatten():
    ax_tmp.spines['top'].set_visible(False)
    ax_tmp.spines['right'].set_visible(False)
    ax_tmp.spines['bottom'].set_visible(False)
    ax_tmp.spines['left'].set_visible(False)
    ax_tmp.set_yticks([])
    ax_tmp.tick_params(length=0.05)
# ICU first column:


# row 1: RESPIRATION COMPARISON.
modality = 'amendsumeffort'
variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
title = None
sleep_summary_barplots(ax[0,0], summary_dn_icu_sel, variables, x_labels,  color='navy', title=title)

# row 2: ECG COMPARISON.
modality = 'ecg_nn'
variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
title = None
sleep_summary_barplots(ax[1,0], summary_dn_icu_sel, variables, x_labels,  color='darkred', title=title)

ax[2,0].set_xticks([])
ax[2,0].text(0.2, 0.5, 'No Expert Labels\navailable for ICU.')

ax[0,0].text(  
0.5, 1.5, f'ICU \n\n(n={summary_dn_icu_sel.shape[0]})', # 1.27
ha='center', va='top', fontdict = font_headers,
transform=ax[0,0].transAxes
)
    
    
for i_ahi_cat, ahi_category in enumerate(ahi_categories_sel):

    summary_days_sleeplab = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_' + ahi_category] == 1]
    summary_days_sleeplab = summary_days_sleeplab.loc[np.any([summary_days_sleeplab[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                               summary_days_sleeplab[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                               axis=0), :] 
    print(f'Sleeplab AHI={ahi_category}: {summary_days_sleeplab.shape[0]} ({summary_days_sleeplab.study_id.unique().shape[0]} subjects)')

    ax[0,i_ahi_cat+1].text( 
    0.5, 1.3, f'{ahi_names[ahi_category]} \n(n={summary_days_sleeplab.shape[0]})',
    ha='center', va='top', fontdict = font_headers,
    transform=ax[0,i_ahi_cat+1].transAxes
    )
    # row 1: RESPIRATION COMPARISON.

    modality = 'amendsumeffort'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
    title = None
    sleep_summary_barplots(ax[0,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels,  color='cornflowerblue', title=title)

    # row 2: ECG COMPARISON.
    modality = 'ecg_nn'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
    sleep_summary_barplots(ax[1,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels,  color='tomato', title=title)

    # row 3: EXPERT, only available for sleeplab
    modality = 'expert'
    variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]

    sleep_summary_barplots(ax[2,i_ahi_cat+1], summary_days_sleeplab, variables, x_labels,  color='green', title=title)


ax[0,(n_ahi_categories+1)//2].text( 
0.5, 1.5, f'Sleeplab',
ha='center', va='top', fontdict = font_headers,
transform=ax[0,(n_ahi_categories+1)//2].transAxes
)

ax[0, 0].text( 
-0.1, 0.5, f'Breathing',
ha='center', va='top', fontdict = font_headers, rotation='vertical',
transform=ax[0, 0].transAxes
)

ax[1, 0].text( 
-0.1, 0.5, f'HRV',
ha='center', va='top', fontdict = font_headers, rotation='vertical',
transform=ax[1, 0].transAxes
)

ax[2, 0].text( 
-0.1, 0.5, f'Expert',
ha='center', va='top', fontdict = font_headers, rotation='vertical',
transform=ax[2, 0].transAxes
)

for ax_tmp in ax[:2,:].flatten():   
    ax_tmp.set_xticklabels(['Dur', 'S', 'R', 'N1', 'N2', 'N3', 'SFI', 'WT'])

plt.subplots_adjust(left=None, bottom=None, right=None, top=None, wspace=0.02, hspace=0.5)
plt.tight_layout()

# plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_8indices.jpg'), dpi=500)
# plt.savefig(os.path.join(plots_savedir, f'Figure_Sleep_Stage_Analysis_Histograms_Indices_All_minhoursleep_{str(min_hours_sleep_icu)}_ahi_{ahi_categories_to_plot}_agree_{agreement}_{icu_day_v}_8indices.svg'))

Min Hours of Sleep: 2
full Segments included:
ICU:      129 (65 subjects)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Sleeplab AHI=all: 190 (190 subjects)
Sleeplab AHI=ahi_0_5: 69 (69 subjects)
Sleeplab AHI=ahi_15_100: 49 (49 subjects)

## Box for each Feature plot

In [39]:
# ### 3x2 plot
# # cols: data type, rows: stage version (resp, ecg, expert)

# variables_template = ['sleep_hours_MODALITY',
#              'stages_distribution_MODALITY_S',
#              'stages_distribution_MODALITY_R',
#              'stages_distribution_MODALITY_N1',
#             'stages_distribution_MODALITY_N2',
#              'stages_distribution_MODALITY_N3',
#              'sleep_MODALITY_sfi',
#              'sleep_MODALITY_sfi_w',
#              'sleep_MODALITY_arousali',
#             ]

# x_labels = ['Sleep Dur. (h)', 'Sleep Efficiency', 'Stage R (%)', 'Stage N1 (%)', 'Stage N2 (%)', 'Stage N3 (%)', 'SFI', 'SFI Wake', 'Arousal I.']

In [18]:
#### parameters for all upcoming plots/analysis
agreement = 'agreement_relaxed'
icu_day_v = 'full'
do_agreement_for_sleeplab = True
min_hours_sleep_icu = 2 # also for sleeplab if do_agreement_for_sleeplab is True.

In [19]:
sleeplab_all = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_all'] == 1]
sleeplab_ahi_0_5 = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_ahi_0_5'] == 1]
sleeplab_ahi_5_15 = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_ahi_5_15'] == 1]
sleeplab_ahi_15_30 = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_ahi_15_30'] == 1]
sleeplab_ahi_30_100 = summary_days_sleeplab_full.loc[summary_days_sleeplab_full['matched_ahi_30_100'] == 1]


if do_agreement_for_sleeplab:

    sleeplab_all = sleeplab_all.loc[np.any([sleeplab_all[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                           sleeplab_all[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                           axis=0), :]
    
    sleeplab_ahi_0_5 = sleeplab_ahi_0_5.loc[np.any([sleeplab_ahi_0_5[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                           sleeplab_ahi_0_5[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                           axis=0), :]
    
    sleeplab_ahi_5_15 = sleeplab_ahi_5_15.loc[np.any([sleeplab_ahi_5_15[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                           sleeplab_ahi_5_15[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                           axis=0), :]
        
    sleeplab_ahi_15_30 = sleeplab_ahi_15_30.loc[np.any([sleeplab_ahi_15_30[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                           sleeplab_ahi_15_30[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                           axis=0), :]
            
    sleeplab_ahi_30_100 = sleeplab_ahi_30_100.loc[np.any([sleeplab_ahi_30_100[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                           sleeplab_ahi_30_100[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                           axis=0), :]

In [20]:
print(f'Min Hours of Sleep: {min_hours_sleep_icu}')
print(f'{icu_day_v} Segments included:')
print(f'ICU:      {summary_dn_icu_sel.shape[0]} ({summary_dn_icu_sel.study_id.unique().shape[0]} subjects)')
print(f'Sleeplab AHI All: {sleeplab_all.shape[0]} ({sleeplab_all.study_id.unique().shape[0]} subjects)')
print(f'Sleeplab AHI [0,5]: {sleeplab_ahi_0_5.shape[0]} ({sleeplab_ahi_0_5.study_id.unique().shape[0]} subjects)')
print(f'Sleeplab AHI [5,15]: {sleeplab_ahi_5_15.shape[0]} ({sleeplab_ahi_5_15.study_id.unique().shape[0]} subjects)')
print(f'Sleeplab AHI [15, 30]: {sleeplab_ahi_15_30.shape[0]} ({sleeplab_ahi_15_30.study_id.unique().shape[0]} subjects)')
print(f'Sleeplab AHI [30, 100]: {sleeplab_ahi_30_100.shape[0]} ({sleeplab_ahi_30_100.study_id.unique().shape[0]} subjects)')

Min Hours of Sleep: 2
full Segments included:

NameError: name 'summary_dn_icu_sel' is not defined

In [20]:
ahi_category = 'all'

if icu_day_v == 'day_night':
    summary_dn_icu_sel = summary_dn_icu.loc[np.any([summary_dn_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_dn_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :]
elif icu_day_v == 'full':

    icu_2 = summary_f_icu.loc[np.any([summary_f_icu.sleep_hours_breathing >= min_hours_sleep_icu, 
                                                   summary_f_icu.sleep_hours_ecg_nn >= min_hours_sleep_icu],
                                                   axis=0), :]
#     min_hours_sleep_icu = 4
#     icu_4 = summary_f_icu.loc[np.any([summary_f_icu.sleep_hours_breathing >= min_hours_sleep_icu, 
#                                                    summary_f_icu.sleep_hours_ecg_nn >= min_hours_sleep_icu],
#                                                    axis=0), :]



# fig, ax = plt.subplots(3,2,figsize=(6,9))
# for ax_tmp in ax.flatten():
#     ax_tmp.spines['top'].set_visible(False)
#     ax_tmp.spines['right'].set_visible(False)
#     ax_tmp.spines['bottom'].set_visible(False)
#     ax_tmp.spines['left'].set_visible(False)
#     ax_tmp.set_yticks([])
    
modality = 'ecg_nn'
variables = [x.replace('MODALITY', modality) for x in variables_template]


# var_name = {
#   'sleep_hours_ecg_nn' : 'Sleep Duration (h) [ECG]',
#  'stages_distribution_ecg_nn_S': 'Sleep Efficiency [ECG]',
#  'stages_distribution_ecg_nn_R': 'Stage R (%) [ECG]',
#  'stages_distribution_ecg_nn_N1': 'Stage N1 (%) [ECG]',
#  'stages_distribution_ecg_nn_N2': 'Stage N2 (%) [ECG]',
#  'stages_distribution_ecg_nn_N3': 'Stage N3 (%) [ECG]',
# 'stages_distribution_ecg_nn_N2N3': 'Stage N2+N3 (%) [ECG]',

#  'sleep_ecg_nn_sfi': 'SFI [ECG]',
#  'sleep_ecg_nn_sfi_w': 'SFI-Wake [ECG]',
#  'sleep_ecg_nn_arousali': 'Arousal Index [ECG]',
# 'sleep_hours_breathing' : 'Sleep Duration (h) [Respiration]',
#  'stages_distribution_breathing_S': 'Sleep Efficiency [Respiration]',
#  'stages_distribution_breathing_R': 'Stage R (%) [Respiration]',
#  'stages_distribution_breathing_N1': 'Stage N1 (%) [Respiration]',
#  'stages_distribution_breathing_N2': 'Stage N2 (%) [Respiration]',
#  'stages_distribution_breathing_N3': 'Stage N3 (%) [Respiration]',
#     'stages_distribution_breathing_N2N3': 'Stage N2+N3 (%) [Respiration]',

#  'sleep_breathing_sfi': 'SFI [Respiration]',
#  'sleep_breathing_sfi_w': 'SFI-Wake [Respiration]',
#  'sleep_breathing_arousali': 'Arousal Index [Respiration]',
# }

var_name = {
  f'hours_sleep_ecg_nn_{agreement}' : 'Sleep Duration (h) [HRV]',
f'hours_discordant_ecg_nn_{agreement}' : 'Discordant Sleep (h) [HRV]',
 f'perc_S_ecg_nn_{agreement}': 'Sleep Efficiency [HRV]',
 f'perc_R_ecg_nn_{agreement}': 'Stage R (%) [HRV]',
 f'perc_N1_ecg_nn_{agreement}': 'Stage N1 (%) [HRV]',
 f'perc_N2_ecg_nn_{agreement}': 'Stage N2 (%) [HRV]',
 f'perc_N3_ecg_nn_{agreement}': 'Stage N3 (%) [HRV]',
 f'perc_N2N3_ecg_nn_{agreement}': 'Stage N2+N3 (%) [HRV]',
 f'sfi_ecg_nn_{agreement}': 'SFI [HRV]',
 f'sfi_w_ecg_nn_{agreement}': 'SFI-Wake [HRV]',
 f'arousali_ecg_nn_{agreement}': 'Wake Transitions/h [HRV]',
 f'hours_sleep_amendsumeffort_{agreement}' : 'Sleep Duration (h) [Breathing]',
f'hours_discordant_amendsumeffort_{agreement}' : 'Discordant Sleep (h) [Breathing]',
 f'perc_S_amendsumeffort_{agreement}': 'Sleep Efficiency [Breathing]',
 f'perc_R_amendsumeffort_{agreement}': 'Stage R (%) [Breathing]',
 f'perc_N1_amendsumeffort_{agreement}': 'Stage N1 (%) [Breathing]',
 f'perc_N2_amendsumeffort_{agreement}': 'Stage N2 (%) [Breathing]',
 f'perc_N3_amendsumeffort_{agreement}': 'Stage N3 (%) [Breathing]',
 f'perc_N2N3_amendsumeffort_{agreement}': 'Stage N2+N3 (%) [Breathing]',
 f'sfi_amendsumeffort_{agreement}': 'SFI [Breathing]',
 f'sfi_w_amendsumeffort_{agreement}': 'SFI-Wake [Breathing]',
 f'arousali_amendsumeffort_{agreement}': 'Wake Transitions/h [Breathing]',
}

variables_to_use = 'all_discordant'
    
if variables_to_use == 'all':
    variables_template = ['hours_sleep_MODALITY_AGREEMENT',
 'perc_S_MODALITY_AGREEMENT',
 'perc_R_MODALITY_AGREEMENT',
 'perc_N1_MODALITY_AGREEMENT',
 'perc_N2_MODALITY_AGREEMENT',
 'perc_N3_MODALITY_AGREEMENT',
 'sfi_MODALITY_AGREEMENT',
#  'sfi_w_MODALITY_AGREEMENT',
 'arousali_MODALITY_AGREEMENT']
    
elif variables_to_use == 'n2n3_sum':
    variables_template = ['hours_sleep_MODALITY_AGREEMENT',
 'perc_S_MODALITY_AGREEMENT',
 'perc_R_MODALITY_AGREEMENT',
 'perc_N1_MODALITY_AGREEMENT',
 'perc_N2N3_MODALITY_AGREEMENT',
 'sfi_MODALITY_AGREEMENT',
#  'sfi_w_MODALITY_AGREEMENT',
 'arousali_MODALITY_AGREEMENT']

elif variables_to_use == 'all_discordant':
    variables_template = ['hours_sleep_MODALITY_AGREEMENT',
 'hours_discordant_MODALITY_AGREEMENT',
 'perc_R_MODALITY_AGREEMENT',
 'perc_N1_MODALITY_AGREEMENT',
 'perc_N2_MODALITY_AGREEMENT',
 'perc_N3_MODALITY_AGREEMENT',
 'sfi_MODALITY_AGREEMENT',
#  'sfi_w_MODALITY_AGREEMENT',
 'arousali_MODALITY_AGREEMENT']
    
if 0:
    n_subplots = len(variables_template)*2
    fig, ax = plt.subplots(int(np.ceil(n_subplots/4)), 4, figsize=(8,8))

    for i_variable, var_temp in enumerate(variables_template):

        for i_modality, modality in enumerate(['amendsumeffort', 'ecg_nn']):

            var = var_temp.replace('MODALITY', modality).replace('AGREEMENT', agreement)
            ax[i_variable // 2, i_modality + 2*(i_variable % 2)] = plot_mean_std_all_elements(var, ax[i_variable // 2, i_modality + 2*(i_variable % 2)])
            ax[i_variable // 2, i_modality + 2*(i_variable % 2)].set_xticks(np.arange(7))
            ax[i_variable // 2, i_modality + 2*(i_variable % 2)].set_xticklabels(['>2h', '>4h', 'All', 'Norm', 'Mild', 'Mod', 'Sev'])
            ax[i_variable // 2, i_modality + 2*(i_variable % 2)].set_title(var_name[var])

        ax[i_variable // 2, i_modality + 2*(i_variable % 2) - 1], ax[i_variable // 2, i_modality + 2*(i_variable % 2)] = set_shared_ylim(ax[i_variable // 2, i_modality + 2*(i_variable % 2) - 1], 
                                      ax[i_variable // 2, i_modality + 2*(i_variable % 2)])

    # for row in range(int(np.ceil(n_subplots/4))):
    #     for axis_each_row in ax[row,:]:
    #         axis_each_row.get_shared_y_axes().join(axis_each_row, ax[row, 0])

    for axis_bottom in ax[-1, :]:
        axis_bottom.text(0.12, -0.15, f'ICU', ha='center', va='top', rotation='horizontal',
                         fontdict = font_headers, transform=axis_bottom.transAxes)
        axis_bottom.text(0.7, -0.15, f'Sleeplab (AHI cat.)', ha='center', va='top', rotation='horizontal',
                        fontdict = font_headers, transform=axis_bottom.transAxes)

    ax = ax.flatten().flatten()
    for i in range(len(ax)):
        c_axis = 'black'
        ticklength = 1
        lw = 0.3
        for spine in ['bottom', 'top', 'right', 'left']:
            ax[i].spines[spine].set_color(c_axis)
            ax[i].spines[spine].set_linewidth(lw)
        ax[i].tick_params(axis='x', colors=c_axis, length=ticklength)
        ax[i].tick_params(axis='y', colors=c_axis, length=ticklength)
        ax[i].yaxis.label.set_color(c_axis)
        ax[i].xaxis.label.set_color(c_axis)

    plt.subplots_adjust(left=None, bottom=0.1, right=None, top=None, wspace=-1, hspace=0.5)
    plt.tight_layout()

    # plt.savefig(os.path.join(plots_savedir, f'Figure_SleepStagesIndices_Featuregrid_{variables_to_use}_agree_{agreement}_{icu_day_v}.jpg'), dpi=500)
    # plt.savefig(os.path.join(plots_savedir, f'Figure_SleepStagesIndices_Featuregrid_{variables_to_use}_agree_{agreement}_{icu_day_v}.svg'))

In [21]:
# Main Sleeplab vs ICU.
# R vs. N1 vs. N2+N3
# both modalities.

In [22]:
#### select version of plot:
ahi_category = 'all'
# agreement = 'agreement_relaxed'
# icu_day_v = 'full'
variables_to_use = 'n2n3_discordant'
statistic = 'mean_std'
statistic = 'median_iqr'
####

if variables_to_use == 'n2n3_sum':
    variables_template = [
         'perc_N1_MODALITY_AGREEMENT', 
         'perc_N2N3_MODALITY_AGREEMENT',
        'perc_R_MODALITY_AGREEMENT', 
        'hours_sleep_MODALITY_AGREEMENT',
         'sfi_MODALITY_AGREEMENT',
         'arousali_MODALITY_AGREEMENT']

    var_names = ['N1', 'N2 + N3', 'R', 'Sleep Dur (h)', 'SFI', 'Wake T./h']

elif variables_to_use == 'n2n3_discordant':
    variables_template = [
         'perc_N1_MODALITY_AGREEMENT', 
         'perc_N2N3_MODALITY_AGREEMENT',
        'perc_R_MODALITY_AGREEMENT', 
        'hours_sleep_MODALITY_AGREEMENT',
         'hours_discordant_MODALITY_AGREEMENT', 
         'arousali_MODALITY_AGREEMENT'] 

    var_names = ['N1', 'N2 + N3', 'R', 'Sleep\nDuration (h)', 'Discordant\nSleep (h)', 'Wake\nTransitions /h']
    
marker = {'amendsumeffort': 'o',
         'ecg_nn': 's'}


min_hours_sleep_icu = 4
if icu_day_v == 'day_night':
    summary_dn_icu_sel = summary_dn_icu.loc[np.any([summary_dn_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_dn_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :]
elif icu_day_v == 'full':

    summary_dn_icu_sel = summary_dn_icu.loc[np.any([summary_dn_icu[f'hours_sleep_amendsumeffort_{agreement}'] >= min_hours_sleep_icu, 
                                                   summary_dn_icu[f'hours_sleep_ecg_nn_{agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :]

legend_handles = []

figdummy, axdummy = plt.subplots(1,1);
plt.close()

fig, ax = plt.subplots(1, 2, figsize=(5,2))

i_pos = 0

for i_var, var_temp in enumerate(variables_template[:3]):

    for modality in ['amendsumeffort', 'ecg_nn']:
        var = var_temp.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        if statistic == 'mean_std':
            ax[0] = plot_mean_std_element(summary_dn_icu_sel, var, ax[0], position=i_pos, color='navy', marker=marker[modality])
            ax[0] = plot_mean_std_element(sleeplab_all, var, ax[0], position=i_pos+2, color='orange', marker=marker[modality])
        elif statistic == 'median_iqr':
            ax[0] = plot_mean_std_element(summary_dn_icu_sel, var, ax[0], position=i_pos, color='navy', marker=marker[modality])
            ax[0] = plot_mean_std_element(sleeplab_all, var, ax[0], position=i_pos+2, color='orange', marker=marker[modality])
        i_pos += 1
        
#     ax[0].text(i_pos-0.5, 89, var_names[i_var], ha='center', va='top', rotation='horizontal',
#                     fontdict = font_headers)
    i_pos += 3

ax[0].set_xticks([1.5, 6.5, 11.5])
ax[0].set_xticklabels(var_names[:3])


legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='navy', fmt='.', zorder=1, marker=marker['amendsumeffort']))
legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='navy', fmt='.', zorder=1, marker=marker['ecg_nn']))
legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='orange', fmt='.', zorder=1, marker=marker['amendsumeffort']))
legend_handles.append(axdummy.errorbar(0, 0, yerr=1, color='orange', fmt='.', zorder=1, marker=marker['ecg_nn']))

ax[0].set_ylim([0, 95])
ax[1].legend(legend_handles, ['ICU, Respiration', 'ICU, ECG', 'Sleeplab, Respiration', 'Sleeplab, ECG'], 
             frameon=False, markerscale=1, ncol=1, bbox_to_anchor=(0.2, 0.48, 0.5, 0.5), loc='best')
ax[0].set_ylabel('%')

# Subplot 2:

i_pos = 0

for i_var, var_temp in enumerate(variables_template[3:]):

    for modality in ['amendsumeffort', 'ecg_nn']:
        var = var_temp.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        if statistic == 'mean_std':
            ax[1] = plot_mean_std_element(summary_dn_icu_sel, var, ax[1], position=i_pos, color='navy', marker=marker[modality])
            ax[1] = plot_mean_std_element(sleeplab_all, var, ax[1], position=i_pos+2, color='orange', marker=marker[modality])
        elif statistic == 'median_iqr':
            ax[1] = plot_median_iqr_element(summary_dn_icu_sel, var, ax[1], position=i_pos, color='navy', marker=marker[modality])
            ax[1] = plot_median_iqr_element(sleeplab_all, var, ax[1], position=i_pos+2, color='orange', marker=marker[modality])
            
        i_pos += 1
    i_pos += 3

ax[1].set_xticks([1.5, 6.5, 11.5])
ax[1].set_xticklabels(var_names[3:])
ymin, ymax = ax[1].get_ylim()
ax[1].set_ylim([0, ymax])
# ax[1].set_ylabel('%')



plt.subplots_adjust(left=None, bottom=0.1, right=None, top=None, wspace=0.02, hspace=0.5)

c_axis = 'black'
ticklength = 1
lw = 0.3
for i in range(2):
    for spine in ['bottom', 'top', 'right', 'left']:
        ax[i].spines[spine].set_color(c_axis)
        ax[i].spines[spine].set_linewidth(lw)
    ax[i].tick_params(axis='x', colors=c_axis, length=ticklength)
    ax[i].tick_params(axis='y', colors=c_axis, length=ticklength)
    ax[i].yaxis.label.set_color(c_axis)
    ax[i].xaxis.label.set_color(c_axis)

plt.tight_layout()

# plt.savefig(os.path.join(plots_savedir, f'Figure_SleepStagesIndices_MainSleeplabVsICU_{variables_to_use}_agree_{agreement}_{icu_day_v}_{statistic}.jpg'), dpi=500)
# plt.savefig(os.path.join(plots_savedir, f'Figure_SleepStagesIndices_MainSleeplabVsICU_{variables_to_use}_agree_{agreement}_{icu_day_v}_{statistic}.svg'))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [23]:
agreement = 'agreement_relaxed'
segments_only_discordant = summary_f_icu.loc[np.any([summary_f_icu[f'hours_sleep_amendsumeffort_{agreement}'] < 0.01, 
                                               summary_f_icu[f'hours_sleep_ecg_nn_{agreement}'] < 0.01],
                                               axis=0), :]

In [24]:
agreement = 'all'
agreement = 'agreement_relaxed'

summary_f_icu[['sleep_hours_ecg_nn', 'sleep_hours_breathing', f'hours_sleep_amendsumeffort_{agreement}']]

,sleep_hours_ecg_nn,sleep_hours_breathing,hours_sleep_amendsumeffort_agreement_relaxed
2,4.375000,0.000000,0.000001
5,3.075000,5.166667,4.366668
8,1.708333,0.000000,0.000001
11,2.125000,7.550833,2.933334
14,4.883333,1.374444,0.775001
...,...,...,...
1217,4.383333,19.083333,0.808334
1220,0.000000,0.508333,0.000001
1223,15.458611,0.000000,0.000001
1226,7.479444,11.254167,3.808334
1229,10.899972,20.671111,2.025001