In [1]:
import pandas as pd
import numpy as np
import os
import sys
%load_ext autoreload
%autoreload 2
%matplotlib widget
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

from icu_sleep_breathing_2020_help_functions import * 

sys.path.append('/home/wolfgang/repos/sleep_research_io/')
from sleep_research_functions import *

pd.options.display.max_rows = 300
pd.options.display.max_columns = 300


font = {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : 8}

font_headers =  {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : 9}

font_subplots =  {'family' : 'sans-serif',
        'weight' : 'bold',
        'size'   : 9}

matplotlib.rc('font', **font)

In [2]:
plots_savedir = '/scr/wolfgang/Dropbox (Partners HealthCare)/SleepInICUandSleeplabPaper/Plots/hypnograms'
if not os.path.exists(plots_savedir):
    os.makedirs(plots_savedir)

In [3]:
[summary_subjects_icu, summary_subjects_sleeplab, 
 summary_days_icu, summary_days_sleeplab] = load_summary_data_with_inclusion_criteria()

summary_subjects_sleeplab = summary_subjects_sleeplab.query("matched_all == 1")
summary_subjects_sleeplab['sex'] = (summary_subjects_sleeplab['sex'] == 'Male').astype(int)

summary_days_sleeplab = summary_days_sleeplab.query("matched_all == 1")
summary_days_sleeplab['sex'] = (summary_days_sleeplab['sex'] == 'Male').astype(int)

/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3338: DtypeWarning: Columns (15,91,92,93,6455,6456,6457,12819,12820,12821,19185,19186,19187,21491,21492,21493,21519,21520,21521,21526,21527,21528,25549,25550,25551,31913,31914,31915,38279,38280,38281,44643,44644,44645,46851,46852,46853,46865,46866,46867,46879,46880,46881,46949,46950,46951,46956,46957,46958,46963,46964,46965,46970,46971,46972,46977,46978,46979,46984,46985,46986,51007,51008,51009,53336,53337,53338,57305,57373,57374,57375,59588,59589,59590,59602,59603,59604,59686,59687,59688,63669,63737,63738,63739,65952,65953,65954,65959,65960,65961,65980,65981,65982,66036,66037,66038,66043,66044,66045,66050,66051,66052,66057,66058,66059,66071,66072,66073,66078,66079,66080,70033,70101,70102,70103,72318,72319,72320,72332,72333,72334,72402,72403,72404,72416,72417,72418,76399,76467,76468,76469,78682,78683,78684,78696,78697,78698,78710,78711,78712,78766,78767,78768,78787,78788,78789,78801,78802,78803,78808,78809,78810,82763,82831,82832,82833,85039,85040,85041,85046,85047,85048,85053,85054,85055,85060,85061,85062,85067,85068,85069,85074,85075,85076,85137,85138,85139,85144,85145,85146,85151,85152,85153,89127,89195,89196,89197,91405,91406,91407,91412,91413,91414,91419,91420,91421,91426,91427,91428,91433,91434,91435,91440,91441,91442,91496,91497,91498,91503,91504,91505,91510,91511,91512,91517,91518,91519,91531,91532,91533,91538,91539,91540,95493,95561,95562,95563,97776,97777,97778,97783,97784,97785,97790,97791,97792,97804,97805,97806,97867,97868,97869,97874,97875,97876,97881,97882,97883,97888,97889,97890,97895,97896,97897,97902,97903,97904,101857,101925,101926,101927,104126,104127,104128,104133,104134,104135,104140,104141,104142,104154,104155,104156,104161,104162,104163,104168,104169,104170,104224,104225,104226,104231,104232,104233,104238,104239,104240,104245,104246,104247,104259,104260,104261,104266,104267,104268,108221,108289,108290,108291,110492,110493,110494,110499,110500,110501,110506,110507,110508,110513,110514,110515,110520,110521,110522,110527,110528,110529,110534,110535,110536,110590,110591,110592,110597,110598,110599,110604,110605,110606,110611,110612,110613,110618,110619,110620,110625,110626,110627,110632,110633,110634,114587,114655,114656,114657,116863,116864,116865,116870,116871,116872,116877,116878,116879,116884,116885,116886,116891,116892,116893,116898,116899,116900,116961,116962,116963,116968,116969,116970,116975,116976,116977,116989,116990,116991,116996,116997,116998,120951,121019,121020,121021,123234,123235,123236,123241,123242,123243,123248,123249,123250,123262,123263,123264,123318,123319,123320,123325,123326,123327,123332,123333,123334,123339,123340,123341,123353,123354,123355,123360,123361,123362,127315,127383,127384,127385,129593,129594,129595,129600,129601,129602,129607,129608,129609,129614,129615,129616,129621,129622,129623,129628,129629,129630,129684,129685,129686,129691,129692,129693,129698,129699,129700,129705,129706,129707,129719,129720,129721,129726,129727,129728,133681,133749,133750,133751,135964,135965,135966,135978,135979,135980,135992,135993,135994,136069,136070,136071,136090,136091,136092,140045,140113,140114,140115,142328,142329,142330,142342,142343,142344,142356,142357,142358,142412,142413,142414,142419,142420,142421,142447,142448,142449,142454,142455,142456,146409,146477,146478,146479,148694,148695,148696,148708,148709,148710,148722,148723,148724,148778,148779,148780,148785,148786,148787,148792,148793,148794,148799,148800,148801,148813,148814,148815,148820,148821,148822,152775,159139,159207,159208,159209,165503) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3338: DtypeWarning: Columns (15,2294,2295,2296,2301,2302,2303,2308,2309,2310,2315,2316,2317,2322,2323,2324,2329,2330,2331,2336,2337,2338,2392,2393,2394,2399,2400,2401,2406,2407,2408,2413,2414,2415,2420,2421,2422,2427,2428,2429,2434,2435,2436) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

# of subjects ICU before inclusion criteria: 108
# of 12-hour segments ICU before inclusion criteria: 1230
# of subjects ICU after inclusion criteria: 102
# of 12-hour segments ICU after inclusion criteria: 1161
24-hour segments: 387
12-hour segments: 774

# of subjects sleeplab before inclusion criteria: 412
# of 12-hour segments sleeplab before inclusion criteria: 412

In [4]:
for agreement in ['all', 'agreement_relaxed', 'disagreement_relaxed', 'agreement', 'disagreement']:
    for modality in ['amendsumeffort', 'ecg_nn']:
        var_n2 = 'perc_N2_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        var_n3 = 'perc_N3_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        var_sum = 'perc_N2N3_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)

        summary_days_icu[var_sum] = summary_days_icu[var_n2] + summary_days_icu[var_n3]
        summary_days_sleeplab[var_sum] = summary_days_sleeplab[var_n2] + summary_days_sleeplab[var_n3]
        
        
for agreement in ['agreement_relaxed', 'agreement', 'all']:
    for modality in ['amendsumeffort', 'ecg_nn']:
        var_sleep = 'hours_sleep_MODALITY_all'.replace('MODALITY', modality) # all overlap sleep
        var_agreeing = 'hours_sleep_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        
        var_discordant = 'hours_discordant_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement) # discordant sleep among overlap sleep
        summary_days_icu[var_discordant] = summary_days_icu[var_sleep] - summary_days_icu[var_agreeing]
        summary_days_sleeplab[var_discordant] = summary_days_sleeplab[var_sleep] - summary_days_sleeplab[var_agreeing]
        
        var_discordant_perc = 'perc_discordant_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement) # discordant sleep among overlap sleep in %
        summary_days_icu[var_discordant_perc] = np.divide(summary_days_icu[var_sleep] - summary_days_icu[var_agreeing], summary_days_icu[var_sleep])
        summary_days_sleeplab[var_discordant_perc] = np.divide(summary_days_sleeplab[var_sleep] - summary_days_sleeplab[var_agreeing], summary_days_sleeplab[var_sleep])

In [5]:
dir_icu = f'/scr/wolfgang/Sleep_And_Breathing/icu_files_step6'
dir_sleeplab = f'/scr/wolfgang/Sleep_And_Breathing/sleeplab_files_step6'
print(os.listdir(dir_icu)[:2])
print(os.listdir(dir_sleeplab)[:2])

staging_cols_icu = ['stage_pred_ecg_nn', 'stage_pred_amendsumeffort'] 
staging_cols_sleeplab = [ 'stage_pred_expert', 'stage_pred_ecg_nn', 'stage_pred_amendsumeffort'] 
var_discordance = 'perc_discordant_ecg_nn_agreement_relaxed'

['icusleep_173.h5', 'icusleep_139.h5']
['psg_airgo_10hz_313.h5', 'psg_airgo_10hz_283.h5']

In [6]:
age_min = 45
age_max = 110
# sex = 0

# summary_days_icu = summary_days_icu.query("day_cat == 'f'")
# sel1_icu = summary_days_icu.query(f"age >= {age_min} & age <= {age_max} & sex == {sex}")
# sel1_sleeplab = summary_days_sleeplab.query(f"age >= {age_min} & age <= {age_max} & sex == {sex}")

summary_days_icu = summary_days_icu.query("day_cat == 'f'")
sel1_icu = summary_days_icu.query(f"age >= {age_min} & age <= {age_max}")
sel1_sleeplab = summary_days_sleeplab.query(f"age >= {age_min} & age <= {age_max}")


sel1_icu = sel1_icu.query(f"{var_discordance} > 0")
sel1_sleeplab = sel1_sleeplab.query(f"{var_discordance} > 0")
sel1_icu.sort_values(by=var_discordance, ascending=True, inplace=True)
sel1_sleeplab.sort_values(by=var_discordance, ascending=True, inplace=True)

print(f"#ICU: {sel1_icu.mrn.unique().shape[0]}")
print(f"#Sleeplab: {sel1_sleeplab.mrn.unique().shape[0]}")

colors = {
    'stage_pred_ecg_nn': 'crimson',
    'stage_pred_amendsumeffort': 'blue',
    'stage_pred_expert': 'orange',
}

#ICU: 79
#Sleeplab: 204

In [7]:
plt.close('all')
%matplotlib inline

for jloc, row in sel1_icu.iterrows():
    
    try:
        filepath = os.path.join(dir_icu, 'icusleep_' + str(row.study_id).zfill(3) + '.h5')
        data, hdr, fs = read_in_routine(filepath)

        print(f"discordance (%): {row[var_discordance]}")

        dt_start = row['timerange'].split(" - ")[0]
        dt_end = row['timerange'].split(" - ")[1]

        data = data.loc[dt_start : dt_end]


        fig, ax = plt.subplots(1, 1, figsize = (7.2, 3))

        for i_version, staging_version in enumerate(staging_cols_icu):
            ax.plot(data[staging_version] + i_version * 0.04, c=colors[staging_version])
            ax.set_title(f'study_id {row.study_id}, sex {row.sex}, age {np.round(row.age)} discordance: {np.round(row[var_discordance], 2)}')
            ax.set_yticks([5, 4, 3, 2, 1])
            ax.set_yticklabels(['W', 'R', 'N1', 'N2', 'N3'])

        plt.savefig(os.path.join(plots_savedir, f"icu_{row.study_id}_{dt_start}.png"),dpi=300)
        plt.savefig(os.path.join(plots_savedir, f"icu_{row.study_id}_{dt_start}.png"), dpi=300)
        
        plt.show()

    except Exception as e:
        print(e)
        continue

In [9]:
plt.close('all')


for jloc, row in sel1_sleeplab.iterrows():
    
    try:
        filepath = os.path.join(dir_sleeplab, 'psg_airgo_10hz_' + str(row.study_id).zfill(3) + '.h5')
        data, hdr, fs = read_in_routine(filepath)

        print(f"discordance (%): {row[var_discordance]}")

        dt_start = row['timerange'].split(" - ")[0]
        dt_end = row['timerange'].split(" - ")[1]

        data = data.loc[dt_start : dt_end]
        fig, ax = plt.subplots(1, 1, figsize = (7.2, 3))

        for i_version, staging_version in enumerate(staging_cols_sleeplab):
            ax.plot(data[staging_version] + i_version * 0.04, c=colors[staging_version])
            ax.set_title(f'study_id {row.study_id},sex {row.sex}, age {np.round(row.age)}, ahi {np.round(row.ahi_expert, 1)}, discordance: {np.round(row[var_discordance], 2)}')
            ax.set_yticks([5, 4, 3, 2, 1])
            ax.set_yticklabels(['W', 'R', 'N1', 'N2', 'N3'])

        plt.savefig(os.path.join(plots_savedir, f"sleeplab_{row.study_id}_{dt_start}.png"), dpi=300)
        plt.savefig(os.path.join(plots_savedir, f"sleeplab_{row.study_id}_{dt_start}.png"), dpi=300)

        plt.show()

    except Exception as e:
        print(e)
        continue

discordance (%): 0.009584660862110649

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.010118041797360814

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.014992501050824504

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.017093999561709792

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.019108265649733194

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.02285713502041092

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.024122803843490637

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.03184712767252343

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.03190183579359474

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.034482753132718355

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.03580901286859206

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.03663003126299908

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.038359782270933965

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.03952568232592521

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.04102561577910823

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.04185020920258773

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.04347820415886427

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.0462850115052358

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.04801096603386023

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.051190468877552076

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.05156536613656734

<ipython-input-9-c9542d52dc06>:16: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, ax = plt.subplots(1, 1, figsize = (7.2, 3))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.05244754144457173

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.05479447551138999

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.057416234976324594

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.0586510160731351

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.06185564459561044

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.06307976332175953

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.06666665531915085

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.06734991496048338

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.0676691627565169

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.06787328474028458

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.07418394984547785

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.07439023301606339

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.07593306420596171

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.07671956454186807

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.07780611053988097

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.08297870221820351

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.08552628202909907

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.0890125025292068

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.0904347637353537

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.09077154176613461

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.09223845774059067

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.09396750432006898

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.09433940904284738

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.09658244934636867

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.09681696071878611

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.09683096545824667

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.09826582779248935

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.10167308597069456

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.10221462987094448

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.10493045184367351

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.10688403473535468

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.10709502965006208

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.10765547148646752

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1111110946502082

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.11170926863376546

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.11728386374034792

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.11753369151436803

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.11995636380069398

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.12051278343196418

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.12261144153921498

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.12396688067758005

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.12406574755173432

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.12415348205596183

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.12499996010639557

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1256281154516351

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.12658226100129874

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1267806051087284

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.12698407860923994

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.13226741879056655

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.13283579710403626

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.13333326666670006

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1344430011099102

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.13519309823353692

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.13636360255447877

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1381294725531847

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.13926171692717104

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.14180204281204556

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.14204543033316525

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.14214459586695388

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.14334860412633893

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.14643301930918354

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1488314663471391

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.15081519280187083

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.15328464915552564

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.15500683319503428

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.15549212744785262

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1564245547891808

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1599378583966722

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.16316636578358015

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.16666655555562965

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.16896549393579388

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.16972473950004777

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1697530549840022

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1699999708571478

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.17190384357031202

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.172077855034602

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1736204295633223

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.17380949897959538

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.17460314688838932

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.17508810692059604

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.17557247887653155

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.17613632360538106

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.17661686270143406

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.17762234781163383

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1783782626735597

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.18160914530322425

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.18194067138425798

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.18273087966324192

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.18339764091174338

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.18383308727513625

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.18506994990918516

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1906004624750509

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.1925819927106432

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.19924803041442254

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2020724760396447

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.20373246586641386

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.20380947722450052

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.20833315972236696

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2093017414835122

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.21455928832523147

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.21518983709876158

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2154420599588453

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2160882871757185

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.21678318040002556

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.21703289548366078

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.22135003679434154

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.222067001888212

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.22267201068696083

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2239263391546615

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.22535198571719112

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.225903532805952

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.22736025571631852

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2305474707040448

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.23216991219971242

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.23349431880947136

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.23589729072987237

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.23684173130252956

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2385444358149161

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.23917132071457908

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2435158080376124

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.24734441626505305

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2520660532067637

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.25263125983419804

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.25294884619415264

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.25577552690913663

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2571022289030291

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2652519049596059

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2653060141608107

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2656247509767959

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.26737963624925626

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2708331979167345

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2725831494295121

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.27549462243629413

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2760562913707677

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.27786493980566285

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2780373052231854

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.27935218148142804

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2806120730946491

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2812029567754063

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2831324277834599

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.283443663558623

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.28721166778742097

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2877262886777572

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.29299351860120315

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.2977527588057148

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.30049252202191457

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.3055999413248112

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.3064513163374358

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.3064747672273784

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.3065324784728774

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.3095558046477838

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.310344720570786

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.31487876198805737

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.31843570082083233

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.34116016444859154

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.34974742175544105

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.3514588300065522

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.35526287742404394

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.3569276463383772

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.36111102513229565

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.3651114729951791

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.38725467416391707

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.39874403791321106

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.4026665378133747

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.40519467890035993

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.41310534248911523

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.4176134939953998

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.4204081117867617

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.4449338423024066

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.45508975495716103

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.4799999113846317

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.4814813991769688

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.48999970600017645

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.5175256451482939

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.5263124653949554

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.5517710269584152

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.58702054507011

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.587155747832753

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.5916660750005917

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.6049542730188882

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.6072185289464469

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.6181433034236362

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.6311187487163465

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.6666653333360001

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.7218541134161289

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.8337180137502042

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.8614317513027596

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

discordance (%): 0.9492183050539196

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [10]:
plt.close('all')

In [11]:
icu_collection = {}

# selections:
study_id = 15
filepath = os.path.join(dir_icu, 'icusleep_' + str(study_id).zfill(3) + '.h5')
data, hdr, fs = read_in_routine(filepath)
dt_start = '2018-10-14 08:00:00'
dt_end = '2018-10-15 08:00:00'

icu_collection[study_id] = data.loc[dt_start : dt_end, staging_cols_icu]


# selections:
study_id = 29
filepath = os.path.join(dir_icu, 'icusleep_' + str(study_id).zfill(3) + '.h5')
data, hdr, fs = read_in_routine(filepath)
dt_start = '2019-01-24 08:00:00'
dt_end = '2019-01-25 08:00:00'

icu_collection[study_id] = data.loc[dt_start : dt_end, staging_cols_icu]


# selections:
study_id = 186
filepath = os.path.join(dir_icu, 'icusleep_' + str(study_id).zfill(3) + '.h5')
data, hdr, fs = read_in_routine(filepath)
dt_start = '2019-11-14 08:00:00'
dt_end = '2019-11-15 08:00:00'

icu_collection[study_id] = data.loc[dt_start : dt_end, staging_cols_icu]

In [12]:
sleeplab_collection = {}

# selections:
study_id = 26
filepath = os.path.join(dir_sleeplab, 'psg_airgo_10hz_' + str(study_id).zfill(3) + '.h5')
data, hdr, fs = read_in_routine(filepath)
sleeplab_collection[study_id] = data[staging_cols_sleeplab]

# selections:
study_id = 390
filepath = os.path.join(dir_sleeplab, 'psg_airgo_10hz_' + str(study_id).zfill(3) + '.h5')
data, hdr, fs = read_in_routine(filepath)
sleeplab_collection[study_id] = data[staging_cols_sleeplab]

# selections:
study_id = 377
filepath = os.path.join(dir_sleeplab, 'psg_airgo_10hz_' + str(study_id).zfill(3) + '.h5')
data, hdr, fs = read_in_routine(filepath)
sleeplab_collection[study_id] = data[staging_cols_sleeplab]

In [46]:
plt.close('all')
import matplotlib.dates as mdates

width_ratio = 24/7
alpha = 0.75
lw = 1

fig, ax = plt.subplots(3, 2, figsize = (7.2, 5), gridspec_kw={'width_ratios': [1, width_ratio]})

col = 0
for i_subject, study_id in enumerate(sleeplab_collection.keys()):

    data = sleeplab_collection[study_id]
    data = data[data.stage_pred_expert > -1]
    
    for i_version, staging_version in enumerate(staging_cols_sleeplab):
        ax[i_subject, col].plot(data[staging_version] + i_version * 0.05, c=colors[staging_version], lw=lw, alpha=alpha)
#     ax[i_subject, col].set_title(f'study_id {row.study_id}, sex {row.sex}, age {np.round(row.age)} discordance: {np.round(row[var_discordance], 2)}')
    ax[i_subject, col].set_yticks([5, 4, 3, 2, 1])
    ax[i_subject, col].set_yticklabels(['W', 'R', 'N1', 'N2', 'N3'])
    ax[i_subject, col].set_ylim([0.8, 5.2])
    ax[i_subject, col].xaxis.set_major_formatter(mdates.DateFormatter('%H'))
    ax[i_subject, col].xaxis.set_major_locator(mdates.HourLocator(interval=3))

col = 1
for i_subject, study_id in enumerate(icu_collection.keys()):

    data = icu_collection[study_id]
    
    for i_version, staging_version in enumerate(staging_cols_icu):
        ax[i_subject, col].plot(data[staging_version] + i_version * 0.05, c=colors[staging_version], lw=lw, alpha=alpha)
#     ax[i_subject, col].set_title(f'study_id {row.study_id}, sex {row.sex}, age {np.round(row.age)} discordance: {np.round(row[var_discordance], 2)}')
    ax[i_subject, col].set_yticks([5, 4, 3, 2, 1])
    ax[i_subject, col].set_yticklabels(['W', 'R', 'N1', 'N2', 'N3'])
    ax[i_subject, col].set_ylim([0.8, 5.2])
    ax[i_subject, col].xaxis.set_major_formatter(mdates.DateFormatter('%H'))

    
for ax_tmp in ax.flatten():
    ax_tmp.spines["right"].set_visible(False)
    ax_tmp.spines["top"].set_visible(False)

ax[2, 0].set_xlabel('Daytime (hour)')
ax[2, 1].set_xlabel('Daytime (hour)')

ax[0, 0].text(0.5, 1.6, 'Sleeplab (overnight)', ha='center', fontweight='bold', transform=ax[0, 0].transAxes)
ax[0, 1].text(0.5, 1.6, 'ICU (24-hours)', ha='center', fontweight='bold', transform=ax[0, 1].transAxes)

ax[0, 1].text(0, 1.05, '72-year-old male\ndiagnosis: hypotension, shock\nHRV and breathing models concordance 99%', transform=ax[0, 1].transAxes)
ax[1, 1].text(0, 1.05, '69-year-old male\ndiagnosis: gastrointestinal bleeding\nHRV and breathing models concordance 76%', transform=ax[1, 1].transAxes)
ax[2, 1].text(0, 1.05, '79-year-old female\ndiagnosis: hypoxemic respiratory failure, shock\nHRV and breathing models concordance 56% ', transform=ax[2, 1].transAxes)

ax[0, 0].text(0, 1.05, '61-year-old female\nFull night CPAP titration, AHI 3\nHRV-breathing concord. 97%', transform=ax[0, 0].transAxes)
ax[1, 0].text(0, 1.05, '79-year-old female\nSplit Night, AHI D./T. 32/14\nHRV-breathing concord. 86%', transform=ax[1, 0].transAxes) # AHI diagnostic 32, AHI titration 14
ax[2, 0].text(0, 1.05, '76-year-old male\nSplit Night, AHI D./T. 10/6\nHRV-breathing concord. 45%', transform=ax[2, 0].transAxes)

ax[0, 0].legend(['Hypnogram sleep expert', 'Hypnogram HRV-based model', 'Hypnogram breathing-based model'], loc=(0, 1.77), frameon=False, ncol=3)

plt.subplots_adjust(hspace=0.85, wspace=0.17, left=0.04, right=0.99, bottom=0.08, top=0.83)

plt.savefig(os.path.join(plots_savedir, f'hypnograms_ICU_sleeplab_widthr{width_ratio}.jpg'), dpi=600)
plt.savefig(os.path.join(plots_savedir, f'hypnograms_ICU_sleeplab_widthr{width_ratio}.svg'))
plt.savefig(os.path.join(plots_savedir, f'hypnograms_ICU_sleeplab_widthr{width_ratio}.tiff'), dpi=600)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [120]:
ax[0, 0].legend

In [ ]:
ax[0, 0].legend

In [85]:
summary_subjects_icu.loc[np.isin(summary_subjects_icu.study_id, [15, 29, 186])]

,inclusion_subject,study_id,mrn,enrolled,age,bmi,sex,osa_diagnosis_yn,osa_diagnosis,icu_mortality,3_month_mortality,icu_los,hospital_los,icu_readmission,diagnosis,lvef,date_of_echo,chf,copd,med_surg,CCI,CCI_weighted,Belt_Length,d1_timerange,d1_hr_mean,d1_hr_std,d1_hr_median,d1_hr_q25,d1_hr_q75,d1_hr_sda,d1_hr_asd,d1_spo2_mean,d1_spo2_std,d1_spo2_median,d1_spo2_q25,d1_spo2_q75,d1_spo2_sda,d1_spo2_asd,d1_spo2_airgo_mean,d1_spo2_airgo_std,d1_spo2_airgo_median,d1_spo2_airgo_q25,d1_spo2_airgo_q75,d1_spo2_airgo_sda,d1_spo2_airgo_asd,d1_spo2_clean_mean,d1_spo2_clean_std,d1_spo2_clean_median,d1_spo2_clean_q25,d1_spo2_clean_q75,d1_spo2_clean_sda,d1_spo2_clean_asd,d1_spo2_airgo_clean_mean,d1_spo2_airgo_clean_std,d1_spo2_airgo_clean_median,d1_spo2_airgo_clean_q25,d1_spo2_airgo_clean_q75,d1_spo2_airgo_clean_sda,d1_spo2_airgo_clean_asd,d1_edw_bp_systolic_mean,d1_edw_bp_systolic_std,d1_edw_bp_systolic_median,d1_edw_bp_systolic_q25,d1_edw_bp_systolic_q75,d1_edw_bp_diastolic_mean,d1_edw_bp_diastolic_std,d1_edw_bp_diastolic_median,d1_edw_bp_diastolic_q25,d1_edw_bp_diastolic_q75,d1_edw_bp_map_mean,d1_edw_bp_map_std,d1_edw_bp_map_median,d1_edw_bp_map_q25,d1_edw_bp_map_q75,d1_cpc_hfc_lfc_ratio_mean,d1_cpc_hfc_lfc_ratio_std,d1_cpc_hfc_lfc_ratio_median,d1_cpc_hfc_lfc_ratio_q25,d1_cpc_hfc_lfc_ratio_q75,d1_cpc_hfc_mean,d1_cpc_hfc_std,d1_cpc_hfc_median,d1_cpc_hfc_q25,d1_cpc_hfc_q75,d1_cpc_hfc_sum,d1_cpc_lfc_mean,d1_cpc_lfc_std,d1_cpc_lfc_median,d1_cpc_lfc_q25,d1_cpc_lfc_q75,d1_cpc_lfc_sum,d1_hrv_nn_mean,d1_hrv_nn_std,d1_hrv_nn_median,d1_hrv_nn_q25,d1_hrv_nn_q75,d1_hrv_nn_sda,d1_hrv_nn_asd,d1_hco3_arterial_mean,d1_hco3_arterial_min,d1_hco3_arterial_max,d1_pco2_arterial_mean,d1_pco2_arterial_min,d1_pco2_arterial_max,d1_po2_arterial_mean,d1_po2_arterial_min,d1_po2_arterial_max,d1_ph_arterial_mean,d1_ph_arterial_min,d1_ph_arterial_max,d1_oxygen_flow_rate_max,d1_sofa_score_mean,d1_sofa_score_min,d1_sofa_score_max,d1_ahi_va_a3,d1_ahi_va_a3_ss,d1_ahi_vb_a3,d1_ahi_vb_a3_ss,d1_ahi_ro_a3,d1_ahi_ro_a3_ss,d1_ahi_rsr_a3,d1_ahi_rsr_a3_ss,d1_ahi_expert,d1_ahi_va_a3_ss_aswti,d1_ahi_vb_a3_ss_aswti,d1_ahi_ro_a3_ss_aswti,d1_ahi_rsr_a3_ss_aswti,d1_hypoxic_burden_va_a3,d1_hypoxic_burden_va_a3_ss,d1_hypoxic_burden_vb_a3,d1_hypoxic_burden_vb_a3_ss,d1_hypoxic_burden_ro_a3,d1_hypoxic_burden_ro_a3_ss,d1_hypoxic_burden_rsr_a3,d1_hypoxic_burden_rsr_a3_ss,d1_hypoxic_burden_expert,d1_hypoxic_burden_va_a3_ss_aswti,d1_hypoxic_burden_vb_a3_ss_aswti,d1_hypoxic_burden_ro_a3_ss_aswti,d1_hypoxic_burden_rsr_a3_ss_aswti,d1_hypoxia_LDI,d1_hypoxia_SDI,d1_hypoxia_TDI,d1_hypoxia_pu90,d1_hypoxia_ss_LDI,d1_hypoxia_ss_SDI,d1_hypoxia_ss_TDI,d1_hypoxia_ss_pu90,d1_hypoxia_ss_aswti_LDI,d1_hypoxia_ss_aswti_SDI,...,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_mean,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_std,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_median,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_q25,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_q75,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_sda,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_asd,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_mean,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_std,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_median,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_q25,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_q75,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_sda,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_asd,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_mean,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_std,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_median,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_q25,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_q75,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_sda,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_asd,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_mean,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_std,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_median,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_q25,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_q75,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_sda,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_asd,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_mean,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_std,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_median,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_q25,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_q75,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_sda,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_asd,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_mean,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_std,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_median,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_q25,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_q75,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_sda,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_asd,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_mean,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_std,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_median,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_q25,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_q75,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_sda,f9_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_std,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_median,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_asd,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_mean,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_std,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_median,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_q25,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_q75,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_sda,f9_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_asd,airgo_available_h_sum,ecg_available_sum,airgo_ecg_available_sum
9,1,15,1479357.0,2018-10-11,72.0,20.86,1.0,no,0.0,0.0,0.0,6.0,22.0,no,"hypotension, shock",61,2018-10-11 00:00:00,1,0,1,0.0,0.0,83.0,2018-10-10 08:00:00 - 2018-10-10 20:00:00,68.295326,8.303696,67.000,62.875,72.125,5.965254,5.446293,97.689476,0.915672,98.0,97.0,98.0,0.697591,0.538155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.689476,0.915672,98.0,97.0,98.0,0.697591,0.538155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8887854814529419,0.2862340807914734,0.8208333253860474,0.708333,1.016667,0.091349,0.269716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,5.50,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.851028,126.401806,92.295111
14,1,29,6545068.0,2019-01-23,69.0,22.23,1.0,no,0.0,0.0,0.0,6.0,8.0,no,aortic dissection,none,-,0,0,0,1.0,1.0,74.0,2019-01-22 08:00:00 - 2019-01-22 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Series([], Freq: 100L, Name: hrv_nn, dtype: fl...","Series([], Freq: 100L, Name: hrv_nn, dtype: fl...","Series([], Freq: 100L, Name: hrv_nn, dtype: fl...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.111806,80.144444,38.298472
104,1,186,6807388.0,2019-11-12,79.0,32.25,0.0,no,0.0,0.0,NaN,6.0,11.0,no ?,aortic dissection,71,2019-11-13 00:00:00,0,0,0,1.0,1.0,90.0,2019-11-11 08:00:00 - 2019-11-11 20:00:00,67.378975,6.411902,66.375,64.000,69.000,3.749119,4.020441,94.025726,1.640553,94.0,93.0,95.0,1.469398,0.707514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.025726,1.640553,94.0,93.0,95.0,1.469398,0.707514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126.5,14.849242,126.5,121.25,131.75,62.0,4.24264,62.0,60.5,63.5,83.5,7.778174,83.5,80.75,86.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.861095,0.130627,0.887500,0.850000,0.933333,0.058120,0.108250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,3.25,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.421361,104.142806,68.920806

In [86]:
summary_subjects_sleeplab.loc[np.isin(summary_subjects_sleeplab.study_id, [26, 390, 387])]

,study_id,mrn,age,sex,cci,matched_all,matched_ahi_0_5,matched_ahi_5_15,matched_ahi_15_30,matched_ahi_30_100,matched_ahi_15_100,n1_timerange,n1_hr_mean,n1_hr_std,n1_hr_median,n1_hr_q25,n1_hr_q75,n1_hr_sda,n1_hr_asd,n1_spo2_mean,n1_spo2_std,n1_spo2_median,n1_spo2_q25,n1_spo2_q75,n1_spo2_sda,n1_spo2_asd,n1_spo2_airgo_mean,n1_spo2_airgo_std,n1_spo2_airgo_median,n1_spo2_airgo_q25,n1_spo2_airgo_q75,n1_spo2_airgo_sda,n1_spo2_airgo_asd,n1_spo2_clean_mean,n1_spo2_clean_std,n1_spo2_clean_median,n1_spo2_clean_q25,n1_spo2_clean_q75,n1_spo2_clean_sda,n1_spo2_clean_asd,n1_spo2_airgo_clean_mean,n1_spo2_airgo_clean_std,n1_spo2_airgo_clean_median,n1_spo2_airgo_clean_q25,n1_spo2_airgo_clean_q75,n1_spo2_airgo_clean_sda,n1_spo2_airgo_clean_asd,n1_edw_bp_systolic_mean,n1_edw_bp_systolic_std,n1_edw_bp_systolic_median,n1_edw_bp_systolic_q25,n1_edw_bp_systolic_q75,n1_edw_bp_diastolic_mean,n1_edw_bp_diastolic_std,n1_edw_bp_diastolic_median,n1_edw_bp_diastolic_q25,n1_edw_bp_diastolic_q75,n1_edw_bp_map_mean,n1_edw_bp_map_std,n1_edw_bp_map_median,n1_edw_bp_map_q25,n1_edw_bp_map_q75,n1_cpc_hfc_lfc_ratio_mean,n1_cpc_hfc_lfc_ratio_std,n1_cpc_hfc_lfc_ratio_median,n1_cpc_hfc_lfc_ratio_q25,n1_cpc_hfc_lfc_ratio_q75,n1_cpc_hfc_mean,n1_cpc_hfc_std,n1_cpc_hfc_median,n1_cpc_hfc_q25,n1_cpc_hfc_q75,n1_cpc_hfc_sum,n1_cpc_lfc_mean,n1_cpc_lfc_std,n1_cpc_lfc_median,n1_cpc_lfc_q25,n1_cpc_lfc_q75,n1_cpc_lfc_sum,n1_hrv_nn_mean,n1_hrv_nn_std,n1_hrv_nn_median,n1_hrv_nn_q25,n1_hrv_nn_q75,n1_hrv_nn_sda,n1_hrv_nn_asd,n1_hco3_arterial_mean,n1_hco3_arterial_min,n1_hco3_arterial_max,n1_pco2_arterial_mean,n1_pco2_arterial_min,n1_pco2_arterial_max,n1_po2_arterial_mean,n1_po2_arterial_min,n1_po2_arterial_max,n1_ph_arterial_mean,n1_ph_arterial_min,n1_ph_arterial_max,n1_oxygen_flow_rate_max,n1_sofa_score_mean,n1_sofa_score_min,n1_sofa_score_max,n1_ahi_va_a3,n1_ahi_va_a3_ss,n1_ahi_vb_a3,n1_ahi_vb_a3_ss,n1_ahi_ro_a3,n1_ahi_ro_a3_ss,n1_ahi_rsr_a3,n1_ahi_rsr_a3_ss,n1_ahi_expert,n1_ahi_va_a3_ss_aswti,n1_ahi_vb_a3_ss_aswti,n1_ahi_ro_a3_ss_aswti,n1_ahi_rsr_a3_ss_aswti,n1_hypoxic_burden_va_a3,n1_hypoxic_burden_va_a3_ss,n1_hypoxic_burden_vb_a3,n1_hypoxic_burden_vb_a3_ss,n1_hypoxic_burden_ro_a3,n1_hypoxic_burden_ro_a3_ss,n1_hypoxic_burden_rsr_a3,n1_hypoxic_burden_rsr_a3_ss,n1_hypoxic_burden_expert,n1_hypoxic_burden_va_a3_ss_aswti,n1_hypoxic_burden_vb_a3_ss_aswti,n1_hypoxic_burden_ro_a3_ss_aswti,n1_hypoxic_burden_rsr_a3_ss_aswti,n1_hypoxia_LDI,n1_hypoxia_SDI,n1_hypoxia_TDI,n1_hypoxia_pu90,n1_hypoxia_ss_LDI,n1_hypoxia_ss_SDI,n1_hypoxia_ss_TDI,n1_hypoxia_ss_pu90,n1_hypoxia_ss_aswti_LDI,n1_hypoxia_ss_aswti_SDI,n1_hypoxia_ss_aswti_TDI,n1_hypoxia_ss_aswti_pu90,n1_self_similarity_sleep,n1_self_similarity_sleep_q50,n1_self_similarity_sleep_q75,n1_self_similarity_apnea,n1_self_similarity_apnea_q50,n1_self_similarity_apnea_q75,n1_opioids_sum,n1_benzos_sum,n1_antipsychotics_sum,n1_dex_studydrug_sum,...,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_mean,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_std,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_median,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_q25,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_q75,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_sda,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N3_asd,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_mean,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_std,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_median,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_q25,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_q75,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_sda,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2_asd,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_mean,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_std,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_median,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_q25,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_q75,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_sda,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N1_asd,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_mean,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_std,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_median,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_q25,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_q75,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_sda,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_R_asd,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_mean,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_std,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_median,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_q25,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_q75,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_sda,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_W_asd,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_mean,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_std,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_median,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_q25,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_q75,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_sda,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_N2N3_asd,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_mean,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_std,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_median,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_q25,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_q75,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_sda,n1_hrv_sd1sd2_stagewise_agrelaxed_amendsumeffort_S_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_std,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_median,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N3_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_std,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_median,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_std,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_median,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N1_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_std,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_median,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_R_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_std,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_median,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_W_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_std,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_median,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_N2N3_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_std,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_median,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_ecg_nn_S_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_std,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_median,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N3_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_std,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_median,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_std,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_median,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N1_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_std,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_median,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_R_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_std,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_median,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_W_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_std,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_median,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_N2N3_asd,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_mean,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_std,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_median,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_q25,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_q75,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_sda,n1_hrv_sd1sd2_stagewise_disrelaxed_amendsumeffort_S_asd,airgo_available_h_sum,ecg_available_sum,airgo_ecg_available_sum
22,26,2964631.0,61.189,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2019-02-01 20:00:00 - 2019-02-02 08:00:00,63.453884,5.366163,63.0,60.0,66.0,4.201375,2.918281,95.543678,3.738056,95.0,95.0,96.0,1.298246,1.619965,95.568474,2.823444,95.0,95.0,96.0,0.929383,1.289019,95.624329,1.194013,95.0,95.0,96.0,0.947548,0.673974,95.622238,1.192691,95.0,95.0,96.0,0.947046,0.673373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.039827,2.334276,-1.879164,-4.226064,-0.383040,0.511018,0.862112,0.249107,0.079262,0.551445,125169.132812,18.380011,35.591045,1.571618,0.204438,18.057159,4502018.0,0.943073,0.080084,0.950,0.895,0.995,0.058883,0.051846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.982190,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,6.699191,3.932134,10.631324,0.000000,7.112231,3.783102,10.895333,0.000000,7.250307,3.847102,11.097409,0.000000,0.000004,0.068762,0.078710,0,0,0,NaN,NaN,NaN,NaN,...,0.380011,0.130066,0.353240,0.255830,0.448506,0.125102,0.021552,0.409172,0.177549,0.340217,0.295617,0.477605,0.142962,0.070285,0.434209,0.231096,0.345953,0.267879,0.548176,0.220552,0.038828,0.313802,0.172892,0.259927,0.180678,0.399715,0.147756,0.067343,0.304315,0.142872,0.258376,0.210680,0.324396,0.141254,0.005246,0.406001,0.173256,0.341430,0.293748,0.472261,0.139788,0.066985,0.393156,0.190230,0.334690,0.268634,0.478698,0.167143,0.070620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.362092,0.129247,0.391056,0.279847,0.500891,0.098548,0.048342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.344653,0.137859,0.346460,0.189699,0.492215,0.114428,0.044704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.333067,0.148860,0.328661,0.172864,0.498286,0.118207,0.040032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.333067,0.148860,0.328661,0.172864,0.498286,0.118207,0.040032,0.314992,0.143532,0.294789,0.175410,0.454690,0.122712,0.038150,6.934667,7.000139,6.934667
352,387,1864323.0,66.195,1,5.0,1.0,1.0,0.0,0.0,0.0,0.0,2019-11-16 20:00:00 - 2019-11-17 08:00:00,50.702347,5.521657,51.0,49.0,53.0,3.452363,2.580914,89.391678,8.609368,91.0,88.0,92.0,5.608833,2.516322,89.383293,8.619198,91.0,88.0,92.0,5.614416,2.509338,90.413322,2.240269,91.0,89.0,92.0,2.007367,0.909502,90.406952,2.240029,91.0,89.0,92.0,2.006519,0.909605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.659400,1.348256,-2.840286,-3.536739,-2.041243,0.572492,0.549550,0.416176,0.235649,0.682501,137621.953125,16.470871,24.102314,6.612607,2.429670,18.927591,3959449.0,1.161909,0.131516,1.165,1.105,1.235,0.051063,0.120644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.284464,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.5,0.0,0.0,0.0,0.0,8.983330,9.965882,18.949213,0.289926,10.789471,9.999997,20.789468,0.504314,10.061347,10.797543,20.858891,0.497715,0.000007,0.272710,0.290572,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.188288,0.092857,1.195793,1.144099,1.251009,0.092622,0.030318,1.098364,0.172639,1.153586,0.978437,1.217799,0.162602,0.043991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.993000,0.113946,1.001823,0.926313,1.081762,0.107792,0.045966,1.188288,0.092857,1.195793,1.144099,1.251009,0.092622,0.030318,1.157761,0.132762,1.188078,1.105302,1.240408,0.126131,0.036358,1.115499,0.136376,1.099624,1.017652,1.220265,0.126945,0.038126,0.996076,0.092143,1.009041,0.955443,1.061822,0.087901,0.023454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.884516,0.145353,0.899515,0.768964,0.973865,0.130280,0.032794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.080686,0.136371,1.059462,0.993384,1.158130,0.129900,0.035797,1.063940,0.147720,1.050999,0.973831,1.145738,0.135849,0.037894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.164284,0.081171,1.182539,1.085988,1.231964,0.066828,0.023008,1.099746,0.177332,1.093579,0.974370,1.243281,0.161192,0.039978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.012076,0.100292,1.019181,0.964642,1.069051,0.088656,0.031813,1.164284,0.081171,1.182539,1.085988,1.231964,0.066828,0.023008,1.110662,0.166814,1.121501,0.998920,1.235580,0.154761,0.040379,7.201444,6.777222,6.759028
355,390,5481509.0,77.986,0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,2019-11-17 20:00:00 - 2019-11-18 08:00:00,56.694645,10.309443,58.0,56.0,60.0,8.119257,3.421882,90.543213,15.750191,93.0,92.0,95.0,12.862973,3.657587,90.524261,15.785202,93.0,92.0,95.0,12.890685,3.672232,93.236900,2.093619,93.0,92.0,95.0,1.666650,1.137743,93.230309,2.096628,93.0,92.0,95.0,1.669373,1.140583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.266397,3.048060,-3.095326,-4.194347,-0.856714,0.441538,0.803145,0.113267,0.006075,0.428242,112111.460938,40.408607,175.829758,1.610016,0.008479,7.493605,10260190.0,1.020821,0.098610,1.030,0.990,1.070,0.043697,0.078883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.187570,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39.9,0.0,0.0,0.0,0.0,16.438414,9.132452,25.570866,0.027223,18.974829,9.136029,28.110857,0.033610,18.316737,10.400181,28.716918,0.030784,0.000004,0.204152,0.322626,0,0,0,NaN,NaN,NaN,NaN,...,1.256307,0.218845,1.311949,1.094353,1.417077,0.212131,0.075828,0.929231,0.409137,1.012660,0.508627,1.302391,0.378578,0.140460,0.581530,0.292042,0.511692,0.367018,0.749880,0.267278,0.093249,1.193567,0.277911,1.204744,0.970747,1.426113,0.194075,0.148938,0.598807,0.259367,0.530620,0.422121,0.793880,0.225629,0.100543,0.976337,0.404191,1.067511,0.620315,1.330342,0.374368,0.142681,0.870736,0.416385,0.870978,0.466751,1.253587,0.383233,0.136765,1.014772,0.397500,1.263993,0.515591,1.338577,0.382776,0.032050,1.034151,0.278279,1.083175,0.794706,1.189012,0.177192,0.056394,0.96398,0.186597,0.881964,0.797304,1.131018,0.106982,0.077703,1.256440,0.209910,1.305207,1.106491,1.428383,0.181059,0.125989,0.561064,0.22693,0.481597,0.398413,0.622764,0.195237,0.04756,1.025686,0.335704,1.128481,0.687804,1.320815,0.183073,0.115691,1.120751,0.288457,1.160820,0.936911,1.359831,0.180294,0.115987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.867982,0.421752,0.832641,0.436990,1.282177,0.412064,0.054580,1.095320,0.307543,1.208086,0.840931,1.366966,0.222803,0.133365,1.105651,0.219587,1.122172,0.861872,1.219093,0.15953,0.072897,0.986271,0.264803,1.069556,0.831735,1.141314,0.293867,0.039419,0.867982,0.421752,0.832641,0.436990,1.282177,0.412064,0.054580,0.975119,0.378866,1.086233,0.609686,1.330953,0.333297,0.108899,7.740917,7.153889,7.153889


MRN: 2964631.0  
Air026  
/media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Burgess~ Chery_46639851-2530-4db3-b4fd-0c5e8dca3ec2  

MRN: 2560550.0  
Air377  
/media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Snyder~ AmyBet_67bfad41-f8fc-4109-876c-6ee0c9995a44  

MRN: 1864323.0  
Air387  
/media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Davis~ Lawrenc_30f7bb7f-8ab9-4207-8c15-13e6d7f6514a