In [1]:
import pandas as pd
import numpy as np
import os

### Covid Sedation Project
create medication dictionary

In [2]:
medication_dictionary_output_path = '/media/mad3/Projects/Wolfgang/Covid19_Sedation/medication_dictionary.csv'

meds_to_study = {
'Quetiapine': [2183, 21824],
'Haloperidol': [3585, 3584, 10162, 3578, 3581, 3583, 4004082788],
'Olanzapine': [28159, 38263, 21057, 17936],
'Risperidone': [35686, 35687, 17377],
'Ziprasidone': [33175],
'Aripiprazole': [76823, 70306, 36438, 34370],
'Chlorpromazine': [40042091, 4004081579, 4004081580, 4004081581, 4004082787, 4004081582, 1649, 1653, 1654, 1656],
'Valproic acid': [40042145, 4004081267, 4004081266, 20887, 127503, 8429, 27631, 2551, 2553, 34418, 81426],
'Phenobarbital': [6215, 6212, 6219, 6220, 6004200028, 40042138, 4004082809, 4004082808, 4004082017, 6221, 6224],
'Gabapentin': [18309, 29169, 18308, 160018, 18307, 40042051, 5004201003],
'Ketamine': [4236, 4237, 4238, 701576, 40042242, 701114, 702142, 40042224, 700038, 40042151, 1004200015],
'Dexmedetomidine': [27103, 181527, 7006048, 6004080205, 4004081395, 1004200072, 40042097],
'Clonidine': [27505, 27506, 27507, 1755, 1756],
'Isoflurane': [127796],
'Propofol': [11150, 701735, 40042190, 40042189, 60042003, 701734],
'Midazolam': [172732, 172731, 10608, 700622, 709150, 6004200010, 40042228, 7005111, 700041, 1004080126, 1004080124, 1004080127, 1004080125, 1004200076, 40042042, 701800, 7000097, 40042195],
'Diazepam': [2404, 2405, 2402, 114047, 2401, 106278],
'Lorazepam': [4572, 4573, 10467, 4571, 4004229, 40042153],
'Clonazepam': [35626, 9637, 9638, 700122, 700994],
'Alprazolam': [324, 325],
'Chlordiazepoxide': [1623, 1624],
'Methadone': [4953, 10546, 15996, 4954, 4952],
'Fentanyl': [709111, 3037,27908, 41382, 27905, 27906, 27907, 700629, 701610, 700646, 40042232, 700001, 701220, 40042108, 702138, 5004200025],
'Hydromorphone': [192972, 3757, 10224, 700102, 701604, 709542, 702131, 702146, 162068, 127812, 126597, 119834, 10225, 3760, 3758, 118595, 10226, 701612, 700660, 702147, 701609, 40042244, 40042056, 40042117],
'Morphine': [29464, 15852, 770099, 27392, 30851, 5176, 5168, 27390, 5178, 5169, 116036, 5170, 160280, 116697, 5172, 160281, 185637, 5173, 116966, 116040, 5175, 700618, 702151, 40042230, 159236, 701606, 701804, 40042126, 709538, 702141, 40042125, 40042295],
'Oxycodone': [87822, 10812, 10814, 10813],
'Hydrocodone': [34505, 70832],
'Tramadol': [14632],
'Meperidine': [123225, 4903, 4904, 119043, 40042120],
'Rocuronium': [700794, 707434, 95811, 125950, 701594, 40042074, 701929, 40042199],
'Vecuronium': [700762, 701741, 6004200012, 11634, 1004200084, 40042066, 700485, 701739, 701740, 4004082804, 500420052, 40042279],
'Aprepitant': [35490, 35489, 196340, 35488, 4004080346, 40042322, 4004289068, 701147],
'Atazanavir': [36148, 36150, 77648, 3004080577],
'Cobicistat': [179628],
'Indinavir': [16645],
'Letermovir': [196330, 196332, 196331, 196333, 2004080317],
'Lopinovir_Ritonavir': [708003, 43391, 28929],
'Nelfinavir': [20032],
'Ritonavir': [100995, 16440],
'Ciprofloxacin': [108130, 25118, 108132, 25519, 22988, 40042018],
'Clarithromycin': [12885, 9616, 9617, 2899],
'Erythromycin': [116538, 2899, 40042021, 4004081188, 4004081189, 4004082351, 2903],
'Fluconazole': [14232, 10044, 13577, 10045, 10049, 10050, 40042022, 700483],
'Itraconazole': [19928, 10364],
'Posaconazole': [172781, 173183, 4004088000],
'Voriconazole': [33010, 33009, 38103, 33008, 40042037, 4004081236, 4004081237],
'Cyclosporine': [9706, 9708, 9707, 9705, 40042093, 4004081591, 4004081593, 28843, 28844, 28842],
'Diltiazem': [701780, 701781, 2475, 701783, 97252, 2476, 700616, 40042226, 27480, 29272, 404081773, 4004081772, 40042099, 5004200021],
'Verapamil': [8528, 8527, 8530, 11640, 8531],
'Dronedarone': [98329],
'Fluvoxamine': [10085],
'Nefazodone': [13444, 13445],
'Imatinib': [32979, 701917],
}
    
meds_to_study_new = {}
for key in meds_to_study:
    meds_to_study_new[key.lower()] = meds_to_study[key]
meds_to_study = meds_to_study_new

meds_to_study_df = pd.DataFrame(columns = ['med_name', 'erx'])
i = 0
for key in meds_to_study.keys():
    values = meds_to_study[key]
    for value in values:
        i += 1
        meds_to_study_df.loc[i, 'med_name'] = key
        meds_to_study_df.loc[i, 'erx'] = value
        
meds_to_study_df.to_csv(medication_dictionary_output_path, index=False)

meds_to_study_df

        med_name     erx
1     quetiapine    2183
2     quetiapine   21824
3    haloperidol    3585
4    haloperidol    3584
5    haloperidol   10162
..           ...     ...
331  fluvoxamine   10085
332   nefazodone   13444
333   nefazodone   13445
334     imatinib   32979
335     imatinib  701917

[335 rows x 2 columns]

### Covid Delirium Project

In [4]:
medication_dictionary_output_path = '/scr/wolfgang/Covid19_Delirium/medication_dictionary.csv'

meds_to_study_df = pd.DataFrame(columns = ['med_name'])
meds_to_study_df['med_name'] = ['Quetiapine',
'Haloperidol',
'Olanzapine',
'Risperidone',
'Ziprasidone',
'Aripiprazole',
'Chlorpromazine',
'Valproic acid',
'Phenobarbital',
'Gabapentin',
'Ketamine',
'Dexmedetomidine',
'Clonidine',
'Isoflurane',
'Propofol',
'Midazolam',
'Diazepam',
'Lorazepam',
'Clonazepam',
'Alprazolam',
'Chlordiazepoxide',
'Methadone',
'Fentanyl',
'Hydromorphone',
'Morphine',
'Oxycodone',
'Hydrocodone',
'Tramadol',
'Meperidine',
'Cisatracurium',
'Rocuronium',
'Vecuronium',
'Modafinil',
'Methylphenidate',
'Amantadine',
'Caffeine',
'Melatonin']
meds_to_study_df['med_name'] = [x.lower() for x in meds_to_study_df['med_name']]
meds_to_study_df.to_csv(medication_dictionary_output_path, index=False)

In [27]:
if 0:
    cohort_path = '/scr/wolfgang/Covid19_Delirium/cohort.csv'
    cohort = pd.read_csv(cohort_path)
    cohort.rename({'Admission': 'AdmissionDTS', 'Discharge': 'DischargeDTS'}, axis=1, inplace=True)
    cohort = cohort.iloc[:, :6]
    cohort.to_csv(cohort_path, index=False)

In [28]:
cohort

    PatientID  study_id      mrn AdmissionDTS DischargeDTS  Weight
0   Z12922609         1  5474581   2020-04-15   2020-05-03   70.10
1    Z6922426         2  4700402   2020-04-06   2020-04-30  108.50
2    Z6403204         3  3524929   2020-04-06   2020-05-05   68.60
3   Z17755458         4  6916790   2020-04-02   2020-05-15   67.40
4   Z12002271         5  4055351   2020-04-06   2020-05-09   77.60
..        ...       ...      ...          ...          ...     ...
62  Z17790585        63  6963412   2020-05-30   2020-07-31   89.55
63  Z10153042        64  3358971   2020-05-24   2020-09-28  101.60
64  Z17777920        65  6948537   2020-05-15   2020-06-12   75.95
65   Z7513203        66  5496087   2020-06-03   2020-06-25   79.90
66  Z17796471        67  6971196   2020-06-10   2020-06-22   66.90

[67 rows x 6 columns]

### equivalency tables:

In [1]:
version = 'covid_hypoxia'
# like covid_sedation but dexmedetomidine and propofol are used as benzos as well.
project_dir = '/scr/wolfgang/Covid19_Sedation'



opioids = [
    ['fentanyl_parenteral', 1, np.nan, np.nan],
    ['fentanyl_transdermal', 1, np.nan, np.nan],
    ['hydromorphone_oral', 0.1/7.5, np.nan, np.nan],
    ['hydromorphone_parenteral', 0.1/1.5, np.nan, np.nan],
    ['hydrocodone_oral', 0.1/30, np.nan, np.nan],
    ['morphine_oral', 0.1/30, np.nan, np.nan],
    ['morphine_parenteral', 0.1/10, np.nan, np.nan],
    ['oxycodone_oral', 0.1/20, np.nan, np.nan],
    ['meperidine_oral', 0.1/300, np.nan, np.nan],
    ['meperidine_parenteral', 0.1/100, np.nan, np.nan],
    ['codeine_oral', 0.1/200, np.nan, np.nan],
    ['tramadol_oral', 0.1/120, np.nan, np.nan],
    ['methadone_oral', 4 * 0.1 / 30, 0, 20],
    ['methadone_oral', 8 * 0.1 / 30, 20, 40],
    ['methadone_oral', 10 * 0.1 / 30, 40, 60],
    ['methadone_oral', 12 * 0.1 / 30, 60, 100000],
    ['methadone_parenteral', 4 * 0.1 / 30, 0, 20],
    ['methadone_parenteral', 8 * 0.1 / 30, 20, 40],
    ['methadone_parenteral', 10 * 0.1 / 30, 40, 60],
    ['methadone_parenteral', 12 * 0.1 / 30, 60, 100000],
    ]

opioids = pd.DataFrame(opioids)
opioids.columns = ['med', 'equivalency_factor', 'tdd_min', 'tdd_max']
opioids['tdd_dependent'] = np.nan
for jloc, row in opioids.iterrows():
    opioids.loc[jloc, 'tdd_dependent'] = int('methadone' in row['med'])
opioids['category'] = ['opioids'] * opioids.shape[0]

benzos = [
        ['midazolam_parenteral', 1, np.nan, np.nan],
        ['clonazepam_oral', 1/0.125, np.nan, np.nan],
        ['lorazepam_parenteral', 2, np.nan, np.nan],
        ['lorazepam_oral', 2, np.nan, np.nan],
        ['diazepam_parenteral', 1/1.25, np.nan, np.nan],
        ['diazepam_oral', 1/1.25, np.nan, np.nan],
        ['phenobarbital_parenteral', 1/7.5, np.nan, np.nan],
        ['phenobarbital_oral', 1/7.5, np.nan, np.nan],
        ['chlordiazepoxide_oral', 0.1, np.nan, np.nan],
        ['alprazolam_oral', 4, np.nan, np.nan],
        ['alprazolam_parenteral', 2, np.nan, np.nan],
        ['propofol_parenteral', 1/40, np.nan, np.nan],
        ['dexmedetomidine_parenteral', 1*1000/14.82, np.nan, np.nan],
        ]

benzos = pd.DataFrame(benzos)
benzos.columns = ['med', 'equivalency_factor', 'tdd_min', 'tdd_max']

benzos['tdd_dependent'] = np.nan
for jloc, row in benzos.iterrows():
    benzos.loc[jloc, 'tdd_dependent'] = int('methadone' in row['med'])
    
benzos['category'] = ['benzos'] * benzos.shape[0]


equivalency = pd.concat([opioids, benzos], axis=0)
equivalency.to_csv(os.path.join(project_dir, f'equivalency_table_{version}.csv'), index=False)

NameError: name 'np' is not defined

In [3]:
version = 'covid_sedation'
project_dir = '/scr/wolfgang/Covid19_Sedation'
# like covid_sedation but dexmedetomidine and propofol are used as benzos as well.

opioids = [
    ['fentanyl_parenteral', 1, np.nan, np.nan],
    ['fentanyl_transdermal', 1, np.nan, np.nan],
    ['hydromorphone_oral', 0.1/7.5, np.nan, np.nan],
    ['hydromorphone_parenteral', 0.1/1.5, np.nan, np.nan],
    ['hydrocodone_oral', 0.1/30, np.nan, np.nan],
    ['morphine_oral', 0.1/30, np.nan, np.nan],
    ['morphine_parenteral', 0.1/10, np.nan, np.nan],
    ['oxycodone_oral', 0.1/20, np.nan, np.nan],
    ['meperidine_oral', 0.1/300, np.nan, np.nan],
    ['meperidine_parenteral', 0.1/100, np.nan, np.nan],
    ['codeine_oral', 0.1/200, np.nan, np.nan],
    ['tramadol_oral', 0.1/120, np.nan, np.nan],
    ['methadone_oral', 4 * 0.1 / 30, 0, 20],
    ['methadone_oral', 8 * 0.1 / 30, 20, 40],
    ['methadone_oral', 10 * 0.1 / 30, 40, 60],
    ['methadone_oral', 12 * 0.1 / 30, 60, 100000],
    ['methadone_parenteral', 4 * 0.1 / 30, 0, 20],
    ['methadone_parenteral', 8 * 0.1 / 30, 20, 40],
    ['methadone_parenteral', 10 * 0.1 / 30, 40, 60],
    ['methadone_parenteral', 12 * 0.1 / 30, 60, 100000],
    ]

opioids = pd.DataFrame(opioids)
opioids.columns = ['med', 'equivalency_factor', 'tdd_min', 'tdd_max']
opioids['tdd_dependent'] = np.nan
for jloc, row in opioids.iterrows():
    opioids.loc[jloc, 'tdd_dependent'] = int('methadone' in row['med'])
opioids['category'] = ['opioids'] * opioids.shape[0]

benzos = [
        ['midazolam_parenteral', 1, np.nan, np.nan],
        ['clonazepam_oral', 1/0.125, np.nan, np.nan],
        ['lorazepam_parenteral', 2, np.nan, np.nan],
        ['lorazepam_oral', 2, np.nan, np.nan],
        ['diazepam_parenteral', 1/1.25, np.nan, np.nan],
        ['diazepam_oral', 1/1.25, np.nan, np.nan],
        ['phenobarbital_parenteral', 1/7.5, np.nan, np.nan],
        ['phenobarbital_oral', 1/7.5, np.nan, np.nan],
        ['chlordiazepoxide_oral', 0.1, np.nan, np.nan],
        ['alprazolam_oral', 4, np.nan, np.nan],
        ['alprazolam_parenteral', 2, np.nan, np.nan],
        ]

benzos = pd.DataFrame(benzos)
benzos.columns = ['med', 'equivalency_factor', 'tdd_min', 'tdd_max']

benzos['tdd_dependent'] = np.nan
for jloc, row in benzos.iterrows():
    benzos.loc[jloc, 'tdd_dependent'] = int('methadone' in row['med'])
    
benzos['category'] = ['benzos'] * benzos.shape[0]


equivalency = pd.concat([opioids, benzos], axis=0)
equivalency.to_csv(os.path.join(project_dir, f'equivalency_table_{version}.csv'), index=False)

In [54]:
# extend covid-sedation with antipsychotics for covid-delirium

version = 'covid_delirium'
# like covid_sedation but dexmedetomidine and propofol are used as benzos as well.
project_dir = '/scr/wolfgang/Covid19_Delirium'

antipsychotics = [
        ['chlorpromazine_oral', 300, np.nan, np.nan], 
        ['chlorpromazine_parenteral', 100, np.nan, np.nan], 
        ['fluphenazine_oral', 10, np.nan, np.nan],
        ['fluphenazine_parenteral', None, np.nan, np.nan], 
        ['haloperidol_oral', 8 , np.nan, np.nan], 
        ['haloperidol_parenteral', 8, np.nan, np.nan], 
        ['loxapine_oral', 100, np.nan, np.nan], 
        ['loxapine_parenteral', None, np.nan, np.nan], 
        ['perphenazine_oral', 30, np.nan, np.nan], 
        ['perphenazine_parenteral', 10, np.nan, np.nan], 
        ['pimozide_oral', 4, np.nan, np.nan], 
        ['pimozide_parenteral', None, np.nan, np.nan], 
        ['prochlorperazine_oral', 100, np.nan, np.nan], 
        ['prochlorperazine_parenteral', 50, np.nan, np.nan], 
        ['trifluoperazine_oral', 20, np.nan, np.nan], 
        ['trifluoperazine_parenteral', 8, np.nan, np.nan], 
        ['thioridazine_oral', 300, np.nan, np.nan], 
        ['thioridazine_parenteral', 0, np.nan, np.nan], 
        ['thiothixene_oral', 30, np.nan, np.nan], 
        ['thiothixene_parenteral', None, np.nan, np.nan], 
        ['tiothixene_oral', 30, np.nan, np.nan], 
        ['tiothixene_parenteral', None, np.nan, np.nan], 
        ['aripiprazole_oral', 15, np.nan, np.nan], 
        ['aripiprazole_parenteral', 15, np.nan, np.nan], 
        ['asenapine_oral', 20, np.nan, np.nan], 
        ['asenapine_parenteral', None, np.nan, np.nan], 
        ['brexpiprazole_oral', None, np.nan, np.nan], 
        ['brexpiprazole_parenteral', None, np.nan, np.nan], 
        ['cariprazine_oral', None, np.nan, np.nan],
        ['cariprazine_parenteral', None, np.nan, np.nan],
        ['clozapine_oral', 300, np.nan, np.nan], 
        ['clozapine_parenteral', 300, np.nan, np.nan], 
        ['iloperidone_oral', None, np.nan, np.nan], 
        ['iloperidone_parenteral', None, np.nan, np.nan], 
        ['lurasidone_oral', 60, np.nan, np.nan], 
        ['lurasidone_parenteral', None, np.nan, np.nan], 
        ['olanzapine_oral', 10, np.nan, np.nan], 
        ['olanzapine_parenteral', 10, np.nan, np.nan], 
        ['paliperidone_oral', 6, np.nan, np.nan], 
        ['paliperidone_parenteral', 2.5, np.nan, np.nan], 
        ['quetiapine_oral', 400, np.nan, np.nan], 
        ['quetiapine_parenteral', None, np.nan, np.nan], 
        ['risperidone_oral', 5, np.nan, np.nan], 
        ['risperidone_parenteral', 2.7, np.nan, np.nan], 
        ['ziprasidone_oral', 80, np.nan, np.nan], 
        ['ziprasidone_parenteral', 40, np.nan, np.nan], 
]

antipsychotics = pd.DataFrame(antipsychotics)
antipsychotics.columns = ['med', 'equivalency_factor', 'tdd_min', 'tdd_max']
antipsychotics['tdd_dependent'] = 0

antipsychotics['category'] = ['antipsychotics'] * antipsychotics.shape[0]

equivalency = pd.concat([opioids, benzos, antipsychotics], axis=0)
equivalency.to_csv(os.path.join(project_dir, f'equivalency_table_{version}.csv'), index=False)