In [5]:
import sys
sys.path.append('C:/Users/wg984/Wolfgang/repos/ICU-Sleep/code1/')
sys.path.append('C:/Users/wg984/Wolfgang/repos/Bedmaster-ICU-tools/code/')
import numpy as np
import pandas as pd
from bmresearch_tools import BMR_load, BMR_plot, get_metadata 
from resample_BMR import remove_non_monotonic_data
%matplotlib widget
import matplotlib.pyplot as plt
import os

In [125]:
for studyid in range(8,33):
    studyid = str(studyid).zfill(3)
    os.mkdir('C:/Users/wg984/Dropbox (Partners HealthCare)/ICU-SLEEP-MATERIALS/TimeAlignmentAirGoBedmaster/Plots/'+studyid)

In [120]:
doc_path = 'C:/Users/wg984/Dropbox (Partners HealthCare)/ICU-SLEEP-MATERIALS/TimeAlignmentAirGoBedmaster/timealignment.csv'
doc = pd.read_csv(doc_path)
doc['study_id'] = doc['study_id'].apply(lambda x: str(x).zfill(3))
doc.head()

Empty DataFrame
Columns: [study_id, airgo_available, bmr_available, code_successful, note, TS_manual, TS_auto1, TS_auto2, TS_auto3, person_to_check]
Index: []

In [121]:
doc_path = 'C:/Users/wg984/Dropbox (Partners HealthCare)/ICU-SLEEP-MATERIALS/TimeAlignmentAirGoBedmaster/timealignment.csv'
doc = pd.read_csv(doc_path)
doc['study_id'] = [str(x).zfill(3) for x in range(1,190)]
doc.to_csv(doc_path, index=False)

In [6]:
study_id = '001'
airgo_features_dir = '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_features_v1/'
bmr_studyid_dir = '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/BMR_studyID/'
airgo_path = os.path.join(airgo_features_dir, 'airgo_'+study_id+'.csv')
bmr_path = os.path.join(bmr_studyid_dir, 'BMR_'+study_id+'.h5')

In [7]:
airgo_data = pd.read_csv(airgo_path)
if 'DateTime' in airgo_data.columns:
    airgo_data.rename(columns={'DateTime': 'datetime'}, inplace=True)
airgo_data.set_index('datetime', inplace=True)
airgo_data.index = pd.to_datetime(airgo_data.index, infer_datetime_format=1)

In [8]:
print(airgo_data.columns)
airgo_data.head()

Index(['band', 'accx', 'accy', 'accz', 'crcstatus', 'deriv1', 'deriv2',
       'ventilation0', 'ventilation_3s', 'ventilation_10s', 'ventilation_60s',
       'hypo_10_60', 'movavg_1s', 'movavg_1_2s', 'movavg_2s', 'movavg_3s',
       'movavg_5s', 'movavg_10s', 'movavg_60s', 'peaks', 'rr_10s', 'rr_60s'],
      dtype='object')

,band,accx,accy,accz,crcstatus,deriv1,deriv2,ventilation0,ventilation_3s,ventilation_10s,...,movavg_1s,movavg_1_2s,movavg_2s,movavg_3s,movavg_5s,movavg_10s,movavg_60s,peaks,rr_10s,rr_60s
datetime,,,,,,,,,,,,,,,,,,,,,
2018-06-06 15:26:00.400,16094.0,3.0,1.0,14.0,NaN,0.0,0.0,0.0,0.0,0.0,...,16094.000000,16094.000000,16094.000000,16094.000000,16094.000000,16094.000000,16094.000000,0,0.0,0.0
2018-06-06 15:26:00.500,16136.0,3.0,1.0,14.0,NaN,42.0,42.0,42.0,840.0,252.0,...,16115.000000,16115.000000,16115.000000,16115.000000,16115.000000,16115.000000,16115.000000,0,0.0,0.0
2018-06-06 15:26:00.600,16131.0,3.0,1.0,14.0,NaN,-5.0,-47.0,0.0,840.0,252.0,...,16120.333333,16120.333333,16120.333333,16120.333333,16120.333333,16120.333333,16120.333333,0,0.0,0.0
2018-06-06 15:26:00.700,16120.0,3.0,1.0,14.0,NaN,-11.0,-6.0,0.0,840.0,252.0,...,16120.250000,16120.250000,16120.250000,16120.250000,16120.250000,16120.250000,16120.250000,0,0.0,0.0
2018-06-06 15:26:00.800,16109.0,3.0,1.0,14.0,NaN,-11.0,0.0,0.0,840.0,252.0,...,16118.000000,16118.000000,16118.000000,16118.000000,16118.000000,16118.000000,16118.000000,0,0.0,0.0

In [9]:
airgo_data.tail()

,band,accx,accy,accz,crcstatus,deriv1,deriv2,ventilation0,ventilation_3s,ventilation_10s,...,movavg_1s,movavg_1_2s,movavg_2s,movavg_3s,movavg_5s,movavg_10s,movavg_60s,peaks,rr_10s,rr_60s
datetime,,,,,,,,,,,,,,,,,,,,,
2018-06-07 04:28:53.000,10104.000000,3.0,3.0,246.0,NaN,16.000000,17.250000,16.0,6560.0,3984.000000,...,10076.800000,10070.656250,10100.009375,10062.269410,9990.560000,9894.765379,9866.853741,1,18.0,15.0
2018-06-07 04:28:53.100,10085.333333,3.0,3.0,246.0,NaN,-18.666667,-34.666667,0.0,6560.0,3984.000000,...,10082.933333,10073.684028,10096.951042,10066.646914,9997.336354,9898.013333,9867.050511,0,18.0,15.0
2018-06-07 04:28:53.200,10050.666667,3.0,3.0,246.0,NaN,-34.666667,-16.000000,0.0,6560.0,3984.000000,...,10084.475000,10075.333333,10090.800000,10069.995062,10003.277188,9900.920000,9867.206648,0,18.0,15.0
2018-06-07 04:28:53.300,10032.000000,3.0,3.0,246.0,NaN,-18.666667,16.000000,0.0,6560.0,3976.303207,...,10081.675000,10076.000000,10083.200000,10072.827435,10008.623750,9903.627172,9867.348666,0,18.0,15.0
2018-06-07 04:28:53.400,10081.600000,3.0,3.0,246.0,NaN,49.600000,68.266667,49.6,7552.0,4252.352187,...,10081.360000,10079.862500,10078.423750,10077.386667,10014.675750,9906.794426,9867.590137,0,18.0,15.0

In [10]:
spo2_data = BMR_load(bmr_path, signals=['SPO2%'], loadEvents=0)
spo2_data = remove_non_monotonic_data(spo2_data)
spo2_data = spo2_data['SPO2%']
spo2_data.set_index('datetime', inplace=True)
spo2_data.drop('posix',axis=1, inplace=True)
spo2_data.rename(columns={'signal': 'spo2'}, inplace=True)

In [11]:
spo2_data.head()

                     spo2
datetime
2018-06-05 07:17:34  98.0
2018-06-05 07:17:36  98.0
2018-06-05 07:17:38  98.0
2018-06-05 07:17:40  98.0
2018-06-05 07:17:42  97.0

In [12]:
# resample spo2 and airgo between airgo min and airgo max.

In [13]:
spo2_data = spo2_data.loc[airgo_data.index[0] : airgo_data.index[-1],:]

In [14]:
data = pd.concat([spo2_data, airgo_data], join='outer', axis=1, sort=True)

In [15]:
data.spo2 = data.spo2.interpolate(method='pchip', order=3, limit_area='inside',
                          limit=None) 
data.shape

(469731, 23)

In [16]:
data = data.loc[(1- np.isnan(data.spo2.values)).astype('bool'),:]
data.shape

(469721, 23)

In [17]:
data

,spo2,band,accx,accy,accz,crcstatus,deriv1,deriv2,ventilation0,ventilation_3s,...,movavg_1s,movavg_1_2s,movavg_2s,movavg_3s,movavg_5s,movavg_10s,movavg_60s,peaks,rr_10s,rr_60s
datetime,,,,,,,,,,,,,,,,,,,,,
2018-06-06 15:26:01.000,96.0,16158.645161,3.000000,1.000000,14.000000,NaN,54.645161,59.645161,54.645161,1932.903226,...,16121.806452,16121.806452,16121.806452,16121.806452,16121.806452,16121.806452,16121.806452,0,0.0,0.0
2018-06-06 15:26:01.100,96.0,16216.000000,3.000000,1.000000,14.000000,NaN,57.354839,2.709677,57.354839,3080.000000,...,16133.580645,16133.580645,16133.580645,16133.580645,16133.580645,16133.580645,16133.580645,0,0.0,0.0
2018-06-06 15:26:01.200,96.0,16219.390307,2.740741,0.740741,14.259259,NaN,3.390307,-53.964532,3.390307,3147.806135,...,16143.115052,16143.115052,16143.115052,16143.115052,16143.115052,16143.115052,16143.115052,0,0.0,0.0
2018-06-06 15:26:01.300,96.0,16220.945488,2.259259,0.259259,14.740741,NaN,1.555181,-1.835125,1.555181,3178.909761,...,16150.898096,16150.898096,16150.898096,16150.898096,16150.898096,16150.898096,16150.898096,0,0.0,0.0
2018-06-06 15:26:01.400,96.0,16224.000000,2.000000,0.000000,15.000000,NaN,3.054512,1.499331,3.054512,3240.000000,...,16163.898096,16157.543723,16157.543723,16157.543723,16157.543723,16157.543723,16157.543723,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-06-07 04:28:52.600,95.0,10094.750000,3.000000,3.000000,245.156250,NaN,-1.250000,-12.500000,0.000000,6240.000000,...,10065.325000,10078.802083,10090.021875,10044.891667,9962.768600,9881.701042,9866.186205,0,12.0,14.0
2018-06-07 04:28:52.700,95.0,10092.000000,3.000000,3.000000,245.500000,NaN,-2.750000,-1.500000,0.000000,6240.000000,...,10064.125000,10073.218750,10095.546875,10049.052435,9969.631400,9884.899687,9866.324991,0,12.0,14.0
2018-06-07 04:28:52.800,95.0,10089.250000,3.000000,3.000000,245.843750,NaN,-2.750000,0.000000,0.000000,6240.000000,...,10065.587500,10069.541667,10099.012500,10053.195062,9976.491600,9888.112420,9866.476442,0,12.0,14.0
2018-06-07 04:28:52.900,95.0,10088.000000,3.000000,3.000000,246.000000,NaN,-1.250000,1.500000,0.000000,6240.000000,...,10069.487500,10068.208333,10100.212500,10057.402469,9983.360000,9891.346370,9866.643109,0,12.0,14.0
2018-06-07 04:28:53.000,95.0,10104.000000,3.000000,3.000000,246.000000,NaN,16.000000,17.250000,16.000000,6560.000000,...,10076.800000,10070.656250,10100.009375,10062.269410,9990.560000,9894.765379,9866.853741,1,18.0,15.0

In [37]:
data['hypo_10_60_movavg2sec'] = data.hypo_10_60.rolling('2s').mean()
data['hypo_10_60_movavg4sec'] = data.hypo_10_60.rolling('4s').mean()
data['hypo_10_60_movavg6sec'] = data.hypo_10_60.rolling('6s').mean()
data['hypo_10_60_movavg8sec'] = data.hypo_10_60.rolling('8s').mean()
data['hypo_10_60_movavg10sec'] = data.hypo_10_60.rolling('10s').mean()

In [19]:
data['hypo_10_60_movavg10sec'].values.shape

(469721,)

In [20]:
np.ones(data['hypo_10_60_movavg10sec'].shape).shape

(469721,)

In [38]:
data['hypo_10_60_movavg4sec'] = np.minimum(data['hypo_10_60_movavg4sec'].values,np.ones(data['hypo_10_60_movavg4sec'].shape)*1.2)
data['hypo_10_60_movavg6sec'] = np.minimum(data['hypo_10_60_movavg6sec'].values,np.ones(data['hypo_10_60_movavg6sec'].shape)*1.2)
data['hypo_10_60_movavg8sec'] = np.minimum(data['hypo_10_60_movavg8sec'].values,np.ones(data['hypo_10_60_movavg8sec'].shape)*1.2)
data['hypo_10_60_movavg10sec'] = np.minimum(data['hypo_10_60_movavg10sec'].values,np.ones(data['hypo_10_60_movavg10sec'].shape)*1.2)

In [22]:
plt.figure()
plt.plot(data.hypo_10_60.index, data.hypo_10_60)
plt.plot(data.hypo_10_60_movavg2sec.index, data.hypo_10_60_movavg2sec)
plt.plot(data.hypo_10_60_movavg4sec.index, data.hypo_10_60_movavg4sec)
plt.legend(['10-60', '2sec','4 sec'])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\wg984\.conda\envs\visualization\lib\site-packages\pandas\plotting\_matplotlib\converter.py:103: FutureWarning:

Using an implicitly registered datetime converter for a matplotlib plotting method. The converter was registered by pandas on import. Future versions of pandas will require you to explicitly register matplotlib converters.

To register the converters:
	>>> from pandas.plotting import register_matplotlib_converters
	>>> register_matplotlib_converters()

In [23]:
plt.close()

In [24]:
idx_start = 386000
idx_end = 390000

idx_start = 380000
idx_end = 400000

In [25]:
plt.figure()
ax0= plt.subplot(311)
plt.plot(data.band.index[idx_start:idx_end], data.band[idx_start:idx_end])
ax1= plt.subplot(312, sharex=ax0)
plt.plot(data.hypo_10_60.index[idx_start:idx_end], data.hypo_10_60[idx_start:idx_end])
# plt.plot(data.hypo_10_60_movavg2sec.index[idx_start:idx_end], data.hypo_10_60_movavg2sec[idx_start:idx_end])
# plt.plot(data.hypo_10_60_movavg4sec.index[idx_start:idx_end], data.hypo_10_60_movavg4sec[idx_start:idx_end])
# plt.plot(data.hypo_10_60_movavg6sec.index[idx_start:idx_end], data.hypo_10_60_movavg6sec[idx_start:idx_end])
plt.plot(data.hypo_10_60_movavg8sec.index[idx_start:idx_end], data.hypo_10_60_movavg8sec[idx_start:idx_end])
# plt.plot(data.hypo_10_60_movavg10sec.index[idx_start:idx_end], data.hypo_10_60_movavg10sec[idx_start:idx_end])

ax2= plt.subplot(313, sharex=ax0)
plt.plot(data.spo2.index[idx_start:idx_end], data.spo2[idx_start:idx_end])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [26]:
plt.figure()
ax0= plt.subplot(311)
plt.plot(data.band.index[idx_start:idx_end], data.band[idx_start:idx_end])
ax1= plt.subplot(312, sharex=ax0)
# plt.plot(data.hypo_10_60.index[idx_start:idx_end], data.hypo_10_60[idx_start:idx_end])
# plt.plot(data.hypo_10_60_movavg2sec.index[idx_start:idx_end], data.hypo_10_60_movavg2sec[idx_start:idx_end])
# plt.plot(data.hypo_10_60_movavg4sec.index[idx_start:idx_end], data.hypo_10_60_movavg4sec[idx_start:idx_end])
plt.plot(data.hypo_10_60_movavg6sec.index[idx_start:idx_end-1], np.diff(data.hypo_10_60_movavg6sec[idx_start:idx_end]))
plt.plot(data.hypo_10_60_movavg8sec.index[idx_start:idx_end-1], np.diff(data.hypo_10_60_movavg8sec[idx_start:idx_end]))
plt.plot(data.hypo_10_60_movavg10sec.index[idx_start:idx_end-1], np.diff(data.hypo_10_60_movavg10sec[idx_start:idx_end]))

ax2= plt.subplot(313, sharex=ax0)
plt.plot(data.spo2.index[idx_start:idx_end-1], np.diff(data.spo2[idx_start:idx_end]))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [27]:
spearman = []
pearson = []
lagrange = range(-3000,3000,10)
for lag in lagrange:
#     hypo = data.hypo_10_60_movavg8sec.iloc[idx_start:idx_end]
#     spo2 = data.spo2.iloc[idx_start-lag:idx_end-lag]
    hypo = pd.Series(np.diff(data.hypo_10_60_movavg8sec.iloc[idx_start:idx_end]))
    spo2 = pd.Series(np.diff(data.spo2.iloc[idx_start-lag:idx_end-lag]))
    spearman.append(spo2.corr(hypo, method='spearman'))
    pearson.append(spo2.corr(hypo, method='pearson'))

plt.figure()
plt.plot(np.array(lagrange)/10, spearman)
plt.plot(np.array(lagrange)/10, pearson)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [28]:
for i in range(40):
    plt.close()

In [29]:
idx_start = 380000
idx_end = 400000
lagrange = range(-3000,3000,10)

maxspearman = []
maxpearson = []

hypo_diff = pd.Series(np.diff(data.hypo_10_60_movavg8sec)) 
spo2_diff = pd.Series(np.diff(data.spo2))

for lag in lagrange:

        
        spearman.append(spo2_diff.corr(hypo_diff, method='spearman'))
        pearson.append(spo2_diff.corr(hypo_diff, method='pearson'))

KeyboardInterrupt:

In [ ]:

plt.close()
# plt.figure(figsize=(50,10))

idx_start = 380000
idx_end = 400000
lagrange = range(-3000,3000,10)

maxspearman = []
maxpearson = []

hypo_diff = pd.Series(np.diff(data.hypo_10_60_movavg8sec)) 
spo2_diff = pd.Series(np.diff(data.spo2))


spearman =[]
pearson = []

for lag in lagrange:
#         hypo = data.hypo_10_60_movavg2sec.iloc[idx_start:idx_start+20000]
#         spo2 = data.spo2.iloc[idx_start+lag:idx_start+20000+lag]
    hypo = hypo_diff.iloc[idx_start:idx_end]
    spo2 = spo2_diff.iloc[idx_start-lag:idx_end-lag]

    spearman.append(spo2.corr(hypo, method='spearman'))
    pearson.append(spo2.corr(hypo, method='pearson'))

maxspearman.append(lagrange[np.argmax(spearman)]/10)
maxpearson.append(lagrange[np.argmax(pearson)]/10)

#     print(lagrange[np.argmax(spearman)]/10)
#     print(lagrange[np.argmax(pearson)]/10)
#     print('\n')
#     plt.subplot(len(searchrange),1,i+1)
#     plt.plot(np.array(lagrange)/10,spearman)
#     plt.plot(np.array(lagrange)/10,pearson)

In [ ]:
maxpearson

In [ ]:
maxspearman

In [ ]:
data.shape[0]

In [47]:

plt.close()
# plt.figure(figsize=(50,10))

# idx_start = 380000
# idx_end = 400000
lagrange = range(-3000,3000,10)
searchrange = range(0,data.shape[0]-5001,5000)

maxspearman = []
maxpearson = []

# hypo_diff = pd.Series(np.diff(data.hypo_10_60_movavg8sec)) 
# spo2_diff = pd.Series(np.diff(data.spo2))

# searchrange = range(0,spo2_diff.shape[0]-5000,5000)

for [i,idx_start] in enumerate(searchrange):
    spearman =[]
    pearson = []
    idx_end = idx_start + 20000
    
    for lag in lagrange:
#         hypo = data.hypo_10_60_movavg2sec.iloc[idx_start:idx_start+20000]
#         spo2 = data.spo2.iloc[idx_start+lag:idx_start+20000+lag]

#         hypo = hypo_diff.iloc[idx_start:idx_end]
#         spo2 = spo2_diff.iloc[idx_start-lag:idx_end-lag]

        hypo = pd.Series(np.diff(data.hypo_10_60_movavg8sec.iloc[idx_start:idx_end]))
        spo2 = pd.Series(np.diff(data.spo2.iloc[idx_start-lag:idx_end-lag]))
        
        spearman.append(spo2.corr(hypo, method='spearman'))
        pearson.append(spo2.corr(hypo, method='pearson'))
    
    maxspearman.append(lagrange[np.argmax(spearman)]/10)
    maxpearson.append(lagrange[np.argmax(pearson)]/10)
    
#     print(lagrange[np.argmax(spearman)]/10)
#     print(lagrange[np.argmax(pearson)]/10)
#     print('\n')
#     plt.subplot(len(searchrange),1,i+1)
#     plt.plot(np.array(lagrange)/10,spearman)
#     plt.plot(np.array(lagrange)/10,pearson)

In [44]:
idx_start = 380000
idx_end = 400000
plt.figure()
ax0= plt.subplot(211)
plt.plot(data.hypo_10_60_movavg8sec.iloc[idx_start:idx_end])
plt.legend(['hypopnea indication curve'])
ax1= plt.subplot(212, sharex=ax0)
plt.plot(data.spo2.iloc[idx_start:idx_end])
plt.legend(['SPO2%'])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [46]:
idx_start = 380000
idx_end = 400000
plt.figure()
plt.plot(np.diff(data.hypo_10_60_movavg8sec.iloc[idx_start:idx_end]))
plt.plot(np.diff(data.spo2.iloc[idx_start:idx_end]))
plt.legend(['deriv. hypopnea indication curve','deriv SPO2%'])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [69]:
# note: -6 beause of 8sec moving average. approximation to correct for it
plt.figure()
plt.hist(np.array(maxspearman),histtype='step', bins=len(lagrange)//2)
plt.hist(np.array(maxpearson),histtype='step', bins=len(lagrange)//2)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([ 2.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  3.,  5.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  4.,  1.,  9., 17.,  5.,  4.,  2.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  2.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,
         0.,  0.,  0.,  1.,  3.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,
         0.,  2.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  1.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,
         0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         1.]),
 array([-280.        , -278.10333333, -276.20666667, -274.31      ,
        -272.41333333, -270.51666667, -268.62      , -266.72333333,
        -264.82666667, -262.93      , -261.03333333, -259.13666667,
        -257.24      , -255.34333333, -253.44666667, -251.55      ,
        -249.65333333, -247.75666667, -245.86      , -243.96333333,
        -242.06666667, -240.17      , -238.27333333, -236.37666667,
        -234.48      , -232.58333333, -230.68666667, -228.79      ,
        -226.89333333, -224.99666667, -223.1       , -221.20333333,
        -219.30666667, -217.41      , -215.51333333, -213.61666667,
        -211.72      , -209.82333333, -207.92666667, -206.03      ,
        -204.13333333, -202.23666667, -200.34      , -198.44333333,
        -196.54666667, -194.65      , -192.75333333, -190.85666667,
        -188.96      , -187.06333333, -185.16666667, -183.27      ,
        -181.37333333, -179.47666667, -177.58      , -175.68333333,
        -173.78666667, -171.89      , -169.99333333, -168.09666667,
        -166.2       , -164.30333333, -162.40666667, -160.51      ,
        -158.61333333, -156.71666667, -154.82      , -152.92333333,
        -151.02666667, -149.13      , -147.23333333, -145.33666667,
        -143.44      , -141.54333333, -139.64666667, -137.75      ,
        -135.85333333, -133.95666667, -132.06      , -130.16333333,
        -128.26666667, -126.37      , -124.47333333, -122.57666667,
        -120.68      , -118.78333333, -116.88666667, -114.99      ,
        -113.09333333, -111.19666667, -109.3       , -107.40333333,
        -105.50666667, -103.61      , -101.71333333,  -99.81666667,
         -97.92      ,  -96.02333333,  -94.12666667,  -92.23      ,
         -90.33333333,  -88.43666667,  -86.54      ,  -84.64333333,
         -82.74666667,  -80.85      ,  -78.95333333,  -77.05666667,
         -75.16      ,  -73.26333333,  -71.36666667,  -69.47      ,
         -67.57333333,  -65.67666667,  -63.78      ,  -61.88333333,
         -59.98666667,  -58.09      ,  -56.19333333,  -54.29666667,
         -52.4       ,  -50.50333333,  -48.60666667,  -46.71      ,
         -44.81333333,  -42.91666667,  -41.02      ,  -39.12333333,
         -37.22666667,  -35.33      ,  -33.43333333,  -31.53666667,
         -29.64      ,  -27.74333333,  -25.84666667,  -23.95      ,
         -22.05333333,  -20.15666667,  -18.26      ,  -16.36333333,
         -14.46666667,  -12.57      ,  -10.67333333,   -8.77666667,
          -6.88      ,   -4.98333333,   -3.08666667,   -1.19      ,
           0.70666667,    2.60333333,    4.5       ,    6.39666667,
           8.29333333,   10.19      ,   12.08666667,   13.98333333,
          15.88      ,   17.77666667,   19.67333333,   21.57      ,
          23.46666667,   25.36333333,   27.26      ,   29.15666667,
          31.05333333,   32.95      ,   34.84666667,   36.74333333,
          38.64      ,   40.53666667,   42.43333333,   44.33      ,
          46.22666667,   48.12333333,   50.02      ,   51.91666667,
          53.81333333,   55.71      ,   57.60666667,   59.50333333,
          61.4       ,   63.29666667,   65.19333333,   67.09      ,
          68.98666667,   70.88333333,   72.78      ,   74.67666667,
          76.57333333,   78.47      ,   80.36666667,   82.26333333,
          84.16      ,   86.05666667,   87.95333333,   89.85      ,
          91.74666667,   93.64333333,   95.54      ,   97.43666667,
          99.33333333,  101.23      ,  103.12666667,  105.02333333,
         106.92      ,  108.81666667,  110.71333333,  112.61      ,
         114.50666667,  116.40333333,  118.3       ,  120.19666667,
         122.09333333,  123.99      ,  125.88666667,  127.78333333,
         129.68      ,  131.57666667,  133.47333333,  135.37      ,
         137.26666667,  139.16333333,  141.06      ,  142.95666667,
         144.85333333,  146.75      ,  148.64666667,  150.54333333,
         152.44      ,  154.33666667,  156.23333333,  158.13      ,
         160.02666667,  161.92333333,  163.82      ,  165.71666667,
         167.61333333,  169.51      ,  171.40666667,  173.30333333,
         175.2       ,  177.09666667,  178.99333333,  180.89      ,
         182.78666667,  184.68333333,  186.58      ,  188.47666667,
         190.37333333,  192.27      ,  194.16666667,  196.06333333,
         197.96      ,  199.85666667,  201.75333333,  203.65      ,
         205.54666667,  207.44333333,  209.34      ,  211.23666667,
         213.13333333,  215.03      ,  216.92666667,  218.82333333,
         220.72      ,  222.61666667,  224.51333333,  226.41      ,
         228.30666667,  230.20333333,  232.1       ,  233.99666667,
         235.89333333,  237.79      ,  239.68666667,  241.58333333,
         243.48      ,  245.37666667,  247.27333333,  249.17      ,
         251.06666667,  252.96333333,  254.86      ,  256.75666667,
         258.65333333,  260.55      ,  262.44666667,  264.34333333,
         266.24      ,  268.13666667,  270.03333333,  271.93      ,
         273.82666667,  275.72333333,  277.62      ,  279.51666667,
         281.41333333,  283.31      ,  285.20666667,  287.10333333,
         289.        ]),
 <a list of 1 Patch objects>)

In [49]:
np.argsort(maxspearman)

array([12, 33, 22, 10, 11,  9, 47, 30, 29, 31, 92, 24, 46, 36,  6, 90, 89,
       88, 91, 87, 68, 67, 66, 65, 64, 62, 63, 86, 61, 60, 83, 84, 85, 69,
       70, 59, 81, 72, 73, 74, 75, 76, 77, 80, 71, 82, 57, 56, 55, 54, 58,
       79, 78,  3, 49, 48, 51, 53, 50, 52, 13,  1, 15, 32,  7,  8, 16, 17,
       39, 38, 40,  0, 20, 18, 19, 41, 42, 44, 43, 45, 35, 14, 23,  2, 34,
       21, 28, 26, 25, 37,  4,  5, 27], dtype=int64)

In [76]:
from scipy.signal import argrelextrema, find_peaks

maxspearman = np.array(maxspearman)
# for local maxima
counts, lag = np.histogram(maxspearman, len(lagrange)//2)

In [79]:
# local_max = argrelextrema(counts, np.greater)
# local_max_lag = lag[local_max]

local_max = find_peaks(counts, distance=5)[0]
local_max_lag = lag[local_max]
local_max_lag

array([-244.28, -232.34, -220.4 , -190.55, -122.89, -108.96,  -81.1 ,
        -67.17,  -55.23,  -37.32,  -11.45,   -1.5 ,   20.39,   30.34,
         42.28,   58.2 ,   70.14,  107.95,  239.29,  251.23,  267.15,
        285.06])

In [85]:
local_max_count = counts[local_max]
print(local_max_count)
idx_candidates = np.argsort(local_max_count)[::-1][:3]
print(local_max_lag[idx_candidates])
print(local_max_count[idx_candidates])
# np.argsort()

[ 1  3  1  2  1  1  1 18  1  1  3  3  2  4  1  1  1  1  1  2  1  1]
[-67.17  30.34 -11.45]
[18  4  3]

In [104]:
doc.loc[doc.study_id==study_id,'TS_auto1'] = idx_candidates[0]
doc.loc[doc.study_id==study_id,'TS_auto2'] = idx_candidates[1]
doc.loc[doc.study_id==study_id,'TS_auto3'] = idx_candidates[2]

In [105]:
doc

,study_id,airgo_available,plot_done,note,TS_manual,TS_auto1,TS_auto2,TS_auto3,person_to_check
0,001,NaN,NaN,NaN,NaN,7,13,10,NaN
1,002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
184,185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
study_id

'001'

In [31]:
# note: -6 beause of 8sec moving average. approximation to correct for it
plt.figure()
plt.hist(np.array(maxspearman)-6,histtype='step', bins=len(lagrange)//2)
plt.hist(np.array(maxpearson)-6,histtype='step', bins=len(lagrange)//2)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  4.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  4.,  2., 15., 11.,  3.,  2.,  4.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  3.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  2.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  2.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  1.,  0.,
         0.,  3.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         1.]),
 array([-286.        , -284.10333333, -282.20666667, -280.31      ,
        -278.41333333, -276.51666667, -274.62      , -272.72333333,
        -270.82666667, -268.93      , -267.03333333, -265.13666667,
        -263.24      , -261.34333333, -259.44666667, -257.55      ,
        -255.65333333, -253.75666667, -251.86      , -249.96333333,
        -248.06666667, -246.17      , -244.27333333, -242.37666667,
        -240.48      , -238.58333333, -236.68666667, -234.79      ,
        -232.89333333, -230.99666667, -229.1       , -227.20333333,
        -225.30666667, -223.41      , -221.51333333, -219.61666667,
        -217.72      , -215.82333333, -213.92666667, -212.03      ,
        -210.13333333, -208.23666667, -206.34      , -204.44333333,
        -202.54666667, -200.65      , -198.75333333, -196.85666667,
        -194.96      , -193.06333333, -191.16666667, -189.27      ,
        -187.37333333, -185.47666667, -183.58      , -181.68333333,
        -179.78666667, -177.89      , -175.99333333, -174.09666667,
        -172.2       , -170.30333333, -168.40666667, -166.51      ,
        -164.61333333, -162.71666667, -160.82      , -158.92333333,
        -157.02666667, -155.13      , -153.23333333, -151.33666667,
        -149.44      , -147.54333333, -145.64666667, -143.75      ,
        -141.85333333, -139.95666667, -138.06      , -136.16333333,
        -134.26666667, -132.37      , -130.47333333, -128.57666667,
        -126.68      , -124.78333333, -122.88666667, -120.99      ,
        -119.09333333, -117.19666667, -115.3       , -113.40333333,
        -111.50666667, -109.61      , -107.71333333, -105.81666667,
        -103.92      , -102.02333333, -100.12666667,  -98.23      ,
         -96.33333333,  -94.43666667,  -92.54      ,  -90.64333333,
         -88.74666667,  -86.85      ,  -84.95333333,  -83.05666667,
         -81.16      ,  -79.26333333,  -77.36666667,  -75.47      ,
         -73.57333333,  -71.67666667,  -69.78      ,  -67.88333333,
         -65.98666667,  -64.09      ,  -62.19333333,  -60.29666667,
         -58.4       ,  -56.50333333,  -54.60666667,  -52.71      ,
         -50.81333333,  -48.91666667,  -47.02      ,  -45.12333333,
         -43.22666667,  -41.33      ,  -39.43333333,  -37.53666667,
         -35.64      ,  -33.74333333,  -31.84666667,  -29.95      ,
         -28.05333333,  -26.15666667,  -24.26      ,  -22.36333333,
         -20.46666667,  -18.57      ,  -16.67333333,  -14.77666667,
         -12.88      ,  -10.98333333,   -9.08666667,   -7.19      ,
          -5.29333333,   -3.39666667,   -1.5       ,    0.39666667,
           2.29333333,    4.19      ,    6.08666667,    7.98333333,
           9.88      ,   11.77666667,   13.67333333,   15.57      ,
          17.46666667,   19.36333333,   21.26      ,   23.15666667,
          25.05333333,   26.95      ,   28.84666667,   30.74333333,
          32.64      ,   34.53666667,   36.43333333,   38.33      ,
          40.22666667,   42.12333333,   44.02      ,   45.91666667,
          47.81333333,   49.71      ,   51.60666667,   53.50333333,
          55.4       ,   57.29666667,   59.19333333,   61.09      ,
          62.98666667,   64.88333333,   66.78      ,   68.67666667,
          70.57333333,   72.47      ,   74.36666667,   76.26333333,
          78.16      ,   80.05666667,   81.95333333,   83.85      ,
          85.74666667,   87.64333333,   89.54      ,   91.43666667,
          93.33333333,   95.23      ,   97.12666667,   99.02333333,
         100.92      ,  102.81666667,  104.71333333,  106.61      ,
         108.50666667,  110.40333333,  112.3       ,  114.19666667,
         116.09333333,  117.99      ,  119.88666667,  121.78333333,
         123.68      ,  125.57666667,  127.47333333,  129.37      ,
         131.26666667,  133.16333333,  135.06      ,  136.95666667,
         138.85333333,  140.75      ,  142.64666667,  144.54333333,
         146.44      ,  148.33666667,  150.23333333,  152.13      ,
         154.02666667,  155.92333333,  157.82      ,  159.71666667,
         161.61333333,  163.51      ,  165.40666667,  167.30333333,
         169.2       ,  171.09666667,  172.99333333,  174.89      ,
         176.78666667,  178.68333333,  180.58      ,  182.47666667,
         184.37333333,  186.27      ,  188.16666667,  190.06333333,
         191.96      ,  193.85666667,  195.75333333,  197.65      ,
         199.54666667,  201.44333333,  203.34      ,  205.23666667,
         207.13333333,  209.03      ,  210.92666667,  212.82333333,
         214.72      ,  216.61666667,  218.51333333,  220.41      ,
         222.30666667,  224.20333333,  226.1       ,  227.99666667,
         229.89333333,  231.79      ,  233.68666667,  235.58333333,
         237.48      ,  239.37666667,  241.27333333,  243.17      ,
         245.06666667,  246.96333333,  248.86      ,  250.75666667,
         252.65333333,  254.55      ,  256.44666667,  258.34333333,
         260.24      ,  262.13666667,  264.03333333,  265.93      ,
         267.82666667,  269.72333333,  271.62      ,  273.51666667,
         275.41333333,  277.31      ,  279.20666667,  281.10333333,
         283.        ]),
 <a list of 1 Patch objects>)

In [ ]:

# plt.close()
# plt.figure(figsize=(50,10))

# idx_start = 380000
# idx_end = 400000
# lagrange = range(-3000,3000,10)
# searchrange = range(0,450000,20000)
# maxspearman = []
# maxpearson = []

# for [i,idx_start] in enumerate(searchrange):
#     spearman =[]
#     pearson = []
#     idx_end = idx_start + 20000
    
#     for lag in lagrange:
# #         hypo = data.hypo_10_60_movavg2sec.iloc[idx_start:idx_start+20000]
# #         spo2 = data.spo2.iloc[idx_start+lag:idx_start+20000+lag]
#         hypo = pd.Series(np.diff(data.hypo_10_60_movavg8sec.iloc[idx_start:idx_end]))
#         spo2 = pd.Series(np.diff(data.spo2.iloc[idx_start-lag:idx_end-lag]))
    
#         spearman.append(spo2.corr(hypo, method='spearman'))
#         pearson.append(spo2.corr(hypo, method='pearson'))
    
#     maxspearman.append(lagrange[np.argmax(spearman)]/10)
#     maxpearson.append(lagrange[np.argmax(pearson)]/10)
    
# #     print(lagrange[np.argmax(spearman)]/10)
# #     print(lagrange[np.argmax(pearson)]/10)
# #     print('\n')
#     plt.subplot(len(searchrange),1,i+1)
#     plt.plot(np.array(lagrange)/10,spearman)
#     plt.plot(np.array(lagrange)/10,pearson)

In [184]:

plt.close()
plt.figure(figsize=(50,10))

for [i,idx_start] in enumerate(range(40000,200000,20000)):
    spearman =[]
    pearson = []
    for lag in range(-600,600,10):
        hypo = data.hypo_10_60_movavg2sec.iloc[idx_start:idx_start+5000]
        spo2 = data.spo2.iloc[idx_start+lag:idx_start+5000+lag]
        spearman.append(spo2.corr(hypo, method='spearman'))
        pearson.append(spo2.corr(hypo, method='pearson'))
    plt.subplot(len(range(40000,200000,20000)),1,i+1)
    plt.plot(spearman)
#     plt.plot(pearson)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [181]:
plt.close()
plt.figure(figsize=(50,10))

plt.plot(spearman)
plt.plot(pearson)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [180]:
i

7

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

0.00626685049219263

datetime
2018-06-06 15:42:41.000    0.652884
2018-06-06 15:42:41.100    0.657893
2018-06-06 15:42:41.200    0.662863
2018-06-06 15:42:41.300    0.668361
2018-06-06 15:42:41.400    0.674664
                             ...
2018-06-06 15:59:20.500    0.806488
2018-06-06 15:59:20.600    0.807903
2018-06-06 15:59:20.700    0.808276
2018-06-06 15:59:20.800    0.808435
2018-06-06 15:59:20.900    0.808447
Name: hypo_10_60_movavg2sec, Length: 10000, dtype: float64