In [45]:
import pandas as pd
import numpy as np
import os
import sys

In [46]:
sofa_dir = '/media/mad3/Projects/ICU_SLEEP_STUDY/Sleep_And_Breathing/SOFA_results_studyid'

In [3]:
meds = pd.read_csv('/media/mad3/Projects/ICU_SLEEP_STUDY/data/data_analysis/edw_data/edw_icu_sleep_2020_07_07_meds_encounter.csv')

/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (14,16,17,20,23,26,27,28,33,34,38) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [47]:
top10_rem = pd.read_csv('top10_rem.csv')
bottom10_rem = pd.read_csv('bottom10_rem.csv')

In [48]:
def add_meds_and_sofa(top10_rem):

    top10_rem['medications'] = np.nan
    top10_rem['SOFA_mean'] = np.nan
    top10_rem['SOFA_max'] = np.nan

    for jloc, row in top10_rem.iterrows():
        mrn = row.MRN

        try:
            sofa = pd.read_csv(os.path.join(sofa_dir, 'SOFA_ICU' + row.study_id[-3:] + '.csv'))
            top10_rem.loc[jloc, 'SOFA_mean'] = sofa['SOFA_score'].mean()
            top10_rem.loc[jloc, 'SOFA_max'] = sofa['SOFA_score'].max()
        except Exception as e:
            print(e)
            continue
        top10_rem.loc[jloc, 'medications'] = '; '.join(meds[meds.MRN == mrn].MedicationDSC.unique())

    return top10_rem

In [49]:
top10_rem = add_meds_and_sofa(top10_rem)
top10_rem.to_csv('top10_rem.csv')

[Errno 2] File b'/media/mad3/Projects/ICU_SLEEP_STUDY/Sleep_And_Breathing/SOFA_results_studyid/SOFA_ICU153.csv' does not exist: b'/media/mad3/Projects/ICU_SLEEP_STUDY/Sleep_And_Breathing/SOFA_results_studyid/SOFA_ICU153.csv'

In [50]:
bottom10_rem = add_meds_and_sofa(bottom10_rem)
bottom10_rem.to_csv('bottom10_rem.csv')

In [51]:
top10_rem

,study_id,MRN,Age,Sex,RSSComb1,IBI_mean_SSComb1_S,IBI_std_SSComb1_S,MV_mean_SSComb1_S,MV_std_SSComb1_S,BSI_mean_SSComb1_S,BSI_std_SSComb1_S,RR_mean_SSComb1_S,RR_std_SSComb1_S,medications,SOFA_mean,SOFA_max
0,icu_119,6308196.0,62.0,Female,87.0,5.28,3.65,0.33,0.19,0.32,0.12,16.38,4.65,ACETAMINOPHEN 325 MG TABLET; MIDAZOLAM (PF) 1 ...,0.033563,2.0
1,icu_084,6539323.0,62.0,Male,89.0,4.53,1.23,0.12,0.08,0.12,0.07,14.36,3.55,PANTOPRAZOLE IVPB 40 MG (100 ML) MBP; SODIUM C...,0.107330,10.0
2,icu_061,5987312.0,54.0,Male,91.0,4.94,1.56,0.15,0.10,0.15,0.09,15.17,3.42,MYCOPHENOLATE MOFETIL 250 MG CAPSULE; OMEPRAZO...,0.187280,5.0
3,icu_153,480086.0,76.0,Male,91.0,2.25,0.61,0.12,0.08,0.14,0.08,27.72,3.65,NaN,NaN,NaN
4,icu_037,6492716.0,66.0,Male,92.0,4.07,1.49,0.16,0.10,0.19,0.10,18.14,3.89,LACTATED RINGERS INTRAVENOUS SOLUTION; MIDAZOL...,0.061538,2.0
5,icu_122,1194303.0,84.0,Male,95.0,4.26,0.81,0.12,0.07,0.11,0.06,16.53,3.20,MELATONIN 1 MG TABLET; MAGNESIUM SULFATE 2 GRA...,0.003665,1.0
6,icu_100,1723880.0,56.0,Male,97.0,2.95,1.15,0.14,0.07,0.19,0.07,22.94,3.77,LACTATED RINGERS INTRAVENOUS SOLUTION; ROCURON...,0.042450,9.0
7,icu_169,3165797.0,64.0,Male,99.0,3.65,0.92,0.08,0.06,0.10,0.06,17.33,3.01,LACTATED RINGERS INTRAVENOUS SOLUTION; FENTANY...,0.005078,2.0
8,icu_085,6358295.0,55.0,Female,100.0,4.17,1.19,0.14,0.07,0.16,0.07,16.71,2.55,MYCOPHENOLATE MOFETIL 250 MG CAPSULE; MIDAZOLA...,0.273950,12.0
9,icu_042,4101850.0,74.0,Female,100.0,3.76,1.20,0.14,0.10,0.16,0.09,17.81,3.32,GABAPENTIN 100 MG CAPSULE; MORPHINE 4 MG/ML IN...,0.007457,2.0

In [52]:
bottom10_rem

,study_id,MRN,Age,Sex,RSSComb1,IBI_mean_SSComb1_S,IBI_std_SSComb1_S,MV_mean_SSComb1_S,MV_std_SSComb1_S,BSI_mean_SSComb1_S,BSI_std_SSComb1_S,RR_mean_SSComb1_S,RR_std_SSComb1_S,medications,SOFA_mean,SOFA_max
0,icu_152,6751620.0,64.0,Male,0.0,2.88,0.88,0.09,0.06,0.11,0.08,23.57,3.71,ACETAMINOPHEN 325 MG TABLET; CEFTRIAXONE IVPB ...,1.083871,3.0
1,icu_178,1745708.0,64.0,Female,0.0,2.82,0.93,0.14,0.08,0.15,0.08,23.72,4.67,IPRATROPIUM-ALBUTEROL 0.5 MG-3 MG(2.5 MG BASE)...,0.179446,9.0
2,icu_067,6603851.0,50.0,Female,0.0,3.46,0.82,0.12,0.08,0.13,0.08,19.55,3.32,LACTATED RINGERS INTRAVENOUS SOLUTION; ACETAMI...,0.116693,4.0
3,icu_090,5946494.0,52.0,Female,0.0,3.41,1.26,0.14,0.09,0.17,0.08,20.92,3.99,ASPIRIN 325 MG TABLET; FENTANYL 25 MCG/HR TRAN...,0.782494,16.0
4,icu_092,6546904.0,68.0,Female,0.0,2.12,0.58,0.11,0.09,0.13,0.08,28.75,3.63,LACTATED RINGERS INTRAVENOUS SOLUTION; FENTANY...,0.203779,9.0
5,icu_051,1810580.0,67.0,Male,0.0,3.92,1.55,0.13,0.07,0.17,0.06,19.57,4.38,LACTATED RINGERS INTRAVENOUS SOLUTION; MIDAZOL...,0.000000,0.0
6,icu_047,4352857.0,71.0,Male,0.0,3.77,0.70,0.11,0.07,0.10,0.06,17.56,3.08,NOREPINEPHRINE INFUSION IN NS 16 MCG/ML (250 M...,0.527601,7.0
7,icu_149,4203280.0,76.0,Female,0.0,4.74,1.57,0.16,0.12,0.16,0.12,13.86,2.38,HYDROMORPHONE (PF) 0.5 MG/0.5 ML INJECTION SYR...,0.043347,7.0
8,icu_050,6577287.0,54.0,Female,0.0,5.08,1.04,0.13,0.07,0.12,0.06,15.29,2.84,LACTATED RINGERS INTRAVENOUS SOLUTION; MIDAZOL...,0.000000,0.0
9,icu_123,5761027.0,66.0,Male,0.0,5.28,3.85,0.51,0.22,0.45,0.13,14.14,5.32,IOPAMIDOL 76 % INTRAVENOUS SOLUTION; MORPHINE ...,0.034698,4.0