In [62]:
import numpy as np
import pandas as pd
import os
import h5py
import scipy.io as sio
import datetime

In [2]:
hypoxic_table = pd.read_csv('hypoxic_table_results_tmp.csv')

In [3]:
hypoxic_table = hypoxic_table.dropna(how='all', axis=1)

In [4]:
hypoxic_table.iloc[:, 45:80]

,MatchedMRN,MatchedLastName,MatchedFirstName,MatchedDOB,Visit_1_HypoxiaBurden,Visit_1_AHI,Visit_1_Total_Sleep_Time,Visit_1_T90_minutes,Visit_1_T90_minutes_desat,Visit_1_T90_minutes_unspecific,...,Visit_4_T90_minutes,Visit_4_T90_minutes_desat,Visit_4_T90_minutes_unspecific,Visit_5_HypoxiaBurden,Visit_5_AHI,Visit_5_Total_Sleep_Time,Visit_5_T90_minutes,Visit_5_T90_minutes_desat,Visit_5_T90_minutes_unspecific,Visit_6_HypoxiaBurden
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,978221.0,Matthews,John D,1955-01-04,14.3,5.9,7.761111,4.449417,4.149667,0.29975,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
932,5331799.0,Ren,Jian,1979-05-21,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
933,5331799.0,Ren,Jian,1979-05-21,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
934,5331799.0,Ren,Jian,1979-05-21,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
935,5331799.0,Ren,Jian,1979-05-21,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
hypoxic_table.Visit_1_HypoxiaBurden.dropna()

2      14.3
10     41.6
14     30.7
18      1.9
20      0.6
       ...
907     0.0
911     2.3
912     2.6
920     0.0
924     2.4
Name: Visit_1_HypoxiaBurden, Length: 276, dtype: float64

In [6]:
hypoxic_table.shape

(936, 160)

In [7]:
hypoxic_table_with_psg_data = pd.read_csv('/scr/wolfgang/Hypoxia_Study/hypoxic_table_with_psg_data.csv')
psg_studies_ahi_hypoxia_burden = pd.read_csv('/scr/wolfgang/Hypoxia_Study/psg_studies_ahi_hypoxia_burden.csv')

In [8]:
hypoxic_table_with_psg_data.Visit_1_HypoxiaBurden.dropna()

2       13.7
14      30.7
18       2.5
20       0.6
24     112.5
       ...
909     21.5
912     26.6
913      0.0
918      6.4
920      0.0
Name: Visit_1_HypoxiaBurden, Length: 399, dtype: float64

In [9]:
hypoxic_table_with_psg_data.shape

(932, 143)

In [10]:
hypoxic_table.loc[pd.isna(hypoxic_table.Visit_1_HypoxiaBurden) & pd.notna(hypoxic_table_with_psg_data.Visit_1_HypoxiaBurden)]

,File,Line,ID,Name,Multiple values,EMPI,EPIC_PMRN,MRN_Type,MRN,Report_Number,...,Visit_9_Date,Visit_9_Type,Visit_9_Path,Visit_9_Signalfile,Visit_9_Labelfile,Visit_10_Date,Visit_10_Type,Visit_10_Path,Visit_10_Signalfile,Visit_10_Labelfile
32,xaa,181053.0,xaa-181053,"Crocker, Linda L",NaN,100323388.0,1.005701e+10,MGH,4969559.0,E5692702,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,xaa,196712.0,xaa-196712,"PAGE, CATHERINE",NaN,100432068.0,1.006312e+10,MGH,2866189.0,SIS23720,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,xaa,206011.0,xaa-206011,"Piccetto, Frederick A",NaN,100452876.0,1.006424e+10,MGH,2965458.0,E13454261,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,xaa,211410.0,xaa-211410,"Santizo, Floridalma",NaN,100463588.0,1.006485e+10,MGH,3230779.0,E5915939,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,xaa,289669.0,xaa-289669,"Day, Jean P",NaN,100121955.0,1.004571e+10,MGH,1343780.0,E10747662,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,xad,6675.0,xad -6675,"PHILLIPO, GARY",NaN,102492986.0,1.004916e+10,MGH,1238059.0,SIS21310,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,xad,12123.0,xad -12123,"Hunter, Daniel R",NaN,102582538.0,1.005295e+10,MGH,4014933.0,E11126421,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
909,xad,60212.0,xad -60212,"Hazimeh, Khalid",*multiple reports,110511786.0,1.009457e+10,MGH,3283155.0,E14463548,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
913,xaa,1095352.0,NaN,"Boucher, Jessica",congenital heart disease,105185116.0,1.004513e+10,MGH,4251881.0,HF005181,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
918,NaN,NaN,NaN,"Dowling, Carol",NaN,100107472.0,1.002380e+10,BWH,4566709.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
hypoxic_table.loc[hypoxic_table.Report_Number == 'E5692702', ['Visit_1_HypoxiaBurden', 'MRN', 'MRN_Match', 'NameMatch', 'Visit_1_Signalfile', 'Visit_1_Labelfile']]

,Visit_1_HypoxiaBurden,MRN,MRN_Match,NameMatch,Visit_1_Signalfile,Visit_1_Labelfile
32,NaN,4969559.0,True,1.0,NaN,NaN

In [12]:
sleeplab_table = pd.read_csv('sleeplab_table.csv')

In [13]:
row = sleeplab_table.loc[sleeplab_table.MRN_int == 4969559]
print(row.Signalfile.values[0])
print(row.Labelfile.values[0])
print(row.Path.values[0])
row

nan
nan
M:\Datasets_ConvertedData\sleeplab\grass_data\Crocker_Linda_111813_2248.000

,FolderName,PatientID,MRN,LastName,FirstName,Sex,DateOfBirth,DateOfVisit,TypeOfTest,Path,MRN_int,Signalfile,Labelfile
6454,Crocker_Linda_111813_2248.000,Z8395802,496-95-59,Crocker,Linda L,Female,1947-06-05,2013-11-18,PSG all night CPAP,M:\Datasets_ConvertedData\sleeplab\grass_data\...,4969559,NaN,NaN
16724,Crocker_Linda_090313_2158.000,Z8395802,496-95-59,Crocker,Linda L,Female,1947-06-05,2013-09-03,PSG Diagnostic,M:\Datasets_ConvertedData\sleeplab\grass_data\...,4969559,NaN,NaN

In [14]:
os.listdir('/media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Crocker_Linda_111813_2248.000')

['MedicalReport.csv',
 '11_18_13_4969559_pre.docx',
 'SleepStatistics.xml',
 'ID_archived.csv',
 'CROCKER_LINDA_111813_2248.000.XML PSG Statistics.doc',
 'hx note.doc',
 'raw',
 'Signal_TwinData9_Exported_183.mat',
 'CROCKER_LINDA_111813_2248.xml',
 'Crocker_Linda_111813_2248.000__11_18_13_4969559_pre.csv',
 'annotations.csv',
 'ID.csv',
 'Observation.csv',
 'CROCKER_LINDA_111813_2248.000.CPAP ALl Night MD 022209_R2.doc',
 'TwinData9_Exported_183.edf',
 'TECH_SUM_CROCKER_111813.docx',
 'Observation.xml',
 'SleepStatistics.csv',
 'Study.xml',
 'psg 1.doc',
 'CROCKER_LINDA_111813_2248.000.MGH CPAP LONG.doc',
 '11_18_13_4969559_post.docx',
 'Study.csv',
 'Crocker_Linda_111813_2248.000__11_18_13_4969559_pre.docx']

In [15]:
table_grass = pd.read_csv('/media/mad3/Datasets_ConvertedData/sleeplab/grass_studies_list.csv')
table_natus = pd.read_csv('/media/mad3/Datasets_ConvertedData/sleeplab/natus_studies_list.csv')
assert np.all(table_grass.columns == table_natus.columns)
sleeplab_table = pd.concat([table_grass, table_natus], axis=0)
sleeplab_table = sleeplab_table[pd.notna(sleeplab_table.MRN)]

In [16]:
def time_diff(start, end):
    if start > end: # end < start e.g., 23:55:00-00:25:00
        end += timedelta(1) # +day
        assert end >= start
    return end - start

In [63]:
def get_grass_start_end_time(starttime_raw, endtime_raw):
    
    time_str_elements = starttime_raw.flatten()
    start_time = ''.join(chr(time_str_elements[j]) for j in range(time_str_elements.shape[0]))
    time_str_elements = endtime_raw.flatten()
    end_time = ''.join(chr(time_str_elements[j]) for j in range(time_str_elements.shape[0]))

    start_time = start_time.split(':')
    second_elements = start_time[-1].split('.')
    start_time = datetime.datetime(1990,1,1,hour=int(float(start_time[0])), minute=int(float(start_time[1])),
        second=int(float(second_elements[0])), microsecond=int(float('0.'+second_elements[1])*1000000))
    end_time = end_time.split(':')
    second_elements = end_time[-1].split('.')
    end_time = datetime.datetime(1990,1,1,hour=int(float(end_time[0])), minute=int(float(end_time[1])),
        second=int(float(second_elements[0])), microsecond=int(float('0.'+second_elements[1])*1000000))

    return start_time, end_time


def load_mgh_signal(signal_path, channels=None, reverse_sign=False):
    
    try: # usually Grass, saved as pre 7.3 format:
        ff = sio.loadmat(signal_path)
        data_path = os.path.basename(signal_path)
        if 's' not in ff:
            raise Exception('No signal found in %s.'%data_path)
        signal = ff['s']
        if reverse_sign:
            signal = -signal
        channel_names = [ff['hdr'][0,i]['signal_labels'][0].upper().replace('EKG','ECG') for i in range(ff['hdr'].shape[1])]
        if 'grass' in signal_path:
            Fs = 200.
        else:
            raise Exception('Safety check to make sure this is Grass data with Fs=200')

    except: # saved as .mat 7.3. new grass or natus files:
        with h5py.File(signal_path,'r') as ff:

            hdr = ff['hdr']
            signal_labels = hdr['signal_labels'][:]
            channel_names = [ ''.join([chr(x) for x in np.squeeze(ff[signal_labels[i,0]][:])]) for i in range(signal_labels.shape[0]) ]
            channel_names = [channel.upper() for channel in channel_names]
            signal = ff['s'][()]
            signal = np.transpose(signal);

            if 'recording' in ff.keys(): # only available for natus:
                year = int(np.squeeze(ff['recording']['year']))
                month = int(np.squeeze(ff['recording']['month']))
                day = int(np.squeeze(ff['recording']['day']))
                hour = int(np.squeeze(ff['recording']['hour']))
                if (hour >= 7) and (hour <=10):         # 'typo' by sleep techs
                    hour = hour + 12
                minute = int(np.squeeze(ff['recording']['minute']))
                second = int(np.squeeze(ff['recording']['second']))
                millisecond = int(np.squeeze(ff['recording']['millisecond']))
                Fs = int(np.squeeze(ff['recording']['samplingrate']))

                start_time = datetime.datetime(1990,1,1,hour=hour, minute=minute,
                        second=second, microsecond=int(millisecond*1000))
                end_time = start_time+datetime.timedelta(seconds=max(signal.shape)/Fs)

            else: # grass:
                if 'grass' in signal_path:
                    Fs = 200.
                else:
                    raise Exception('Safety check to make sure this is Grass data with Fs=200')

            # Label part for grass:
            ff.close()

    # end of loading part
    ##################################
    
    # only take signal channels to study
    if channels is None:
        signal_channel_ids = list(range(len(channel_names)))
        signal_channel_names = channel_names
        
    elif 'SumEffort' in channels:
        signal_channel_ids = []
        signal_channel_names = []
        for ichannel in ['ABD', 'CHEST']:
            found = False
            for j in range(len(channel_names)):
                if channel_names[j]==ichannel.upper():
                    signal_channel_ids.append(j)
                    signal_channel_names.append(channel_names[j])
                    found = True
                    break
            if not found:
                raise Exception('Channel %s is not found.'%ichannel)
        signal = signal[signal_channel_ids,:]#.T
        # do effort belt average here:
        signal = np.sum(signal,0,keepdims=1)/2
        
    else:
        signal_channel_ids = []
        signal_channel_names = []
        for i in range(len(channels)):
            found = False
            for j in range(len(channel_names)):
                if channel_names[j]==channels[i].upper():
                    signal_channel_ids.append(j)
                    signal_channel_names.append(channel_names[j])
                    found = True
                    break
            if not found:
                raise Exception('Channel %s is not found.'%channels[i])
        signal = signal[signal_channel_ids,:]#.T

    # check whether the signal contains NaN
    if np.any(np.isnan(signal)):
        raise Exception('Found Nan in signal in %s'%data_path)

    params = {'Fs':Fs*1.0, 'channel_ids': signal_channel_ids, 'channel_names': signal_channel_names}

    return signal, params

In [64]:
path_signal = '/media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Crocker_Linda_111813_2248.000/Signal_TwinData9_Exported_183.mat'

signal, params = load_mgh_signal(path_signal)

In [75]:
fs = params['Fs']
fmt = '%H:%M:%S'

path_signal = '/media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Crocker_Linda_111813_2248.000/annotations.csv'



path_annotations = '/media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Crocker_Linda_111813_2248.000/annotations.csv'
annotations = pd.read_csv(path_annotations)
annotations = annotations[annotations['duration'].notna()]
annotations['time'] = pd.to_datetime(annotations['time'])
columns = annotations.event.unique().tolist()

time_start = annotations.iloc[0]['time']
time_end = annotations.iloc[-1]['time']
time_delta = time_end - time_start
recording_len_seconds = time_delta.seconds

ann = pd.DataFrame(index=np.arange(signal.shape[1]) , columns=columns)

for i in range(annotations.shape[0]):
    current_time = annotations.iloc[i]['time']
    tdelta = time_diff(time_start , current_time) 
    time_samples_index = int (tdelta.seconds * fs)
    duration_of_event = int (annotations.iloc [i]['duration'] * fs)
    if duration_of_event < 1:
        duration_of_event = int(np.ceil(duration_of_event))   
    event_name = annotations.iloc [i]['event']
    ann.at [time_samples_index:(time_samples_index + duration_of_event -1), event_name] = 1

In [ ]:
apnea = ann['']

In [78]:
ann

,Sleep_stage_?,Position - Supine - 1,Treatment - Start - 1,Sleep_stage_W,RespEvent - Hypopnea - 4,Sleep_stage_N1,Sleep_stage_N2,PLM - Isolated - 1,EKGEvent - SinusTach - 1,Sleep_stage_N3,Sleep_stage_R,RespEvent - CentralApnea - 2,RespEvent - RERA - 6,PLM - Periodic - 1,Position - Disconnect - 1,Position - Right - 1,Position - Left - 1,Treatment - None - 1
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5739995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5739996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5739997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5739998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5739999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
fs = params ['Fs']
annotation = pd.read_csv(label_path)

test = annotation.copy()
start_time = annotation.iloc[0]['time']
test = test[test['duration'].notna()]
columnsName = test.event.unique().tolist()
from datetime import datetime
FMT = '%H:%M:%S'
s1 = test.iloc[-1]['time']
s2 = test.iloc[0]['time']
tdelta = datetime.strptime(s1, FMT) - datetime.strptime(s2, FMT)
len_in_seconds=tdelta.seconds
label = pd.DataFrame(index=np.arange(signal.shape[1]) , columns=columnsName)
start_time = test.iloc [0]['time']
start_time = datetime.strptime(start_time, '%H:%M:%S')
for i in range(len(test)):
    current_time = test.iloc[i]['time']
    current_time = datetime.strptime(current_time, '%H:%M:%S')
    tdelta = time_diff(start_time , current_time) 
    len_in_seconds=tdelta.seconds
    time_samples_index = int (len_in_seconds * fs)
    duration_of_event = int (test.iloc [i]['duration'] * fs)
    if duration_of_event < 1:
        duration_of_event = int(np.ceil(duration_of_event))   
    event_name = test.iloc [i]['event']
    label.at [time_samples_index:(time_samples_index + duration_of_event -1), event_name] = 1

In [14]:
row = sleeplab_table.loc[sleeplab_table.MRN_int == 2866189].iloc[0, :]
row

FolderName                        Page_Catherine_100413_2142.000
PatientID                                               Z9225006
MRN                                                    286-61-89
LastName                                                    Page
FirstName                                              Catherine
Sex                                                       Female
DateOfBirth                                           1975-02-22
DateOfVisit                                           2013-10-04
TypeOfTest                                       PSG Split night
Path           M:\Datasets_ConvertedData\sleeplab\grass_data\...
MRN_int                                                  2866189
Signalfile     /media/mad3/Datasets_ConvertedData/sleeplab/na...
Labelfile      /media/mad3/Datasets_ConvertedData/sleeplab/na...
Name: 571, dtype: object

In [71]:
path = row.Path
path = path.replace('M:', '/media/mad3')
path = path.replace('\\', '/')
path

'/media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Page_Catherine_100413_2142.000'

In [73]:
from sleep_analysis_functions import compute_spo2_clean, compute_hypoxia_burden, desaturation_detection, hypoxaemic_burden_minutes

def compute_hypoxia_statistics(signalfilepath, labelfilepath):
    
    signal, sleep_stage, apnea, params = check_load_mgh_dataset(signalfilepath, labelfilepath, channels=['SAO2','SPO2','PTAF', 'CFlow'], report_and_actual_time_tol=300, reverse_sign=False)
    
    data = pd.DataFrame()
    data['Apnea'] = apnea
    for iSignal, name in enumerate(params['signal_names']):
        data[name] = signal[iSignal]
    data.rename({'SAO2':'SPO2'}, axis=1, inplace=True)
    data['spo2'] = data['SPO2']
    fs = int(params['Fs'])

    dt_start = pd.Timestamp('2000-01-01 00:00:00')
    dt_end = dt_start + datetime.timedelta(seconds=(data.shape[0]-1) / fs)
    pseudo_dt_index = pd.date_range(start=dt_start, end=dt_end, periods=data.shape[0])
    data.index = pseudo_dt_index

    data = compute_spo2_clean(data, fs=fs)
    data['spo2'] = data['spo2_clean']

    data['Apnea_Binary'] = np.isin(data['Apnea'],[1,2,3,4]).astype(int)
    data['Apnea_End'] = np.isin(data['Apnea_Binary'].diff(), [-1])
    
    sleep_stage = sleep_stage[np.logical_not(pd.isna(sleep_stage))]
    hours_sleep = sum(sleep_stage<5)/fs/3600
    
    data, hypoxia_burden = compute_hypoxia_burden(data, fs, hours_sleep=hours_sleep)
    
    
    T90burden, T90desaturation, T90nonspecific = hypoxaemic_burden_minutes(data['spo2'].values, fs)
    
    AHI = np.round(sum(data['Apnea_End'])/hours_sleep,1)

    return hypoxia_burden, AHI, hours_sleep, T90burden, T90desaturation, T90nonspecific

In [79]:
signalfilepath = row.Signalfile.values[0]
labelfilepath = row.Labelfile.values[0]

print(signalfilepath)
print(labelfilepath)

/media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Nuxoll~ Ravi_11af46dc-5c46-4d83-9623-4827cc02263d/Signal_Nuxoll~ Ravi_11af46dc-5c46-4d83-9623-4827cc02263d.mat
/media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Nuxoll~ Ravi_11af46dc-5c46-4d83-9623-4827cc02263d/Labels_Nuxoll~ Ravi_11af46dc-5c46-4d83-9623-4827cc02263d.mat

In [ ]:
hypoxia_burden, ahi, total_sleep_time, T90burden, T90desaturation, T90nonspecific = compute_hypoxia_statistics(signalfilepath, labelfilepath)

In [81]:
os.listdir(path)

['MedicalReport.csv',
 'PAGE_CATHERINE_100413_2142.000.Diagnostic MD 042209_R2.doc',
 'Page_Catherine_100413_2142.000__10_04_13_2866189_pre.csv',
 'PAGE_CATHERINE_100413_2142.000.XML PSG Statistics.doc',
 'SleepStatistics.xml',
 'ID_archived.csv',
 'hx note.doc',
 'Signal_Page_Catherine_100413_2142.000.mat',
 'raw',
 'Page_Catherine_100413_2142.000.edf',
 'PAGE_CATHERINE_100413_2142.000.MGH PSG LONG.doc',
 'annotations.csv',
 'ID.csv',
 'Tech_Report_Template_v2.doc',
 'Observation.csv',
 'PAGE_CATHERINE_100413_2142.xml',
 'Page_Catherine_100413_2142.000__10_04_13_2866189_pre.doc.docx',
 'Observation.xml',
 'SleepStatistics.csv',
 'Study.xml',
 '10_04_13_2866189_post.doc.docx',
 'Labels_Page_Catherine_100413_2142.000.mat',
 'Study.csv',
 '10_04_13_2866189_pre.doc.docx']

In [59]:
sleeplab_avail_full_tmp

0       1119471
1       1119471
2       1182974
3       3361961
4       3429470
         ...
5661    3361231
5662    3361231
5663    1347068
5664    3322691
5665    3389032
Name: MRN_int, Length: 5666, dtype: int64

In [48]:
hypoxic_table.columns

Index(['File', 'Line', 'ID', 'Name', 'Multiple values', 'EMPI', 'EPIC_PMRN',
       'MRN_Type', 'MRN', 'Report_Number',
       ...
       'Visit_9_Date', 'Visit_9_Type', 'Visit_9_Path', 'Visit_9_Signalfile',
       'Visit_9_Labelfile', 'Visit_10_Date', 'Visit_10_Type', 'Visit_10_Path',
       'Visit_10_Signalfile', 'Visit_10_Labelfile'],
      dtype='object', length=160)

In [43]:
hypoxic_table_with_psg_data.loc[hypoxic_table_with_psg_data.Report_Number == 'E5692702', 'Visit_1_HypoxiaBurden']

32    4.1
Name: Visit_1_HypoxiaBurden, dtype: float64

In [37]:
hypoxic_table_with_psg_data.head()

,File,Line,ID,Name,Multiple values,EMPI,EPIC_PMRN,MRN_Type,MRN,Report_Number,...,Visit_10_AHI,Visit_10_Total_Sleep_Time,Visit_11_Date,Visit_11_Type,Visit_11_Path,Visit_11_Signalfile,Visit_11_Labelfile,Visit_11_HypoxiaBurden,Visit_11_AHI,Visit_11_Total_Sleep_Time
0,xaa,11252.0,xaa-11252,"Cunningham, William",*,100006892,10028692548,MGH,75751,HA004046,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,xaa,14878.0,xaa-14878,"CANADY, MILDRED",NaN,100001724,10040013376,BWH,371260,4412350964,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,xaa,31930.0,xaa-31930,"Matthews, John",NaN,100080788,10043352730,MGH,978221,HC014805,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,xaa,35634.0,xaa-35634,"CROKE, WILLIAM",NaN,100076644,10043112944,MGH,937117,SIS31526,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,xaa,39029.0,xaa-39029,"Walker, Desiree",NaN,100075764,10043064202,BWH,3904687,E12638408,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
hypoxic_table.head()

,File,Line,ID,Name,Multiple values,EMPI,EPIC_PMRN,MRN_Type,MRN,Report_Number,...,Visit_9_Date,Visit_9_Type,Visit_9_Path,Visit_9_Signalfile,Visit_9_Labelfile,Visit_10_Date,Visit_10_Type,Visit_10_Path,Visit_10_Signalfile,Visit_10_Labelfile
0,xaa,11252.0,xaa-11252,"Cunningham, William",*,100006892.0,1.002869e+10,MGH,75751.0,HA004046,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,xaa,14878.0,xaa-14878,"CANADY, MILDRED",NaN,100001724.0,1.004001e+10,BWH,371260.0,4412350964,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,xaa,31930.0,xaa-31930,"Matthews, John",NaN,100080788.0,1.004335e+10,MGH,978221.0,HC014805,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,xaa,35634.0,xaa-35634,"CROKE, WILLIAM",NaN,100076644.0,1.004311e+10,MGH,937117.0,SIS31526,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,xaa,39029.0,xaa-39029,"Walker, Desiree",NaN,100075764.0,1.004306e+10,BWH,3904687.0,E12638408,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
psg_studies_ahi_hypoxia_burden

,FirstName,LastName,DateOfBirth,Sex,MRN,MRN_int,DateOfVisit,TypeOfTest,Total_Sleep_Time,AHI,Hypoxia_Burden
0,John D,Matthews,1/4/1955,Male,097-82-21,978221,08/14/2009,PSG all night CPAP,7.8,6.1,13.7
1,John D,Matthews,1/4/1955,Male,097-82-21,978221,08/18/2012,PSG all night CPAP,6.5,0.3,0.0
2,John D,Matthews,1/4/1955,Male,097-82-21,978221,07/24/2009,PSG Split night,4.6,40.4,96.5
3,Lawrence S,Frishkopf,6/26/1930,Male,083-63-34,836334,08/11/2017,PSG Split night,6.9,12.2,30.7
4,Richard P,Fitzgerald,1/21/1938,Male,199-67-47,1996747,10/18/2017,PSG all night CPAP,7.2,2.8,2.5
...,...,...,...,...,...,...,...,...,...,...,...
707,Carol,Dowling,8/28/1942,Female,231-37-30,2313730,12/19/2014,PSG all night CPAP,6.4,7.3,6.4
708,Carol,Dowling,8/28/1942,Female,231-37-30,2313730,10/26/2015,PSG Split night,5.5,10.1,9.5
709,Milagros,Garcia,4/28/1960,Female,300-13-58,3001358,01/05/2010,PSG Diagnostic,4.4,0.5,0.0
710,Milagros,Garcia,4/28/1960,Female,300-13-58,3001358,01/23/2009,PSG Diagnostic,6.2,2.9,1.6
711,Michelle,Osborne,10/8/1969,Female,528-69-65,5286965,09/26/2016,PSG all night CPAP,NaN,NaN,NaN